### PR TITLE
Respect latest available staleness prior to time conductor start

### LINKED ISSUE #8200: Staleness should be reported for `really` stale telemetry (timestamp before start bound)
#### Summary
Latest available data which is stale, is not being marked as stale, unless it arrives within the specified time conductor bounds. Actually, it is marked stale if it arrives after the start bounds, which is another bug since it should not be stale if it is future telemetry. Latest available telemetry could be stale but have been received long before the start bound, in which case it should remain marked as stale until new telemetry datum comes in.

This can occur in infrequently updated telemetry such as positional or state telemetry.

(This is based on the assumption that a staleness provider is marking telemetry as stale if its timestamp is greater than some tolerance).

#### Expected vs Current Behavior
- Latest available telemetry should be marked stale, even if the timestamp is prior to the start bound
- Any incoming telemetry, including latest available telemetry, should not be marked as stale if the timestamp is after the end bound

#### Steps to Reproduce
1. Open a display with stale telemetry (should be as sparse as possible)
2. Reduce the start time of the time conductor so that the start time is after the timestamp of the latest telemetry datum
3. Navigate away and back to telemetry
4. Observe telemetry is not marked as stale
5. Return the start time of the time conductor so that the start time is before the timestamp of the latest telemetry datum
6. Navigate away and back to telemetry
7. Observe telemetry is again marked as stale
The same telemetry is marked or not marked as stale depending on the start bound, but it should be marked as stale in both cases.
8. Repeat **Steps to Reproduce** but with toggling the latest available telemetry timestamp before and after end bounds

#### Environment

* Open MCT Version: 3491473d3
* Deployment Type: VIPER
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by davetsay**
Closes #8200 

### Describe your changes:
Latest available staleness used in staleness calculation even if prior to time conductor start bound
Clear staleness 

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this a [notable change](../docs/src/process/release.md) that will require a special callout in the release notes? For example, will this break compatibility with existing APIs or projects that consume these plugins?

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Has this been smoke tested?
* [x] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [x] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?

### CODE REVIEW

File: src/utils/staleness.js [hunk 1]
```diff
@@ -34,16 +34,23 @@ class StalenessUtils {
 
   shouldUpdateStaleness(stalenessResponse, id) {
```
Comment (akhenry) [inline src/utils/staleness.js:34]: My strong suspicion is that we are making this more complicated than it needs to be. For situational awareness I think we should go stale when we receive a staleness event _except_ if the staleness event was received out of order. This might happen in a race condition with a telemetry value update.

So, let's basically remove all of this logic and just check whether the timestamp on the staleness event is > the last received telemetry update. Ignore the bounds, they are irrelevant for staleness, we always want to indicate if the parameter is stale, whatever time window the user is looking at.

**Review by akhenry — APPROVED** [review]
Also, tests please. Thanks!

File: src/utils/staleness.js (hunk 1 above)
Comment (davetsay) [reply src/utils/staleness.js:34]: Copy. This PR will be updated with the contribution from @marcelo-earth on #8207, and then this will just be adding an example staleness provider and e2e tests.

File: e2e/tests/functional/staleness.e2e.spec.js [hunk 2]
```diff
@@ -20,43 +20,49 @@
...
-    // Immediately navigate to the folder
-    await page.goto(folder.url);
-
-    // Verify that staleness is not shown
-    await expect(page.getByLabel('Object View')).not.toHaveClass(/is-stale/);
+    test('indicates when telemetry is stale and clears staleness when telemetry is not stale', async ({
+      page
+    }) => {
+      await expect(objectView).toHaveClass(/is-stale/, {
+        timeout: 5 * 1000 // Give 3 seconds for the staleness to be updated
```
Comment (akhenry) [inline e2e/tests/functional/staleness.e2e.spec.js:58]: I think these comments need updating.

File: src/ui/mixins/staleness-mixin.js [hunk 3]
```diff
@@ -167,24 +165,31 @@ export default {
       const id = this.getSubscriptionId(domainObject);
       const stalenessResponse = await this.openmct.telemetry.isStale(domainObject);
       if (stalenessResponse !== undefined) {
-        const SKIP_CHECK = false;
-        this.handleStalenessResponse(id, stalenessResponse, SKIP_CHECK, callback);
+        this.handleStalenessResponse(id, stalenessResponse, callback);
       }
     },
-    handleStalenessResponse(id, stalenessResponse, skipCheck, callback) {
+    handleStalenessResponse(id, stalenessResponse, callback) {
```
Comment (akhenry) [inline src/ui/mixins/staleness-mixin.js:171]: GOOD! Function arguments like `skipCheck` are a code smell.

File: src/utils/staleness.js [hunk 4]
```diff
@@ -29,15 +29,14 @@ class StalenessUtils {
...
     const stalenessResponseTime = this.parseTime(stalenessResponse);
-    const { start } = this.openmct.time.getBounds();
-    const isStalenessInCurrentClock = stalenessResponseTime > start;
 
-    if (stalenessResponseTime > this.lastStalenessResponseTime && isStalenessInCurrentClock) {
+    // Accept latest staleness updates from staleness provider,
+    // regardless of whether the update occurred within time conductor bounds.
+    if (stalenessResponseTime > this.lastStalenessResponseTime) {
```
Comment (akhenry) [inline src/utils/staleness.js:39]: So there's still a potential race condition here, per my previous comment. Let's say a parameter goes stale just as it receives a fresh value. For whatever reason, Yamcs sends us these updates out of order, so we receive parameter update first, and then the staleness message. With the current logic we will update the parameter value and then mark it stale, even though it's no longer stale.

To remedy this we need to track the latest parameter timestamp `as well as` the latest staleness response time. `shouldUpdateStaleness` needs to check both `lastStalenessResponseTime` _and_ `lastTelemetryReceivedTime`.

**Review by akhenry — APPROVED** [review]
