### PR TITLE
Fix legend color to be in sync with plot color on change

### LINKED ISSUE #5233: Legend color is not in sync with plot color on change
#### Summary
Legend needs to update swatch color when user sets color from Plot Series area in Inspector.

#### Expected vs Current Behavior
User currently must nav away and back to see the change, which is undesirable.

#### Steps to Reproduce
1. Create an overlay plot
2. Add a telemetry endpoint to it
3. Change the color of the series from inspector properties
4. Observe that the plot series color changes, but the legend shows the old color in the swatch.

#### Environment
* Open MCT Version: 2.0.3
* Deployment Type: all
* OS: Mac / Windows
* Browser: All

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?

#### Additional Information
In the image below, the swatch colors don't match the plot colors.

image

### PR DESCRIPTION
**Pull request by alizenguyen**
Closes #5233 

### Describe your changes:

Duplicate of pull request #5338 but branched off of release/2.0.5 instead of master.

Contains a few other changes from last pull request:

- Noticed the swatch was fixed for overlays, but not for stacked plots. I fixed that by checking type of the domainObject and adjusting the path to the observer.
- Add e2e to test the swatch color change

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by shefalijoshi** [comment]
@alizenguyen This appears to be working for Overlay plots, however if you drag a sinewave generator directly into a Stacked Plot and then change the color of the sinewave generator, it is not being reflected in the legend of the stacked plot.

**Review by shefalijoshi — CHANGES_REQUESTED** [review]
Partially working - see comment.

**Comment by alizenguyen** [comment]
Ah, so it's not working when you initially add one? I'll look into it.

**Comment by alizenguyen** [comment]
When a plot is first added to the stacked plot, the color config is not added to the series until you actually change the color in edit mode. So, I added an observer to the domain object that would then add the color observer that will watch for that particular path and remove itself after it grabs the updated series config length which is implement into the path.

Not sure if there was a better way to detect changes for that initial series color config addition. Watching for changes in 'configuration.series' did not detect changes to the array length.

File: src/plugins/plot/legend/PlotLegendItemExpanded.vue [hunk 1]
```diff
@@ -169,6 +175,55 @@ export default {
                 this.formattedMinY = '';
                 this.formattedMaxY = '';
             }
+
+            if (this.domainObject.configuration) {
```
Comment (shefalijoshi) [inline src/plugins/plot/legend/PlotLegendItemExpanded.vue:179]: Some telemetry endpoints that are added to stacked plots don't have configuration. their properties are saved on the parent (stacked plot). In this case, you need to observe the stacked plot to find legend color changes.

See: https://github.com/nasa/openmct/blob/release/2.0.5/src/plugins/plot/inspector/forms/SeriesForm.vue#L301
and
https://github.com/nasa/openmct/blob/release/2.0.5/src/plugins/plot/inspector/PlotOptionsEdit.vue#L122

**Review by shefalijoshi — DISMISSED** [review]

File: src/plugins/plot/legend/PlotLegendItemExpanded.vue (hunk 1 above)
Comment (alizenguyen) [reply src/plugins/plot/legend/PlotLegendItemExpanded.vue:179]: Thanks Shefali!

That is correct. The domain object in this case is the stacked plot (the parent). So if you drag a telemetry object into the stacked plot, delete it, and re-add it. It should retain the same color properties. 

This check in particular distinguishes domain objects with configurations (stacked plot, overlays, etc.) against telemetry objects which are always blue, non-editable, and do not need a color observer so it will not run the code. 

I hope that makes sense!

Comment (shefalijoshi) [reply src/plugins/plot/legend/PlotLegendItemExpanded.vue:179]: Non editable objects still need color observers - but changes will be saved to the parent stacked plot. I'll take a look at this and push a change of how this could be done.

File: src/plugins/plot/MctPlot.vue [hunk 2]
```diff
@@ -359,11 +360,6 @@ export default {
         this.setTimeContext();
 
         this.loaded = true;
-
-        //We're referencing the canvas elements from the mct-chart in the initialize method.
-        // So we need $nextTick to ensure the component is fully mounted before we can initialize stuff.
-        this.$nextTick(this.initialize);
```
Comment (akhenry) [inline src/plugins/plot/MctPlot.vue:365]: ❤️

File: src/plugins/plot/configuration/PlotSeries.js [hunk 3]
```diff
@@ -225,6 +235,12 @@ export default class PlotSeries extends Model {
             });
         /* eslint-enable you-dont-need-lodash-underscore/concat */
     }
+
+    upateName(name) {
```
Comment (akhenry) [inline src/plugins/plot/configuration/PlotSeries.js:239]: typo

File: src/plugins/plot/configuration/PlotSeries.js [hunk 4]
```diff
@@ -126,10 +126,15 @@ export default class PlotSeries extends Model {
      */
     destroy() {
         super.destroy();
+        this.openmct.time.off('bounds', this.updateLimits);
```
Comment (akhenry) [inline src/plugins/plot/configuration/PlotSeries.js:129]: Good catch!

File: src/plugins/plot/legend/PlotLegendItemCollapsed.vue [hunk 5]
```diff
@@ -103,8 +105,18 @@ export default {
         }
     },
     mounted() {
+        eventHelpers.extend(this);
```
Comment (akhenry) [inline src/plugins/plot/legend/PlotLegendItemCollapsed.vue:108]: IS there any value in making this a mixin that is used by *Collapsed and *Expanded?

**Review by akhenry — CHANGES_REQUESTED** [review]
Looking awesome! Couple of comments

File: src/plugins/plot/legend/PlotLegendItemCollapsed.vue (hunk 5 above)
Comment (shefalijoshi) [reply src/plugins/plot/legend/PlotLegendItemCollapsed.vue:108]: Yes and no. There is some overlap, but the initialize() method is slightly different. If this changes in the future I think there might be value.

**Review by akhenry — APPROVED** [review]
