### PR TITLE
Resize plans properly

### LINKED ISSUE #7587: Resizing the window causes Plan activities to stay fixed
#### Summary

Resizing the window causes Plan activities to stay fixed by the vertical NOW line to resize.

#### Expected vs Current Behavior

UTC Time and vertical NOW lines should stay properly aligned on resize.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by scottbell**
Closes #7587 

### Describe your changes:

Ensure element isn't null for the resize observer, and that we're *deeply* watching the size.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this a [notable change](../docs/src/process/release.md) that will require a special callout in the release notes? For example, will this break compatibility with existing APIs or projects that consume these plugins?

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Has this been smoke tested?
* [x] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [x] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?

### CODE REVIEW

File: src/ui/components/TimeSystemAxis.vue [hunk 1]
```diff
@@ -139,7 +143,7 @@ export default {
       }
     },
     setDimensions() {
-      const axisHolder = this.$refs.axisHolder;
+      const axisHolder = this.axisHolder;
```
Comment (ozyx) [inline src/ui/components/TimeSystemAxis.vue:146]: super nitpicky, but can we just use `this.axisHolder` here instead of creating the new const?

**Review by ozyx — APPROVED** [review]
Approved with 1 nitpick that you could take or leave

**Comment by ozyx** [comment]
I wonder if we can have a visual test that resizes a plan? that might catch a regression like this.
