### PR TITLE
[Notebook] Handle conflicts properly

### LINKED ISSUE #5921: Conflict resolution is not working in multi-user notebooks
#### Summary

When two users make conflicting changes to a notebook the notebook plugin will detect the conflict and attempt to merge the changes from the two users.

#### Expected vs Current Behavior
Adding two different entries at the same time should result in both entries appearing in the notebook with no errors shown to the user.

#### Steps to Reproduce
1. Open a notebook in Chrome
2. Open the same notebook in Firefox
3. In the Chrome network tab throttle the network connection down to slow 3d
4. Add an entry to the notebook in Chrome 
5. Quickly jump over the Firefox and add an entry there.

Observe that an error is displayed to the user, and the entry made in Firefox appears in Chrome.

#### Environment
* Open MCT Version: 2.1.2
* Deployment Type: VIPER Dev

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by jvigliotta**
Closes #5921 

### Describe your changes:

Since we added transactions to notebooks, conflict resolution has not been working. This is because the remote notebook object that was requested to handle merges, was not being returned, due to be in a transaction, the local copy of the notebook was being returned. This resulted in NO conflicts being found and no merging happening. This has been resolved with a `forceRemote` flag being passed to get, which will in all circumstances return a remotely fetched object.

In this PR some cosmetic additions to notebook have been added as well, a progress bar (sometimes conflicts can take a bit to merge) for saving an entry. We've disabled the drop area/click area for new entries as well to try to prevent spamming of notebook entries.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/api/objects/ObjectAPI.js [hunk 1]
```diff
@@ -196,20 +196,22 @@ export default class ObjectAPI {
      * @returns {Promise} a promise which will resolve when the domain object
      *          has been saved, or be rejected if it cannot be saved
      */
-    get(identifier, abortSignal) {
+    get(identifier, abortSignal = undefined, forceRemote = false) {
```
Comment (ozyx) [inline src/api/objects/ObjectAPI.js:199]: Would it be more readable to have this be an argument called `useCache` that is `true` by default?

File: src/api/objects/ObjectAPI.js [hunk 2]
```diff
@@ -391,15 +393,14 @@ export default class ObjectAPI {
...
-
                 savedObjectPromise = provider.update(domainObject);
             }
 
             if (savedObjectPromise) {
                 savedObjectPromise.then(response => {
                     savedResolve(response);
                 }).catch((error) => {
-                    if (lastPersistedTime !== undefined) {
+                    if (isNewObject) {
```
Comment (ozyx) [inline src/api/objects/ObjectAPI.js:403]: Previously, this was checking if `lastPersistedTime` was defined, meaning that the object is not new. This seems to have the opposite check, and means `lastPersistedTime` can potentially be undefined. I think this should be `if (!isNewObject)` instead

File: src/plugins/notebook/components/Notebook.vue [hunk 3]
```diff
@@ -50,7 +50,7 @@
         <Sidebar
             ref="sidebar"
             class="c-notebook__nav c-sidebar c-drawer c-drawer--align-left"
-            :class="[{'is-expanded': showNav}, {'c-drawer--push': !sidebarCoversEntries}, {'c-drawer--overlays': sidebarCoversEntries}]"
+            :class="sidebarClasses"
```
Comment (ozyx) [inline src/plugins/notebook/components/Notebook.vue:53]: nice!

File: src/plugins/notebook/components/Notebook.vue [hunk 4]
```diff
@@ -133,6 +134,11 @@
                     To start a new entry, click here or drag and drop any object
                 </span>
             </div>
+            <progress-bar
+                v-if="savingTransaction"
+                class="c-telemetry-table__progress-bar"
+                :model="{ progressPerc: undefined }"
```
Comment (ozyx) [inline src/plugins/notebook/components/Notebook.vue:140]: nitpick, but kinda feel like this should be `null` as it is an initialized value.

that would require a change to `ProgressBar` and anything else that calls up an indefinite progress bar so I'll leave that up to you whether or not you think it's worth it. In general I'm trying to not use `null` and `undefined` interchangeably as there is some convention for the difference between the two:

https://stackoverflow.com/a/5076962/6596223

Comment (ozyx) [reply src/plugins/notebook/components/Notebook.vue:140]: this comment is non-blocking for this PR

File: src/plugins/notebook/components/Notebook.vue [hunk 5]
```diff
@@ -891,13 +916,21 @@ export default {
         },
         startTransaction() {
             if (!this.openmct.objects.isTransactionActive()) {
+                this.activeTransaction = true;
```
Comment (ozyx) [inline src/plugins/notebook/components/Notebook.vue:919]: What happens if there's already an active transaction?

File: src/plugins/notebook/components/Notebook.vue [hunk 6]
```diff
@@ -891,13 +916,21 @@ export default {
...
         async saveTransaction() {
             if (this.transaction !== undefined) {
-                await this.transaction.commit();
-                this.openmct.objects.endTransaction();
+                this.savingTransaction = true;
+                try {
+                    await this.transaction.commit();
+                } finally {
+                    this.openmct.objects.endTransaction();
+                    this.transaction = undefined;
```
Comment (ozyx) [inline src/plugins/notebook/components/Notebook.vue:930]: Prefer to use `null` over `undefined` for initialized variables with "no value"

File: src/plugins/notebook/monkeyPatchObjectAPIForNotebooks.js [hunk 7]
```diff
@@ -74,19 +74,22 @@ async function resolveNotebookTagConflicts(localAnnotation, openmct) {
 
 async function resolveNotebookEntryConflicts(localMutable, openmct) {
     if (localMutable.configuration.entries) {
+        const FORCE_REMOTE = true;
```
Comment (ozyx) [inline src/plugins/notebook/monkeyPatchObjectAPIForNotebooks.js:77]: See previous comment. Would it read better if we do something like `USE_CACHE = false` ?

File: src/plugins/objectMigration/plugin.js [hunk 8]
```diff
@@ -36,8 +36,8 @@ export default function () {
         }
 
         let wrappedFunction = openmct.objects.get;
-        openmct.objects.get = function migrate(identifier) {
-            return wrappedFunction.apply(openmct.objects, [identifier])
+        openmct.objects.get = function migrate() {
+            return wrappedFunction.apply(openmct.objects, [...arguments])
```
Comment (ozyx) [inline src/plugins/objectMigration/plugin.js:40]: How can we test this change? Would this affect all object migrations?

File: src/plugins/persistence/couch/CouchObjectProvider.js [hunk 9]
```diff
@@ -219,7 +224,12 @@ class CouchObjectProvider {
                 console.error(error.message);
                 throw new Error(`CouchDB Error - No response"`);
             } else {
-                console.error(error.message);
+                if (!isNotebookOrAnnotationType(body.model)) {
```
Comment (ozyx) [inline src/plugins/persistence/couch/CouchObjectProvider.js:227]: Let's make this a positive condition for readability.

**Review by ozyx — CHANGES_REQUESTED** [review]
Awesome work! I've tested it and seems to work well. I've left a few comments, mostly focused on readability but I think there's one minor coding mistake in there.

**Comment by ozyx** [comment]
I'm doing some testing with localStorage and I'm noticing that if an entry is left blank (even if it's confirmed blank), you are unable to create another entry until you add some text to the existing blank entry:


https://user-images.githubusercontent.com/9259993/209739626-33c1a6d0-55b6-4aa0-ace0-31532800fd78.mov

File: src/plugins/persistence/couch/CouchObjectProvider.js (hunk 9 above)
Comment (ozyx) [reply src/plugins/persistence/couch/CouchObjectProvider.js:227]: Also this is potentially undefined as not all requests will have a body so we should check for that

File: src/api/objects/ObjectAPI.js (hunk 2 above)
Comment (jvigliotta) [reply src/api/objects/ObjectAPI.js:403]: Oh dang... yep. Whoopsie!

File: src/plugins/notebook/components/Notebook.vue (hunk 4 above)
Comment (jvigliotta) [reply src/plugins/notebook/components/Notebook.vue:140]: Agreed, as this is related to another component, I've created an issue to address this: https://github.com/nasa/openmct/issues/6085
I don't want to push this out any further or add any unrelated changes to this PR, `ProgressBar` is used in multiple other places. Good point though!

File: src/plugins/notebook/components/Notebook.vue (hunk 5 above)
Comment (jvigliotta) [reply src/plugins/notebook/components/Notebook.vue:919]: There's two situations where we spin up a transaction in notebooks (regarding entries). On a new entry (this will prevent those "blank" entries from popping up randomly when a new entry is created) and when we're editing an existing entry. Once we create a new entry, it's then being edited, this results in a request to start a transaction again, so this is just checking if that's the case, if it is, nothing changes and the transaction will be ended when the entry is blurred.

File: src/plugins/notebook/components/Notebook.vue (hunk 3 above)
Comment (jvigliotta) [reply src/plugins/notebook/components/Notebook.vue:53]: This was SO annoying. It was making it so the rest of the syntax highlighting in VSCode was all janked up. Hopefully this helps others be less annoyed! (it's also just the right way to do this)

File: src/plugins/notebook/components/Notebook.vue (hunk 4 above)
Comment (ozyx) [reply src/plugins/notebook/components/Notebook.vue:140]: This is great, and a good first issue for open source contributors. Thanks for creating that!

File: src/api/objects/ObjectAPI.js (hunk 1 above)
Comment (jvigliotta) [reply src/api/objects/ObjectAPI.js:199]: This is a little tricky. When this flag is passed in, we skip the cache AND we skip returning any dirty objects from a transaction. If we pass in true, it will automatically resort to fetching the remote object. That was my thinking. That being said, we don't plan to have this around for too long as we'd like to remove the need for transactions altogether. More than happy to discuss more though.

File: src/plugins/notebook/monkeyPatchObjectAPIForNotebooks.js (hunk 7 above)
Comment (jvigliotta) [reply src/plugins/notebook/monkeyPatchObjectAPIForNotebooks.js:77]: I definitely understand what you mean. This will hopefully just be a temporary flag.

File: src/plugins/objectMigration/plugin.js (hunk 8 above)
Comment (jvigliotta) [reply src/plugins/objectMigration/plugin.js:40]: Not entirely sure how we'd test it. But this should actually make things a bit better. It now will include abort signals, which it previously wasn't. What I'd really like, is for this to not patch the `get` method and just make these migrations `getInterceptors`.

**Review by ozyx — APPROVED** [review]
LGTM
