### PR TITLE
Fix plot zoom when child of time strip

### LINKED ISSUE #3974: [Timestrip] Zoom and pan are incorrectly disabled for Plot object views contained within a Timestrip
### Reproduce
1. Create a Timestrip and add numeric telemetry that view as plots. Save the Timestrip.
2. In the tree, expand the Timestrip and navigate to one of the telemetry points. The main view should show a plot view.
3. Mouseover the plot and observe: no zoom buttons are displayed.
4. Try to zoom via dragging a marquee or by using the mousewheel, observe: nothing happens.

This is a side effect of the desire to disable zoom and pan while viewing the Timestrip itself, but has had an undesired effect of suppressing those features for the Timestrip's children's views themselves.

Solution: use CSS `pointer-events: none` applied to the plot view's `.gl-plot-display-area` element when within a Timestrip.

### PR DESCRIPTION
**Pull request by shefalijoshi**
Resolves #3974

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? Will users need to change how they are calling the API, or how they've extended core plugins such as Tables or Plots?

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### CODE REVIEW

File: src/plugins/plan/PlanViewProvider.js [hunk 1]
```diff
@@ -25,7 +25,9 @@ import Vue from 'vue';
 
 export default function PlanViewProvider(openmct) {
     function isCompactView(objectPath) {
-        return objectPath.find(object => object.type === 'time-strip') !== undefined;
+        let isChildOfTimeStrip = objectPath.find(object => object.type === 'time-strip');
```
Comment (nikhilmandlik) [inline src/plugins/plan/PlanViewProvider.js:28]: Looks good but wondering  about following change to avoid extra checks,
```
if (openmct.router.isNavigatedObject(objectPath)) return false;
....
```

**Review by nikhilmandlik — APPROVED** [review]
LGTM, small change if it makes sense 😄

File: src/plugins/plan/PlanViewProvider.js (hunk 1 above)
Comment (shefalijoshi) [reply src/plugins/plan/PlanViewProvider.js:28]: No we need both checks so I'd rather keep it as is.

**Comment by nikhilmandlik** [comment]
### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
