### PR TITLE
Fixes [Flexible Layout] bug with composition

### LINKED ISSUE #3679: [Flexible Layouts] Does not add objects that are saved directly in the layout
Flexible Layouts does not add any items that are directly saved in the layout, when navigated away from the layout.

## Testing Instructions

1. Create a Flexible Layout.
2. Save and Navigate away.
3. Create a sine wave generator and save into flexible layout created in step 1.
4. Navigate to the flexible layout.
5. Notice that there are no items in the flexible layout.
6. Try and drop in the same sine wave generator into the layout again.
7. Notice nothing happens. (This is bad)

### PR DESCRIPTION
**Pull request by deeptailor**
This PR fixes #3679 

## Author Checklist
Changes address original issue? Yes
Unit tests included and/or updated with changes? N/A
Command line build passes? Yes
Changes have been smoke-tested? Yes
Testing instructions included? Yes in issue

### CODE REVIEW

File: src/plugins/flexibleLayout/components/flexibleLayout.vue [hunk 1]
```diff
@@ -171,9 +172,11 @@ export default {
         }
     },
     mounted() {
+        this.buildIdentifierMap();
         this.composition = this.openmct.composition.get(this.domainObject);
         this.composition.on('remove', this.removeChildObject);
         this.composition.on('add', this.addFrame);
+        this.composition.load();
 
         this.RemoveAction = new RemoveAction(this.openmct);
```
Comment (jvigliotta) [inline src/plugins/flexibleLayout/components/flexibleLayout.vue:181]: I think you can remove this.RemoveAction and it's import now since you're using composition.remove.

**Review by jvigliotta — CHANGES_REQUESTED** [review]
Just one thing I noticed, otherwise looks good!

File: src/plugins/flexibleLayout/components/flexibleLayout.vue (hunk 1 above)
Comment (deeptailor) [reply src/plugins/flexibleLayout/components/flexibleLayout.vue]: Fixed, please review again

File: src/plugins/flexibleLayout/components/flexibleLayout.vue [hunk 2]
```diff
@@ -168,26 +168,30 @@ export default {
         },
         rowsLayout() {
             return this.domainObject.configuration.rowsLayout;
+        },
+        allContainersAreEmpty() {
+            return !this.containers.filter(container => container.frames.length).length;
```
Comment (nikhilmandlik) [inline src/plugins/flexibleLayout/components/flexibleLayout.vue:173]: may be use `this.containers.every(container => container.frames.length ===0)`

**Review by nikhilmandlik — DISMISSED** [review]
Small optional change (little too picky 😄 ) for better readable code else LGTM

File: src/plugins/flexibleLayout/components/flexibleLayout.vue (hunk 2 above)
Comment (deeptailor) [reply src/plugins/flexibleLayout/components/flexibleLayout.vue:173]: I agree, this was old code I was moving around, ill make the change

**Comment by deeptailor** [comment]
@nikhilmandlik  - Change made as requested

**Review by jvigliotta — APPROVED** [review]
### Reviewer Checklist
Check | Passed
-- | --
Changes appear to address issue?? | Y
Appropriate unit tests included? | N/A
Code style and in-line documentation are appropriate? | Y
Commit messages meet standards? | Y
Has associated issue been labelled unverified? (if PR closes issue) | Y
