### PR TITLE
Check for circular references in originalPath - 5615

### LINKED ISSUE #5615: Infinite loop in some search cases
#### Summary
Typing certain text into the search box can result in infinite requests in the network tab.
Looks like it's something to do with getOriginalPath. Suspect there is a circular reference somewhere.

#### Steps to Reproduce
1. Search for "orphan"
2. Observe that the search activity indicator appears and never disappears.
3. Observe that no results are shown
4. Open the network tab and observe that requests are firing off endlessly.

#### Environment
* Open MCT Version: 2.0.7
* Deployment Type: testathon

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by scottbell**
Closes #5615 

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Changes appear not to be breaking changes?
* [x] Appropriate unit tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Commit messages meet standards?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [x] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/api/objects/ObjectAPISpec.js [hunk 1]
```diff
@@ -377,6 +377,73 @@ describe("The Object API", () => {
...
+
+            openmct.objects.addProvider('fooNameSpace', mockObjectProvider);
+
+            mockObjectProvider.create.and.returnValue(Promise.resolve(true));
+            mockObjectProvider.update.and.returnValue(Promise.resolve(true));
+
+            openmct.objects.addProvider('fooNameSpace', mockObjectProvider);
+        });
+
+        it('can construct paths even with cycles', async () => {
```
Comment (ozyx) [inline src/api/objects/ObjectAPISpec.js:441]: Awesome test!

File: src/api/objects/ObjectAPI.js [hunk 2]
```diff
@@ -638,19 +638,37 @@ export default class ObjectAPI {
...
+            const identifierToCheck = utils.parseKeyString(keyStringToCheck);
+
+            return this.areIdsEqual(identifierToCheck, pathElement.identifier);
         });
     }
 
+    /**
+     * Given an identifier, constructs the original path by walking up its parents
+     * @param {module:openmct.ObjectAPI~Identifier} identifier
+     * @param {Array<module:openmct.DomainObject>} path an array of path objects
```
Comment (ozyx) [inline src/api/objects/ObjectAPI.js:656]: This is actually an array of domain objects right?

This is an interesting method, because although it's called `getOriginalPath`, it's actually returning a list of all ancestors to the given domainObject? I'm wondering if there is any value in some kind of `Path` object that can provide this information as either a list of ancestors, or a navigable URL, or otherwise... just thinking out loud

**Review by ozyx — CHANGES_REQUESTED** [review]
One small nitpick about the docs

File: src/api/objects/ObjectAPI.js (hunk 2 above)
Comment (scottbell) [reply src/api/objects/ObjectAPI.js:656]: > I'm wondering if there is any value in some kind of Path object that can provide this information as either a list of ancestors, or a navigable URL, or otherwise

It does seem to be a pretty common pattern throughout the OpenMCT framework to transform these path arrays to URLs and the like. Having object methods to deal with this would be handy!

**Review by ozyx — APPROVED** [review]
LGTM!
