### PR TITLE
[Edit Mode] Fixed issue with save dialog not being displayed for new objects after mutation

### LINKED ISSUE #1080: Save dialog not being displayed for new objects when mutations have been made
Detected in VISTA in a recently deployed version:

1. create new object (say, historical table)
2. add one or more telemetry elements to the table
3. press save

Expected behavior: the "save in" dialog will show and prompt the user for a name and location to save the element in.
Actual behavior: the object saves and is orphaned.

Assigning to myself to isolate further.

### PR DESCRIPTION
**Pull request by akhenry**
Fixes #1080 

### Changes
* Removed navigation listener from EditAction which previously cancelled edit mode on navigation
* Added call to `EditorCapability.cancel()' to `NavigateAction`. Although this mixes edit and browse concerns, it does not introduce a hard dependency on edit mode. Another approach I considered was a decorator for the `NavigateAction` in the edit bundle, but decorating actions is awkward in the current API, and would have added indirection that would make the code harder to follow.
* Added a new test to `NavigateActionSpec`

### Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? Y
3. Command line build passes? Y
4. Changes have been smoke-tested? Y

### CODE REVIEW

File: platform/commonUI/edit/src/actions/EditAction.js [hunk 1]
```diff
@@ -69,18 +69,14 @@ define(
...
-            }
+
             //If this is not the currently navigated object, then navigate
             // to it.
             if (this.navigationService.getNavigation() !== this.domainObject) {
                 this.navigationService.setNavigation(this.domainObject);
             }
 
-            this.navigationService.addListener(cancelEditing);
+            //this.navigationService.addListener(cancelEditing);
```
Comment (VWoeltjen) [inline platform/commonUI/edit/src/actions/EditAction.js]: Commented line here should be removed

File: platform/commonUI/edit/src/services/TransactionService.js [hunk 2]
```diff
@@ -138,7 +138,7 @@ define(
                 try {
                     results.push(onCancel());
                 } catch (error) {
-                    this.$log.error("Error committing transaction.");
+                    this.$log.error("Error cancelling transaction.");
```
Comment (VWoeltjen) [inline platform/commonUI/edit/src/services/TransactionService.js]: Good catch!

File: platform/commonUI/browse/test/navigation/NavigateActionSpec.js [hunk 3]
```diff
@@ -112,6 +140,21 @@ define(
                 });
             });
 
+            describe("in edit more", function () {
```
Comment (VWoeltjen) [inline platform/commonUI/browse/test/navigation/NavigateActionSpec.js]: Typo - "in edit mode"

File: platform/commonUI/browse/src/navigation/NavigateAction.js [hunk 4]
```diff
@@ -48,20 +48,34 @@ define(
          */
         NavigateAction.prototype.perform = function () {
             var self = this,
-                navigationAllowed = true;
+                navigateTo = this.domainObject,
+                currentObject = self.navigationService.getNavigation(),
+                editing = currentObject.hasCapability('editor') &&
```
Comment (VWoeltjen) [inline platform/commonUI/browse/src/navigation/NavigateAction.js]: I _think_ this variable assignment could be moved into `cancelIfEditing` to simplify readability of that function a bit

File: platform/commonUI/edit/src/actions/EditAction.js (hunk 1 above)
Comment (akhenry) [inline platform/commonUI/edit/src/actions/EditAction.js]: Whoops, yep, missed that one. Thanks!

**Comment by akhenry** [comment]
@VWoeltjen Changes made, back to you.

**Comment by VWoeltjen** [comment]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
