### PR TITLE
[Locator] Don't reset root unnecessarily

### LINKED ISSUE #1008: [locator widget] unclear what is happening when folders are not valid selections
When a user is using the locator widget (e.g. move, copy, link, etc), and they select a location that is invalid, the locator refreshes with no contents selected.

With scratchpad enabled, you can reproduce like so:

1. Create a folder inside of the "scratchpad" folder.
2. Create an object inside of the "my items" folder.
3. right click on the object you created in "my items" and select "move".
4. in the locator widget, expand the scratchpad folder.
5. Select the folder you created in the "scratchpad" folder as the destination.

Behavior: the locator tree collapses, the folder you attempted to select is no longer visible.  There is no message indicating why it doesn't work.

Here's a short gif showing current behavior:
clicking-is-weird

Throwing this in le guin for triage, we can move it to a later sprint after looking at it.

@charlesh88 think we'd need some design about how to show users that their selection is invalid.  Or should we grey out invalid choices?  Need some messaging to users about why this can't be done.

### PR DESCRIPTION
**Pull request by VWoeltjen**
...as this will trigger a refresh of the mct-representation for
the tree, which will in turn create a new mct-tree instance,
resulting in any expanded/collapsed state being lost.

Fixes #1008.

Also normalizes some whitespace in the associated spec.

### Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? Y
3. Command line build passes? Y
4. Changes have been smoke-tested? Y

### CODE REVIEW

File: platform/commonUI/edit/src/creation/LocatorController.js [hunk 1]
```diff
@@ -50,7 +50,7 @@ define(
                         $scope.rootObject =
                             (context && context.getRoot()) || $scope.rootObject;
                     }, 0);
-                } else if (!contextRoot) {
+                } else if (!contextRoot && !$scope.rootObject) {
                     //If no context root is available, default to the root
                     // object
                     $scope.rootObject = undefined;
```
Comment (akhenry) [inline platform/commonUI/edit/src/creation/LocatorController.js]: This line seems a little redundant, especially given the logic immediately before it.

Comment (VWoeltjen) [inline platform/commonUI/edit/src/creation/LocatorController.js]: Good point! Fixed in fdbe31cb762f673fb90c829e2e6bae7ae65403c5

**Comment by akhenry** [comment]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
