### PR TITLE
Fix complex displays not loading

### LINKED ISSUE #7857: Display became inoperable
#### Summary
In a production deployment, a complex display - which relies on a Remote Clock - became inoperable. Troubleshooting resulted in the following analysis. 1) the remote clock never receives a time via historical request. 2) The main event loop is getting blocked with style recalculations, so it fails to process telemetry values, including the current time via subscriptions. The Remote Clock relies on getting time via telemetry request or subscription. Other telemetry requests rely on Remote Clock having a time set, so they in turn get stalled.

Fix these
1. Remote Clock never receives telemetry from a historical request, due to a code regression.
2. Progress bars are very CPU intensive.
3. Plans are polling to resize internal components due to window resizes.

#### Expected vs Current Behavior
The Remote Clock gets a time set and telemetry begins to flow and views render properly

#### Steps to Reproduce
See VIPERGC-415 for full instructions, or...

#### Poor Man's Steps to Reproduce
1. Build a complex display with all the things
2. Configure to use Remote Clock
3. Open complex display on multiple (at least 3) windows
4. Refresh displays in sequence until they get stuck loading and never resolving

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available? Navigate to another view first to set remote clock, then navigate to complex display
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [x] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by davetsay**
Closes #7857 

### Describe your changes:
1. Clock
  1.1 pass in default timeContext in request options
  1.3 observe for clock tick, instead of polling, to determine if clock has time set
2. Progress Bars
  2.1 use scale instead of move animation 
3. Plan
  3.1 use a `ResizeObserver` instead of polling for size changes

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this a [notable change](../docs/src/process/release.md) that will require a special callout in the release notes? For example, will this break compatibility with existing APIs or projects that consume these plugins?

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes? #7860 
* [x] Has this been smoke tested?
* [x] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [x] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?

### CODE REVIEW

File: src/plugins/plan/components/PlanView.vue [hunk 1]
```diff
@@ -143,13 +142,15 @@ export default {
...
     this.handleConfigurationChange(this.configuration);
     this.planViewConfiguration.on('change', this.handleConfigurationChange);
     this.loadComposition();
+
+    this.resizeObserver = new ResizeObserver(this.resize);
+    this.resizeObserver.observe(this.$refs.plan);
   },
   beforeUnmount() {
-    clearInterval(this.resizeTimer);
+    this.resizeObserver.disconnect();
```
Comment (ozyx) [inline src/plugins/plan/components/PlanView.vue:153]: we should use our [ResizeObserver composable](https://github.com/nasa/openmct/blob/43cc96332856c680ab3d8b9db8877a35628a19d0/src/ui/composables/resize.js#L34) here

File: src/plugins/remoteClock/requestInterceptor.js [hunk 2]
```diff
@@ -20,16 +20,43 @@
...
+     * @returns {boolean} True if the interceptor applies, false otherwise.
+     */
+    appliesTo: (_, request) => {
       // Get the activeClock from the Global Time Context
+      /** @type {import("../../api/time/TimeContext").default} */
       const { activeClock } = openmct.time;
+      const timeContext = request?.timeContext ?? openmct.time;
+
+      if (request.strategy === 'latest' && timeContext.isRealTime()) {
+        return false;
```
Comment (ozyx) [inline src/plugins/remoteClock/requestInterceptor.js:49]: maybe a small comment above explaining the logic or referencing the ticket might be useful for future us

File: src/ui/components/progress-bar.scss [hunk 3]
```diff
@@ -1,16 +1,13 @@
...
   0% {
-    left: 0;
-    width: 0;
+    transform:scaleX(0);
   }
-  70% {
-    left: 0;
-    width: 100%;
+  90% {
+    transform:scaleX(1);
```
Comment (ozyx) [inline src/ui/components/progress-bar.scss:7]: noice

**Review by ozyx — CHANGES_REQUESTED** [review]
Looks good! Just a few suggestions

File: src/plugins/plan/components/PlanView.vue (hunk 1 above)
Comment (davetsay) [reply src/plugins/plan/components/PlanView.vue:153]: We have a composable? Will fix

Comment (davetsay) [reply src/plugins/plan/components/PlanView.vue:153]: Actually I will maybe tackle this with the e2e test pr.

File: src/api/telemetry/TelemetryAPI.js [hunk 4]
```diff
@@ -253,6 +253,10 @@ export default class TelemetryAPI {
       options.domain = this.openmct.time.getTimeSystem().key;
     }
 
+    if (!Object.hasOwn(options, 'timeContext')) {
```
Comment (akhenry) [inline src/api/telemetry/TelemetryAPI.js:256]: We should remove [the equivalent code in TelemetryConnections](https://github.com/nasa/openmct/blob/37b2660f27006ed5a29f8d2815c6284ab22cc7e6/src/api/telemetry/TelemetryCollection.js#L65), no? [It's duplicative now](https://github.com/nasa/openmct/blob/37b2660f27006ed5a29f8d2815c6284ab22cc7e6/src/api/telemetry/TelemetryCollection.js#L130).

**Review by akhenry — CHANGES_REQUESTED** [review]

File: src/plugins/remoteClock/RemoteClock.js [hunk 5]
```diff
@@ -152,15 +152,18 @@ export default class RemoteClock extends DefaultClock {
...
+          const offsets = this.openmct.time.getClockOffsets();
+          this.openmct.time.off('tick', tickListener); // Unregister the tick listener
+          resolve({
+            start: this.lastTick + offsets.start,
+            end: this.lastTick + offsets.end
+          });
+        }
+      };
+
+      this.openmct.time.on('tick', tickListener);
```
Comment (akhenry) [inline src/plugins/remoteClock/RemoteClock.js:166]: You can use `this.openmct.time.once` and remove the boilerplate code that removes the listener above.

File: src/plugins/remoteClock/requestInterceptor.js [hunk 6]
```diff
@@ -20,16 +20,44 @@
...
+     *
+     * @param {Object} _ - Unused parameter.
+     * @param {import('../../api/telemetry/TelemetryAPI').TelemetryRequestOptions} request - The request object.
+     * @returns {boolean} True if the interceptor applies, false otherwise.
+     */
+    appliesTo: (_, request) => {
       // Get the activeClock from the Global Time Context
+      /** @type {import("../../api/time/TimeContext").default} */
       const { activeClock } = openmct.time;
+      const timeContext = request?.timeContext ?? openmct.time;
```
Comment (akhenry) [inline src/plugins/remoteClock/requestInterceptor.js:46]: We don't need this any more, we know the global time context will be added to the request if it's absent.

File: src/plugins/remoteClock/RemoteClock.js (hunk 5 above)
Comment (davetsay) [reply src/plugins/remoteClock/RemoteClock.js:166]: i _think_ that is correct, but didn't do it because if for some reason there is a non positive tick. Is that possible?

Comment (akhenry) [reply src/plugins/remoteClock/RemoteClock.js:166]: In our test environments a negative time should never occur. It's not invalid in theory though, which is _WHY WE SHOULD NEVER USER 0 AS A DEFAULT VALUE FOR TIME_.

File: src/api/telemetry/TelemetryCollection.js [hunk 7]
```diff
@@ -62,9 +62,6 @@ export default class TelemetryCollection extends EventEmitter {
     this.futureBuffer = [];
     this.parseTime = undefined;
     this.metadata = this.openmct.telemetry.getMetadata(domainObject);
-    if (!Object.hasOwn(options, 'timeContext')) {
```
Comment (akhenry) [inline src/api/telemetry/TelemetryCollection.js:65]: 👍

File: src/plugins/remoteClock/RemoteClock.js (hunk 5 above)
Comment (akhenry) [reply src/plugins/remoteClock/RemoteClock.js:166]: It's fine, let's leave it as-is.

File: src/api/telemetry/TelemetryCollection.js (hunk 7 above)
Comment (davetsay) [reply src/api/telemetry/TelemetryCollection.js]: added this back. its needed after all. e2e tests caught this.

Comment (akhenry) [reply src/api/telemetry/TelemetryCollection.js]: Ok, I am guessing that this was needed here because of these lines - https://github.com/nasa/openmct/blob/vipergc-415/src/api/telemetry/TelemetryCollection.js#L87

In that case, I think the right thing to do is move the call to `standardizeRequesstOptions` to the `load()` function above those lines that depend upon the options having a default time context.

Comment (davetsay) [reply src/api/telemetry/TelemetryCollection.js:65]: ok. i've fixed this

Comment (akhenry) [reply src/api/telemetry/TelemetryCollection.js:65]: I don't see it in the `load` function? I think if we add the call to `standardize...`  to line TelemetryCollection:83 we might solve our problems here?

**Review by akhenry — CHANGES_REQUESTED** [review]

File: src/api/telemetry/TelemetryCollection.js (hunk 7 above)
Comment (akhenry) [reply src/api/telemetry/TelemetryCollection.js:65]: I still don't see it in the `load()` function? I think if we move the call to `standardizeRequestOptions(...)` to line 83 we should be good?

**Review by akhenry — CHANGES_REQUESTED** [review]

File: src/api/telemetry/TelemetryCollection.js (hunk 7 above)
Comment (davetsay) [reply src/api/telemetry/TelemetryCollection.js:65]: Calling `standardizeRequestOptions` in load breaks tests.

**Comment by davetsay** [comment]
@akhenry , ready to review again. calling `standardizeRequestOptions` in load breaks tests. I think its setting of option bounds too early, is then conflicting with what should be sent in a request on a time conductor and indepedent time conductor bounds change.

**Review by akhenry — APPROVED** [review]
