### PR TITLE
Link action fix

### LINKED ISSUE #4951: [Link Action] Unable to link root level objects
#### Summary

When you try to create a link for a root level item (ex. My Items), when you select a location, a console error blocks you from completing the action. This is due to a "parent" item being checked, but for root level objects, no parent is provided.

#### Expected vs Current Behavior

Uh, you should be able to link root level objects.

#### Steps to Reproduce

1. Right click a root level item (ex. My Items)
2. Select Create link
3. Notice errors in console

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

### PR DESCRIPTION
**Pull request by jvigliotta**
Closes #4951 

### Describe your changes:
Fixes a small bug related to the implementation of https://github.com/nasa/openmct/issues/4899

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/plugins/remove/RemoveAction.js [hunk 1]
```diff
@@ -92,23 +92,33 @@ export default class RemoveAction {
...
+        const parentKeyString = this.openmct.objects.makeKeyString(parent.identifier);
+        const childLocation = child.location;
+
+        return childLocation !== parentKeyString;
+    }
+
+    appliesTo(objectPath) {
+        const parent = objectPath[1];
+        const parentType = parent && this.openmct.types.get(parent.type);
+        const child = objectPath[0];
```
Comment (scottbell) [inline src/plugins/remove/RemoveAction.js:115]: does objectPath always have a length of at least one?

**Review by scottbell — APPROVED** [review]
All questions answered - looks good!
