### PR TITLE
Request data when switching between real time and fixed.

### LINKED ISSUE #4777: Plots in a Tabs View don't re-query when Time Conductor toggled to Local Clock
#### Summary
1. Place a Stacked Plot with some real-time data in a Tabs View.
1. Put the Time Conductor (TC) in Local Clock (RT) mode. Verify that data is visible that has some distinct values to it. 
1. Switch the TC to Fixed mode, then wait for a minute or two.
1. Switch the TC back to Local Clock.

Observe: the plot will draw traces from the time in which the TC was switched to Fixed mode directly to the time in which it was switched back to RT. This may not be the case for all plots, see this example:

It should have re-queried and filled in the data for all plots in the view.

#### Impact Check List

- [X] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [X] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Environment
* Open MCT Version: 1.8.3
* Deployment Type: /stable
* OS: Mac
* Browser: Chrome

### PR DESCRIPTION
**Pull request by shefalijoshi**
Closes #4777 

Update display bounds when switching between time conductor modes. Which in turn re-requests data.
Also add some null checks.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/plugins/plot/MctPlot.vue [hunk 1]
```diff
@@ -456,6 +456,8 @@ export default {
         },
         updateRealTime(clock) {
             this.isRealTime = clock !== undefined;
+            //re-request data if we switch from/to realtime
+            this.updateDisplayBounds(this.timeContext.bounds());
```
Comment (jvigliotta) [inline src/plugins/plot/MctPlot.vue:460]: I _think_ we may only need to do this if we switch from fixed time to realtime. Because if we're switching from realtime to fixed time, then the bounds wouldn't have changed?

File: src/plugins/timeConductor/ConductorInputsFixed.vue [hunk 2]
```diff
@@ -131,6 +131,10 @@ export default {
             this.setViewFromBounds(bounds);
         },
         clearAllValidation() {
+            if (!this.$refs.startDate || !this.$refs.endDate) {
```
Comment (jvigliotta) [inline src/plugins/timeConductor/ConductorInputsFixed.vue:134]: I'm not a 100% on what this does, but is there any case where we'd want to `clearValidationForInput` for just one of them? So, say there's a startDate, but no endDate, would we want to clear validation for just startDate? If so, maybe build the array below based on if there's is a date.

File: src/plugins/timeConductor/ConductorInputsRealtime.vue [hunk 3]
```diff
@@ -155,6 +155,10 @@ export default {
             this.setViewFromBounds(bounds);
         },
         clearAllValidation() {
+            if (!this.$refs.startOffset || !this.$refs.endOffset) {
```
Comment (jvigliotta) [inline src/plugins/timeConductor/ConductorInputsRealtime.vue:158]: Same question as InputsFixed.

**Review by jvigliotta — CHANGES_REQUESTED** [review]
Good job finding this! I had a couple questions.

File: src/plugins/timeConductor/ConductorInputsFixed.vue (hunk 2 above)
Comment (shefalijoshi) [reply src/plugins/timeConductor/ConductorInputsFixed.vue:134]: OK I can do that.

File: src/plugins/plot/MctPlot.vue (hunk 1 above)
Comment (shefalijoshi) [reply src/plugins/plot/MctPlot.vue]: Done

File: src/plugins/timeConductor/ConductorInputsFixed.vue (hunk 2 above)
Comment (shefalijoshi) [reply src/plugins/timeConductor/ConductorInputsFixed.vue]: Done

**Review by jvigliotta — APPROVED** [review]
Nice work! LGTM!
