### PR TITLE
[CLA Approved] Fix references to telemetry data "unit" in the plot LEGEND form, top legend display and documentation

### LINKED ISSUE #3562: [Documentation] API.md telemetry value specification uses "units" field instead of "unit"
The current API documentation in [API.md](https://github.com/nasa/openmct/blob/master/API.md) incorrectly (?) specifies a field on telemetry values called "units" instead of the currently used "unit".

This means that following the API documentation will leave users (me included, after recently updating Open MCT in [one of my projects](https://github.com/AudunVN/mct-depot)) confused as to why value units don't show up anywhere despite being included as described in the documentation.

### LINKED ISSUE #5540: "units" displayed instead of "unit" in the plot top legend and legend form
#### Summary

The options "Show When Collapsed" and "Show When Expanded" in the Overlay Plot right pane form display "units" instead of "unit" (we disregard the case intentionally here), when just viewing as well as editing. Not a big deal, but this is not coherent with the choice of naming this field "unit" elsewhere (refer to #3562 ) and can lead to confusion. 

image
image

#### Expected vs Current Behavior

The user should always see the same reference to this field: "unit", "Unit". More specifically, the `config.legend` field should be called "unit", as the existing field `PlotSeries.metadata["<some-y-key>"].unit` and the "unit" field of the Telemetry "range" values.

#### Steps to Reproduce

1. Create an Overlay Plot and drag in a telemetry entry.
2. Still in editing mode, on the right pane, scroll down to the LEGEND form and observe the options "When Collapsed Show" and "When Expanded Show".
3. Click "Save and finish editing", this switches the vue to view mode.
4. Observe the options "Show When Collapsed" and "Show When Expanded". 

#### Environment

<details>
<summary>`npx envinfo --system --browsers --npmPackages --binaries --markdown` command output</summary>

## System:
 - OS: macOS 10.15.7
 - CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
 - Memory: 21.07 GB / 64.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
 - npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
## Browsers:
 - Chrome: 103.0.5060.134
 - Firefox: 99.0.1
 - Safari: 15.5
## npmPackages:
 - @babel/eslint-parser: 7.18.2 => 7.18.2
 - @braintree/sanitize-url: 6.0.0 => 6.0.0
 - @percy/cli: 1.2.1 => 1.2.1
 - @percy/playwright: 1.0.4 => 1.0.4
 - @playwright/test: 1.23.0 => 1.23.0
 - @types/eventemitter3: ^1.0.0 => 1.2.0
 - @types/jasmine: ^4.0.1 => 4.0.3
 - @types/karma: ^6.3.2 => 6.3.3
 - @types/lodash: ^4.14.178 => 4.14.182
 - @types/mocha: ^9.1.0 => 9.1.1
 - ajv: ^6.9.1 => 6.12.6
 - babel-loader: 8.2.5 => 8.2.5
 - babel-plugin-istanbul: 6.1.1 => 6.1.1
 - codecov: 3.8.3 => 3.8.3
 - comma-separated-values: 3.6.4 => 3.6.4
 - copy-webpack-plugin: 11.0.0 => 11.0.0
 - cross-env: 7.0.3 => 7.0.3
 - css-loader: 4.0.0 => 4.0.0
 - d3-axis: 3.0.0 => 3.0.0
 - d3-scale: 3.3.0 => 3.3.0
 - d3-selection: 3.0.0 => 3.0.0
 - eslint: 8.18.0 => 8.18.0
 - eslint-plugin-compat: 4.0.2 => 4.0.2
 - eslint-plugin-playwright: 0.9.0 => 0.9.0
 - eslint-plugin-vue: 9.1.1 => 9.1.1
 - eslint-plugin-you-dont-need-lodash-underscore: 6.12.0 => 6.12.0
 - eventemitter3: 1.2.0 => 1.2.0
 - express: 4.18.1 => 4.18.1
 - file-saver: 2.0.5 => 2.0.5
 - git-rev-sync: 3.0.2 => 3.0.2
 - html2canvas: 1.4.1 => 1.4.1
 - imports-loader: 0.8.0 => 0.8.0
 - jasmine-core: 4.2.0 => 4.2.0
 - jsdoc: 3.5.5 => 3.5.5
 - karma: 6.3.20 => 6.3.20
 - karma-chrome-launcher: 3.1.1 => 3.1.1
 - karma-cli: 2.0.0 => 2.0.0
 - karma-coverage: 2.2.0 => 2.2.0
 - karma-coverage-istanbul-reporter: 3.0.3 => 3.0.3
 - karma-firefox-launcher: 2.1.2 => 2.1.2
 - karma-jasmine: 5.1.0 => 5.1.0
 - karma-junit-reporter: 2.0.1 => 2.0.1
 - karma-sourcemap-loader: 0.3.8 => 0.3.8
 - karma-spec-reporter: 0.0.34 => 0.0.34
 - karma-webpack: 5.0.0 => 5.0.0
 - lighthouse: 9.6.1 => 9.6.1
 - location-bar: 3.0.1 => 3.0.1
 - lodash: 4.17.21 => 4.17.21
 - mini-css-extract-plugin: 2.6.1 => 2.6.1
 - moment: 2.29.4 => 2.29.4
 - moment-duration-format: 2.3.2 => 2.3.2
 - moment-timezone: 0.5.34 => 0.5.34
 - node-bourbon: 4.2.3 => 4.2.3
 - nyc: 15.1.0 => 15.1.0
 - painterro: 1.2.78 => 1.2.78
 - playwright: >=1 => 1.21.1
 - plotly.js-basic-dist: 2.12.0 => 2.12.0
 - plotly.js-gl2d-dist: 2.12.0 => 2.12.0
 - printj: 1.3.1 => 1.3.1
 - request: 2.88.2 => 2.88.2
 - resolve-url-loader: 5.0.0 => 5.0.0
 - sass: 1.52.2 => 1.52.2
 - sass-loader: 13.0.2 => 13.0.2
 - sinon: 14.0.0 => 14.0.0
 - style-loader: ^1.0.1 => 1.3.0
 - uuid: 8.3.2 => 8.3.2
 - vue: 2.6.14 => 2.6.14
 - vue-eslint-parser: 9.0.2 => 9.0.2
 - vue-loader: 15.9.8 => 15.9.8
 - vue-template-compiler: 2.6.14 => 2.6.14
 - webpack: 5.68.0 => 5.68.0
 - webpack-cli: 4.10.0 => 4.10.0
 - webpack-dev-middleware: 5.3.3 => 5.3.3
 - webpack-hot-middleware: 2.25.1 => 2.25.1
 - webpack-merge: 5.8.0 => 5.8.0

</details>

* Open MCT Version: `master` branch, SHA 488cd82ae168a39c3d64a8224077972035b56a2d
* Deployment Type: openmct connected to yarp.js telemetry server
* OS: MacOS Catalina version 10.15.7
* Browser: Chrome Version 103.0.5060.134

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by nunoguedelha**
Closes #3562 
Closes #5540 

### Describe your changes:

The "unit" or "units" are not displayed at all or inconsistently displayed in the plot legends. As reported in https://github.com/nasa/openmct/issues/3562, the telemetry value blocks have a field called "unit" which is documented in the main [API])(https://github.com/nasa/openmct/blob/488cd82ae168a39c3d64a8224077972035b56a2d/API.md) as "units", but both "unit" and "units" syntax are inconsistently used in the OpenMCT plugins code and documentation.

- Rename the `units` attribute to `unit` when referencing the telemetry data "unit" within:
   - the legend-form vue for setting the `valueToShowWhenCollapsed` and `showUnitsWhenExpanded` and displaying the available choices in write mode,
   - the plot-options-browse vue for displaying the selected choices within the form in read mode,
   - the plot-legend-item-collapsed when checking which field to display.
- Update API documentation

<details>
<summary>Notes on the analysis</summary>

Here are the greps helping to cover all relevant occurrences of `<some-path>.units`, `"units"`, `Units` (not part of a word). 
=> We will address only the grep matches related to the plot top legend and plot form "LEGEND".
=> We only cared about whole-word occurrences, which seem to be more relevant to the clarity of the code.

##### All relevant occurrences related to plot legend
```
src/plugins/plot/inspector/forms/LegendForm.vue:                <option value="units">Units</option>
src/plugins/plot/legend/PlotLegendItemCollapsed.vue:        v-show="!!highlights.length && (valueToShowWhenCollapsed !== 'none' && valueToShowWhenCollapsed !== 'units')"
src/plugins/plot/inspector/forms/LegendForm.vue:                > Units</li>
src/plugins/plot/inspector/PlotOptionsBrowse.vue:                    <span v-if="showUnitsWhenExpanded">Units</span>
```

There is no functional impact because the `units` field here belongs to the structure `legend` and is used to activate/deactivate the display of the actual `metadata.value[key].unit`.

</details>

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
   Before change - All:388, Passed:33, Failed:1, Flaky:2, Skipped:352
   After change - All:388, Passed:34, Failed:1, Flaky:2, Skipped:351
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by ozyx** [comment]
Thank you so much for your contribution! If you haven't already, please complete and submit a [Contributor License Agreement (CLA)](https://github.com/nasa/openmct/discussions/3821). This is required before we can approve/merge your code.  Thanks again, we will be taking a look at this shortly!

**Comment by nunoguedelha** [comment]
> please complete and submit a [Contributor License Agreement (CLA)](https://github.com/nasa/openmct/discussions/3821).

I've already sent it a week ago. I guess it takes some time to be processed. Thanks for the heads up.

**Comment by unlikelyzero** [comment]
@nunoguedelha would you mind pulling in the changes from master? It'll allow us to see the visual changes on the PR

**Comment by nunoguedelha** [comment]
Sure @unlikelyzero , I'm on it.

I guess you meant merging the changes from master into the PR branch, instead of doing a rebase.

**Comment by nunoguedelha** [comment]
Done!

**Comment by unlikelyzero** [comment]
@nunoguedelha awesome. Take a look at how our visual tests detected the change!
https://percy.io/b2e34b17/openmct/builds/20144065?utm_campaign=b2e34b17&utm_content=openmct&utm_source=github_status_public

While we review this PR, can you see if there are any e2e or unit tests you can add in this area so that this doesn't change in the future?

**Comment by nunoguedelha** [comment]
Sorry @unlikelyzero , I was offline from Tuesday on. I'll take a look on Monday at the e2e or eventual unit tests I could add here as you recommended. Thank you!

**Comment by nunoguedelha** [comment]
> @nunoguedelha awesome. Take a look at how our visual tests detected the change!
> https://percy.io/b2e34b17/openmct/builds/20144065?utm_campaign=b2e34b17&utm_content=openmct&utm_source=github_status_public

btw, really nice the visual tests with Percy.

**Comment by charlesh88** [comment]
After looking into this more deeply: both "unit" and "units" can be correct depending on the context.
- The current API documentation with "units" is incorrect and should be fixed.
- Use "unit" when referring to a singleton usage case. For example, "unit" would be correct when referring to the unit of measurement used by a given telemetry point.
- "Units" is correct when there can be more than one unit of measurement. For example, in the UI where the user can configure what is displayed in a plot legend, "Units" is correct because the units displayed can be more than one of a kind.

File: src/plugins/plot/inspector/forms/LegendForm.vue [hunk 1]
```diff
@@ -89,7 +89,7 @@
                     v-model="showUnitsWhenExpanded"
                     type="checkbox"
                     @change="updateForm('showUnitsWhenExpanded')"
-                > Units</li>
+                > Unit</li>
```
Comment (charlesh88) [inline src/plugins/plot/inspector/forms/LegendForm.vue:92]: Per comments 8/14/22 this change should be reverted please.

File: src/plugins/plot/legend/PlotLegendItemCollapsed.vue [hunk 2]
```diff
@@ -41,7 +41,7 @@
         <span class="plot-series-name">{{ nameWithUnit }}</span>
     </div>
     <div
-        v-show="!!highlights.length && (valueToShowWhenCollapsed !== 'none' && valueToShowWhenCollapsed !== 'units')"
+        v-show="!!highlights.length && (valueToShowWhenCollapsed !== 'none' && valueToShowWhenCollapsed !== 'unit')"
```
Comment (charlesh88) [inline src/plugins/plot/legend/PlotLegendItemCollapsed.vue:44]: Per comments 8/14/22 this change should be reverted please.

**Review by charlesh88 — APPROVED** [review]
LGTM!

File: src/plugins/plot/inspector/forms/LegendForm.vue [hunk 3]
```diff
@@ -54,7 +54,7 @@
                 <option value="nearestValue">Nearest value</option>
                 <option value="min">Minimum value</option>
                 <option value="max">Maximum value</option>
-                <option value="units">Units</option>
+                <option value="unit">Unit</option>
```
Comment (jvigliotta) [inline src/plugins/plot/inspector/forms/LegendForm.vue:57]: @charlesh88 Did you want this to be "Units" or maybe "Unit(s)"? You had mentioned there could be more than one type?

**Review by jvigliotta — APPROVED** [review]
LGTM as well! Thanks for the contribution!

**Comment by jvigliotta** [comment]
@nunoguedelha Hi! This is all set, can you update with the base branch and we'll merge this in. Thanks!

**Comment by nunoguedelha** [comment]
Thank you all for your reviews.

@jvigliotta , sorry for the delay, I'm back from summer break for good this time. Updating now with `master` branch...

File: src/plugins/plot/inspector/forms/LegendForm.vue (hunk 3 above)
Comment (nunoguedelha) [reply src/plugins/plot/inspector/forms/LegendForm.vue:57]: @jvigliotta @charlesh88 , I didn't see this conversation resolved, but I assume, from the review outcome, that my initial change (`Unit`) was accepted in this case.

Nevertheless, I understand @charlesh88's point of view, which makes sense to me too on a use case basis. Let me add a few comments just for closure on the topic:
- In lines 52 to 57, the option values are related to a single telemetry point or singleton as you mentioned.
- Regarding the values to display when the legend is expanded (https://github.com/nasa/openmct/blob/9e545f763afb19d2e96e8d75d91c7084b0947850/src/plugins/plot/inspector/forms/LegendForm.vue#L67-L93), the available options also relate to a single telemetry entry (`Nearest timestamp`, `Nearest value`, etc).
<br>
So, for all these cases, we would agree on the choice of `Unit`, and to be thorough, it would have been better to rename `showUnitsWhenExpanded` to `showUnitWhenExpanded`.
