### PR TITLE
Fix navigation warnings, tidy editing, navigation, browse logic.

### LINKED ISSUE #1360: [Navigation] Navigation confirmation not working with any objects
Currently openmct will allow navigation away from a dirty object without a warning. 

eg. 
1. Edit a display layout
2. Drag in a telemetry point
3. Click on another object to navigate away
4. Application merrily navigates to the other object without a warning

### PR DESCRIPTION
**Pull request by larkin**
I have done quite a lot of hand testing on trees, locators, search results, and editing, but happy to test other interactions if there are things I might have missed.  Commit messages have a lot of detail, though I've copied some of that here for the benefit of the reviewer.

Resolves #1360.

# Navigation Changes

Remove policy checking in navigation action and depend on navigation
service to provide those checks.

* Register checkFunctions with navigationService.checkBeforeNavigation
  which returns a function for unregistering them.
* navigationService.setNavigation will run checks before allowing
  navigation, unless a `force` argument is supplied.
  
Remove mct-before-unload, and move the functionality to the navigation
service.  The navigation service considers "unload" to be a navigation
event and prompts in much the same way as it would before any other
navigation event.

# TreeView Changes

Add methods to tree view via scope for more fine grained control.

Can supply a "allowSelection" function which should return true
if a given selection is allowed.  This is executed before a node
is selected and allows you to prevent selection.  Before this, if
you wanted to prevent the selection from changing, you had to wait
for it to change and then change it back to the original value.

Can also supply an "onSelection" function which is called when a
value is successfully selected.  This allows you to handle the
selection event without waiting for digest.  You can still $watch
"selectedObject" if you prefer.

Additionally, this changes the tree node to trigger a digest only
when the value is set via a MouseClick, instead of every time.

# Browse Controller:

BrowseController uses new MCTTreeView parameters to prevent navigation
events before triggering digests.  It also no longer sets navigation
more frequently than it should.

# Edit Representation and Edit Controller:

Navigation action is no longer responsible for exiting edit mode.

Simplify edit registration and remove extra abstractions.  No longer
attach a status listener for every representation-- just use a single watch
for the edit controller.  Simplifies logic involved in switching controllers.

EditObjectController now exits edit mode when it is destroyed.
It also injects a check function in the navigation service to
replace the old functionality implemented in EditNavigationPolicy.

# Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? Y
3. Command line build passes? Y
4. Changes have been smoke-tested? Y

### CODE REVIEW

File: platform/commonUI/browse/src/navigation/NavigateAction.js [hunk 1]
```diff
@@ -47,36 +44,12 @@ define(
...
-
-            function navigate() {
-                return self.navigationService.setNavigation(navigateTo);
-            }
-
-            if (allow()) {
-                return cancelIfEditing().then(navigate);
-            } else {
-                return this.$q.when(false);
+            if (this.navigationService.shouldNavigate()) {
```
Comment (VWoeltjen) [inline platform/commonUI/browse/src/navigation/NavigateAction.js]: The one thing that I'm feeling iffy about here is the addition of the `shouldNavigate` method to NavigationService. I think it would be non-obvious during maintenance which `setNavigation` calls should  depend upon this check and which should not.

Is there any reason not to include this check/prompt as part of the `setNavigation` call? `setNavigation` could also return the promise that's needed here (rejected if the navigation does not occur for some reason), which would in turn make it simpler to change the prompt from a `window.confirm` to a custom asynchronous dialog at a later time.

File: docs/src/guide/index.md [hunk 2]
```diff
@@ -1338,20 +1338,6 @@ are supported:
 
 Open MCT defines several Angular directives that are intended for use both 
 internally within the platform, and by plugins. 
-
-## Before Unload
```
Comment (VWoeltjen) [inline docs/src/guide/index.md]: Good to see number of directives (and scope of Angular reliance) decrease!

File: platform/commonUI/browse/src/navigation/NavigateAction.js (hunk 1 above)
Comment (larkin) [inline platform/commonUI/browse/src/navigation/NavigateAction.js]: Using an asynchronous navigation results in a tiny amount of latency which I didn't like, but there's always the async navigate action which is useful for chaining actions.  There's a reasonable difference between the two.

I think there's a possibility to change it in the future and don't think it would be hard to change, happy to re-evaluate if we start putting setNavigation calls all over the place.  At this point I was happy to cut out some code and make it easier to follow the behavior.

Comment (VWoeltjen) [inline platform/commonUI/browse/src/navigation/NavigateAction.js]: That makes sense; the overall code reduction associated with this changeset is great, and I'm fine with leaving those changes as future refactors-if-necessary

**Comment by VWoeltjen** [comment]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
