### PR TITLE
Fix stacked plot child selection

### LINKED ISSUE #6261: Stacked Plots don't allow child selection while editing
#### Expected vs Current Behavior
Stacked Plots must allow child selection.

#### Steps to Reproduce

1. Edit a Stacked Plot, add at least one telemetry point.
2. While editing, click the child plot.
3. The child should select and hilite with a dashed border, but doesn't.

#### Environment

* Open MCT Version:  2.1.6-SNAPSHOT
* Deployment Type:  /testathon
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by shefalijoshi**
Closes #6261 

### Describe your changes:
When there are no annotations and no new annotation selections, make sure the plot is still selected.

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [x] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [x] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Review by scottbell — APPROVED** [review]
LGTM

**Comment by scottbell** [comment]
https://user-images.githubusercontent.com/9853862/216672866-27db7717-6e0a-468d-89ae-2ffa916a2028.mov

File: src/plugins/plot/MctPlot.vue [hunk 1]
```diff
@@ -1190,28 +1190,42 @@ export default {
         selectNearbyAnnotations(event) {
             // need to stop propagation right away to prevent selecting the plot itself
             event.stopPropagation();
-            if (!this.annotationViewingAndEditingAllowed || this.annotationSelections.length) {
+
+            const nearbyAnnotations = this.gatherNearbyAnnotations();
+
+            if (this.annotationViewingAndEditingAllowed && this.annotationSelections.length) {
```
Comment (ozyx) [inline src/plugins/plot/MctPlot.vue:1196]: Let's just put 
```js
if (!this.annotationViewingAndEditingAllowed) {
    return;
}
```

after `stopPropagation()` and remove the redundant check from the other conditions?

**Review by ozyx — CHANGES_REQUESTED** [review]
Looks good overall. Left one refactor suggestion, and we should add some e2e coverage for this before we merge.

File: src/plugins/plot/MctPlot.vue (hunk 1 above)
Comment (shefalijoshi) [reply src/plugins/plot/MctPlot.vue:1196]: No, that would be incorrect. If annotations are not allowed, we should fallback to plot selection - `this.selectPlot()`

File: e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js [hunk 2]
```diff
@@ -29,29 +29,36 @@ const { test, expect } = require('../../../../pluginFixtures');
...
+    let stackedPlot;
 
-    test('Using the remove action removes the correct plot', async ({ page }) => {
+    test.beforeEach(async ({ page }) => {
+        //Open a browser, navigate to the main page, and wait until all networkevents to resolve
         await page.goto('/', { waitUntil: 'networkidle' });
-        const overlayPlot = await createDomainObjectWithDefaults(page, {
-            type: "Overlay Plot"
+        stackedPlot = await createDomainObjectWithDefaults(page, {
+            type: "Stacked Plot"
```
Comment (ozyx) [inline e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js:38]: lol nice catch

File: e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js [hunk 3]
```diff
@@ -76,4 +83,20 @@ test.describe('Stacked Plot', () => {
...
     });
+
+    test('Selecting a child plot shows it\'s properties in the inspector.', async ({ page }) => {
+
+        await page.goto(stackedPlot.url);
+
+        //Click on the 2nd plot canvas - There will be 2 canvases for each swg, so we click on the 3rd canvas
+        await page.locator('canvas').nth(3).click();
+
+        // Expand the elements pool vertically
```
Comment (ozyx) [inline e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js:94]: this comment doesn't seem to match what's happening below?

File: e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js [hunk 4]
```diff
@@ -76,4 +83,20 @@ test.describe('Stacked Plot', () => {
         await expect(page.locator('.js-elements-pool__tree >> text=swg b')).toHaveCount(0);
         await expect(page.locator('.js-elements-pool__tree >> text=swg c')).toHaveCount(1);
     });
+
+    test('Selecting a child plot shows it\'s properties in the inspector.', async ({ page }) => {
+
+        await page.goto(stackedPlot.url);
+
+        //Click on the 2nd plot canvas - There will be 2 canvases for each swg, so we click on the 3rd canvas
+        await page.locator('canvas').nth(3).click();
```
Comment (ozyx) [inline e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js:92]: We should improve this selector so we can avoid using `nth(i)`

File: src/plugins/plot/MctPlot.vue (hunk 1 above)
Comment (ozyx) [reply src/plugins/plot/MctPlot.vue:1196]: so it's okay to do `this.selectPlot()` regardless of whether `this.annotationViewingAndEditingAllowed` is true or false?

I'm a bit confused here

File: e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js [hunk 5]
```diff
@@ -76,4 +83,20 @@ test.describe('Stacked Plot', () => {
...
+
+        // Expand the elements pool vertically
+        const propertiesInspector = await page.locator('.js-inspector-views');
+        await expect(propertiesInspector.locator('.js-series-properties >> h2')).toContainText("Plot Series");
```
Comment (ozyx) [inline e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js:96]: We should confirm this with all elements in the stacked plot, and we should verify it works while in edit mode also

File: e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js [hunk 6]
```diff
@@ -76,4 +83,20 @@ test.describe('Stacked Plot', () => {
...
+        await expect(propertiesInspector.locator('.js-yaxis-properties >> h2')).toContainText("Y Axis");
+
+        const plotSeriesItems = await propertiesInspector.locator('.js-series-properties .c-object-label');
```
Comment (ozyx) [inline e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js:99]: remove unnecessary await

File: e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js [hunk 7]
```diff
@@ -76,4 +83,20 @@ test.describe('Stacked Plot', () => {
...
+
+    test('Selecting a child plot shows it\'s properties in the inspector.', async ({ page }) => {
+
+        await page.goto(stackedPlot.url);
+
+        //Click on the 2nd plot canvas - There will be 2 canvases for each swg, so we click on the 3rd canvas
+        await page.locator('canvas').nth(3).click();
+
+        // Expand the elements pool vertically
+        const propertiesInspector = await page.locator('.js-inspector-views');
```
Comment (ozyx) [inline e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js:95]: remove unnecessary await

File: src/ui/inspector/InspectorViews.vue [hunk 8]
```diff
@@ -21,7 +21,7 @@
  *****************************************************************************/
 
 <template>
-<div></div>
+<div class="js-inspector-views"></div>
```
Comment (ozyx) [inline src/ui/inspector/InspectorViews.vue:24]: If this is solely used for e2e, we should consider using an `aria-label` instead

File: src/ui/inspector/ElementsPool.vue [hunk 9]
```diff
@@ -34,7 +34,7 @@
         <ul
             v-if="elements.length > 0"
             id="inspector-elements-tree"
-            class="c-tree c-elements-pool__tree"
+            class="c-tree c-elements-pool__tree js-elements-pool__tree"
```
Comment (ozyx) [inline src/ui/inspector/ElementsPool.vue:37]: we can select on the `id` here instead of adding another class for e2e

File: src/plugins/plot/inspector/PlotOptionsBrowse.vue [hunk 10]
```diff
@@ -26,7 +26,7 @@
 >
     <ul
         v-if="!isStackedPlotObject"
-        class="c-tree"
+        class="c-tree js-series-properties"
```
Comment (ozyx) [inline src/plugins/plot/inspector/PlotOptionsBrowse.vue:29]: we should consider using an `aria-label` here instead of an extra class if used solely for e2e

**Review by ozyx — CHANGES_REQUESTED** [review]
Looking good so far. I noticed that we can only switch between properties of objects if clicking on them while not in edit mode. Once in edit mode, if you click the canvas, it will switch to the parent object. SO we are unable to switch between elements while in edit mode, something I think we were able to do previously?

Other than that,  got some suggestions for improving the e2e test and selectors.

File: src/plugins/plot/inspector/PlotOptionsBrowse.vue (hunk 10 above)
Comment (shefalijoshi) [reply src/plugins/plot/inspector/PlotOptionsBrowse.vue:29]: I plan to use this for adding unit tests at a later point.

File: src/ui/inspector/ElementsPool.vue (hunk 9 above)
Comment (shefalijoshi) [reply src/ui/inspector/ElementsPool.vue:37]: I'm following the pattern you used for Overlay Plots where you used the js class. Has that pattern changed?

File: src/ui/inspector/InspectorViews.vue (hunk 8 above)
Comment (shefalijoshi) [reply src/ui/inspector/InspectorViews.vue:24]: Hmm There is nothing here to label though. It represents a section. Adding a label doesn't make sense?

File: e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js (hunk 4 above)
Comment (shefalijoshi) [reply e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js:92]: I could try to grab the plot div first, but we will always need to click on the 1st canvas, so it will still be nth(1). But then the 1 is fixed.

File: src/ui/inspector/InspectorViews.vue (hunk 8 above)
Comment (ozyx) [reply src/ui/inspector/InspectorViews.vue:24]: It's an accessible label, not a visible label. It will be used for a11y screen readers and for selectors in our e2e tests

File: src/plugins/plot/inspector/PlotOptionsBrowse.vue (hunk 10 above)
Comment (ozyx) [reply src/plugins/plot/inspector/PlotOptionsBrowse.vue:29]: We should add it then when you add the unit tests instead of adding an unused class, but also we should update the e2e tests to not be reliant on this.

if it has an accessible name (label, aria-label, etc) then we can use role selectors to deterministically select on this without the need of another class:

```js
expect(page.getByRole('list', { name: "Plot series properties" }).locator('h2')).toContainText("Plot Series");
```

File: e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js (hunk 5 above)
Comment (shefalijoshi) [reply e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js:96]: Done.

File: e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js (hunk 4 above)
Comment (ozyx) [reply e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js:92]: Can we add a11y to the canvases maybe? aria-label?

**Review by ozyx — APPROVED** [review]
