### PR TITLE
5361 Tags not persisting when several notebook entries are created at once

### LINKED ISSUE #5361: Tags not persisting locally
#### Summary
Tagging a notebook entry, and then returning to a notebook entry, doesn't display the tags.

#### Expected vs Current Behavior
Tags should display

#### Steps to Reproduce
For original issue:
1. Tag a notebook entry
2. Navigate away
3. Observe entry is lacking tags

For @ozyx's issue:
1. Create several notebook entries in the same notebook
2. Quickly add one tag to them all
3. Quickly navigate away, then back to the notebook
4. Observe some entries may be missing added tags

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [X] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by scottbell**
Closes #5361 

### Describe your changes:
Add tag with annotation creation to avoid race condition

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Changes appear not to be breaking changes?
* [x] Appropriate unit tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Commit messages meet standards?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [x] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/api/annotation/AnnotationAPI.js [hunk 1]
```diff
@@ -172,17 +172,19 @@ export default class AnnotationAPI extends EventEmitter {
                 name: contentText,
                 domainObject: targetDomainObject,
                 annotationType,
-                tags: [],
+                tags: [tag],
```
Comment (scottbell) [inline src/api/annotation/AnnotationAPI.js:175]: either create the annotation with the new tag, or mutate, but don't try to both at once.

File: e2e/tests/plugins/notebook/tags.e2e.spec.js [hunk 2]
```diff
@@ -137,10 +146,55 @@ test.describe('Tagging in Notebooks', () => {
...
+        // Click Clock
+        await page.click('text=Clock');
+        // Click button:has-text("OK")
+        await Promise.all([
+            page.waitForNavigation(),
+            page.locator('[name="mctForm"] >> text=My Items').click(),
+            page.locator('button:has-text("OK")').click()
+        ]);
+
+        await page.click('.c-disclosure-triangle');
```
Comment (unlikelyzero) [inline e2e/tests/plugins/notebook/tags.e2e.spec.js:164]: what element is this?

File: e2e/tests/plugins/notebook/tags.e2e.spec.js [hunk 3]
```diff
@@ -137,10 +146,55 @@ test.describe('Tagging in Notebooks', () => {
...
+        await page.click('text="Unnamed Notebook"');
+
+        for (let iteration = 0; iteration < ITERATIONS; iteration++) {
+            const entryLocator = `[aria-label="Notebook Entry"] >> nth = ${iteration}`;
+            await expect(page.locator(entryLocator)).toContainText("Science");
+            await expect(page.locator(entryLocator)).toContainText("Driving");
+        }
+
         //Go to baseURL
         await page.reload();
```
Comment (unlikelyzero) [inline e2e/tests/plugins/notebook/tags.e2e.spec.js:188]: There are some timing issues associated with page.reload(). I would try to add some sort of logic to ensure everything has stabilized and is ready to be interacted with.

File: e2e/tests/plugins/notebook/tags.e2e.spec.js [hunk 4]
```diff
@@ -31,44 +31,53 @@ const { test } = require('../../../fixtures');
...
+        const entryLocator = `[aria-label="Notebook Entry Input"] >> nth = ${iteration}`;
+        await page.locator(entryLocator).click();
+        await page.locator(entryLocator).fill(`Entry ${iteration}`);
+    }
+
 }
 
 /**
   * Creates a notebook object, adds an entry, and adds a tag.
   * @param {import('@playwright/test').Page} page
```
Comment (unlikelyzero) [inline e2e/tests/plugins/notebook/tags.e2e.spec.js:60]: I think this needs to be updated with params for iterations

File: e2e/tests/plugins/notebook/tags.e2e.spec.js [hunk 5]
```diff
@@ -31,44 +31,53 @@ const { test } = require('../../../fixtures');
   * Creates a notebook object and adds an entry.
   * @param {import('@playwright/test').Page} page
```
Comment (unlikelyzero) [inline e2e/tests/plugins/notebook/tags.e2e.spec.js:32]: I think this needs to be updated with params for the iterations param

File: e2e/tests/plugins/notebook/tags.e2e.spec.js (hunk 2 above)
Comment (scottbell) [reply e2e/tests/plugins/notebook/tags.e2e.spec.js:164]: The little arrow/triangle next to the tree item that expands the tree to show objects.

**Review by ozyx — APPROVED** [review]
LGTM
