### PR TITLE
Format ISO datetime to allow text wrapping in Imagery view thumbs

### LINKED ISSUE #3412: Image thumbnail display is broken
From hulk/viper:

Screen Shot 2020-09-30 at 6 13 59 PM

Fix and deploy asap ahead of next week's sims.

### PR DESCRIPTION
**Pull request by charlesh88**
Fixes #3412. Replace "T" with space character in datetime values at display time to allow proper formatting. See #3412 for testing notes.

### Author Checklist
1. Changes address original issue? Y
1. Unit tests included and/or updated with changes? N/A
1. Command line build passes? Y
1. Changes have been smoke-tested? **Kind of**. Cannot duplicate ISO format of data locally with Example Imagery to test solution, but code has been run locally and works properly with existing UTC-style data.

### CODE REVIEW

File: src/plugins/imagery/components/ImageryViewLayout.vue [hunk 1]
```diff
@@ -153,9 +153,11 @@ export default {
                 : this.imageUrl;
         },
         getTime(datum) {
-            return datum
+            let dateTimeStr = datum
                 ? this.timeFormat.format(datum)
                 : this.time;
+            // Replace ISO "T" with a space to allow wrapping
+            return dateTimeStr ? dateTimeStr.replace("T"," ") : "";
```
Comment (shefalijoshi) [inline src/plugins/imagery/components/ImageryViewLayout.vue:160]: This is fine for now, but we need a more generic solution to this problem. Especially if they're expecting to see the `T` in the formatted output.
Since the `T` in ISO time indicates the beginning of the time element. Maybe instead of eliminating the `T` can we keep it and put a space before it instead? Like this

`2020-10-01 T22:50:49.897Z`

**Review by shefalijoshi — CHANGES_REQUESTED** [review]

File: src/plugins/imagery/components/ImageryViewLayout.vue (hunk 1 above)
Comment (charlesh88) [reply src/plugins/imagery/components/ImageryViewLayout.vue:160]: The T is needed when the it's all smashed together, but the space makes it more readable and it gets wrapped to 2 lines in the thumb element - it's easier to parse without the T in that case.

Agree on the more generic solution. A better approach here I think would be to use proper time-formatting code that can handle a variety of time formats as input, and give me back separated date and time as two values. Wrapping the text using a space character is too brittle.

Comment (shefalijoshi) [reply src/plugins/imagery/components/ImageryViewLayout.vue:160]: I see your point.

**Review by shefalijoshi — APPROVED** [review]

**Comment by shefalijoshi** [comment]
I will merge once the linter errors are fixed.

**Comment by charlesh88** [comment]
Unit tested on hulk and works as designed. IMO we should merge this ASAP.

**Comment by charlesh88** [comment]
> I will merge once the linter errors are fixed.

Linting fixed, update pushed.

File: src/plugins/imagery/components/ImageryViewLayout.vue (hunk 1 above)
Comment (akhenry) [reply src/plugins/imagery/components/ImageryViewLayout.vue]: The problem, as I see it, is that we have conflating parsing raw telemetry data with formatting for human consumption in our API. These are two different problems, and they're not necessarily linked. Telemetry metadata should specify a "parser" for telemetry timestamps, not a formatter. Formatting for human consumption is a separate problem, and should be handled as such. For one, it needs to be context-sensitive. What's appropriate for a table doesn't necessarily work for a scale in a plot for example.

**Comment by shefalijoshi** [comment]
## Reviewer Checklist
Changes appear to address issue? Yes
Appropriate unit tests included? N/A
Code style and in-line documentation are appropriate? Yes
Commit messages meet standards? Yes
Has associated issue been labelled unverified? (only applicable if this PR closes the issue) Yes

**Review by shefalijoshi — APPROVED** [review]
