### PR TITLE
Separate out object name checking from the sorting function

### LINKED ISSUE #4571: Adding an item with the same name doesn't update tree view
#### Summary
Adding items (either via Create, or by drag and drop) that have the same name into an object, when that objects tree node is expanded, will result in the tree not updating properly. Collapsing and expanding the tree node will cause it to update properly.

**Having added a bunch of folders and objects into a folder. Note disparity between tree and grid view.**

Screen Shot 2021-12-13 at 3 15 26 PM

**Two different Condition widgets with the same name dragged into a Display Layout. Note disparity with tree.**

Screen Shot 2021-12-13 at 3 18 52 PM

#### Expected vs Current Behavior
Tree should update without having to manipulate the tree node.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce
1. Expand a folder or other container (like a Layout) in the tree. Create or drag ites
2. Create or drag a number of items that have the same name (independent of upper/lowercase letters) into the container created in 1.
3. Observe: the newly added items will not show up in the tree.

#### Environment
* Open MCT Version: 1.8.2 1a4a9b2fb76a3480935227e3b9701d961507b115
* Deployment Type: /testathon
* OS:
* Browser:

### PR DESCRIPTION
**Pull request by khalidadil**
Closes #4571

### Describe your changes:
Lowercases all tree objects when doing the name sorting.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Review by michaelrogers — APPROVED** [review]
Looks good to me!

**Comment by unlikelyzero** [comment]
@khalidadil do you have a link to the original issue?

**Comment by khalidadil** [comment]
> @khalidadil do you have a link to the original issue?

yup, good catch - just linked it!

File: src/ui/layout/mct-tree.vue [hunk 1]
```diff
@@ -430,28 +430,36 @@ export default {
...
+            let objectName;
+            if (!domainObject) {
+                return objectName;
+            }
+
+            if (domainObject.name) {
+                objectName = domainObject.name.toLowerCase();
+            }
+
+            if (domainObject.object && domainObject.object.name) {
```
Comment (nikhilmandlik) [inline src/ui/layout/mct-tree.vue:443]: this looks like weird case, when does this happen?

Comment (khalidadil) [reply src/ui/layout/mct-tree.vue:443]: There's a check for this in the older code as well, I just copied it over.

File: src/ui/layout/mct-tree.vue [hunk 2]
```diff
@@ -430,28 +430,36 @@ export default {
...
+                objectName = domainObject.object.name.toLowerCase();
+            }
+
+            return objectName;
+        },
         sortNameAscending(a, b) {
             // sorting tree children items
-            if (!(a.name && b.name)) {
-                if (a.object.name.toLowerCase()
```
Comment (khalidadil) [inline src/ui/layout/mct-tree.vue:436]: @nikhilmandlik here's how it looked before ^

Comment (nikhilmandlik) [reply src/ui/layout/mct-tree.vue:436]: yeah that looks funny to me, `domainObject` should not have `object` inside it

Comment (khalidadil) [reply src/ui/layout/mct-tree.vue:436]: @michaelrogers I know you worked on some things related to sorting in the tree - do you have context on this?

Comment (michaelrogers) [reply src/ui/layout/mct-tree.vue:436]: I believe the intention was to support passing in a tree object.composition and therefore sort the children of the array which are not full domain objects. This may no longer be in use since the sort approach has changed some over time.

Comment (michaelrogers) [reply src/ui/layout/mct-tree.vue:436]: In testing this locally, I added a folder in `My Items> Unnamed Folder` and there was a case that domainObject.name was not present on a domainObject but there was a domainObject.object.name property. So it would seem that we would need to catch that scenario, appears to only appear on tree item additions. Below is the example object, where the `domainObject.name` is missing.

`{
   id: "537073c7-fdc2-42a0-ada7-f876d042934c"
   isNew: false
   leftOffset: "36px"
   navigationPath: "/browse/mine/f83fb952-1a6f-475e-aada-3054d08d24ad/537073c7-fdc2-42a0-ada7-f876d042934c"
   object: Object
   objectPath: Array(3)
}`

**Review by nikhilmandlik — APPROVED** [review]
LGTM
