### PR TITLE
Gauge fixes for Firefox and units display

### LINKED ISSUE #5139: Unset Gauge limits are being handled as 0
#### Summary
If a low and/or high limit is not set for a Gauge, it is treated by the Gauge as if it _was_ actually set to 0. Instead, that limit should not be displayed at all. The fix here is to use a `v-if="lowLimit !== empty` instead of the current `null` check.

#### Steps to Reproduce

1. Edit props:
image

2. Observe: limits are displayed properly.
image

3. Edit properties to remove limit definitions
image

4. Observe: limits should not be displayed, but are.
image

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

### Testing Notes
1. Create a Gauge view or edit existing.
2. Repeat steps 1 - 4 in 'Steps to Reproduce' above.
3. Verify that limits are not displayed, and the Gauge looks similar to this:
image

### LINKED ISSUE #5323: Gauge is not displayed correctly on Firefox
#### Summary
Creating a Gauge object in Firefox does not display the radial view correctly.

#### Expected vs Current Behavior
The Gauge should appear as it does in Chrome.

#### Steps to Reproduce
1. Create a Gauge object
2. View it in Firefox
3. Expect the Gauge radial to display 

#### Environment
* Open MCT Version: 2.0.5
* Deployment Type: Viper testathon
* OS: All
* Browser: Firefox

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information
image

### LINKED ISSUE #5325: Gauges don't pay attention to the "Display units" property setting
#### Summary
Gauge properties "Display units" setting is not having any affect, but should.

image

#### Expected vs Current Behavior
Setting "Display units" to disabled should suppress the display of units.

#### Steps to Reproduce

1. Edit Properties for a Gauge with a telemetry source that has units, set "Display units" to disabled.
2. Save, nav away and back, then observe: units should be hidden, but are not.

#### Environment

* Open MCT Version:  release/2.0.5
* Deployment Type:  /testathon
* OS: Macos
* Browser: Chrome

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by charlesh88**
Screen Shot 2022-06-24 at 11 00 26 AM

- Significant work refactoring SVG markup and CSS for dial gauge;
- Fixed missing `v-if` to control display of units for #5325;
- Fixed bad `.length` test for limit properties;
- Fixed cross-browser problems with current value display in dial gauge;
- Added "out of range" indicator (yellow arrows) and hover tooltip;
- Range text (purple arrows) now dynamically sizes to fit based on character length;

Closes #5323 
Closes #5325
Closes #5139

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by unlikelyzero** [comment]
@charlesh88 before merging this pr, can you review https://github.com/nasa/openmct/pull/5347 so that we can verify this element

File: src/plugins/gauge/components/Gauge.vue [hunk 1]
```diff
@@ -343,14 +390,28 @@ export default {
         dialLowLimitDeg() {
             return this.percentToDegrees(this.valToPercent(this.limitLow));
         },
+        meterOorRangeIndicatorAspectRatio() {
```
Comment (scottbell) [inline src/plugins/gauge/components/Gauge.vue:393]: I think this has a typo

File: src/plugins/gauge/components/Gauge.vue [hunk 2]
```diff
@@ -343,14 +390,28 @@ export default {
...
+            const DIGITS_RATIO = 3;
+            const VIEWBOX_STR = '0 0 X 10';
 
             return VIEWBOX_STR.replace('X', this.digits * DIGITS_RATIO);
         },
+        rangeFontSize() {
+            const CHAR_THRESHOLD = 3;
+            const START_PERC = 8.5;
+            const REDUCE_PERC = 0.8;
+            const RANGE_CHARS_MAX = Math.max(this.rangeLow.toString().length, this.rangeHigh.toString().length);
```
Comment (scottbell) [inline src/plugins/gauge/components/Gauge.vue:409]: can `rangeLow` ever be null?

File: src/plugins/gauge/components/Gauge.vue [hunk 3]
```diff
@@ -343,14 +390,28 @@ export default {
...
+
+            return this.fontSizeFromChars(RANGE_CHARS_MAX, CHAR_THRESHOLD, START_PERC, REDUCE_PERC);
+        },
         isDialLowLimit() {
-            return this.limitLow.length > 0 && this.dialLowLimitDeg < getLimitDegree('low', 'max');
+            return this.limitLow.toString().length > 0 && this.dialLowLimitDeg < getLimitDegree('low', 'max');
```
Comment (scottbell) [inline src/plugins/gauge/components/Gauge.vue:414]: can `limitLow` ever be null?

File: src/plugins/gauge/components/Gauge.vue [hunk 4]
```diff
@@ -362,7 +423,7 @@ export default {
             return this.dialLowLimitDeg >= getLimitDegree('low', 'q3');
         },
         isDialHighLimit() {
-            return this.limitHigh.length > 0 && this.dialHighLimitDeg < getLimitDegree('high', 'max');
+            return this.limitHigh.toString().length > 0 && this.dialHighLimitDeg < getLimitDegree('high', 'max');
```
Comment (scottbell) [inline src/plugins/gauge/components/Gauge.vue:426]: can `limitHigh` ever be null?

File: src/plugins/gauge/components/Gauge.vue [hunk 5]
```diff
@@ -428,6 +502,9 @@ export default {
         meterLowLimitPerc() {
             return 100 - this.valToPercentMeter(this.limitLow);
         },
+        valueExpected() {
+            return this.curVal.toString().indexOf(DEFAULT_CURRENT_VALUE) === -1;
```
Comment (scottbell) [inline src/plugins/gauge/components/Gauge.vue:506]: is `curVal` ever null?

File: src/plugins/gauge/components/Gauge.vue [hunk 6]
```diff
@@ -504,6 +581,11 @@ export default {
                 ]
             });
         },
+        fontSizeFromChars(charNum, charThreshold, startPerc, reducePerc) {
+            const fs = (charNum <= charThreshold) ? startPerc : (startPerc - ((charNum - charThreshold) * reducePerc));
+
+            return fs.toString() + "%";
```
Comment (scottbell) [inline src/plugins/gauge/components/Gauge.vue:587]: can `fs` ever not be a number? e.g., `NaN`?

File: src/plugins/gauge/components/Gauge.vue (hunk 1 above)
Comment (charlesh88) [reply src/plugins/gauge/components/Gauge.vue:393]: Assume you mean the "Oor"? If so, not a typo: that's for "out of range". Looking at it now, I think I should do that bit in all caps, rather than camel.

Comment (scottbell) [reply src/plugins/gauge/components/Gauge.vue:393]: Got it!

Comment (scottbell) [reply src/plugins/gauge/components/Gauge.vue:393]: Though shouldn’t it be meterOORangeIndicatorAspectRatio then? I’d add a comment specifying what the OO stands for so dummies like me won’t bother you in the future about it 😄

**Comment by unlikelyzero** [comment]
@charlesh88 the gauge is now available in our visual tests: https://percy.io/b2e34b17/openmct/builds/19244755/changed/1080234572?browser=chrome&browser_ids=18%2C22%2C23%2C25&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1024&widths=1024%2C2000

You can see how it looks at the different available resolutions and browsers. Note: Safari is not rendering the gauge.

File: src/plugins/gauge/components/Gauge.vue (hunk 2 above)
Comment (charlesh88) [reply src/plugins/gauge/components/Gauge.vue:409]: Never in a normal case; this value is set by default and passed in from GaugePlugin.js, and should be handled there.

File: src/plugins/gauge/components/Gauge.vue (hunk 3 above)
Comment (charlesh88) [reply src/plugins/gauge/components/Gauge.vue:414]: Never in a normal case; this value is set by default and passed in from GaugePlugin.js, and should be handled there.

File: src/plugins/gauge/components/Gauge.vue (hunk 4 above)
Comment (charlesh88) [reply src/plugins/gauge/components/Gauge.vue:426]: Never in a normal case; this value is set by default and passed in from GaugePlugin.js, and should be handled there.

File: src/plugins/gauge/components/Gauge.vue (hunk 3 above)
Comment (scottbell) [reply src/plugins/gauge/components/Gauge.vue:414]: Cool

File: src/plugins/gauge/components/Gauge.vue (hunk 2 above)
Comment (scottbell) [reply src/plugins/gauge/components/Gauge.vue:409]: 👍

File: src/plugins/gauge/components/Gauge.vue (hunk 1 above)
Comment (charlesh88) [reply src/plugins/gauge/components/Gauge.vue:393]: I've renamed this to `meterOutOfRangeIndicatorAspectRatio`

File: src/plugins/gauge/components/Gauge.vue (hunk 4 above)
Comment (scottbell) [reply src/plugins/gauge/components/Gauge.vue:426]: 👍

File: src/plugins/gauge/components/Gauge.vue (hunk 5 above)
Comment (charlesh88) [reply src/plugins/gauge/components/Gauge.vue:506]: I added a check in that method:
```
valueExpected() {
    if (this.curVal === undefined || Object.is(this.curVal, 'null')) {
        return false;
    }

    return this.curVal.toString().indexOf(DEFAULT_CURRENT_VALUE) === -1;
}
```

File: src/plugins/gauge/components/Gauge.vue (hunk 6 above)
Comment (charlesh88) [reply src/plugins/gauge/components/Gauge.vue:587]: No, it's always a number.

**Review by scottbell — APPROVED** [review]
Good work @charlesh88!

**Comment by charlesh88** [comment]
@shefalijoshi @scottbell @akhenry Can I get an approve and merge on this?

**Review by scottbell — APPROVED** [review]
