### PR TITLE
do not show loaded tabs before showing current tab

### LINKED ISSUE #6387: [Tabs] in eager load mode, only load the selected tab on tabs view load
#### Summary
The tabs view remembers which tab was last selected. If the last selected tab is any tab besides the first, on load the tabs view will first load the first tab and then the last selected tab. This may be resolved by just implementing the fix for #4479.

#### Expected vs Current Behavior
Only the last selected tab should be loaded. Internally, this means views in tabs should not be destroyed

#### Steps to Reproduce
1. Create a tabs view with Eager load tabs set to true
2. drop telemetry into multiple tabs
3. navigate to the tabs view
4. select the last, right-most tab
5. navigate away from tabs view
6. open browser console and clear network requests
7. navigate to the tabs view
8. observe that telemetry requests will fire for the first tab twice when telemetry requests for each tab should only fire once
9. tabs are traditionally brittle so regression testing with eager load = false is recommended

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [x] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by davetsay**
Closes #6387 

### Describe your changes:
* Do not show any tabs until show current tab logic is fired
* Show the first tab by default if no current tab

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [x] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Review by shefalijoshi — CHANGES_REQUESTED** [review]
Looks good!
Please add a test for it.

**Comment by davetsay** [comment]
e2e test to be covered in #6425

File: src/plugins/tabs/components/tabs.vue [hunk 1]
```diff
@@ -123,6 +123,7 @@ export default {
             this.composition.on('remove', this.removeItem);
             this.composition.on('reorder', this.onReorder);
             this.composition.load().then(() => {
+                this.setCurrentTab = true;
```
Comment (shefalijoshi) [inline src/plugins/tabs/components/tabs.vue:126]: This will also catch the case where the composition is empty and someone adds stuff to it after the view is mounted right?
OR if there is an error loading the composition?

Comment (davetsay) [reply src/plugins/tabs/components/tabs.vue:126]: good catch. i need to set `this.setCurrentTab = false` after setting current tab in this block.

**Review by shefalijoshi — APPROVED** [review]
Looks good!

**Review by shefalijoshi — CHANGES_REQUESTED** [review]
One small issue.

https://user-images.githubusercontent.com/5247066/225451634-f771010a-6bc4-42bd-99da-03663273b2b5.mov

In fixed timespan mode:
Add a few objects to the tabs view
Make sure that generally the right tab shows up as you navigate away and back.
Using the navigation tree, remove all objects from the tabs view composition and then navigate away to another object and come back to the empty tabs view.
Add an object to the view (or 2 objects). Newly added objects are not visible.
Manually selecting a tab does resolve this.

**Comment by davetsay** [comment]
@shefalijoshi . nice catch. pushed fix. i'll search to see if we have an issue filed for that.

**Review by shefalijoshi — APPROVED** [review]
