### PR TITLE
[Table] Retain rows in scope

### LINKED ISSUE #1738: [Table] real-time data is lost when sorting
When viewing a telemetry table that has both historical and realtime data, if you sort the table, then all realtime data will be removed during the sort, so that only the historical data still persists.  Sorting thus results in gaps appearing in the data.

Easy to reproduce on master by looking at a sinewave in table mode, setting time conductor to follow mode with a ten second window, and then resorting.

table-realtime-sort-data-loss

If there's a simple fix, this should be high priority.

### PR DESCRIPTION
**Pull request by VWoeltjen**
This avoids losing rows during table sorting, which fixes #1738 

### Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? Y
3. Command line build passes? Y
4. Changes have been smoke-tested? Y

### CODE REVIEW

File: platform/features/table/test/controllers/TelemetryTableControllerSpec.js [hunk 1]
```diff
@@ -436,5 +436,28 @@ define(
                 expect(mockScope.$broadcast).toHaveBeenCalledWith("remove:rows", discardedRows);
             });
 
+            describe('when telemetry is added', function () {
+                var testRows;
+                var expectedRows;
+
+                beforeEach(function () {
+                    testRows = [ { a: 0 }, { a: 1 }, { a: 2 } ];
```
Comment (larkin) [inline platform/features/table/test/controllers/TelemetryTableControllerSpec.js]: these break code style (no spaces before opening/closing brackets in array literal), can you tweak?

**Comment by VWoeltjen** [comment]
Oops! `gulp fixstyle`d. Really ready for review and merge this time.

**Comment by larkin** [comment]
# Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
