### PR TITLE
 Event Generator now shows data in fixed time mode

### LINKED ISSUE #4879: Event Generator does not show data in fixed time mode.
#### Summary
The event generator does not show any events when the conductor is in fixed mode except for events generated in real-time mode.

#### Expected vs Current Behavior
The example event generator should provide events for any fixed time window configured by the user.

#### Steps to Reproduce
1. Switch the time conductor to fixed mode.
2. Create a new event message generator
2. Click on the event message generator and observe that no event messages are displayed.
3. Switch the conductor to real-time mode
4. Observe that event messages begin appearing.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [X] Regression? Did this used to work or has it always been broken?
- [X] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

### PR DESCRIPTION
**Pull request by scottbell**
Closes #4879 

### Describe your changes:
Changed the event generator to use passed start time instead of using `Date.now`. Also added a test to ensure this works for dates long in the past.

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [X] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [X] Changes address original issue?
* [X] Unit tests included and/or updated with changes?
* [X] Command line build passes?
* [X] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Changes appear not to be breaking changes?
* [x] Appropriate unit tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Commit messages meet standards?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [x] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: example/eventGenerator/EventTelemetryProvider.js [hunk 1]
```diff
@@ -33,7 +33,7 @@ class EventTelemetryProvider {
 
     generateData(firstObservedTime, count, startTime, duration, name) {
         const millisecondsSinceStart = startTime - firstObservedTime;
-        const utc = Math.floor(startTime / duration) * duration;
+        const utc = startTime + (count * duration);
```
Comment (scottbell) [inline example/eventGenerator/EventTelemetryProvider.js:36]: allows any request to show data. previous incarnation was showing data well into the future

File: example/eventGenerator/EventTelemetryProvider.js [hunk 2]
```diff
@@ -75,15 +75,15 @@ class EventTelemetryProvider {
         const duration = domainObject.telemetry.duration * 1000;
         const size = options.size ? options.size : this.defaultSize;
         const data = [];
-        const firstObservedTime = Date.now();
+        const firstObservedTime = options.start;
```
Comment (scottbell) [inline example/eventGenerator/EventTelemetryProvider.js:78]: just use the start request

File: indexTest.js [hunk 3]
```diff
@@ -1,3 +1,2 @@
-const testsContext = require.context('.', true, /\/(src|platform|\.\/example)\/.*Spec.js$/);
-
+const testsContext = require.context('.', true, /^\.\/(src|example)\/.*Spec.js$/);
```
Comment (scottbell) [inline indexTest.js:1]: Adjusted regex so that we don't pick up:
`./node_modules/fooPackage/src/FooSpec.js`
`./node_modules/fooPackage/example/FooSpec.js`
but we do pick up:
`./example/eventGenerator/pluginSpec.js`

As the `example` directory is often released to users, it seems like it should be covered by tests

File: example/exampleUser/pluginSpec.js [hunk 4]
```diff
@@ -26,7 +26,7 @@ import {
 } from '../../src/utils/testing';
 import ExampleUserProvider from './ExampleUserProvider';
 
-describe("The Example User Plugin", () => {
+xdescribe("The Example User Plugin", () => {
```
Comment (scottbell) [inline example/exampleUser/pluginSpec.js:29]: This test leaks login forms into the display:
image

causing plugin tests that assume absolute positioning to fail, e.g., the Menu API:
```
 Menu Placements
      ✗ default menu position BOTTOM_RIGHT (5ms)
	Error: Expected 141 to equal 16.
	    at <Jasmine>
	    at UserContext.eval (webpack-internal:///./src/api/menu/MenuAPISpec.js:198:25)
	    at <Jasmine>

      ✗ menu position BOTTOM_RIGHT (5ms)
	Error: Expected 141 to equal 16.
	    at <Jasmine>
	    at UserContext.eval (webpack-internal:///./src/api/menu/MenuAPISpec.js:214:25)
	    at <Jasmine>
```
This is probably because the form never cleans itself up:
https://github.com/nasa/openmct/blob/master/example/exampleUser/ExampleUserProvider.js#L99
It leaked into the code base broken as the regex (fixed in this PR) was excluding the `example` directory, and thus never running the test.

Comment (unlikelyzero) [reply example/exampleUser/pluginSpec.js:29]: If you think that the leaky test can get fixed in a single day, we just put it in this PR given that everybody else is out.

Can you think of a e2e scenario to cover this?

File: karma.conf.js [hunk 5]
```diff
@@ -36,7 +36,7 @@ module.exports = (config) => {
     if (coverageEnabled) {
         webpackConfig.module.rules.push({
             test: /\.js$/,
-            exclude: /node_modules|e2e|example|lib|dist|\.*.*Spec\.js/,
+            exclude: /node_modules|e2e|lib|dist|\.*.*Spec\.js/,
```
[the remark this answers is not in the document]
Comment (unlikelyzero) [reply karma.conf.js:39]: i think so

File: example/exampleUser/pluginSpec.js (hunk 4 above)
Comment (scottbell) [reply example/exampleUser/pluginSpec.js:29]: I can’t think of one off the top of my head, and I’m out the rest of the day, so I guess I should file a ticket!

Comment (scottbell) [reply example/exampleUser/pluginSpec.js:29]: https://github.com/nasa/openmct/issues/4886

File: .github/workflows/prcop-config.json [hunk 6]
```diff
@@ -3,7 +3,7 @@
     {
       "name": "descriptionRegexp",
       "config": {
-        "regexp": "x] Testing instructions",
+        "regexp": "(?i)x] Testing instructions",
```
Comment (scottbell) [inline .github/workflows/prcop-config.json:6]: @unlikelyzero This was tripping me up as I was using `X` to check the boxes in the template instead of `x`

Comment (unlikelyzero) [reply .github/workflows/prcop-config.json]: thanks for fixing this. You're not the only one who was using the INCORRECT markdown format ;)

**Review by unlikelyzero — APPROVED** [review]

**Comment by jvigliotta** [comment]
@jvigliotta to take a look.

**Review by jvigliotta — APPROVED** [review]
This looks good to me. Nice work!
