### PR TITLE
Mct5549 fix composition error

### LINKED ISSUE #5549: The in-memory search indexer is observing mutation of the composition property.
https://github.com/nasa/openmct/blob/2fa053e80ca7013aeb7ff94b57ac81e47c6197d6/src/api/objects/InMemorySearchProvider.js#L315

This is an unreliable method of detecting composition changes as not all objects will use the composition property to define their composition.

Instead, the Composition API should be used. It provides observers for composition changes that are agnostic of the underlying data structure.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by scottbell**
Closes #5549 

### Describe your changes:
The domain object comes in on the `composition.add` callback as a mutable domain object, which has functions dangling on it. The index function cannot handle these dangling functions as it will eventually be serialized using `structuredClone`. Thus we're using `JSON.parse`/`JSON.stringify` to discard those functions.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Changes appear not to be breaking changes?
* [x] Appropriate unit tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Commit messages meet standards?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [x] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/api/objects/InMemorySearchProvider.js [hunk 1]
```diff
@@ -281,17 +288,30 @@ class InMemorySearchProvider {
...
-                    .areIdsEqual([identifier, indexedIdentifier])));
-
-        identifiersToIndex.forEach(identifier => {
-            this.openmct.objects.get(identifier).then(objectToIndex => provider.index(objectToIndex));
-        });
+        // The object comes in as a mutable domain object, which has functions,
+        // which the index function cannot handle as it will eventually be serialized
+        // using structuredClone. Thus we're using JSON.parse/JSON.stringify to discard
+        // those functions.
+        const nonMutableDomainObject = JSON.parse(JSON.stringify(newDomainObjectToIndex));
```
Comment (scottbell) [inline src/api/objects/InMemorySearchProvider.js:297]: Had to add the 👆to ensure serializability (not a word)

Comment (ozyx) [reply src/api/objects/InMemorySearchProvider.js:297]: It is, in fact, a [word](https://en.wikipedia.org/wiki/Serializability)!

**Review by ozyx — APPROVED** [review]
Tested locally following instructions in the related issue and seems to work well. Also ran the unit tests a few times over to ensure they are stable.

LGTM!

**Review by davetsay — APPROVED** [review]
