### PR TITLE
[StackedPlots] Destroy programmatically created component instances

### LINKED ISSUE #4344: [StackedPlots] Programatically created MCTPlots aren't being destroyed
#### Summary
StackedPlots have a StackedPlotItem as children. In StackedPlotItem, a MCTPlot is programmatically created, because of this, Vue is unaware it's a child of StackedPlotItem. Need to programmatically destroy these plots, when StackedPlotItem is destroyed.

#### Expected vs Current Behavior
The plots in the stacked plot should also be destroyed and their resources released.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. View a stacked plot with plot children
2. Note the historical requests for these child plots
3. Navigate away to a folder
4. Change the time bounds to trigger a historical request
5. Note requests are still mad for those child plots
6. This bad.

### PR DESCRIPTION
**Pull request by jvigliotta**
### All Submissions:
Destroying child components created programmatically. Removed eventHelper.js from StackedPlots.vue as it wasn't being used.

closes #4344

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### CODE REVIEW

File: src/plugins/plot/stackedPlot/StackedPlotItem.vue [hunk 1]
```diff
@@ -75,6 +75,11 @@ export default {
     mounted() {
         this.updateView();
     },
+    beforeDestroy() {
+        if (this.component) {
```
Comment (davetsay) [inline src/plugins/plot/stackedPlot/StackedPlotItem.vue:79]: i see another method, `updateView` destroying `this.component`. It also does a little more cleanup. Do we need to do the same here? If so, can we make a `destroyComponent` method?
