### PR TITLE
Prevent cyclic references in link & move actions

### LINKED ISSUE #5620: Disallow move and link to child object
#### Summary
Currently the move and link actions allow an object to be moved or linked to a child of itself. This creates a circular reference. A circular link is actually recoverable, but a circular move is not and will cause the UI to freeze. In any case, neither should be allowed.

#### Expected vs Current Behavior
User should not be able to select a child folder as a target location the a move or link action.

#### Steps to Reproduce
1. Create a folder called Parent Folder
2. Create a folder called Child Folder as a child of the Parent Folder
3. Create a folder called Grandchild Folder as a child of the Child Folder
4. Context click on the Parent Folder and select "move"
5. Select Grandchild Folder as the new location
6. Observe that the UI hangs

#### Environment
* Open MCT Version: 2.0.7
* Deployment Type: all

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by scottbell**
Closes #5620 

### Describe your changes:
In form validation, check if path contains ourselves. If it does, reject.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: e2e/appActions.js [hunk 1]
```diff
@@ -192,6 +192,28 @@ async function setTimeConductorMode(page, isFixedTimespan = true) {
     }
 }
 
+/**
+    * Creates a folder in the default location
+    * @param {import('@playwright/test').Page} page - page to load
+    * @param {string} name - the name of the folder
+    */
+async function createFolderInDefaultLocation(page, name) {
```
Comment (unlikelyzero) [inline e2e/appActions.js:200]: @scottbell this might be too close to using the existing `createDomainObjectWithDefaults` when specifying the folder object.

File: e2e/tests/functional/plugins/linkAction/linkObjects.e2e.spec.js [hunk 2]
```diff
@@ -0,0 +1,84 @@
...
+ *****************************************************************************/
+
+/*
+This test suite is dedicated to tests which verify the basic operations surrounding linking objects.
+*/
+
+const { test, expect } = require('../../../../pluginFixtures');
+const { createFolderInDefaultLocation } = require('../../../../appActions');
+
+test.describe('Link item tests', () => {
```
Comment (unlikelyzero) [inline e2e/tests/functional/plugins/linkAction/linkObjects.e2e.spec.js:30]: I would move this back into the moveObjects suite and name the suite (moveAndLink.e2e.spec.js). We're actively trying to move away from the plugin structure mirror that we have today

Comment (scottbell) [reply e2e/tests/functional/plugins/linkAction/linkObjects.e2e.spec.js:30]: ah, hadn't realized this

File: e2e/tests/functional/moveAndLinkObjects.e2e.spec.js [hunk 3]
```diff
@@ -137,6 +157,59 @@ test.describe('Move item tests', () => {
         let okButtonStateDisabled2 = await okButton2.isDisabled();
         expect(okButtonStateDisabled2).toBeTruthy();
     });
+
+    test('Create a basic object and verify that it can be linked to another folder', async ({ page, openmctConfig }) => {
+        const { myItemsFolderName } = openmctConfig;
```
Comment (unlikelyzero) [inline e2e/tests/functional/moveAndLinkObjects.e2e.spec.js:162]: @scottbell @ozyx is there a way we could move this a higher scope?

Comment (scottbell) [reply e2e/tests/functional/moveAndLinkObjects.e2e.spec.js:162]: @unlikelyzero how do you mean?

Comment (unlikelyzero) [reply e2e/tests/functional/moveAndLinkObjects.e2e.spec.js:162]: Could this be set for the entire suite instead of individual tests?

Comment (ozyx) [reply e2e/tests/functional/moveAndLinkObjects.e2e.spec.js:162]: There _should_ be a way to do this. The need for `myItemsFolderName` is likely unavoidable in some scenarios, but since it's a deployment-wide configuration we shouldn't have to import it every test. I'm working on a PR which will include improvements to tree selection, I'll see if I can improve our usage of this as a part of those changes. That's the most common scenario where we use this anyway.

**Review by unlikelyzero — APPROVED** [review]
Amazing work!

**Comment by ozyx** [comment]
@scottbell @unlikelyzero 

I think this will need to be retargeted against 2.0.8 before merge?

**Comment by scottbell** [comment]
> @scottbell @unlikelyzero
> 
> I think this will need to be retargeted against 2.0.8 before merge?

Is there a 2.0.8? If not, I guess we should wait?

**Comment by ozyx** [comment]
> > @scottbell @unlikelyzero
> > I think this will need to be retargeted against 2.0.8 before merge?
> 
> Is there a 2.0.8? If not, I guess we should wait?

There is now! LET'S GOOOOOO
