### PR TITLE
Improve Tab lazy loading logic and fix delete tab issue

### LINKED ISSUE #3672: [Tabs View] Improve Lazy Load logic
At the moment, when using the lazy load option, we destroy the tabs when the user clicks away from the current tab. 

We should keep already loaded tabs active but use visibility hidden to hide it from users view, this will greatly improve load times, and allows users to switch back and forth like tabs view was designed to.

## Testing Notes
1. Create a dense layout with multiple plots and tables
2. Create a stacked plot with 3 to 4 plots.
3. Create a tabs view and set the eager load option to false.
4. Add the 2 views created earlier into the tabs view. 
5. Refresh the page.
6. Click on the other tab, notice that the new tab will load when you click on it.
7. Click on the first tab, notice that the first tab will already be loaded when you click on it.

### LINKED ISSUE #3673: [Tabs View] Deleting a tab via the "x" button removes the wrong tab
When deleting a tab using the "x" button currently always removes the first tab from the view, regardless of what tab you clicked on.

## Testing Notes
1. Create a tabs view with 3 to 4 unique tabs.
2. Delete the tab to the far right.
3. Notice the tab to the far left is the one that got removed.

### PR DESCRIPTION
**Pull request by deeptailor**
This PR fixes the following issues:

Fixes #3672 
Fixes #3673 

## Author Checklist
Changes address original issue? Yes
Unit tests included and/or updated with changes? N/A
Command line build passes? Yes
Changes have been smoke-tested? Yes
Testing instructions included? Yes in issues

### CODE REVIEW

File: src/plugins/tabs/components/tabs.vue [hunk 1]
```diff
@@ -224,15 +226,21 @@ export default {
...
+            });
+
             let tabToBeRemoved = this.tabsList[pos];
 
             tabToBeRemoved.statusUnsubscribe();
 
             this.tabsList.splice(pos, 1);
 
+            this.loadedTabs[keyStringToBeRemoved] = undefined;
+            delete this.loadedTabs[keyStringToBeRemoved];
```
Comment (nikhilmandlik) [inline src/plugins/tabs/components/tabs.vue:242]: is it reactive? to be safe can use this `this.$delete(target, propertyName/index )` https://vuejs.org/v2/api/#vm-delete

Comment (deeptailor) [reply src/plugins/tabs/components/tabs.vue:242]: We don't the view to react to this delete change, so there is no need to use the vue $delete method.

**Review by nikhilmandlik — APPROVED** [review]
LGTM
