### PR TITLE
Gauge fixes for NaN and composition policy

### LINKED ISSUE #5536: Gauge allows bad drag and drop
#### Summary
The Gauge needs to follow the same rules about drag and drop composition as other telemetry views like plots, but isn't.

#### Expected vs Current Behavior
Gauge should follow the composition rules that plots use.

#### Steps to Reproduce

1. Create or edit a Gauge.
2. Drag a telemetry point into the Gauge to add it. This can be done from the tree, or search results. This should work.
3. Drag a disallowed object type (folder, layout, imagery, etc.) into the Gauge. This should be disallowed, but isn't.

#### Environment

* Open MCT Version:  R 2.0.5
* Deployment Type:  /testathon
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### LINKED ISSUE #5538: Gauge displays NaN when telemetry not available
#### Summary
When a Gauge has a telemetry source, but that source isn't providing any data, the Gauge is displaying NaN.
Screen Shot 2022-07-19 at 9 19 17 AM

#### Expected vs Current Behavior
The Gauge should display "---" and should not display the "out of range" indication.

#### Steps to Reproduce

1. Add a telem source that doesn't have any data currently to a Gauge.

#### Environment

* Open MCT Version:  R 2.0.5
* Deployment Type:  /testathon
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by charlesh88**
Closes #5536
Closes #5538

### Describe your changes:
- Significant changes to code flow for better handling of missing telemetry values to handle NaN problem. Closes #5538.
- Changes to flow to handle range display when updating composition and when ranges are set by limits.
- Added `GaugeCompositionPolicy.js`; closes https://github.com/nasa/openmct/issues/5536.

### All Submissions:
* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Changes appear not to be breaking changes?
* [x] Appropriate unit tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Commit messages meet standards?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [x] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/plugins/gauge/GaugeCompositionPolicy.js [hunk 1]
```diff
@@ -0,0 +1,27 @@
+export default function GaugeCompositionPolicy(openmct) {
+    function hasNumericTelemetry(domainObject) {
+        const hasTelemetry = openmct.telemetry.isTelemetryObject(domainObject);
+        if (!hasTelemetry) {
+            return false;
```
Comment (scottbell) [inline src/plugins/gauge/GaugeCompositionPolicy.js:5]: We should add to be sure the vue component renders properly when the telemetry is unavailable.

File: src/plugins/gauge/components/Gauge.vue [hunk 2]
```diff
@@ -694,25 +700,33 @@ export default {
...
             this.datum = datum;
+            let val = DEFAULT_CURRENT_VALUE;
 
             if (this.isRendering) {
                 return;
             }
 
-            const { start, end } = this.openmct.time.bounds();
-            const parsedValue = this.timeFormatter.parse(this.datum);
+            if (this.datum !== undefined) {
```
Comment (scottbell) [inline src/plugins/gauge/components/Gauge.vue:709]: could we change this to:
`if (!this.datum)`
instead?

**Review by scottbell — COMMENTED** [review]
Good work @charlesh88! I had a few comments below

**Comment by akhenry** [comment]
@charlesh88 This has been reviewed, waiting for followup from you.

**Comment by davetsay** [comment]
@charlesh88 to review comments by @scottbell

**Comment by charlesh88** [comment]
@ozyx Says run lint fix on this, and it should go right in.

**Review by ozyx — CHANGES_REQUESTED** [review]
@charlesh88 to add an e2e test

**Comment by charlesh88** [comment]
@ozyx  e2e tests added, and files have been linted. Ready for a final look.

File: e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js [hunk 3]
```diff
@@ -133,4 +133,50 @@ test.describe('Gauge', () => {
...
+    await page.getByRole('button', { name: ' Create ' }).click();
+    await page.getByRole('menuitem', { name: ' Sine Wave Generator' }).click();
+    await page
+      .getByRole('dialog')
+      .locator('div')
+      .filter({ hasText: 'Loading Delay (ms)' })
+      .nth(3)
+      .click();
+    await page.getByLabel('Loading Delay (ms)').fill('5000');
+    await page.locator('[aria-label="Save"]').click();
```
Comment (ozyx) [inline e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js:154]: I actually found a [great example](https://github.com/nasa/openmct/blob/cc8f726bd5de5f83a376283c08b05f96e412de15/e2e/tests/framework/generateLocalStorageData.e2e.spec.js#L142) of adding a load delay to a SWG. The pattern in the link I shared is the recommended way to do this. 

1.  `createExampleTelemetryObject(page, parent)`- creates a default SWG as a child of the parent and returns it
2. Edit the default SWG to apply the loading delay
3. Navigate to the parent object

File: e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js [hunk 4]
```diff
@@ -133,4 +133,50 @@ test.describe('Gauge', () => {
...
+    await page.getByLabel('Expand My Items folder').click();
+    await page
+      .getByRole('treeitem', { name: 'Expand Unnamed Gauge gauge  Unnamed Gauge' })
+      .locator('a')
+      .click();
+    const gaugeNoDataText = await page.locator('.js-dial-current-value tspan').textContent();
```
Comment (ozyx) [inline e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js:160]: This doesn't need to block this PR from going in, but we should consider adding better ARIA to Gauges to avoid plain CSS selectors.

File: e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js [hunk 5]
```diff
@@ -133,4 +133,50 @@ test.describe('Gauge', () => {
...
+  test('Gauge enforces composition policy', async ({ page }) => {
+    // Create a Gauge
+    await createDomainObjectWithDefaults(page, {
+      type: 'Gauge',
+      name: 'Unnamed Gauge'
+    });
+
+    // Try to create a Folder into the Gauge. Should be disallowed.
+    await page.getByRole('button', { name: ' Create ' }).click();
+    await page.getByRole('menuitem', { name: ' Folder' }).click();
```
Comment (ozyx) [inline e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js:173]: We can avoid the weird symbols in the locators by selection on a RegExp instead:

```suggestion
    await page.getByRole('button', { name: /Create/ }).click();
    await page.getByRole('menuitem', { name: /Folder/ }).click();
```

File: e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js [hunk 6]
```diff
@@ -133,4 +133,50 @@ test.describe('Gauge', () => {
...
+    await expect(page.locator('[aria-label="Save"]')).toBeDisabled();
+    await page.getByLabel('Cancel').click();
+
+    // Try to create a Display Layout into the Gauge. Should be disallowed.
+    await page.getByRole('button', { name: ' Create ' }).click();
+    await page.getByRole('menuitem', { name: ' Display Layout' }).click();
```
Comment (ozyx) [inline e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js:179]: Same thing here

File: e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js [hunk 7]
```diff
@@ -133,4 +133,50 @@ test.describe('Gauge', () => {
...
+    expect(gaugeNoDataText).toBe('--');
+  });
+
+  test('Gauge enforces composition policy', async ({ page }) => {
+    // Create a Gauge
+    await createDomainObjectWithDefaults(page, {
+      type: 'Gauge',
+      name: 'Unnamed Gauge'
+    });
+
```
Comment (ozyx) [inline e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js:170]: We should add a positive case here. e.g.:
1. Create an allowed object into the Gauge
2. Assert that the Save button is enabled

File: src/plugins/gauge/GaugeCompositionPolicy.js [hunk 8]
```diff
@@ -0,0 +1,29 @@
+export default function GaugeCompositionPolicy(openmct) {
```
Comment (ozyx) [inline src/plugins/gauge/GaugeCompositionPolicy.js:1]: Need to add copyright boilerplate here

File: src/plugins/gauge/GaugeCompositionPolicy.js [hunk 9]
```diff
@@ -0,0 +1,29 @@
...
+  function hasNumericTelemetry(domainObject) {
+    const hasTelemetry = openmct.telemetry.isTelemetryObject(domainObject);
+    if (!hasTelemetry) {
+      return false;
+    }
+
+    let metadata = openmct.telemetry.getMetadata(domainObject);
```
Comment (ozyx) [inline src/plugins/gauge/GaugeCompositionPolicy.js:8]: `const` ?

File: src/plugins/gauge/GaugePlugin.js [hunk 10]
```diff
@@ -187,7 +189,8 @@ export default function () {
                 onChange
               };
             },
-            template: `<GaugeFormController :model="model" @on-change="onChange"></GaugeFormController>`
+            template: `
+                          <GaugeFormController :model="model" @on-change="onChange"></GaugeFormController>`
```
Comment (ozyx) [inline src/plugins/gauge/GaugePlugin.js:193]: weird formatting. maybe a `prettier` glitch? 🤔

File: src/plugins/gauge/components/GaugeComponent.vue [hunk 11]
```diff
@@ -402,10 +402,10 @@ export default {
       const CHAR_THRESHOLD = 3;
       const START_PERC = 8.5;
       const REDUCE_PERC = 0.8;
-      const RANGE_CHARS_MAX = Math.max(
-        this.rangeLow.toString().length,
-        this.rangeHigh.toString().length
-      );
+      const RANGE_CHARS_MAX =
+        this.rangeLow && this.rangeHigh
+          ? Math.max(this.rangeLow.toString().length, this.rangeHigh.toString().length)
```
Comment (ozyx) [inline src/plugins/gauge/components/GaugeComponent.vue:407]: Could this just be

`Math.max(Number(this.rangeLow), Number(this.rangeHigh))` ? Or am I misunderstanding

**Review by ozyx — CHANGES_REQUESTED** [review]
Awesome work! I've got some suggestions to improve the e2e tests.

File: e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js (hunk 3 above)
Comment (charlesh88) [reply e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js:154]: Implemented.

File: e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js [hunk 12]
```diff
@@ -133,4 +133,50 @@ test.describe('Gauge', () => {
...
+      .filter({ hasText: 'Loading Delay (ms)' })
+      .nth(3)
+      .click();
+    await page.getByLabel('Loading Delay (ms)').fill('5000');
+    await page.locator('[aria-label="Save"]').click();
+    await page.getByLabel('Expand My Items folder').click();
+    await page
+      .getByRole('treeitem', { name: 'Expand Unnamed Gauge gauge  Unnamed Gauge' })
+      .locator('a')
+      .click();
```
[the remark this answers is not in the document]
Comment (charlesh88) [reply e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js:159]: Implemented.

File: e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js [hunk 13]
```diff
@@ -133,4 +133,50 @@ test.describe('Gauge', () => {
 
     // TODO: Verify changes in the UI
   });
+
+  test('Gauge does not display NaN when data not available', async ({ page }) => {
+    // Create a Gauge
+    await createDomainObjectWithDefaults(page, {
+      type: 'Gauge',
+      name: 'Unnamed Gauge'
+    });
```
[the remark this answers is not in the document]
Comment (charlesh88) [reply e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js:142]: Implemented.

File: e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js (hunk 4 above)
Comment (charlesh88) [reply e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js:160]: Agree, but I'd like to add aria's across all the gauge display styles in a future issue.

File: e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js (hunk 5 above)
Comment (charlesh88) [reply e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js:173]: Implemented.

File: src/plugins/gauge/GaugeCompositionPolicy.js (hunk 8 above)
Comment (charlesh88) [reply src/plugins/gauge/GaugeCompositionPolicy.js:1]: Implemented.

File: src/plugins/gauge/GaugeCompositionPolicy.js (hunk 9 above)
Comment (charlesh88) [reply src/plugins/gauge/GaugeCompositionPolicy.js:8]: Yep; copy and paste from OverlayPlotCompositionPolicy.js. Have changed in the Gauge version.

File: src/plugins/gauge/components/GaugeComponent.vue (hunk 11 above)
Comment (charlesh88) [reply src/plugins/gauge/components/GaugeComponent.vue:407]: I need the max of the number of characters, not the numbers themselves. For example, with 10 and -10, Math.max would give me "10" - but "-10" has more characters. Also, if rangeLow is or High are null, I have to check that first.

File: src/plugins/gauge/GaugePlugin.js (hunk 10 above)
Comment (charlesh88) [reply src/plugins/gauge/GaugePlugin.js:193]: Will look.

Comment (charlesh88) [reply src/plugins/gauge/GaugePlugin.js:193]: Implemented.

**Review by scottbell — APPROVED** [review]
Nice work @charlesh88, and thank you for adding the tests. Below are the functionality results.

For the composition issue, it looks resolved. Here's before:

https://github.com/nasa/openmct/assets/9853862/fa9650ac-3fa0-44c2-8e39-bea821b05c01

and after it's properly preventing non-telemetry from being dropped on it:

https://github.com/nasa/openmct/assets/9853862/94b11f2a-6b72-4ce9-8718-1008da6684d0

It still does allow non-numerical telemetry points (e.g., events), but not sure that should hold up the PR.

The NaN issue seems already resolved? Here's before with a delayed Sine Wave Generator set to a 3s delay:

https://github.com/nasa/openmct/assets/9853862/e12e4f4c-7329-49e0-9fe9-f1dcc316d0fe

And here's after which is showing the same behavior:

https://github.com/nasa/openmct/assets/9853862/71eb4321-8feb-4fba-83d3-4839e0885b8d

File: e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js (hunk 7 above)
Comment (charlesh88) [reply e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js:170]: So I'm trying to figure out what the scope of the test that I add should be.... gauge.e2e 'Can add and remove telemetry sources' at line 40 already adds a SWG at line 47, and exercises the Save button at line 58. Do I need to duplicate that?

Comment (ozyx) [reply e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js:175]: Ah, in that case I suppose that's already covered then.

File: e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js [hunk 14]
```diff
@@ -133,4 +136,52 @@ test.describe('Gauge', () => {
...
+
+    //Edit Example Telemetry Object to include 5s loading Delay
+    await page.locator('[aria-label="Loading Delay \\(ms\\)"]').fill('5000');
+
+    await Promise.all([
+      page.waitForNavigation(),
+      page.locator('text=OK').click(),
+      //Wait for Save Banner to appear
+      page.waitForSelector('.c-message-banner__message')
+    ]);
```
Comment (ozyx) [inline e2e/tests/functional/plugins/gauge/gauge.e2e.spec.js:161]: This is an old pattern. We can just do:
```suggestion
  await page.getByRole('button', { name: 'Save' }).click();

  // Wait until the URL is updated
  await page.waitForURL(`**/${gauge.uuid}/*`);
```

**Review by ozyx — CHANGES_REQUESTED** [review]
Looks great! Just one small fix to get the e2e test passing

**Review by ozyx — APPROVED** [review]
