### PR TITLE
Have clicking on annotation search result use the preview action if in edit mode

### LINKED ISSUE #6280: Click on Search Result (Annotation in this case) switches view while in Edit mode
#### Summary
While in Edit mode of an object, Clicking on a search result for a different object opens it in Edit Mode (even if it's not supposed to be editable)

#### Expected vs Current Behavior
The Search result should open in a Preview window while another item is in edit mode.

#### Steps to Reproduce
1. Navigate to an editable domain object and click Edit - This should take you into Edit mode.
2. Search for something - I had searched for a tag and click on a search result (that is different from the object in Step 1)
3. Note that the object from the search results opens in Edit mode.

#### Environment

* Open MCT Version: 2.1.6
* Deployment Type: local / banner
* OS: Mac
* Browser: Firefox (all?)

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by scottbell**
Closes #6280 

### Describe your changes:
Handle edit mode in annotation results.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [x] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [x] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by scottbell** [comment]
Note, I ran the unit tests 30 times in parallel with the search suite enabled and didn't get any test failures. Hopefully that persists!

File: src/ui/layout/search/AnnotationSearchResult.vue [hunk 1]
```diff
@@ -125,19 +126,37 @@ export default {
...
     methods: {
-        clickedResult() {
+        clickedResult(event) {
             const objectPath = this.domainObject.originalPath;
-            let resultUrl = identifierToString(this.openmct, objectPath);
+            if (this.openmct.editor.isEditing()) {
+                event.preventDefault();
+                this.preview(objectPath);
+            } else {
+                let resultUrl = identifierToString(this.openmct, objectPath);
```
Comment (ozyx) [inline src/ui/layout/search/AnnotationSearchResult.vue:143]: `const`

File: src/ui/layout/search/GrandSearchSpec.js [hunk 2]
```diff
@@ -29,7 +29,7 @@ import GrandSearch from './GrandSearch.vue';
 import ExampleTagsPlugin from '../../../../example/exampleTags/plugin';
 import DisplayLayoutPlugin from '../../../plugins/displayLayout/plugin';
 
-xdescribe("GrandSearch", () => {
+describe("GrandSearch", () => {
```
Comment (ozyx) [inline src/ui/layout/search/GrandSearchSpec.js:32]: Last week we disabled pretty much any test that touches the router since it was causing random test flakes. GrandSearch had a few of these so it was on the chopping block. I'm seeing that this test added is already failing due to the async timeout issue. I think there is some logic triggered by a router path change that's not being handled?

Either way, I don't think this should block this PR. Maybe we should try adding e2e coverage for this specific issue instead and keep the search tests skipped for now.

**Review by ozyx — CHANGES_REQUESTED** [review]
Looks good overall! Tested with both object and annotation search results and it worked well. I've left just a couple comments. We might be able to add e2e test coverage for this fairly easily so as not to be blocked by the ongoing unit test router flake issue (😔)

File: src/ui/layout/search/GrandSearchSpec.js (hunk 2 above)
Comment (scottbell) [reply src/ui/layout/search/GrandSearchSpec.js:32]: Might be the latest merge from master? I'll check, and if I can't reproduce locally, disable and try for an e2e test.

**Review by ozyx — APPROVED** [review]
LGTM!
