### PR TITLE
Equal stacked plot y widths for all it's sub-plots

### LINKED ISSUE #3955: Stacked plots need to align the Y axis
Screen Shot 2021-06-17 at 2 42 41 PM

### LINKED ISSUE #4129: y-axes for stacked plots do not line up
#### Summary

Space is collapsing down to the size of each y-axis value set. Different y-axis value widths cause plots to not be lined up vertically.

#### Expected vs Current Behavior

The y-axes should adjust y-axis value width so that the left-most part of all plots line up vertically.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [x] Is this just a visual bug?

#### Steps to Reproduce

1. Create a stacked plot
2. Observe whether the y-axes line up vertically with one another
2. Adjust the plot data/type as needed so that various y-axis value widths are present. ie. 5.3 and 64.0005

#### Environment
* Open MCT Version: 1.7.6
* Deployment Type: 
* OS:
* Browser:

#### Additional Information

image

### PR DESCRIPTION
**Pull request by shefalijoshi**
Resolves #3955

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? Will users need to change how they are calling the API, or how they've extended core plugins such as Tables or Plots?

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### CODE REVIEW

File: src/plugins/plot/stackedPlot/StackedPlot.vue [hunk 1]
```diff
@@ -127,13 +126,15 @@ export default {
         addChild(child) {
             const id = this.openmct.objects.makeKeyString(child.identifier);
 
-            this.tickWidthMap[id] = 0;
+            this.$set(this.tickWidthMap, id, 0);
```
Comment (nikhilmandlik) [inline src/plugins/plot/stackedPlot/StackedPlot.vue:129]: 👍

**Review by nikhilmandlik — APPROVED** [review]
LGTM

**Comment by nikhilmandlik** [comment]
### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
