### PR TITLE
Imagery Bug Fixes (Future Date Issues)

### LINKED ISSUE #3103: [Example Imagery] Console error on pause when start and end date is in future
#### Steps to reproduce:
1. Add a new Example Imagery object
1. change start time and end time to future date.
1. click on 'pause' and observe error in console.
```
Uncaught TypeError: Cannot read property 'selected' of undefined
    at VueComponent.setSelectedImage (ImageryViewLayout.vue?e401:188)
    at VueComponent.boundFn [as setSelectedImage] (vue.js?ba4c:194)
    at VueComponent.paused (ImageryViewLayout.vue?e401:158)
    at Proxy.boundFn (vue.js?ba4c:194)
    at click (ImageryViewLayout.vue?3994:106)
    at invoker (vue.js?ba4c:1989)
    at HTMLAnchorElement.fn._withTask.fn._withTask (vue.js?ba4c:1787)
setSelectedImage @ ImageryViewLayout.vue?e401:188
boundFn @ vue.js?ba4c:194
paused @ ImageryViewLayout.vue?e401:158
boundFn @ vue.js?ba4c:194
click @ ImageryViewLayout.vue?3994:106
invoker @ vue.js?ba4c:1989
fn._withTask.fn._withTask @ vue.js?ba4c:1787
```

Screen Shot 2020-06-22 at 3 21 51 PM

### PR DESCRIPTION
**Pull request by jvigliotta**
Previously if time bounds were set to a future date the code was looking for an "undefined" image name which threw an error in the console. Also, if you pressed pause in future time bounds (no images) an error would be thrown. Added some checks to make sure there's an image to work with.

Closes #3103 

## Author Checklist
Changes address original issue? Yes
Unit tests included and/or updated with changes? No, probably should have some
Command line build passes? Yes
Changes have been smoke-tested? Yes
Testing instructions included? Yes

### CODE REVIEW

File: src/plugins/imagery/components/ImageryViewLayout.vue [hunk 1]
```diff
@@ -185,15 +186,17 @@ export default {
...
-            if (this.isPaused && image.selected) {
-                this.paused(false);
-                this.unselectAllImages();
-            } else {
-                this.imageUrl = this.getImageUrl(image);
-                this.time = this.getTime(image);
-                this.paused(true);
-                this.unselectAllImages();
-                image.selected = true;
+            if(image) {
```
Comment (nikhilmandlik) [inline src/plugins/imagery/components/ImageryViewLayout.vue:189]: space after if  `if (`
Also can flatten this using (avoid nested if else) 😃 
```
if (!image) {
    return;
}
```

Comment (jvigliotta) [reply src/plugins/imagery/components/ImageryViewLayout.vue]: Done and Done!
