### PR TITLE
Fix source maps in dev mode

### LINKED ISSUE #5497: No source maps in development mode
#### Summary

Recently, we updated `app.js` to conditionally use `webpack.dev.js` if `NODE_ENV === 'development'`. However, this is never set, causing OpenMCT to use production/test webpack configs. This is breaking sourcemaps in development mode.

Fix is to also use `webpack.dev.js` if `NODE_ENV` is not set.

#### Expected vs Current Behavior

OpenMCT should produce sourcemaps in development mode, but it's not.

#### Steps to Reproduce

1. Ensure `NODE_ENV` is not set: `unset NODE_ENV`
2. `npm install`
3. `npm start`
4. Examine the source and notice there are no sourcemaps

#### Environment

* Open MCT Version:  `release/2.0.5`
* Deployment Type:  local
* OS: any
* Browser: any

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by ozyx**
Closes #5497 

### Describe your changes:

Use `webpack.dev.js` in the case `NODE_ENV` is not set, or if `NODE_ENV` is expicitly set to `'development'`.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: app.js [hunk 1]
```diff
@@ -12,7 +12,7 @@ const express = require('express');
 const app = express();
 const fs = require('fs');
 const request = require('request');
-const __DEV__ = process.env.NODE_ENV === 'development';
+const __DEV__ = !process.env.NODE_ENV || process.env.NODE_ENV === 'development';
```
Comment (unlikelyzero) [inline app.js:15]: ahhh

**Review by unlikelyzero — APPROVED** [review]

**Comment by jvigliotta** [comment]
Verified Fixed - Testathon: 8/11

Source maps showing when NODE_ENV is unset, or set to 'development'.
