### PR TITLE
[Telemetry Tables] Don't mutate configuration if object is not able to be persisted 

### LINKED ISSUE #7625: [Telemetry Tables] Telemetry mode changes break on objects that are unable to be persisted
#### Summary

When an object is unable to be persisted, changing telemetry modes (limited, unlimited) will break. 

#### Steps to Reproduce

1. view an object that is unable to be persisted, in a table
2. try to switch telemetry modes
3. notice a mutation error in the console and the mode does not switch

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by jvigliotta**
Closes #7625
VIPEROMCT-428

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this a [notable change](../docs/src/process/release.md) that will require a special callout in the release notes? For example, will this break compatibility with existing APIs or projects that consume these plugins?

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Has this been smoke tested?
* [x] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [x] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?

### CODE REVIEW

File: src/plugins/telemetryTable/TelemetryTableConfiguration.js [hunk 1]
```diff
@@ -52,14 +54,19 @@ export default class TelemetryTableConfiguration extends EventEmitter {
...
+    configuration.persistModeChange = this.notPersistable
+      ? false
+      : configuration.persistModeChange ?? this.defaultOptions.persistModeChange;
     configuration.rowLimit = configuration.rowLimit ?? this.defaultOptions.rowLimit;
 
     return configuration;
   }
 
   updateConfiguration(configuration) {
+    if (this.notPersistable) {
```
Comment (unlikelyzero) [inline src/plugins/telemetryTable/TelemetryTableConfiguration.js:66]: how would we test this

**Review by davetsay — APPROVED** [review]
Good change.
I think this is worthy of an e2e test, but the change looks good.

**Comment by ozyx** [comment]
Test on openmct-yamcs side
