### PR TITLE
Upgrade to `karma-jasmine` 5.1.0 and fix unit tests

### LINKED ISSUE #5405: [Unit tests] Update unit tests to match new describe() and it() syntax checks
#### Summary
karma-jasmine-5.1.0 updated syntax checks after giving us deprecation warnings for months. The following tests are failing

```bash
Chrome Headless 103.0.5060.53 (Linux x86_64) ERROR
  An error was thrown in afterAll
  Error: describe with no children (describe() or it()): the plugin when invoked
      at <Jasmine>
      at /tmp/_karma_webpack_276262/commons.js:929829:5
      at <Jasmine>
      at ./src/plugins/viewDatumAction/pluginSpec.js (/tmp/_karma_webpack_276262/commons.js:929777:1)
      at __webpack_require__ (/tmp/_karma_webpack_276262/runtime.js:23:42)
      at webpackContext (/tmp/_karma_webpack_276262/commons.js:931150:9)
      at Array.forEach (<anonymous>)
Chrome Headless 103.0.5060.53 (Linux x86_64) ERROR
  An error was thrown in afterAll
  Error: describe with no children (describe() or it()): the plugin when invoked
      at <Jasmine>
      at /tmp/_karma_webpack_276262/commons.js:929829:5
      at <Jasmine>
      at ./src/plugins/viewDatumAction/pluginSpec.js (/tmp/_karma_webpack_276262/commons.js:929777:1)
      at __webpack_require__ (/tmp/_karma_webpack_276262/runtime.js:23:42)
      at webpackContext (/tmp/_karma_webpack_276262/commons.js:931150:9)
      at Array.forEach (<anonymous>)
```

Update:
- [ ] Fix all failing tests associated with the new check
- [ ] Update karma-jasmine-5.1.0 dependency

### PR DESCRIPTION
**Pull request by ozyx**
Closes #5405 

### Describe your changes:

Upgrade `karma-jasmine` version to 5.1.0 and update unit tests to be compatible.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by ozyx** [comment]
@unlikelyzero ...alright. pretty sure I rebased this correctly.

File: src/plugins/remoteClock/RemoteClockSpec.js [hunk 1]
```diff
@@ -71,7 +71,7 @@ describe("the RemoteClock plugin", () => {
             parse: (datum) => datum.key
         };
 
-        beforeEach((done) => {
+        beforeEach(async () => {
```
Comment (unlikelyzero) [inline src/plugins/remoteClock/RemoteClockSpec.js:74]: here

**Review by unlikelyzero — APPROVED** [review]
