### PR TITLE
Fix object creation

### LINKED ISSUE #4600: [Condition Set] When creating a new condition set, the resulting domain object does not result in 'Edit mode'
#### Summary
When creating a new condition set, the resulting domain object does not result in 'Edit mode'. Otherwise, everything is working correctly.

#### Expected vs Current Behavior
After a new Condition Set is created, the Condition Set should immediately open in 'Edit mode'. It opens in 'View mode'.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce
1. Create New Condition Set from Create Menu
2. After it's saved, note the mode the user ends in.

#### Environment
* Open MCT Version: 1.8.2
* Deployment Type: viper-openmct release/1.8.2

### PR DESCRIPTION
**Pull request by shefalijoshi**
Resolves #4672 
Don't use the `getCapability` legacy method. 

Resolves #4600 
Fix condition set creation and editing
Fix small bug in mct-tree sorting

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### CODE REVIEW

File: src/plugins/formActions/CreateAction.js [hunk 1]
```diff
@@ -110,13 +111,18 @@ export default class CreateAction extends PropertiesAction {
             .reverse()
             .join('/');
 
-        this.openmct.router.navigate(url);
+        function editObject() {
```
Comment (jvigliotta) [inline src/plugins/formActions/CreateAction.js:114]: Maybe next time we can use the fat arrow here and negate the self variable?

File: src/ui/layout/mct-tree.vue [hunk 2]
```diff
@@ -445,6 +445,10 @@ export default {
             }
 
             // sorting composition items
+            if (!a.name || !b.name) {
```
Comment (jvigliotta) [inline src/ui/layout/mct-tree.vue:448]: Nice!

**Review by jvigliotta — APPROVED** [review]
Had one inline comment about the self variable, not anything to hold up this PR though. Looks good nice work!

### Reviewer Checklist
Check | Passed
-- | --
Changes appear to address issue?? | Y
Appropriate unit tests included? | 
Code style and in-line documentation are appropriate? | Y
Commit messages meet standards? | Y
Has associated issue been labelled unverified? (if PR closes issue) | Y
