### PR TITLE
[Telemetry Collection] Fixes: abort requests, naming, bindings, errors, time system handling

### LINKED ISSUE #4118: [Telemetry Collections] Abort signal key name incorrect
#### Summary

The abort signal key for the options being sent to the historical telemetry provider was incorrectly named. This was preventing telemetry requests from aborting.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. View a high density telemetry endpoint with network tab opened to view fetch requests
2. Navigate away from the object
3. Requests should be canceled, currently they are not

### PR DESCRIPTION
**Pull request by jvigliotta**
This fixes a couple issues that popped up during testing.

Updated name so it's not redundant. Added standard errors. Handling time system and telemetry metadata values correctly, fixed a binding error.

closes #4118

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### CODE REVIEW

File: src/api/telemetry/TelemetryCollection.js [hunk 1]
```diff
@@ -363,4 +376,13 @@ export class TelemetryCollection extends EventEmitter {
     _unwatchTimeSystem() {
         this.openmct.time.off('timeSystem', this._timeSystem, this);
     }
+
+    /**
+     * will throw a new Error, for passed in message
+     * @param  {string} message Message describing the error
+     * @private
+     */
+    _error(message) {
```
Comment (akhenry) [inline src/api/telemetry/TelemetryCollection.js:385]: 👍

File: src/api/telemetry/TelemetryCollection.js [hunk 2]
```diff
@@ -307,8 +312,16 @@ export class TelemetryCollection extends EventEmitter {
      * @private
      */
     _timeSystem(timeSystem) {
-        this.timeKey = timeSystem.key;
-        let metadataValue = this.metadata.value(this.timeKey) || { format: this.timeKey };
+        let domains = this.metadata.valuesForHints(['domain']);
+        let domain = domains.filter((d) => d.key === timeSystem.key)[0];
```
Comment (akhenry) [inline src/api/telemetry/TelemetryCollection.js:316]: This is exactly what [`Array.find`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) is for. It has the additional benefit of short-circuiting when it finds a matching element.

**Review by akhenry — CHANGES_REQUESTED** [review]
Looks great! Just one teensy tiny suggestion.

**Comment by akhenry** [comment]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? N/A
4. Commit messages meet standards? Y
5. Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue) Y

**Review by akhenry — APPROVED** [review]
