### PR TITLE
fix: autoscale turned off could cause errors

### LINKED ISSUE #5039: `autoscale` turned off doesn't work
#### Summary

Turning off autoscale causes ticks to disappear, and zoom/pan doesn't work, with an error in console:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'min')
    at VueComponent.updatePan (MctPlot.vue?5bbd:986:1)
    at VueComponent.trackMousePosition (MctPlot.vue?5bbd:678:1)
```

#### Expected vs Current Behavior

I'm not sure how autoscale turned off should work, I've only experienced it in broken state.

#### Steps to Reproduce

1. create an overlay plot
2. save the overlay plot without modifications
3. create a sinwave generator under the overlayplot
4. click the overlay plot in the sidebar so it is active instead of the sin wave generator
5. turn on edit mode for the overlay plot
6. turn off autoscale
7. note that the ticks in the Y axis are gone
8. save the overlay plot
9. try to pan (f.e. alt + mouse drag in Windows)
10. note the error in the console

#### Environment

* Open MCT Version: `master` branch (3a11291a3b6d4562e0685d1b78dbe227318fc46a as of time of writing)
* Deployment Type: npm start
* OS: Windows, but I doubt it is Windows-specific
* Browser: Chrome, but probably same issue in any browser

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Additional Information

Here is an overlay plot before turning off autoscale, showing no error in console yet:

Screenshot 2022-04-06 134826

Here is what it looks like immediately after unchecking the autoscale check box, showing ticks are missing, but no error in the console yet:

Screenshot 2022-04-06 135003

After saving the overlay plot and trying to pan by holding alt while click-dragging with the mouse, the console shows an error, and the pan attempt did not move the plot:

Screenshot 2022-04-06 135256

### PR DESCRIPTION
**Pull request by trusktr**
Closes #5039

### Describe your changes:

ensure when autoscale is turned off there is a default range so that the UI doesn't have an error in which it is not pannable/zoomable due to undefined values. Also there were no Y axis ticks in the broken state. Now they default from -10 to 10.

- [x] Maybe a better default is to choose the current range. Yeah, I think so. I will make that change.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

To test:

- make overlay plot with sine wave generator. 
- turn off autoscale for the overlay plot and save the overlay. 
- you should see ticks in the Y axis instead of no ticks (that was fixed)
- no pan the plot and panning should work (plus no error in console)

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by trusktr** [comment]
I was unable to get snapshot testing to work. Waiting for more info here: https://github.com/microsoft/playwright/issues/13414

File: src/plugins/plot/configuration/YAxisModel.js [hunk 1]
```diff
@@ -170,7 +169,18 @@ export default class YAxisModel extends Model {
...
+
+            if (range) {
+                // If we already have a user-defined range, make sure it maps to the
+                // range we'll actually use for the ticks.
+                this.set('displayRange', range);
+            } else {
+                // Otherwise use the last known displayRange as the initial
+                // values for the user-defined range, so that we don't end up
+                // with any error from an undefined user range.
+                this.set('range', this.get('displayRange'));
```
Comment (shefalijoshi) [inline src/plugins/plot/configuration/YAxisModel.js:182]: Nice

File: src/plugins/plot/configuration/YAxisModel.js [hunk 2]
```diff
@@ -257,7 +270,7 @@ export default class YAxisModel extends Model {
 @typedef {import('./XAxisModel').AxisModelType & {
     autoscale: boolean
     autoscalePadding: number
-    stats: import('./XAxisModel').NumberRange
+    stats?: import('./XAxisModel').NumberRange
```
Comment (shefalijoshi) [inline src/plugins/plot/configuration/YAxisModel.js:273]: What is this change for?

File: src/plugins/plot/configuration/XAxisModel.js [hunk 3]
```diff
@@ -126,7 +126,7 @@ export default class XAxisModel extends Model {
 
 /**
 @typedef {import("./Model").ModelType<{
-    range: NumberRange
+    range?: NumberRange
```
Comment (shefalijoshi) [inline src/plugins/plot/configuration/XAxisModel.js:129]: What is this change for?

**Review by shefalijoshi — CHANGES_REQUESTED** [review]
Nice work. Some changes requested.

File: src/plugins/plot/inspector/forms/YAxisForm.vue [hunk 4]
```diff
@@ -178,12 +178,6 @@ export default {
                         if (Number(range.min) > Number(range.max)) {
                             return 'Minimum must be less than Maximum.';
                         }
-
-                        if (model.get('autoscale')) {
-                            return false;
-                        }
-
-                        return true;
```
[the remark this answers is not in the document]
Comment (trusktr) [reply src/plugins/plot/inspector/forms/YAxisForm.vue:186]: not anymore. Now it returns a union of possible string values or undefined. THen further below it is used like this:

```js
            const validationError = formField.validate?.(newVal, this.yAxis);
```

`validationError` can be `undefined` (falsey) if `formField.validate` doesn't exist (the `?.` operator will return `undefined` in that case, or if the `validate` function returns `undefined`. Then, the code right after that does

```js
            if (validationError) {
                return;
```

in case there there is an error message, otherwise if no error (`undefined`) then it will continue.

Try it out in VS Code, it shows the type awareness (on hover, etc). There's also TypeScript plugins for pretty much all editors, but I haven't tried other ones. F.e. [WebStorm TypeScript](https://www.jetbrains.com/help/webstorm/typescript-support.html), totally worth it for web projects even with plain JS (it infers types in many cases without writing TS syntax, and can thus provide intellisense).

File: src/plugins/plot/configuration/XAxisModel.js (hunk 3 above)
Comment (trusktr) [reply src/plugins/plot/configuration/XAxisModel.js:129]: This just better depicts the type definition of the model object. Because if you look at the `defaultModel` method, it does not return a value for all properties, so some of them can be `undefined` at some points. So the `?` symbol there makes it undefinable. F.e. `foo: number` means foo can only be `number`, but `foo?: number` means foo is `number | undefined` (number or undefined essentially).

File: src/plugins/plot/inspector/forms/YAxisForm.vue (hunk 4 above)
[the remark this answers is not in the document]
Comment (trusktr) [reply src/plugins/plot/inspector/forms/YAxisForm.vue:186]: Note how we no longer need to call the imported `validate()` function, because we cover that case with the new `?.` syntax.

[the remark this answers is not in the document]
Comment (trusktr) [reply src/plugins/plot/inspector/forms/YAxisForm.vue:186]: The operator is called [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)
