### PR TITLE
[e2e] Add clarity to console.error failures

### LINKED ISSUE #5273: [e2e] Update Console error fixture to be more informative
#### Summary
When the Console error detection fails in the fixtures.js, it's not obvious to users why it failed. We need to fix that with some sort of logging that's apparent in CI.

### PR DESCRIPTION
**Pull request by ozyx**
Closes #5273 

### Describe your changes:

Create a separate assert for every `ConsoleMessage` received so it's more clear why tests fail due to console error detection. Additionally, adds a helper function which converts the `ConsoleMessage` to a string in order to provide additional information such as file location, line, and column numbers.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by unlikelyzero** [comment]
@ozyx can you provide an example of what an error would look like in circle CI with this change? Last week, two different developers reached out to me to interpret the results of a failed test that was simply a console error message that was otherwise easy to interpret

**Comment by ozyx** [comment]
> @ozyx can you provide an example of what an error would look like in circle CI with this change? Last week, two different developers reached out to me to interpret the results of a failed test that was simply a console error message that was otherwise easy to interpret

Sure. 

I've added a "reason" for the failure, so it's clear that it was caused by console error detection. Here are a couple examples, [one from an explicit `console.error()` call](https://app.circleci.com/pipelines/github/nasa/openmct/11318/workflows/0fcfea16-68a6-47d2-b575-1a223b7f3496/jobs/39308/parallel-runs/0?filterBy=ALL&invite=true#step-106-19),

...and the[ other from a TypeError](https://app.circleci.com/pipelines/github/nasa/openmct/11318/workflows/0fcfea16-68a6-47d2-b575-1a223b7f3496/jobs/39308/parallel-runs/0?filterBy=ALL&invite=true#step-106-46), a bit more realistic.

Previously, all of the console messages were appended to a single string, and a failure was raised if `[error]` was detected anywhere within the message. This was a bit confusing, because normal console messages / warnings were being lumped in. Now, there is a singular assert against the message type for every message logged to the console, so it's easier to see what caused the failure.

File: e2e/fixtures.js [hunk 1]
```diff
@@ -4,15 +4,29 @@
...
+
 exports.test = base.test.extend({
     page: async ({ baseURL, page }, use) => {
         const messages = [];
-        page.on('console', msg => messages.push(`[${msg.type()}] ${msg.text()}`));
+        page.on('console', (msg) => messages.push(msg));
         await use(page);
-        await expect.soft(messages.toString()).not.toContain('[error]');
+        messages.forEach(
+            msg => expect.soft(msg.type(), `Console error detected: ${consoleMessageToString(msg)}`).not.toEqual('error')
```
Comment (unlikelyzero) [inline e2e/fixtures.js:25]: This is great. The messaging is clear that the failure comes from the overall test execution and not an individual step or assertion within the test (at least it appears that way to _me_ :) )

**Review by unlikelyzero — APPROVED** [review]

**Comment by ozyx** [comment]
@unlikelyzero Percy is showing differences in the UTC timestamp, is this a known issue?
