### PR TITLE
chore: add vue3 to eslint, fix errors, and modify lint script

### LINKED ISSUE #6909: Update eslint configuration to include Vue 3 rules
#### Summary

In order to support the next step of our upgrade to Vue 3, we will need to enable eslint warnings for Vue 3 required changes.

### PR DESCRIPTION
**Pull request by ozyx**
Closes #6909 

### Describe your changes:

Updates our eslint config to include Vue 3 recommended rules. Edits some existing and non-pertinent rules to be warnings. Splits our linting step into two discrete steps, one that lints against *.js files and accepts no warnings, and another that lints against *.vue files and produces warnings in addition to errors. This is to help guide developers on what needs to change in order for us to complete the migration to Vue 3.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/plugins/timeConductor/ConductorClock.vue [hunk 1]
```diff
@@ -58,19 +58,19 @@ export default {
       }
     }
   },
-  data: function () {
+  data() {
```
Comment (unlikelyzero) [inline src/plugins/timeConductor/ConductorClock.vue:61]: let's push this back onto 3.0.1?

Comment (ozyx) [reply src/plugins/timeConductor/ConductorClock.vue:61]: yeah, we should.

**Review by unlikelyzero — APPROVED** [review]

File: .eslintrc.js [hunk 2]
```diff
@@ -28,6 +28,8 @@ module.exports = {
     }
   },
   rules: {
+    'vue/no-deprecated-dollar-listeners-api': 'warn',
```
[the remark this answers is not in the document]
Comment (ozyx) [reply .eslintrc.js:31]: Both warnings are required in order to upgrade fully to Vue 3. The fix is not trivial (though not complicated), so I'm allowing warnings here so we can work these out and eventually disallow warnings again once we upgrade.
