### PR TITLE
fix(multiYAxis): get yRange for yAxis of the series

### LINKED ISSUE #6163: [Plots] Creating a plot with telemetry on axes 2 and 3 only shows no data.
#### Summary
A plot with telemetry on axes 2 and 3, but with nothing on axis 1 shows no data at all. The axes continue scaling etc. but no data is plotted.

#### Expected vs Current Behavior
I think the expected behavior here is open to debate. Two potential solutions:
1. We just fix the bug that is preventing the data showing and allow users to plot on axes 2 and 3 with nothing on 1. Although this configuration doesn't make much sense, it might be the simplest to implement. OR
2. Higher order axes are only "unlocked" when lower order axes are populated. The implementation of this will be complex because we will have to "reshuffle" axes in the event that someone removes the last object from a lower-order axis.

On balance, my preference is for 1.

#### Steps to Reproduce
1. Create a new Overlay Plot
2. Drag two telemetry points into the plot.
3. They will be mapped to axis 1 by default
4. In the elements pool, drag one of the telemetry points to axis 2.
5. Drag the remaining telemetry point to axis 3
6. Observe that historical data remains in the plot but no new data is shown. Navigating away and back will result in an empty plot.

#### Environment
* Open MCT Version: 2.1.6
* Deployment Type: VIPER test

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

unknown

### PR DESCRIPTION
**Pull request by ozyx**
Closes #6163 

### Describe your changes:

Gets the yRange for the specific yAxis that the series belongs to instead of using the main yAxis's range every time.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [x] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/plugins/plot/chart/MctChart.vue [hunk 1]
```diff
@@ -203,8 +203,15 @@ export default {
         },
         onAddPoint(point, insertIndex, series) {
             const xRange = this.config.xAxis.get('displayRange');
-            //TODO: get the yAxis of this series
-            const yRange = this.config.yAxis.get('displayRange');
+            let yRange;
+            if (series.model.yAxisId === this.config.yAxis.get('id')) {
```
Comment (shefalijoshi) [inline src/plugins/plot/chart/MctChart.vue:207]: Use `series.get('yAxisId')` instead of `series.model.yAxisId`

**Review by shefalijoshi — CHANGES_REQUESTED** [review]

**Review by shefalijoshi — APPROVED** [review]
