### PR TITLE
[Imagery] Improve View Large Action Performance

### LINKED ISSUE #4850: Optimize "View Large" action for imagery
#### Summary
Observed multiple times during egress test today: clicking Imagery in a Flex Layout would often be greatly delayed (20 - 40 seconds) before displaying, and sometimes would not display. Thumbnails which should have been present also would fail to display, or only a sub-set of thumbs would be displayed. 

Important note: there was a lot of latency on the network during the test due to nature of how machines had to be connected, page and new image loads were also pretty slow. 

#### Expected vs Current Behavior
Given my understanding of how Large View works, we should be able to display the cached DOM version (already in the web page) instantly. At the very least, display must be rapid and reliable.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce

See summary

#### Environment
* Open MCT Version: 1.8.4 
* Deployment Type: VIPER
* OS: Linux Ubuntu
* Browser: Firefox

#### Additional Information
Unable to file in VIPER repo due to slowness of that server.

### PR DESCRIPTION
**Pull request by jvigliotta**
Closes #4850 

### Describe your changes:

Originally, the existing view wasn't being utilized and a new view was being requested, then shown, this was causing another request of telemetry, which on slower connections, could decrease performance. Now, we're just using the existing view DOM element, so no additional requests are made and it should be instantaneous.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by unlikelyzero** [comment]
@jvigliotta let me take a look at measuring the performance impact of this one pre-merge

File: src/plugins/viewLargeAction/viewLargeAction.js [hunk 1]
```diff
@@ -38,51 +38,53 @@ export default class ViewLargeAction {
...
 
         this.overlay = this.openmct.overlays.overlay({
-            element: this._getPreview(objectPath),
+            element,
             size: 'large',
             autoHide: false,
-            onDestroy() {
-                parentElement.append(childElement);
+            onDestroy: () => {
+                this.preview.$destroy();
```
Comment (nikhilmandlik) [inline src/plugins/viewLargeAction/viewLargeAction.js:66]: also set `this.preview` to null?

File: src/ui/preview/Preview.vue [hunk 2]
```diff
@@ -91,7 +107,13 @@ export default {
         }
     },
     destroyed() {
-        this.view.destroy();
+        if (!this.existingView) {
+            this.view.destroy();
+        } else if (this.existingViewElement) {
+            // if the existing view element is populated, it's the currently viewed view
+            // in preview and we need to add it back to the parent.
+            this.addExistingViewBackToParent();
```
Comment (nikhilmandlik) [inline src/ui/preview/Preview.vue:115]: wondering if we can do this in `src/plugins/viewLargeAction/viewLargeAction.js`? passed down element append back to parent?

**Review by nikhilmandlik — CHANGES_REQUESTED** [review]
small changes to verify

**Review by unlikelyzero — CHANGES_REQUESTED** [review]
Waiting on feedback on performance measurement from @akhenry

File: src/plugins/viewLargeAction/viewLargeAction.js (hunk 1 above)
Comment (jvigliotta) [reply src/plugins/viewLargeAction/viewLargeAction.js:66]: Can do!

File: src/ui/preview/Preview.vue (hunk 2 above)
Comment (jvigliotta) [reply src/ui/preview/Preview.vue:115]: I would, but the way this is set up now, we're storing the view back on the parent when they select another view (ie. telemetry table), this way the view is still active somewhere and if they close from there, it's just back where it belongs anyways.

File: src/ui/preview/Preview.vue [hunk 3]
```diff
@@ -108,24 +130,58 @@ export default {
...
+            this.initializeViewContainer();
             this.view = this.currentView.view(this.domainObject, this.objectPath);
-
-            this.getActionsCollection();
+            this.getActionsCollection(this.view);
             this.view.show(this.viewContainer, false, this.viewOptions);
             this.initObjectStyles();
         },
-        getActionsCollection() {
+        showExistingView() {
```
Comment (akhenry) [inline src/ui/preview/Preview.vue:148]: I _suspect_ that we could simplify this Vue component a little bit by just combining this method with `setView`. See specific comments.

File: src/ui/preview/Preview.vue [hunk 4]
```diff
@@ -62,19 +68,29 @@ export default {
...
             views: [],
             currentView: {},
-            actionCollection: undefined
+            actionCollection: undefined,
+            existingViewIndex: 0
         };
     },
     mounted() {
-        this.views = this.openmct.objectViews.get(this.domainObject, this.objectPath).map((view) => {
+        this.views = this.openmct.objectViews.get(this.domainObject, this.objectPath).map((view, index) => {
```
Comment (akhenry) [inline src/ui/preview/Preview.vue:76]: Two issues here that are nothing to do with your changes but which we should fix anyway.

This function returns view _providers_ not views. I think if we were to rename `this.views` to `this.viewProviders` it will help make some of the subsequent code easier to understand (at least for me).

Also, why is this a `map` function? It doesn't map any values, it should be a `forEach`.

File: src/ui/registries/ViewRegistry.js [hunk 5]
```diff
@@ -92,6 +92,7 @@ define(['EventEmitter'], function (EventEmitter) {
             const wrappedShow = viewObject.show.bind(viewObject);
             viewObject.show = (element, isEditing, viewOptions) => {
                 viewObject.parentElement = element.parentElement;
+                viewObject.key = key; // provide access to provider key on view object
```
Comment (akhenry) [inline src/ui/registries/ViewRegistry.js:95]: This should happen in `.view`, no need to wait until the view is actually shown.

File: src/ui/preview/Preview.vue [hunk 6]
```diff
@@ -108,24 +130,58 @@ export default {
...
+            }
+
             this.clear();
             this.viewKey = view.key;
             this.currentView = view;
-            this.viewContainer = document.createElement('div');
-            this.viewContainer.classList.add('l-angular-ov-wrapper');
-            this.$refs.objectView.append(this.viewContainer);
+            this.initializeViewContainer();
             this.view = this.currentView.view(this.domainObject, this.objectPath);
```
Comment (akhenry) [inline src/ui/preview/Preview.vue:143]:
``` JavaScript
if (view.key === this.existingView.key) {
    this.view = this.existingView;
} else {
    this.view = this.currentView.view(this.domainObject, this.objectPath);
}
```

File: src/ui/preview/Preview.vue [hunk 7]
```diff
@@ -108,24 +130,58 @@ export default {
...
-
-            this.getActionsCollection();
+            this.getActionsCollection(this.view);
             this.view.show(this.viewContainer, false, this.viewOptions);
```
Comment (akhenry) [inline src/ui/preview/Preview.vue:145]:
``` JavaScript
if (view.key === this.existingView.key) {
    this.viewContainer.appendChild(this.existingViewElement);
} else {
    this.view.show(this.viewContainer, false, this.viewOptions);
}
```

**Review by akhenry — CHANGES_REQUESTED** [review]
Good catch! Nice work figuring out what was going on here. At first glance it looks like it already supports existing views, but they're not actually being passed down to the child component. Probably a regression introduced by accident at some point.

File: src/ui/registries/ViewRegistry.js (hunk 5 above)
Comment (jvigliotta) [reply src/ui/registries/ViewRegistry.js:95]: Good call!

File: src/ui/preview/Preview.vue (hunk 4 above)
Comment (jvigliotta) [reply src/ui/preview/Preview.vue:76]: Gotcha!

File: src/ui/preview/Preview.vue (hunk 6 above)
Comment (jvigliotta) [reply src/ui/preview/Preview.vue:143]: Gotcha!

File: src/ui/preview/Preview.vue (hunk 3 above)
Comment (jvigliotta) [reply src/ui/preview/Preview.vue:148]: agreed!

**Comment by unlikelyzero** [comment]
@jvigliotta @akhenry i noticed an issue with a layout shift when running this on an-avenger-themed-internal-machine. I think this is could use one more tweak (post merge)

**Review by akhenry — APPROVED** [review]

**Review by nikhilmandlik — APPROVED** [review]

**Review by unlikelyzero — APPROVED** [review]

**Comment by akhenry** [comment]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N/A small bug fix
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
5. Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue) Y
