### PR TITLE
Handle couch db not found errors so that interceptors are still invoked.

### LINKED ISSUE #5606: On new CouchDB install, "My Items" isn't being created
#### Summary
On a new CouchDB install, the first time OpenMCT connects to the CouchDB, it creates the `My Items` object to store new objects into. With the [recent CouchDB fixes for persistence errors](https://github.com/nasa/openmct/pull/5576), we're throwing an error before the plugin has a chance to load.

#### Expected vs Current Behavior
[Follow a new CouchDB install using the README](https://github.com/nasa/openmct/blob/master/src/plugins/persistence/couch/README.md), an administrator should be able to connect to a new CouchDB installation without issues.

#### Steps to Reproduce
1. [Following a new CouchDB install using the README](https://github.com/nasa/openmct/blob/master/src/plugins/persistence/couch/README.md) to create a new CouchDB installation.
2. Launch OpenMCT, ensure "My Items" is created and no errors are reported.

##### System:
 - OS: macOS 12.5
 - CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
 - Memory: 93.87 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
##### Binaries:
 - Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
 - npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
##### Browsers:
 - Chrome: 103.0.5060.134
 - Firefox: 103.0.1
 - Safari: 15.6

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

#### Additional Information
This error:
```
GET http://localhost:5984/openmct/mine 404 (Object Not Found)
request @ CouchObjectProvider.js?9318:208
eval @ CouchObjectProvider.js?9318:336
Promise.then (async)
#deferBatchedGet @ CouchObjectProvider.js?9318:327
get @ CouchObjectProvider.js?9318:311
get @ ObjectAPI.js?99d1:219
migrate @ plugin.js?29a1:40
getMutable @ ObjectAPI.js?99d1:307
eval @ Browse.js?bb5e:118
pathToObjects @ Browse.js?bb5e:115
navigateToPath @ Browse.js?bb5e:67
eval @ Browse.js?bb5e:20
doPathChange @ ApplicationRouter.js?a65c:322
handleLocationChange @ ApplicationRouter.js?a65c:370
hashChaged @ ApplicationRouter.js?a65c:395
eval @ ApplicationRouter.js?a65c:230
eval @ location-bar.js?f420:213
any @ location-bar.js?f420:20
loadUrl @ location-bar.js?f420:211
start @ location-bar.js?f420:181
start @ ApplicationRouter.js?a65c:231
MCT.start @ MCT.js?b2c3:371
(anonymous) @ (index):202
```

occurs before the [myItemsInterceptor](https://github.com/nasa/openmct/blob/master/src/plugins/myItems/myItemsInterceptor.js#L39) has a chance to run:
```
invoke (myItemsInterceptor.js?7460:40)
(anonymous) (ObjectAPI.js?99d1:461)
applyGetInterceptors (ObjectAPI.js?99d1:460)
(anonymous) (ObjectAPI.js?99d1:222)
Promise.then (async)
get (ObjectAPI.js?99d1:219)
migrate (plugin.js?29a1:40)
getMutable (ObjectAPI.js?99d1:307)
eval (Browse.js?bb5e:118)
pathToObjects (Browse.js?bb5e:115)
navigateToPath (Browse.js?bb5e:67)
eval (Browse.js?bb5e:20)
doPathChange (ApplicationRouter.js?a65c:322)
handleLocationChange (ApplicationRouter.js?a65c:370)
hashChaged (ApplicationRouter.js?a65c:395)
eval (ApplicationRouter.js?a65c:230)
eval (location-bar.js?f420:213)
any (location-bar.js?f420:20)
loadUrl (location-bar.js?f420:211)
start (location-bar.js?f420:181)
start (ApplicationRouter.js?a65c:231)
MCT.start (MCT.js?b2c3:371)
(anonymous) ((index):202)
```

##### Workaround
Comment out the [throw in the CouchObjectProvider](https://github.com/nasa/openmct/blob/master/src/plugins/persistence/couch/CouchObjectProvider.js#L223).

### PR DESCRIPTION
**Pull request by shefalijoshi**
Closes #5606

### Describe your changes:
Ensure interceptors are called when ObjectAPI.get results in an error thrown.
Missing object interceptor then takes care of not found notifications from couchDB

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by scottbell** [comment]
It looks like a bunch of stuff from `release/2.0.7` is going into this PR, at least according to the diff

File: src/plugins/interceptors/missingObjectInterceptor.js [hunk 1]
```diff
@@ -27,10 +27,13 @@ export default function MissingObjectInterceptor(openmct) {
         },
         invoke: (identifier, object) => {
             if (object === undefined) {
+                const keyString = openmct.objects.makeKeyString(identifier);
```
Comment (akhenry) [inline src/plugins/interceptors/missingObjectInterceptor.js:30]: Nice! This is a great solution, thank you.

**Review by akhenry — APPROVED** [review]

**Comment by akhenry** [comment]
@unlikelyzero This has been re-targeted on release/2.0.8. The Couch e2e PR is still draft, can we merge this PR for now, and potentially file a followup for additional e2e tests?

**Comment by shefalijoshi** [comment]
E2E test steps:
1. Start with an empty navigation tree
2. Attempt to navigate to the My Items folder
3. This should attempt to 'get' the 'mine' object from couchdb
4. (CouchDB should throw a 404 not found error)
5. Navigating to MyItems should succeed with empty composition.

File: e2e/tests/functional/couchdb.e2e.spec.js [hunk 2]
```diff
@@ -71,3 +71,38 @@ test.describe("CouchDB Status Indicator @couchdb", () => {
...
+
+        // Go to baseURL
+        await page.goto('./', { waitUntil: 'networkidle' });
+
+        // Verify that error banner is displayed
+        const bannerMessage = await page.locator('.c-message-banner__message').innerText();
+        expect(bannerMessage).toEqual('Failed to retrieve object mine');
+
+        // Verify that a PUT request to create "My Items" folder was made
+        expect.poll(() => createMineFolderRequests.length, {
```
Comment (akhenry) [inline e2e/tests/functional/couchdb.e2e.spec.js:103]: Don't know how playwright works, but just wondering whether this can be achieved with a Promise resolved by the logic on line 81 rather than polling? It might be a bit cleaner than polling?

**Review by akhenry — CHANGES_REQUESTED** [review]

**Comment by akhenry** [comment]
@shefalijoshi Looks like there are some e2e test failures here. Also need an author checklist.

File: e2e/tests/functional/couchdb.e2e.spec.js (hunk 2 above)
Comment (ozyx) [reply e2e/tests/functional/couchdb.e2e.spec.js:103]: So at this point in the test, I'm trying to verify that Open MCT made an attempt to create the 'mine' folder. My other option was to use `page.waitForRequest()` (https://playwright.dev/docs/api/class-page#page-wait-for-request) with the same specified criteria.

The problem with that approach is that if that request is never made, all we get in the test failure is a generic timeout message. Using `.poll()` solves two problems here:

1. Using `.poll()` will stabilize the test. Sometimes the test happens so fast that the page event isn't captured by the time that the assertion resolves. The `.poll()` has a very short timeout of 1sec so it will retry the assertion if it fails at first (and is still within the timeout).
2. We can specify a message to make it more clear what exactly failed here.

**Comment by shefalijoshi** [comment]
> @shefalijoshi Looks like there are some e2e test failures here. Also need an author checklist.

Yes, looks like the console errors that log couchdb conflicts are causing issues. @unlikelyzero @ozyx  I will need your help to fix this.

File: e2e/tests/functional/couchdb.e2e.spec.js (hunk 2 above)
Comment (akhenry) [reply e2e/tests/functional/couchdb.e2e.spec.js:103]: So, in Jasmine I would do this like so -

``` JavaScript
test.describe("CouchDB initialization @couchdb", () => {
    test.use({ failOnConsoleError: false });
  let resolveMyItems;
  
  const awaitCreationOfMyItems = new Promise((resolve, reject) => {
      resolveMyItems = resolve;
  });
  //...
  page.on('request', req => {
      // eslint-disable-next-line playwright/no-conditional-in-test
      if (req.method() === 'PUT' && req.url().endsWith('openmct/mine')) {
          resolveMyItems();
      }
  });
  //...
  
  return awaitCreationOfMyItems;
}
```

Jasmine used to use polling for asynchronous events as well, but moved to an event driven model. I don't know if Playwright supports returning Promises in the same way that Jasmine does though?

Comment (akhenry) [reply e2e/tests/functional/couchdb.e2e.spec.js:103]: Will merge for now, but would like to explore this a little further and establish a consistent pattern.

**Review by akhenry — APPROVED** [review]

**Review by unlikelyzero — APPROVED** [review]
