### PR TITLE
fix: DisplayLayout and FlexibleLayout toolbar actions only apply to selected layout

### LINKED ISSUE #7176: [Display Layout] Adding a Drawing Object to a parent layout also adds it to the child layout
#### Summary

When you are editing a Display Layout that contains other Display Layouts as child elements, using the "+Add" button to add a drawing shape, line, text, or image to the main layout also adds the object to the child layout. This bug is also editing the sublayout by adding these unwanted objects. You can see this happening  by navigating to the original sublayout object, and seeing that the object has been added to it. (Shown in video). 

This can be very problematic, as this bug is making unwanted edits to layouts, whose changes persist. If users are creating personal complex displays that consist of layouts that are shared by many people and should be minimally edited, this problem can escalate pretty quickly. 

https://github.com/nasa/openmct/assets/48999852/6c951340-aa12-4bab-983c-390e223d3aa0

#### Expected vs Current Behavior

If you are in Edit mode of a Display Layout, regardless of if it contains other child Display Layouts or not, adding a drawing object should _only_ add the object to the main layout. Subobject editing should only occur if the user has clicked on the subobject in the main layout. 

#### Steps to Reproduce

1. Create/Navigate to a Display Layout. 
2. Make sure the Display Layout contains one or more child Display Layouts. 
3. Ensuring you are in Edit Mode for the parent Display Layout, add a drawing object using the "+Add" button. 
4. Observe that the object you've chosen has been added to both the parent and child layout. 
5. Save the layout, and navigate to one of the child layouts used by either using the Object Tree, or pressing the "Go to Original" button. Observe that the changes made to the child layout (an unwanted object being added) are still there. 

#### Environment

* Open MCT Version:   3.2.0
* Deployment Type:   /Testathon
* OS:
* Browser: Chrome

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by ozyx**
Closes #7176

### Describe your changes:

- Adds a `keyString` to the event name emitted by toolbar context actions to uniquely apply the action against the selected object
- Adds e2e tests for adding/removing layout objects into a display layout with child layouts
- Adds e2e test stubs for other toolbar action tests

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [x] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [x] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/plugins/displayLayout/plugin.js [hunk 1]
```diff
@@ -85,10 +85,9 @@ class DisplayLayoutView {
     };
   }
 
-  contextAction() {
-    const action = arguments[0];
-    if (this.component && this.component.$refs.displayLayout[action]) {
-      this.component.$refs.displayLayout[action](...Array.from(arguments).splice(1));
+  contextAction(action, ...rest) {
```
Comment (scottbell) [inline src/plugins/displayLayout/plugin.js:88]: nice refactoring

File: src/plugins/flexibleLayout/toolbarProvider.js [hunk 2]
```diff
@@ -98,7 +99,7 @@ function ToolbarProvider(openmct) {
                   emphasis: 'true',
                   callback: function () {
                     openmct.objectViews.emit(
-                      'contextAction',
+                      `contextAction:${primaryKeyString}`,
```
Comment (scottbell) [inline src/plugins/flexibleLayout/toolbarProvider.js:102]: gah, nice catch

Comment (scottbell) [reply src/plugins/flexibleLayout/toolbarProvider.js:102]: So basically all the layouts were getting this event instead of the single one we wanted. It seems like it'd be good practice to have events names always have the domain key slapped on them just in case, unless you really intend it for a nested object (rare)

File: src/plugins/displayLayout/DisplayLayoutToolbar.js [hunk 3]
```diff
@@ -20,855 +20,891 @@
...
+  SWITCH_VIEW_TYPE: 'switchViewType',
+  MERGE_MULTIPLE_TELEMETRY_VIEWS: 'mergeMultipleTelemetryViews',
+  MERGE_MULTIPLE_OVERLAY_PLOTS: 'mergeMultipleOverlayPlots',
+  TOGGLE_GRID: 'toggleGrid'
+});
 
-        function getAddButton(selection, selectionPath) {
-          if (selection.length === 1) {
-            selectionPath = selectionPath || selection[0];
+export default function DisplayLayoutToolbar(openmct) {
```
Comment (scottbell) [inline src/plugins/displayLayout/DisplayLayoutToolbar.js:37]: should we make this guy a class while we're in here?

File: src/plugins/displayLayout/DisplayLayoutToolbar.js [hunk 4]
```diff
@@ -20,855 +20,891 @@
...
+      }
 
-          if (selection.length === 1 && selectionPath === undefined) {
-            displayLayoutContext = selection[0][0].context;
-          } else {
-            displayLayoutContext = selectionPath[1].context;
+      function getViewSwitcherMenu(selectedParent, selectionPath, selection) {
+        if (selection.length === 1) {
+          // eslint-disable-next-line no-unused-vars
+          let displayLayoutContext = selectionPath[1].context;
```
[the remark this answers is not in the document]
Comment (scottbell) [reply src/plugins/displayLayout/DisplayLayoutToolbar.js:596]: probably should remove this if we're not using it

**Review by scottbell — COMMENTED** [review]
Excellent work @ozyx!

Before: 

https://github.com/nasa/openmct/assets/9853862/b8bb88fe-5550-48c3-b500-3fefb7cf55da

After:

https://github.com/nasa/openmct/assets/9853862/43274b1c-f473-4cee-995b-2a9d66796e4a

Had some minor comments, but otherwise looking good.

File: src/plugins/flexibleLayout/toolbarProvider.js (hunk 2 above)
Comment (ozyx) [reply src/plugins/flexibleLayout/toolbarProvider.js:102]: Yeah. Having to handle all those events is costly. This might be a good solution for some cases

File: e2e/test-data/display_layout_with_child_layouts.json
Comment (scottbell) [inline e2e/test-data/display_layout_with_child_layouts.json:1]: Is this meant to be checked in?

**Review by scottbell — COMMENTED** [review]
Tested and looked good. Had a question about checking in the JSON representation of the nest display layouts. Did we want to check this in? Will it change from run to run?

File: e2e/test-data/display_layout_with_child_layouts.json
Comment (ozyx) [reply e2e/test-data/display_layout_with_child_layouts.json:1]: Yep! it will only be regenerated if we run `npm run test:e2e:generatedata`

**Review by scottbell — APPROVED** [review]
