### PR TITLE
Independent time conductor related handling for plot synchronization.

### LINKED ISSUE #7737: Plots are respecting independent time context settings, even if not enabled
#### Summary
If you are viewing a plot in realtime mode, pause the plot, then sync the time conductor, Open MCT will prompt you to accept that time conductor will be changed to Fixed time mode. If you have an independent time context and it is in fixed time mode (an assumption because it has never enabled in this use case), but it is not enabled, you do not get the warning message and you are switched to fixed mode in the time conductor. Furthermore, if you use independent time context and pause then sync time, it works, but the UI isn't completely reactive to that change, the independent time context appears to be in realtime mode still when in fact it has switched to fixed.

I assume many other things doing checks or actions on `this.timeContext` are similarly affected.

Related to settings regarding the Time Conductor Sync warning: #7927 
Viper JIRA: VIPERGC-706

#### Expected vs Current Behavior
Plots should only be listening to ITC if enabled, or time conductor if ITC is not enabled.

#### Steps to Reproduce
`No fixed time change warning prompt`
1. Create an overlay plot, add telemetry to it, and save
2. View the plot in realtime mode
4. hover over the plot and click `Pause`
5. hover over the plot and click `Synchronize with Time Conductor`
6. Observe you get a warning message and are switched to Fixed time mode (This is expected behavior)
7. Toggle the independent time conductor, then toggle the indepedent time conductor off
8. Change the time conductor back to realtime mode.
9. Repeat steps 4 and 5 to pause and sync time with conductor
10. Observe this time there is no warning message.

`Plot display is fixed, but Y-axis is still reacting to new data`
1. Repeat Steps 7-9 of previous test to get in a state where changing time conductor from realtime to fixed time has not given you a warning message before switching
2. Continue to watch plot. If incoming data would adjust the plot axis, it will do so, even if the plot data is outside of the time conductor and plot display bounds

ITC realtime to fixed time mode dispaly issue
1. Toggle on independent time conductor on a plot
4. hover over the plot and click `Pause`
5. hover over the plot and click `Synchronize with Time Conductor`
6. Observe that the plot does indeed switch to fixed time mode, but the ITC appears to be in realtime mode still (clock icon spinning, blue background). Can click the ITC to expand the pop up as well to observe in fixed.
7. Observe also the behavior of `Plot display is fixed, but Y-axis is still reacting to new data`

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by shefalijoshi**
Closes #7737

### Describe your changes:
Ensure that the mode set when independent time conductor is enabled/disabled is propagated correctly.

Also ensure that global time conductor changes are not picked up by the independent time conductor when the user has enabled it at least once before

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this a [notable change](../docs/src/process/release.md) that will require a special callout in the release notes? For example, will this break compatibility with existing APIs or projects that consume these plugins?

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Has this been smoke tested?
* [x] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [x] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?

### CODE REVIEW

**Comment by unlikelyzero** [comment]
@shefalijoshi i think the best test is the first example of steps to reproduce:

> No fixed time change warning prompt
> 
> Create an overlay plot, add telemetry to it, and save
> View the plot in realtime mode
> hover over the plot and click Pause
> hover over the plot and click Synchronize with Time Conductor
> Observe you get a warning message and are switched to Fixed time mode (This is expected behavior)
> Toggle the independent time conductor, then toggle the indepedent time conductor off
> Change the time conductor back to realtime mode.
> Repeat steps 4 and 5 to pause and sync time with conductor
> Observe this time there is no warning message.

File: src/api/time/TimeAPI.js [hunk 1]
```diff
@@ -152,6 +153,12 @@ class TimeAPI extends GlobalTimeContext {
       timeContext.setMode(FIXED_MODE_KEY, value);
     }
 
+    // Also emit the mode in case it's different from the previous time context
+    timeContext.emit(
+      TIME_CONTEXT_EVENTS.modeChanged,
+      JSON.parse(JSON.stringify(timeContext.getMode()))
```
Comment (davetsay) [inline src/api/time/TimeAPI.js:159]: I think we can use `structuredClone` over `JSON` cloning, unless there is a good reason not to.

**Review by davetsay — CHANGES_REQUESTED** [review]
Looks good. I have a couple requests. One is inline, and the other is can you add test coverage?

File: e2e/tests/functional/plugins/plot/plotControls.e2e.spec.js [hunk 2]
```diff
@@ -108,4 +108,59 @@ test.describe('Plot Controls', () => {
...
+    // synchronize time conductor
+    await page.getByTitle('Synchronize Time Conductor').click();
+
+    // expect warning message, ack it.
+    await expect(page.getByLabel('Modal Overlay')).toBeVisible();
+    await page.getByLabel('Modal Overlay').getByRole('button', { name: 'OK' }).click();
+
+    // Toggle independent time conductor ON
+    await page.getByLabel('Enable Independent Time Conductor').click();
+    // Toggle independent time conductor OFF
```
Comment (davetsay) [inline e2e/tests/functional/plugins/plot/plotControls.e2e.spec.js:148]: Before toggling independent time conductor off we need to ensure it is in fixed mode. If both the global time conductor and independent time conductor modes are realtime, you won't see this bug symptom, even without the bug fix.

**Review by davetsay — CHANGES_REQUESTED** [review]

File: e2e/tests/functional/plugins/plot/plotControls.e2e.spec.js (hunk 2 above)
Comment (shefalijoshi) [reply e2e/tests/functional/plugins/plot/plotControls.e2e.spec.js:151]: Good point. Done.

**Review by davetsay — APPROVED** [review]
Awesome. Thanks for perfecting the test.

**Comment by davetsay** [comment]
Some tests failing however. Hopefully flake...
