### PR TITLE
[Notebook] Browse Bar holding onto stale model, reverts changes

### LINKED ISSUE #7943: [Notebook] Changing notebook name in browse bar can cause any changes in notebook to disappear
VIPERGC-702

#### Summary

Editing a notebook name in the browse bar and making changes, then editing it again will cause any changes to be erased.

#### Expected vs Current Behavior

No notebook changes should disappear without explicitly deleting them.

#### Steps to Reproduce

1. Create or visit an existing notebook
2. Edit the name of the notebook in the Browse Bar
3. Make ANY chnages to the notebook (add entries, add pages, sections, etc)
4. Edit the name of the notebook in the browse bar again
5. Notice all changes made have been reverted

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by jvigliotta**
Closes #7943 7943

### Describe your changes:

In Browse.js instead of just watching the name of the domain object to update the page title, we watch the whole object and update the whole object, while also updating the page title if necessary.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this a [notable change](../docs/src/process/release.md) that will require a special callout in the release notes? For example, will this break compatibility with existing APIs or projects that consume these plugins?

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Has this been smoke tested?
* [x] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [x] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [x] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?

### CODE REVIEW

File: src/ui/router/Browse.js [hunk 1]
```diff
@@ -80,13 +80,11 @@ class Browse {
...
   }
 
-  #updateDocumentTitleOnNameMutation(newName) {
-    if (typeof newName === 'string' && newName !== document.title) {
-      document.title = newName;
-      this.#openmct.layout.$refs.browseBar.domainObject = {
-        ...this.#openmct.layout.$refs.browseBar.domainObject,
-        name: newName
-      };
+  #handelBrowseObjectUpdate(newObject) {
```
Comment (akhenry) [inline src/ui/router/Browse.js:83]: Typo

**Review by akhenry — CHANGES_REQUESTED** [review]

File: src/ui/router/Browse.js (hunk 1 above)
Comment (jvigliotta) [reply src/ui/router/Browse.js]: looooooooong exaggerated sigh... Spelling is dumb.

**Review by akhenry — APPROVED** [review]
