### PR TITLE
[Navigation Tree] Simplify logic

### LINKED ISSUE #3384: Object tree cannot be navigated while it's loading
Steps to reproduce:
1. Throttle your bandwidth to a 3G connection.
2. Expand a tree node that requires a connection to a server (eg. "My Items" or "Shared Items" using the Couch DB adapter. LocalStorage will not manifest this problem)
3. Observe the "loading" indicator while the browser requests the tree composition from the server
4. Before the tree items are loaded, attempt to expand a parent node using the `<` arrow next to that node.
5. Observe that the node does not expand.

### LINKED ISSUE #3438: [Navigation Tree] Deleting selected item does not highlight parent when it's selected after
## Observed
- Delete a child folder folder that's currently selected in tree
- Parent folder is now being viewed
- Parent folder is NOT showing as selected

## Expected
- Deleting a child folder that is selected in the tree should update viewed object to parent (does so correctly) AND highlight parent in the tree

### LINKED ISSUE #3439: [Tree] Ancestor composition not being watched for changes
## Overview
Ancestors are not being watched for changes to its composition so changes on the current object, if it children are expanded

## Expected Behavior
The tree structure should react to all changes current visible tree.
* deleting the current node if it has children expanded should be removed from tree

## Steps to Reproduce
1. Create a display layout
1. Create any subobject with a child
1. Expand tree so that the display layout, the subobject, and the subobject's child(ren) are visible
1. In edit mode, delete the subobject
1. Observe that the node in the tree has not changed.

tree delete

### LINKED ISSUE #3455: [Tree] Simplified tree implementation
Given what we've learnt during the initial implementation of the new tree, let's take a step back and look at whether it could be implemented in a simpler and clearer way that will be easier to maintain in the future.

### PR DESCRIPTION
**Pull request by jvigliotta**
Simplified tree code, removed a lot of timeouts and $nextTicks, consolidated navigation of the tree into one method that can track and cancel if new tree nav requests come in, changed some variable names for clarity, simplified logic.

closes #3439
closes #3455
closes #3438
closes #3384

### CODE REVIEW

File: src/ui/layout/mct-tree.vue [hunk 1]
```diff
@@ -1,9 +1,13 @@
 <template>
 <div
+    ref="searchAndTree"
```
Comment (deeptailor) [inline src/ui/layout/mct-tree.vue:3]: If its the root element of the component, we can use this.$el, no need to add a ref

File: src/ui/layout/mct-tree.vue [hunk 2]
```diff
@@ -14,61 +18,84 @@
...
         class="c-tree-and-search__tree c-tree"
     >
         <!-- ancestors -->
-        <li v-if="!activeSearch">
+        <div v-if="!activeSearch">
+
+            <div
+                ref="dummyItem"
+                class="c-tree__item-h"
+                style="left: -1000px; position: absolute;"
```
Comment (deeptailor) [inline src/ui/layout/mct-tree.vue:47]: did you try using visibility: hidden ?

**Review by deeptailor — CHANGES_REQUESTED** [review]
Looks great, you simplified it a bunch. Just a couple of comments

File: src/ui/layout/mct-tree.vue (hunk 1 above)
Comment (jvigliotta) [reply src/ui/layout/mct-tree.vue:3]: good call! updated.

File: src/ui/layout/mct-tree.vue (hunk 2 above)
Comment (jvigliotta) [reply src/ui/layout/mct-tree.vue:47]: I had not, but I just did and it will block the current first ancestor if I do that. I kept the styles as is but included visibility hidden as well as an added layer hiddenness (wow, that's a word). Another option would be to add position: relative to it and any other ancestors (or just the first one) and then use z-indexing to put it in the back.

**Review by deeptailor — APPROVED** [review]

**Comment by deeptailor** [comment]
## Reviewer Checklist
Changes appear to address issue? Yes
Appropriate unit tests included? N/A
Code style and in-line documentation are appropriate? Yes
Commit messages meet standards? Yes
Has associated issue been labelled unverified? (only applicable if this PR closes the issue) Yes
