### PR TITLE
[#4378] Ensure navigated object check works correctly when path is modified

### LINKED ISSUE #4378: Creating a new Condition Set goes into Browse mode
When I create a new Condition Set, it doesn't go into Edit mode, instead saving directly into Browse mode with this error:
> TypeError: Cannot read properties of undefined (reading 'length')
    at parseKeyString (object-utils.js?c88f:63)
    at Array.map (<anonymous>)
    at ObjectAPI.areIdsEqual (ObjectAPI.js?4467:510)
    at ApplicationRouter.isNavigatedObject (ApplicationRouter.js?ae1c:150)
    at ConditionSetViewProvider.canView (ConditionSetViewProvider.js?ca3e:39)
    at eval (ViewRegistry.js?ea6e:61)
    at Array.filter (<anonymous>)
    at ViewRegistry.get (ViewRegistry.js?ea6e:60)
    at isFirstViewEditable (CreateAction.js?95e8:75)
    at navigateAndEdit (CreateAction.js?95e8:91) 'Possibly unhandled rejection: {}'

I didn't get the same problem with Display Layouts, and running master locally doesn't manifest the problem either.

_Originally posted by @charlesh88 in https://github.com/nasa/openmct/pull/4310#pullrequestreview-785053682_

### PR DESCRIPTION
**Pull request by shefalijoshi**
Resolves #4378
On creation of a condition set, the condition set view was never being returned as one of the views from objectViews.get.
This is because the navigated object check in application router was returning false for 2 reasons:
1. The objectPath had objects in the old format, so they didn't have identifiers.
2. The path for the router had not changed yet when we checked if the navigated object  === target object (the condition set).

The fix was to:
1. Assign identifiers to the objectPath being passed to objectViews.get
2. Emit an event when router path is set. Handle the event when creating an object.

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [ ] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [ ] Command line build passes?
* [ ] Has this been smoke tested?
* [ ] Testing instructions included in associated issue?

### CODE REVIEW

**Comment by akhenry** [comment]
1. Legacy objects should never appear in the objectPath. This is a bug, we need to fix it.
> 2. The path for the router had not changed yet when we checked if the navigated object === target object

Where does this check happen? Why was it working previously? What did we change that has broken it?

**Review by akhenry — CHANGES_REQUESTED** [review]
1. Legacy objects should never appear in the objectPath. This is a bug, we need to fix it.
2. > The path for the router had not changed yet when we checked if the navigated object === target object

Where does this check happen? Why was it working previously?

File: src/ui/router/Browse.js [hunk 1]
```diff
@@ -68,6 +68,7 @@ define([
                 objects = objects.reverse();
 
                 openmct.router.path = objects;
```
Comment (nikhilmandlik) [inline src/ui/router/Browse.js:70]: I think we should move this to `src/ui/router/ApplicationRouter.js` there is existing `setPath` may be doing something different

**Comment by shefalijoshi** [comment]
>     1. Legacy objects should never appear in the objectPath. This is a bug, we need to fix it.
> 
>     2. > The path for the router had not changed yet when we checked if the navigated object === target object
> 
> 
> Where does this check happen? Why was it working previously?
@akhenry 
It was working before because we did not have this fix in the condition set view provider for flexible layouts: https://github.com/nasa/openmct/pull/4179/files#diff-0bff5a6f99db64e9b5322caa61d2aa0344eda15148a8fba7ed4bcc992d5254f6R39

File: src/ui/router/Browse.js (hunk 1 above)
Comment (shefalijoshi) [reply src/ui/router/Browse.js:70]: This code has been here for a long time. We can move it, but probably have a separate PR to do it.

File: platform/commonUI/edit/src/creation/CreateAction.js [hunk 2]
```diff
@@ -86,11 +86,23 @@ define(
...
+                    if (isFirstViewEditable(object.useCapability('adapter'), path)) {
+                        openmct.editor.edit();
+                    }
 
-                if (isFirstViewEditable(object.useCapability('adapter'), objectPath)) {
-                    openmct.editor.edit();
+                    openmct.router.off('assigned:path', editObject);
                 }
+
+                openmct.router.on('assigned:path', editObject);
```
Comment (akhenry) [inline platform/commonUI/edit/src/creation/CreateAction.js:103]: You could use `openmct.router.once(` and void having to clean it up.

File: platform/commonUI/edit/src/creation/CreateAction.js [hunk 3]
```diff
@@ -86,11 +86,23 @@ define(
                         })
                         .join('/');
 
-                openmct.router.navigate(url);
+                function editObject() {
+                    const path = objectPath.slice(-1).map(obj => {
+                        const objNew = obj.getCapability('adapter');
+                        objNew.identifier = openmct.objects.parseKeyString(obj.getId());
```
Comment (akhenry) [inline platform/commonUI/edit/src/creation/CreateAction.js:92]: The adapter capability doesn't automatically give them an identifier? It seems like it maybe should?

**Review by akhenry — CHANGES_REQUESTED** [review]
I like this fix. I agree that the new event is the right approach. Maybe we could make it even clearer and call it `afterNavigation`. So it would be called with `openmct.router.on('afterNavigation')`?

A couple of minor suggestions inline.

File: platform/commonUI/edit/src/creation/CreateAction.js (hunk 3 above)
Comment (shefalijoshi) [reply platform/commonUI/edit/src/creation/CreateAction.js:92]: No it doesn't. :( 
Do you want me to add that? I didn't want to touch legacy code at this point since it will go away soon anyway.

File: platform/commonUI/edit/src/creation/CreateAction.js (hunk 2 above)
Comment (shefalijoshi) [reply platform/commonUI/edit/src/creation/CreateAction.js]: Love it! Done.

**Review by nikhilmandlik — DISMISSED** [review]

File: platform/commonUI/edit/src/creation/CreateAction.js (hunk 3 above)
Comment (akhenry) [reply platform/commonUI/edit/src/creation/CreateAction.js:92]: Hrm, this shouldn't be necessary. The adapter capability ultimately calls the `toNewFormat` function in object-utils [which assigns an identifier](https://github.com/nasa/openmct/blob/master/src/api/objects/object-utils.js#L137).

**Review by akhenry — APPROVED** [review]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
5. Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue) Y
