### PR TITLE
Export display

### LINKED ISSUE #6561: [Export as JSON] Issues with items that have identifiers stored in configuration
#### Summary

There is an issue with exporting display layouts (or any item that has configuration that stores identifiers). When we export we find and replace old key strings with new key strings, but this misses the case where identifiers are used (such as above mentioned configuration). This causes odd issues, like display layout items "pancaking" 1:1 coordinates of the grid. This fix adds checks for identifier objects as well and will replace those.

#### Expected vs Current Behavior

Identifiers should have always been included in the replacement, they are not included in the replacement.

#### Steps to Reproduce

1. have an linked/aliased item in a display layout that also has a namespace in it's identifier
2. export the item
3. import the item
4. notice that the positions for aliased items are lost

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by jvigliotta**
Closes #6561 

### Describe your changes:

Finding and replacing identifiers as well.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/plugins/exportAsJSONAction/ExportAsJSONAction.js [hunk 1]
```diff
@@ -156,11 +156,35 @@ export default class ExportAsJSONAction {
      * @private
      */
     _rewriteReferences() {
+        const oldKeyStrings = Object.keys(this.idMap);
         let treeString = JSON.stringify(this.tree);
-        Object.keys(this.idMap).forEach(function (oldId) {
-            const newId = this.idMap[oldId];
-            treeString = treeString.split(oldId).join(newId);
-        }.bind(this));
```
Comment (davetsay) [inline src/plugins/exportAsJSONAction/ExportAsJSONAction.js:163]: We don't need no stinking binders!

**Review by davetsay — APPROVED** [review]
Great find and fix.

Like you said, we really should go through and ensure we're using the api method on creating identifiers.
