### PR TITLE
[Conditionals] fix #2961 in vista-r4.4

### LINKED ISSUE #2961: Condition Set telemetry output being evaluated incorrectly
Example on hulk: https://hulk.ndc.nasa.gov/viper/#/browse/0ff3a037-af01-497e-93b5-5ac3839da282/mine/0b834eca-5833-4f5d-a641-d58ac4f273a7?tc.mode=local&tc.timeSystem=utc&tc.startDelta=3610000&tc.endDelta=0&view=layout.view

Here's some recorded VIPER telemetry that varies between ~-1 and 567 over about an hour:
Screen Shot 2020-04-22 at 9 45 36 PM

Here's a Condition Set that evals that telemetry:
Screen Shot 2020-04-22 at 9 34 22 PM

When the Condition Set is viewed on its own in the main view, the conditions are matching real-time data as expected. But when the CS is dropped into a Layout as telemetry, or is used to control conditional styling, the evaluator isn't working properly. 

What appears to be happening is that historic values within the current Time Conductor range are being included in the evaluation, but shouldn't be. For example, consider this: the TC is set to 1 minute, constraining available historic values to a narrow band:
Screen Shot 2020-04-22 at 9 52 40 PM

In this case, the CS is evaluating as expected, showing an output of 65% based on the value being greater than 100.

But, setting the TC to 2 hours brings the max value of 566 into view:
Screen Shot 2020-04-22 at 9 53 32 PM

Note that even though the current value is 197 and the CS should be matching and displaying 65%, it shows 92%, which is a match against values greater than 500. So the historic 566 value is being used as part of the matching, but should not be, as there are much more current values closer to "now" that should be the ones being evaluated.

IMO, this is a major bug and could cause erroneous displays - we should fix ASAP. 

fix in master and in vista-r4.4-rc6

### PR DESCRIPTION
**Pull request by davetsay**
## Overview
Addresses #2961
- use correct id for data cache
- separate request and subscription any/all telemetry data cache
- use latest timestamp for any/all telemetry requests

## Author Checklist
| | |
| --- | :---: |
| Changes address original issue? | Y |
| Unit tests included and/or updated with changes? | N/A |
| Command line build passes? | Y |
| Changes have been smoke-tested? | Y |

### CODE REVIEW

File: src/plugins/condition/criterion/AllTelemetryCriterion.js [hunk 1]
```diff
@@ -127,20 +128,37 @@ export default class AllTelemetryCriterion extends TelemetryCriterion {
...
+
+                const datum = {
+                    result: evaluateResults(Object.values(telemetryDataCache), this.telemetry),
+                    ...latestTimestamp
+                };
+
                 return {
                     id: this.id,
-                    data: this.formatData(latestDatum, options.telemetryObjects)
+                    data: datum
```
Comment (deeptailor) [inline src/plugins/condition/criterion/AllTelemetryCriterion.js:161]: Do we not need to format the datum anymore?

Comment (davetsay) [reply src/plugins/condition/criterion/AllTelemetryCriterion.js:161]: Format datum take each incoming subscription datum and updates the the class data cache and latest timestamp. We are doing the same just within the request itself so we aren't using formatData here in requests.

Comment (deeptailor) [reply src/plugins/condition/criterion/AllTelemetryCriterion.js:161]: Got it

**Comment by deeptailor** [comment]
## Reviewer Checklist
Changes appear to address issue? Yes
Appropriate unit tests included? N/A
Code style and in-line documentation are appropriate? Yes
Commit messages meet standards? Yes
