### PR TITLE
Ensure stacked plots show cumulative legend

### LINKED ISSUE #7403: [Plot Legends] Legends not expanding when requested
#### Summary

This issue is seen in both Stacked Plots and Overlay Plots. However, the behaviors amongst the two are _slightly_ different, but caused by the same issue. 

***_**OVERLAY PLOT ISSUE (Occurs with both Real Telemetry or Sine Wave Generators)**_ ***
When, in an Overlay Plot that is populated either with _real telemetry,_ or _Sine Wave Generators,_ a user selects the "expand by default" option for the legend and saves, the class that enables the legend to be expanded is being applied, but the legend is not actually expanding. Instead, we're getting into a weird state that looks like the image below. Notice that the triangle icon is indeed the one that we use for expanding an item (the triangle is pointing down), but the legend itself is not expanding. For a user to see the expanded legend, they have to manually click the icon to first collapse it, then click it again to expand it. 
Screenshot 2024-01-23 at 1 59 18 PM

Additionally, the inspector settings are not updating once out of edit mode or even refreshed. This image below shows that even after I saved the plot settings with the legend "expanded by default" enabled, then _refreshed_, the inspector still shows the setting as disabled. However, note that if I do go into edit mode and look at the setting, it shows that it is enabled. 
Screenshot 2024-01-23 at 2 00 58 PM

***_**STACKED PLOT ISSUE (Sine Wave Generators and Real Telemetry present different behaviors)**_ ***
(A) When, in a Stacked Plot that is populated with **Sine Wave Generators**, the following incorrect behavior happens when you enable the "expand by default" setting for legends: 
While the inspector shows that the setting is enabled, the legends in the plot are not being expanded on default. Unlike the Overlay Plot issue from above, the "expanded" class is not being added in the code, and thus is not even being shown visually with the triangle icons.  
Screenshot 2024-01-23 at 2 15 37 PM

(B) When, in a Stacked Plot that is populated with **Real Telemetry**, the following incorrect behavior happens when you enable the "expand by default" setting for legends, save the object, and refresh: 
The same behavior as Overlay Plots occurs, where the Inspector still shows the setting as _disabled_, while the legend icon appears to be expanded, while the legend table itself is collapsed. 
Screenshot 2024-01-23 at 2 28 50 PM

#### Expected vs Current Behavior

When the setting for legends, "expand by default" is enabled on a Overlay Plot or Stacked Plot, the legend should be expanded when you first navigate to the object. You should not have to manually expand the legend.

#### Steps to Reproduce

**OVERLAY PLOT ISSUE & STACKED PLOT ISSUE (USING REAL TELEMETRY)_ **
1. Navigate to an Overlay Plot and go into Edit Mode. For Stacked Plots, make sure the plot is populated with REAL telemetry, not Sine Wave Generators.
2. Under the Config tab in the Inspector, enable the "expand by default" option for legends, then Save. 
3. Observe that in the Inspector, under the Config tab, the "expand by default" setting is still set to "No."
4. Also observe that the legend's triangle icon is pointing down (showing the legend is expanded), but the legend table does not appear until you press the triangle icon to collapse, then press again to expand the legend.

**_STACKED PLOT ISSUE (USING SWGs)_ **
1. Navigate to a Stacked Plot that is populated with SWGs. 
2. Under the Config tab in the Inspector, enable the "expand by default" option for legends, then Save. 
3. Observe that while the inspector is showing the "expand by default" setting set to "Yes", the legend in the plot is completely collapsed.

#### Environment

* Open MCT Version:  3.3.0
* Deployment Type:  testathon
* OS:
* Browser: Chrome

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by scottbell**
Closes #7403 

### Describe your changes:

Listen to series models in the legend, and hide options that don't make sense if the cumulative legend isn't being used.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Has this been smoke tested?
* [x] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [x] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [ ] Is this a breaking change to be called out in the release notes?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?

### CODE REVIEW

File: src/plugins/plot/inspector/PlotOptionsBrowse.vue [hunk 1]
```diff
@@ -79,7 +79,10 @@
           </div>
           <div class="grid-cell value">{{ showLegendsForChildren ? 'Yes' : 'No' }}</div>
         </li>
-        <li class="grid-row">
+        <li
+          v-if="!isStackedPlotObject || (isStackedPlotObject && !showLegendsForChildren)"
```
Comment (ozyx) [inline src/plugins/plot/inspector/PlotOptionsBrowse.vue:83]: should we extract this to a computed property?

File: src/plugins/plot/inspector/forms/LegendForm.vue [hunk 2]
```diff
@@ -26,12 +26,16 @@
...
           v-model="showLegendsForChildren"
+          aria-label="Show Legends For Children"
           type="checkbox"
           @change="updateForm('showLegendsForChildren')"
         />
       </div>
     </li>
-    <li class="grid-row">
+    <li
+      v-if="!isStackedPlotObject || (isStackedPlotObject && !showLegendsForChildren)"
```
Comment (ozyx) [inline src/plugins/plot/inspector/forms/LegendForm.vue:36]: same thing here

**Review by ozyx — APPROVED** [review]
Changes look and work great, just a small suggestion
