### PR TITLE
[Timelist] Fixed Time use Now as start time - 5772

### LINKED ISSUE #5772: [Timelist] Follow up from 5629
#### Summary

    Navigate to a timelist view in local clock mode with the following filters in the inspector:
    
image

    Switch to fixed timespan - verify that all activities are shown
    Refresh the browser
    Observe that the timelist is empty, expectation is that all activities should be displayed.

https://github.com/nasa/openmct/issues/5629#issuecomment-1248733293

#### Expected vs Current Behavior
Timelist is empty when in Fixed timespan mode, expectation is that all activities should be displayed.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by michaelrogers**
Closes #5772 

### Describe your changes:

Updated the fixed time timelist to show current / future events based on the current time. Edit mode view all flag is still maintained. Start / end time formatter updated to use the Time API formatter instead of moment directly.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

**Comment by shefalijoshi** [comment]
@michaelrogers This doesn't appear to be working if I change the fixed timespan bounds. Can you test this?

File: src/plugins/timelist/Timelist.vue [hunk 1]
```diff
@@ -197,23 +197,28 @@ export default {
...
                 this.updateTimeStampAndListActivities(this.openmct.time.bounds()?.start);
             } else {
-                this.setSort();
-                this.setViewBounds();
                 this.updateTimeStampAndListActivities(this.openmct.time.clock().currentValue());
             }
+
+            this.setSort();
+            this.setViewBounds();
+            this.listActivities();
```
Comment (shefalijoshi) [inline src/plugins/timelist/Timelist.vue:221]: The `this.updateTimeStampAndListActivities` method already performs `this.listActivities` so this will result in it being run twice. Can this be done differently?

**Review by shefalijoshi — CHANGES_REQUESTED** [review]

File: src/plugins/timelist/Timelist.vue (hunk 1 above)
Comment (michaelrogers) [reply src/plugins/timelist/Timelist.vue]: Absolutely, I think this was an artifact of the PR being based on an earlier version of master that predated the `updateTimestampAndListActivities` method and then reintroduced from a merge conflict. I've removed it as it did indeed duplicate the 3 method calls.

File: src/plugins/timelist/Timelist.vue [hunk 2]
```diff
@@ -197,21 +197,22 @@ export default {
...
+            } else if (isTick === false && this.openmct.time.clock() === undefined) {
+                // set the start time for fixed time using the selected bounds start
+                this.updateTimeStampAndListActivities(bounds.start);
             }
         },
         setViewFromClock(newClock) {
             this.filterValue = this.domainObject.configuration.filter;
-            const isFixedTime = newClock === undefined;
-            if (isFixedTime) {
+            this.isRealTime = newClock !== undefined;
```
Comment (shefalijoshi) [inline src/plugins/timelist/Timelist.vue:210]: Let's remove this change if it's the same as before and keep `this.isFixedTime`

**Review by shefalijoshi — CHANGES_REQUESTED** [review]
One more small change please.

File: src/plugins/timelist/Timelist.vue (hunk 2 above)
Comment (michaelrogers) [reply src/plugins/timelist/Timelist.vue]: Inverted back to fixed time instead of real time.

**Comment by michaelrogers** [comment]
> One more small change please.

@shefalijoshi - both requested changes have been made!

**Comment by shefalijoshi** [comment]
1. Load a timelist with timespans starting from March, 2023 through December 2024 or later.
2. Display a list with Remote Clock (year 2024) - note that past (2023), present (2024) and future activities are correctly displayed.
3. Now switch to Local Clock OR Fixed Timespan with start time of March, 2023 - note that no past events are displayed even when the time list is configured to display ALL activities.
Expected: The *start* bounds should only be used to set the timestamp which is then used to calculate which activities are tagged as past, present or future. We should still show past events.

https://user-images.githubusercontent.com/5247066/229873178-dcf33510-922c-4bc4-a656-15c618c62eec.mov

File: src/plugins/timelist/Timelist.vue [hunk 3]
```diff
@@ -197,21 +197,22 @@ export default {
...
             }
         },
         setViewFromClock(newClock) {
             this.filterValue = this.domainObject.configuration.filter;
-            const isFixedTime = newClock === undefined;
-            if (isFixedTime) {
+            this.isFixedTime = newClock === undefined;
+            if (this.isFixedTime) {
                 this.hideAll = false;
                 this.showAll = true;
```
Comment (shefalijoshi) [inline src/plugins/timelist/Timelist.vue:213]: We should not set `this.showAll` to true when it is fixed time span anymore. We want to honor the user's configuration of showing past/present/future which is done by calling `this.setViewBounds`.

File: src/plugins/timelist/Timelist.vue [hunk 4]
```diff
@@ -357,21 +358,24 @@ export default {
...
         filterActivities(activity, index) {
-
             const hasFilterMatch = this.filterByName(activity.name);
 
             if (hasFilterMatch === false || this.hideAll === true) {
                 return false;
             }
 
-            if (this.showAll === true) {
+            if (this.isEditing && this.showAll) {
```
Comment (shefalijoshi) [inline src/plugins/timelist/Timelist.vue:367]: see comment above about not showing all for fixed timespan anymore.

File: src/plugins/timelist/Timelist.vue [hunk 5]
```diff
@@ -357,21 +358,24 @@ export default {
...
 
             //current event or future start event or past end event
             const isCurrent = (this.noCurrent === false && this.timestamp >= activity.start && this.timestamp <= activity.end);
-            const isPast = (this.timestamp > activity.end && (this.viewBounds.pastEnd === undefined || activity.end >= this.viewBounds.pastEnd(this.timestamp)));
-            const isFuture = (this.timestamp < activity.start && (this.viewBounds.futureStart === undefined || activity.start <= this.viewBounds.futureStart(this.timestamp)));
+            const isPast = (this.timestamp > activity.end && (this.viewBounds?.pastEnd === undefined || activity.end >= this.viewBounds?.pastEnd(this.timestamp)));
+            const isFuture = (this.timestamp < activity.start && (this.viewBounds?.futureStart === undefined || activity.start <= this.viewBounds?.futureStart(this.timestamp)));
+
+            if (this.isFixedTime) {
+                return isCurrent || isFuture;
```
Comment (shefalijoshi) [inline src/plugins/timelist/Timelist.vue:377]: See comment above about honoring the user's configuration for past/present/future when using fixed timespan mode.

**Review by shefalijoshi — CHANGES_REQUESTED** [review]

File: src/plugins/timelist/Timelist.vue [hunk 6]
```diff
@@ -357,21 +357,19 @@ export default {
...
+                return true;
+            }
 
             const hasFilterMatch = this.filterByName(activity.name);
-
             if (hasFilterMatch === false || this.hideAll === true) {
                 return false;
             }
 
-            if (this.showAll === true) {
```
Comment (shefalijoshi) [inline src/plugins/timelist/Timelist.vue:367]: Are we using `this.showAll` anymore at all? If not, we should get rid of it.

**Review by shefalijoshi — CHANGES_REQUESTED** [review]
Thanks for making the changes!
Still testing, but added some small comments.

File: src/plugins/timelist/Timelist.vue (hunk 6 above)
Comment (michaelrogers) [reply src/plugins/timelist/Timelist.vue:367]: I don't believe we are, but I wasn't sure if I was overlooking a use case for it. Happy to fully remove it.

**Comment by shefalijoshi** [comment]
I tested this again. It looks like currently active activities are not showing up in the local clock mode.
Actual:
image

Expected:
image

**Review by shefalijoshi — CHANGES_REQUESTED** [review]
Found a bug during testing.

**Comment by ozyx** [comment]
> I tested this again. It looks like currently active activities are not showing up in the local clock mode. Actual: image
> 
> Expected: image

I can confirm this behavior. The current activities show up if you go into edit mode, however.

**Comment by ozyx** [comment]
> @shefalijoshi and @ozyx - thanks for testing this locally. Just curious what your timeframe filters were set to in the inspector. I'm trying to nail down the repro locally, and find I can replicate it if current events is set to `don't show` (but that might be desired behavior). Edit mode should ignore all selected filters and display a full list.

I'll confirm but I believe I had the current events set to "show all", which is the default (I'm pretty sure?)

**Comment by michaelrogers** [comment]
@ozyx and @shefalijoshi - The `noCurrent` value was removed in my latest commit which seemed to be the culprit when determining if an activity `isCurrent`. Updated and ready for re-review.

**Comment by shefalijoshi** [comment]
Thanks @michaelrogers 
Something seems off here. The start time is AFTER the end time, but the item is still showing up as a current activity. can you take a look?
image

**Comment by michaelrogers** [comment]
@shefalijoshi - I'm having some difficulty reproducing that particular bug in fixed time or local clock. The start / end times seem to be working properly for me. Could there be some anomalous entries in the test data set?

**Comment by michaelrogers** [comment]
@shefalijoshi - as we discussed I've updated the start / end formatters for the timelist to parse and set to UTC to match the time conductors formatting. This corrects the current activity values which were properly flagged as current but the displayed time value didn't seem to match the current time conductor values.

File: src/plugins/timelist/Timelist.vue [hunk 7]
```diff
@@ -57,7 +57,7 @@ const headerItems = [
             if (clock && clock.formatTime) {
                 return clock.formatTime(value);
             } else {
-                return `${moment(value).format(TIME_FORMAT)}Z`;
+                return `${moment.utc(value).format(TIME_FORMAT)}Z`;
```
Comment (michaelrogers) [inline src/plugins/timelist/Timelist.vue:60]: @shefalijoshi - as we discussed I've updated the start / end formatters for the timelist to parse and set to UTC to match the time conductors formatting. This corrects the current activity values which were properly flagged as current but the displayed time value didn't seem to match the current time conductor values.

Comment (michaelrogers) [reply src/plugins/timelist/Timelist.vue:60]: @akhenry + @charlesh88: This design change needs approval to ensure that it meets the intended goal of the timelist. Effectively all start / end time now are displayed as UTC. Previously the timezone offset was included in the timelist start/end values.

Comment (shefalijoshi) [reply src/plugins/timelist/Timelist.vue:60]: @michaelrogers please make sure that this change does not break the fix for this issue: https://github.com/nasa/openmct/pull/6495#issuecomment-1481830330

**Comment by michaelrogers** [comment]
@shefalijoshi - could we sync to resolve the upstream changes that are in conflict for this ticket. I don't want to regress any of the improvements that have been made in parallel to the Timelist view.

**Review by shefalijoshi — APPROVED** [review]
Approving this, but:
Please retest one more time after the merge from master.

File: src/plugins/timelist/Timelist.vue [hunk 8]
```diff
@@ -44,47 +44,45 @@ const SCROLL_TIMEOUT = 10000;
...
+        }
+    }, {
+        defaultDirection: true,
+        isSortable: true,
+        property: 'end',
+        name: 'End Time',
+        format: function (value, object, key, openmct) {
+            const clock = openmct.time.clock();
+            if (clock && clock.formatTime) {
+                return clock.formatTime(value);
```
Comment (akhenry) [inline src/plugins/timelist/Timelist.vue:68]: This is not part of the Time API. It appears to have been implemented on `RemoteClock` for internal use. The correct way to do this is:
```
const timeFormat = openmct.time.timeSystem().timeFormat;
const timeFormatter = openmct.telemetry.getFormatter(timeFormat);
```
This will work in both realtime and fixed time modes.

File: src/plugins/timelist/Timelist.vue [hunk 9]
```diff
@@ -369,32 +356,22 @@ export default {
...
-      const isPast =
-        this.timestamp > activity.end &&
-        (this.viewBounds.pastEnd === undefined ||
-          activity.end >= this.viewBounds.pastEnd(this.timestamp));
-      const isFuture =
-        this.timestamp < activity.start &&
-        (this.viewBounds.futureStart === undefined ||
-          activity.start <= this.viewBounds.futureStart(this.timestamp));
+            //current event or future start event or past end event
+            const isCurrent = (this.timestamp >= activity.start && this.timestamp <= activity.end);
```
Comment (akhenry) [inline src/plugins/timelist/Timelist.vue:372]: Complex boolean expressions should be split across multiple lines as it was previously.

**Review by akhenry — CHANGES_REQUESTED** [review]
Looks good, just a note about API usage and small formatting suggestion.

File: src/plugins/timelist/Timelist.vue (hunk 9 above)
Comment (ozyx) [reply src/plugins/timelist/Timelist.vue:372]: Running `npm run lint:fix` should fix this

File: src/plugins/timelist/Timelist.vue (hunk 8 above)
Comment (michaelrogers) [reply src/plugins/timelist/Timelist.vue]: Excellent suggestion, this certainly reduces complexity in special logic for fixed vs realtime modes and the end result is more readable.

File: src/plugins/timelist/Timelist.vue (hunk 9 above)
Comment (michaelrogers) [reply src/plugins/timelist/Timelist.vue]: Prettier is adamant that this statement remains on 1 line; I tried breaking lines using parens but it deleted them since they are unnecessary chars.

**Review by akhenry — APPROVED** [review]

**Review by akhenry — CHANGES_REQUESTED** [review]
Just needs updated test instructions.

**Comment by michaelrogers** [comment]
@akhenry - Testing instructions have been added to the original issue.

https://github.com/nasa/openmct/issues/5772#issuecomment-1595033720

**Review by akhenry — CHANGES_REQUESTED** [review]
In testing this it didn't appear to work with real plans in our test environment. Please retest with real plans in our test environment.

**Comment by michaelrogers** [comment]
After conferring with @shefalijoshi - the ticket will be updated to hide activities outside the time bounds.

**Comment by michaelrogers** [comment]
@shefalijoshi - I've updated the filter function to only include activities that fall within the bounds. Note: this affects both modes of the clock. Let me know if that is not desirable.

**Review by akhenry — CHANGES_REQUESTED** [review]
Changes are looking good. I do think that we should make sure we include current activities (see comment).

I've also created [a followup issue](https://github.com/nasa/openmct/issues/6771) to replace the time controls in the inspector with the independent time conductor. Let's implement that immediately after this is merged.

File: src/plugins/timelist/Timelist.vue [hunk 10]
```diff
@@ -365,6 +368,15 @@ export default {
         return false;
       }
 
+      const startInBounds =
+        activity.start >= this.openmct.time.bounds()?.start &&
+        activity.start <= this.openmct.time.bounds()?.end;
+      const endInBounds =
+        activity.end >= this.openmct.time.bounds()?.start &&
+        activity.end <= this.openmct.time.bounds()?.end;
+      if (!(startInBounds || endInBounds)) {
```
[the remark this answers is not in the document]
Comment (michaelrogers) [reply src/plugins/timelist/Timelist.vue]: Addressed by adding a check for `middleInBounds` which would be inclusive of activities that straddle the start and end of the time bounds.

**Comment by akhenry** [comment]
@shefalijoshi  To take a look at failing tests

**Comment by akhenry** [comment]
Changes look good to me. I've [filed a followup issue](https://github.com/nasa/openmct/issues/6797) to use the new global clock in fixed mode.

**Review by akhenry — APPROVED** [review]

**Review by shefalijoshi — APPROVED** [review]
Looks good. I've fixed the broken tests.
