### PR TITLE
[Build] Modify version info injection to fix sourcemaps

### LINKED ISSUE #1707: broken sourcemaps in build
Appears that js sourcemaps are broken when openmct is built.

Doing some debugging, it appears that this is due to the build info replace task and the header insertion.  Commenting both of these lines out results in working sourcemaps.

https://github.com/nasa/openmct/blame/master/gulpfile.js#L87-L88

```
        // .pipe(replace(options.replace))
        // .pipe(header(comment, options.replace.variables))
```

### PR DESCRIPTION
**Pull request by VWoeltjen**
Fixes #1707 and restores both parseability and usability of sourcemaps.

Summary of changes:

* Remove `gulp-header` task; configure `uglify2` to preserve headers more idiomatically
* Remove `gulp-replace-task`; do find-replace upfront in `start.frag`
* Communicate version info to `openmct` imperatively instead of declaratively

This simplifies the `scripts` task such that the output is simply the r.js optimizer's output which correctly matches the generated sourcemap. No more parse error on load, and breakpoints actually end up where you want them to!

I'm not in love with the custom code in `specifyBuildInfo` or `start.frag` processing in this solution and would welcome suggestions for simplification. They feel hacky, but there are corollary simplifications elsewhere to balance that out, at least.

### CODE REVIEW

**Comment by VWoeltjen** [comment]
### Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? Y
3. Command line build passes? Y
4. Changes have been smoke-tested? Y

File: src/MCT.js [hunk 1]
```diff
@@ -210,6 +210,31 @@ define([
     };
 
     /**
+     * Inject build information for the About dialog et al.
+     * @private
+     */
+    MCT.prototype.specifyBuildInfo = function (buildInfo) {
```
Comment (larkin) [inline src/MCT.js]: Don't like this being on the prototype.  Can we just throw this in the openmct.js file, i.e `if (BUILD_INFO) { openmct.legacyExtension(...) }`?  

Or if you really want to test it, hide it in the MCT constructor?

File: src/MCT.js [hunk 2]
```diff
@@ -210,6 +210,31 @@ define([
...
+        var aliases = { timestamp: "Built" };
+        var descriptions = {
+            timestamp: "The date on which this version of Open MCT was built.",
+            revision: "A unique revision identifier for the client sources.",
+            branch: "The name of the branch that was used during the build."
+        };
+        var priorities =
+            { version: 999, timestamp: 990, revision: 995, branch: 994 };
```
Comment (larkin) [inline src/MCT.js]: do priorities actually matter?

File: src/MCT.js (hunk 1 above)
Comment (VWoeltjen) [reply src/MCT.js]: How about hiding it in a build info plugin? Agree that `MCT.prototype` is not the best place for this, but also don't like a lot of low-level in top-level `openmct.js`. Can relocate those tests easily

File: src/MCT.js (hunk 2 above)
Comment (VWoeltjen) [reply src/MCT.js]: For ordering, otherwise no. Happy to snip this and just take them in the order they came from `start.frag`; I'll reorder things there for consistency

File: src/MCT.js (hunk 1 above)
Comment (larkin) [reply src/MCT.js]: @VWoeltjen that works.

File: src/MCT.js (hunk 2 above)
Comment (VWoeltjen) [reply src/MCT.js]: No reordering necessary after removal of priorities, will update PR with other changes momentarily

**Comment by VWoeltjen** [comment]
@larkin - made requested changes, ready for re-review. I did the feedback-related changes as a separate commit to ease review, should squash-merge or similar to avoid adding unnecessary history to MCT.js

### Author Checklist

1. Changes address original issue? y
2. Unit tests included and/or updated with changes? y
3. Command line build passes? y
4. Changes have been smoke-tested? y
