### PR TITLE
Handle missing objects gracefully 

### LINKED ISSUE #4258: Handle missing objects gracefully in Open MCT
#### Summary
When objects in views are missing, we should not fail but handle the issue gracefully. 

#### Expected vs Current Behavior
Currently several views fail with console errors and Open MCT shows an endless spinner when objects are missing. 
We should ensure that views load even when objects are missing.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce
1. In LocalStorage or in CouchDB, create an object / telemetry like a sine wave generator
2. Add this object to several views - Display Layout, Flexible Layout, Telemetry Table, Overlay / Stacked Plots, LAD Tables etc.
3. Delete the object from the persistence storage
4. Lots of console errors are displayed in different views.

#### Environment
* Open MCT Version: 1.7.8
* Deployment Type: /testathon
* OS: Mac
* Browser: All

### PR DESCRIPTION
**Pull request by alizenguyen**
Closes #4258 

### Describe your changes:

Added checks for missing data as a result of missing domain objects to fix console errors located in a display layouts, overlay plots, and stacked plots as shown in the issue #4258.

The result should only display console warnings of missing objects. Stacked plots should have an empty space with no errors shown. See image below.

Screen Shot 2022-06-27 at 9 18 38 PM

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Commit messages meet standards?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [x] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/api/telemetry/TelemetryAPI.js [hunk 1]
```diff
@@ -529,7 +529,7 @@ define([
         }
 
         this.openmct.notifications.error(message);
-        console.error(detailMessage);
+        console.warn(detailMessage);
```
Comment (unlikelyzero) [inline src/api/telemetry/TelemetryAPI.js:532]: is there a scenario where this should still throw an error instead of a warn?

Comment (alizenguyen) [reply src/api/telemetry/TelemetryAPI.js:532]: Hmm I'm not sure... @jvigliotta any incite? It does send an error notification as well.

Comment (unlikelyzero) [reply src/api/telemetry/TelemetryAPI.js:532]: @alizenguyen let's add an e2e test for this

Comment (jvigliotta) [reply src/api/telemetry/TelemetryAPI.js:532]: I think the error notification is sufficient. I think there are many times where a provider doesn't exist for an object, I don't want to throw console errors for that each time, I think a warning would suffice. I mean it's evident from the view as well...

File: e2e/tests/plugins/plot/missingPlotObj.e2e.spec.js [hunk 2]
```diff
@@ -0,0 +1,134 @@
...
+ * under the License.
+ *
+ * Open MCT includes source code licensed under additional open source
+ * licenses. See the Open Source Licenses file (LICENSES.md) included with
+ * this source code distribution or the Licensing information page available
+ * at runtime from the About dialog for additional information.
+ *****************************************************************************/
+
+/*
+Tests to verify log plot functionality. Note this test suite if very much under active development and should not
```
Comment (unlikelyzero) [inline e2e/tests/plugins/plot/missingPlotObj.e2e.spec.js:24]: lets update this text

File: e2e/tests/plugins/plot/missingPlotObj.e2e.spec.js [hunk 3]
```diff
@@ -0,0 +1,134 @@
...
+        const localStorage = await page.evaluate(() => window.localStorage);
+        const parsedData = JSON.parse(localStorage.mct);
+        const keys = Object.keys(parsedData);
+        const lastKey = keys[keys.length - 1];
+
+        delete parsedData[lastKey];
+
+        //Sets local storage with missing object
+        await page.evaluate(
+            `window.localStorage.setItem('mct', '${JSON.stringify(parsedData)}')`
```
Comment (unlikelyzero) [inline e2e/tests/plugins/plot/missingPlotObj.e2e.spec.js:46]: whoa

File: e2e/tests/plugins/plot/missingPlotObj.e2e.spec.js [hunk 4]
```diff
@@ -0,0 +1,134 @@
...
+        );
+
+        //Reloads page and clicks on stacked plot
+        page.reload();
```
Comment (unlikelyzero) [inline e2e/tests/plugins/plot/missingPlotObj.e2e.spec.js:50]: note, reloads on vanilla openmct are known to be troublesome. You should consider putting some sort of logic after  line 50 to verify a properly "settled" DOM

File: e2e/tests/plugins/plot/missingPlotObj.e2e.spec.js [hunk 5]
```diff
@@ -0,0 +1,134 @@
...
+            page.waitForNavigation(),
+            page.locator('text=Unnamed Stacked Plot').first().click()
+        ]);
+
+        //Check that there is only one stacked item plot with a plot, the missing one will be empty
+        await expect(page.locator(".c-plot--stacked-container:has(.gl-plot)")).toHaveCount(1);
+    });
+});
+
+async function makeStackedPlot(page) {
```
Comment (unlikelyzero) [inline e2e/tests/plugins/plot/missingPlotObj.e2e.spec.js:63]: can you add some type hint intellisense here? If they're exclusively used in the context of this suite you can also give it `@private`

File: e2e/tests/plugins/plot/missingPlotObj.e2e.spec.js [hunk 6]
```diff
@@ -0,0 +1,134 @@
...
+        page.reload();
+
+        await page.locator('text=Open MCT My Items >> span').nth(3).click();
+        await Promise.all([
+            page.waitForNavigation(),
+            page.locator('text=Unnamed Stacked Plot').first().click()
+        ]);
+
+        //Check that there is only one stacked item plot with a plot, the missing one will be empty
+        await expect(page.locator(".c-plot--stacked-container:has(.gl-plot)")).toHaveCount(1);
```
Comment (unlikelyzero) [inline e2e/tests/plugins/plot/missingPlotObj.e2e.spec.js:59]: you should be able to intercept page.console errors and verify that console.warn is thrown with this API https://playwright.dev/docs/api/class-consolemessage

**Review by unlikelyzero — APPROVED** [review]
This new suite looks amazing. I'm putting this into 'approve' so that this PR doesn't get locked while i'm OOO tomorrow.

There are a few comments which _should_ be addressed but are not 100% necessary

**Comment by alizenguyen** [comment]
@unlikelyzero I think I addressed all your comments. It dismissed your approval when I pushed the changes. I'll see if someone can review it tomorrow. Enjoy your day off!

File: src/api/telemetry/TelemetryCollection.js [hunk 7]
```diff
@@ -322,7 +322,7 @@ export class TelemetryCollection extends EventEmitter {
      * @private
      */
     _setTimeSystem(timeSystem) {
-        let domains = this.metadata.valuesForHints(['domain']);
+        let domains = this.metadata ? this.metadata.valuesForHints(['domain']) : [];
```
Comment (jvigliotta) [inline src/api/telemetry/TelemetryCollection.js:325]: Can we set domain to it's default of `[]` right off the bat? Then can we just get one check for this.metada and if it exists, then we can set domain to that (as well as metadatavalue as it also relies on this.metadata).

Something like:
``` js
let domains = [];
let metadataValue = { format: timeSystem.key };

if (this.metadata) { ... update if necessary }
```

File: src/plugins/displayLayout/components/TelemetryView.vue [hunk 8]
```diff
@@ -152,7 +152,7 @@ export default {
         },
         unit() {
             let value = this.item.value;
-            let unit = this.metadata.value(value).unit;
+            let unit = this.meta ? this.metadata.value(value).unit : '';
```
Comment (jvigliotta) [inline src/plugins/displayLayout/components/TelemetryView.vue:155]: I think this should be `this.metadata`

File: src/plugins/plot/axis/XAxis.vue [hunk 9]
```diff
@@ -137,15 +137,17 @@ export default {
...
 
             this.xKeyOptions = this.seriesModel.metadata
-                .valuesForHints(['domain'])
-                .map(function (o) {
-                    return {
-                        name: o.name,
-                        key: o.key
-                    };
-                });
+                ? this.seriesModel.metadata
```
Comment (jvigliotta) [inline src/plugins/plot/axis/XAxis.vue:140]: Since this is such a big block of code, can we set this.xKeyOptions to a `[]` right off the bet, then throw the actual assignment in an if block, I think that will make it more readable than a tertiary.

File: src/plugins/plot/axis/YAxis.vue [hunk 10]
```diff
@@ -121,20 +121,22 @@ export default {
...
         setUpYAxisOptions() {
             this.yKeyOptions = this.seriesModel.metadata
-                .valuesForHints(['range'])
-                .map(function (o) {
-                    return {
-                        name: o.name,
-                        key: o.key
-                    };
-                });
+                ? this.seriesModel.metadata
```
Comment (jvigliotta) [inline src/plugins/plot/axis/YAxis.vue:124]: Can we do the same initial setting of `[]`, then the actual assignment in an if block based on metadata existing?

File: src/plugins/plot/inspector/PlotOptionsBrowse.vue [hunk 11]
```diff
@@ -197,36 +197,40 @@ export default {
...
-            this.label = this.config.yAxis.get('label');
-            this.autoscale = this.config.yAxis.get('autoscale');
-            this.logMode = this.config.yAxis.get('logMode');
-            this.autoscalePadding = this.config.yAxis.get('autoscalePadding');
-            const range = this.config.yAxis.get('range');
-            if (range) {
-                this.rangeMin = range.min;
-                this.rangeMax = range.max;
-            }
+            if (this.config) {
```
Comment (jvigliotta) [inline src/plugins/plot/inspector/PlotOptionsBrowse.vue:200]: I don't know a lot about our plots, do any of these options have defaults already or need them? @shefalijoshi any thoughts on that?

File: src/plugins/plot/stackedPlot/StackedPlotItem.vue [hunk 12]
```diff
@@ -161,12 +161,17 @@ export default {
                         loading: true
                     };
                 },
+                computed: {
+                    isMissing() {
+                        return openmct.objects.isMissing(object);
```
Comment (jvigliotta) [inline src/plugins/plot/stackedPlot/StackedPlotItem.vue:166]: I think you can just pass this in as a data variable? I don't think it's state would be changed mid-use and if it was I don't think the code is set up in a way that it would trigger this computed variable update. When you assign object above, can you also just se the the isMissing value as well?

File: src/plugins/plot/stackedPlot/StackedPlotItem.vue [hunk 13]
```diff
@@ -235,28 +240,32 @@ export default {
...
-                            ...this.childObject,
-                            configuration: {
-                                series: [
-                                    {
-                                        identifier: this.childObject.identifier,
-                                        ...persistedSeriesConfig.series
-                                    }
-                                ],
-                                yAxis: persistedSeriesConfig.yAxis
+                    try {
```
Comment (jvigliotta) [inline src/plugins/plot/stackedPlot/StackedPlotItem.vue:243]: Would we be able to just use the `if (!this.isMissing)` here?

**Review by jvigliotta — CHANGES_REQUESTED** [review]
Looking good! Couple suggestions and questions!

File: src/plugins/plot/inspector/PlotOptionsBrowse.vue (hunk 11 above)
Comment (alizenguyen) [reply src/plugins/plot/inspector/PlotOptionsBrowse.vue:200]: I know plots depend a good bit on configs, so this is most likely a temp solution as well as the fix in the StackedPlotItem.vue. I'm looking into another ticket with interceptors that looks like set defaults that could be a solution? We would need to figure out what defaults to set it too though.

**Review by jvigliotta — APPROVED** [review]
LGTM!
