### PR TITLE
Check if creatable is true as a string or a boolean.

### LINKED ISSUE #4140: Overlay Plots cannot be styled
Overlay Plots are not allowing either static or conditional styling, but should. Stacked Plots are working as expected.

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug?

#### Steps to Reproduce
1. Make a new Overlay Plot, stay in Edit mode.
2. Attempt to apply either static or Conditional Styling to the plot. Observe: nothing happens.
3. Inspecting the view shows that while `js-style-receiver` appears to be present in the view, no style is being applied in the DOM.

#### Environment
* Open MCT Version: 1.7.6
* Deployment Type: stable
* OS: MacOS
* Browser: Chrome

#### Additional Information
image

### PR DESCRIPTION
**Pull request by shefalijoshi**
Resolves #4140 

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### CODE REVIEW

**Review by jvigliotta — APPROVED** [review]
LGTM!

File: src/plugins/condition/components/inspector/StylesView.vue [hunk 1]
```diff
@@ -321,7 +321,7 @@ export default {
             if (item) {
                 const type = this.openmct.types.get(item.type);
                 if (type && type.definition) {
-                    creatable = (type.definition.creatable === true);
+                    creatable = (type.definition.creatable !== undefined && (type.definition.creatable === 'true' || type.definition.creatable === true));
```
Comment (akhenry) [inline src/plugins/condition/components/inspector/StylesView.vue:324]: This is checking if the object is creatable, not persistable. To check if an object is persistable:
``` JavaScript
const isPersistable = openmct.object.isPersistable(item);
```
