### PR TITLE
[ExportAsJson] Multiple Aliases in Export and Conditional Styles Fixes

### LINKED ISSUE #6601: [ExportAsJson] Multiple aliases of the same object in an export bug and conditionally styled display items bug
#### Summary

When a display layout contains an aliased object more than once (ex. aliased plot, embedded display layout with the same aliased plot) trouble follows. The reason is when replacing aliased objects in the export, we create a new identifier for each one, when we should only create ONE new identifier and use that with a different location for subsequent same aliases.

#### Expected vs Current Behavior

When you export a display with multiple aliases of the same object, it should export/import without issues. Currently, the duplicate aliases will either not show at all or will lose any configuration information related to the display (display, size, etc).

#### Steps to Reproduce

For Multiple Aliases Bug
1. Create a display layout and any other object in a folder
2. Drag the other object into the display layout (creating an alias in the display layout) somewhere in the middle
3. Create another display layout inside of the first display layout, move it away toward the middle as well and save it
4. Drag the other original object into the new embedded display layout (it should also be an alias)
5. Now export the display layout
6. Now import the display layout
7. One of the aliases will either disappear or lose it's positioning and end up in the top left corner of the display

For Conditionally Styled Items bug
1. Repeat above steps to Step 4.
2. Create a Condition Set styled by some telemetry endpoint (both outside of the display layout to be exported)
3. Use the condition set to conditionally style the items in the display layout
4. Export the display layout
5. Import the display layout
6. Make sure that the conditionally styled items are still conditionally styled
7. Make sure the object used to conditionally style the items is shown in the styles tab in the inspector

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available? If you duplicate the item first (removing any aliases) then you can export it without issue
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### Structure
Screen Shot 2023-04-18 at 3 57 45 PM
### Before Export

Screen Shot 2023-04-18 at 3 52 38 PM
### After Import
Screen Shot 2023-04-18 at 3 54 17 PM

### PR DESCRIPTION
**Pull request by jvigliotta**
Closes #6601

### Describe your changes:

If multiple aliases are detected, the first is created as a new object and and added to it's parent's composition, any subsequent aliases of the same object will not be recreated, but the originally created one will be added to the current parent's composition, creating an alias.

Also, there are cases were `conditionSetIdentifier`s are stored in an object keyed by an item id in the `configuration.objectstyles` object, this fix will handle these as well.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [x] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/plugins/exportAsJSONAction/ExportAsJSONAction.js [hunk 1]
```diff
@@ -109,49 +111,41 @@ export default class ExportAsJSONAction {
...
+            this.externalIdentifiers.push(originalKeyString);
 
-        this.idMap[this._getId(child)] = newIdString;
-        copyOfChild.location = parentId;
-        parent.composition[index] = copyOfChild.identifier;
-        this.tree[newIdString] = copyOfChild;
-        this.tree[parentId].composition[index] = copyOfChild.identifier;
+            copy = JSON.parse(JSON.stringify(child));
+            copy.identifier.key = uuid();
+            copy.location = isReference ? null : parentKeyString;
```
Comment (akhenry) [inline src/plugins/exportAsJSONAction/ExportAsJSONAction.js:125]: What's the reason for nulling the location here? I understand that we don't want to make the condition set a child of the display layout (for example), but I'm concerned about the implications of explicitly setting it to null. I think it might convert condition sets in the tree to links?

**Review by akhenry — CHANGES_REQUESTED** [review]

File: src/plugins/exportAsJSONAction/ExportAsJSONAction.js (hunk 1 above)
Comment (jvigliotta) [reply src/plugins/exportAsJSONAction/ExportAsJSONAction.js:125]: Great question! I was wondering the same thing. I think the idea was to assume that the item was outside of the tree? I have no clue to be honest. Setting it to `null` would just "delete" it, but it could still be referenced, it just wouldn't show anywhere in the tree UNLESS it was in the tree already, let's chat on the best way to handle this.

Comment (jvigliotta) [reply src/plugins/exportAsJSONAction/ExportAsJSONAction.js:125]: In the comments, there was some reference to the fact that the conditional styles aren't included in the composition of the object, so that was the reason they had to be handled separately.

File: src/plugins/exportAsJSONAction/ExportAsJSONAction.js [hunk 2]
```diff
@@ -59,7 +57,11 @@ export default class ExportAsJSONAction {
      * @param {object} objectpath
      */
     invoke(objectpath) {
+        this.externalIdentifiers = [];
         this.tree = {};
+        this.calls = 0;
+        this.idMap = {};
```
Comment (shefalijoshi) [inline src/plugins/exportAsJSONAction/ExportAsJSONAction.js:63]: 🥇

Comment (jvigliotta) [reply src/plugins/exportAsJSONAction/ExportAsJSONAction.js:63]: haha, thanks for pointing this out @shefalijoshi !

File: src/plugins/exportAsJSONAction/ExportAsJSONAction.js (hunk 1 above)
Comment (akhenry) [reply src/plugins/exportAsJSONAction/ExportAsJSONAction.js:125]: @shefalijoshi Any idea why this is nulled?

Comment (shefalijoshi) [reply src/plugins/exportAsJSONAction/ExportAsJSONAction.js:125]: I think it's nulled because a reference (like a condition set referenced in an object style) doesn't have to be in the same location as the parent. It can be anywhere in the tree.
Perhaps instead of null it could be the `root`.

Comment (jvigliotta) [reply src/plugins/exportAsJSONAction/ExportAsJSONAction.js:125]: Yeah, I see the logic behind that, but there's a chance it could be in the exported tree as well right? just in another location? Looks like we might need to handle for both scenarios, but the interesting one is what to do if it's NOT in the exported tree. I could see just plunking it into the root of the export, but we may need to have a notification or something that let's the user know that happened.

Comment (shefalijoshi) [reply src/plugins/exportAsJSONAction/ExportAsJSONAction.js:125]: Yes, it could be in the exported tree.

Comment (akhenry) [reply src/plugins/exportAsJSONAction/ExportAsJSONAction.js:125]: Yeah, conditional styling is a bad edge case that we have ignored for a while. It creates orphaned condition sets that are unreachable from the tree. 

For now I am fine to say that condition sets referenced in conditional styling HAVE to reside in the exported tree. We already have an issue to address the orphaned condition sets - https://github.com/nasa/openmct/issues/5642

If they are not located in the exported tree you _can_ duplicate the condition set into a new location in the imported environment and update the display to reference that instead. It's a pain, but it's a workaround

Comment (akhenry) [reply src/plugins/exportAsJSONAction/ExportAsJSONAction.js:125]: So I'm not sure we should be nulling that location, because the condition set might be in the exported tree somewhere, and we would be turning it into a link I think?

What happens if we _don't_ null it, and the condition set _does not_ reside within the exported tree? What are we guarding against here?

Comment (shefalijoshi) [reply src/plugins/exportAsJSONAction/ExportAsJSONAction.js]: Not null-ing it should be fine. Let's go with that recommendation.

**Comment by akhenry** [comment]
@shefalijoshi  Yeah thanks for reviving this. I have some additional changes for this branch that I need to clean up and merge.

I also had to implement persistence batching in Couch. I will create a separate PR for that.

**Comment by akhenry** [comment]
@jvigliotta My changes ready for review

**Review by unlikelyzero — APPROVED** [review]
