### PR TITLE
When auto scale is turned off, handle user specified range correctly

### LINKED ISSUE #6229: [Overlay Plot] Turning off autoscale on a series causes it to not render on renavigate
#### Summary

Turning off autoscale on a plot series and then navigating away/back again causes the min and max values to become `undefined` and the series to not draw at all (no console errors observed). Entering a min and max value in the YAxis form and saving will then cause the series to redraw.

#### Expected vs Current Behavior

Turning off autoscale should persist its default min and max values on renavigate

#### Steps to Reproduce

1. Create an Overlay Plot
2. Drag an SWG into it
3. Hit Edit
4. Uncheck "autoscale"
5. Observe min and max form fields have sensible defaults and plot series rerenders in the range
6. Save
7. Navigate away and back again
8. Observe plot series is no longer rendered
9. Hit edit
10. Observe min and max are blank form fields

#### Environment

* Open MCT Version:  2.1.6-SNAPSHOT
* Deployment Type:  local
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by shefalijoshi**
Closes #6229 #6230 #5039 

### Describe your changes:
- Fix typo when saving the user specified range
- Ensure range is specified when autoscale is turned off 
- Don't redraw unless absolutely necessary

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/plugins/plot/inspector/forms/YAxisForm.vue [hunk 1]
```diff
@@ -169,7 +169,7 @@ export default {
                     objectPath: `${prefix}.logMode`
                 },
                 range: {
-                    objectPath: `${prefix}.range'`,
+                    objectPath: `${prefix}.range`,
```
Comment (ozyx) [inline src/plugins/plot/inspector/forms/YAxisForm.vue:172]: wow-- great catch

File: src/plugins/plot/chart/MctChart.vue [hunk 2]
```diff
@@ -531,8 +542,17 @@ export default {
 
             return true;
         },
+        redrawIfNotAlreadyHandled(attribute, value, oldValue) {
+            if (Object.keys(HANDLED_ATTRIBUTES).includes(attribute) && oldValue) {
+                return;
+            }
+
+            console.warn('Unhandled change:', attribute);
```
Comment (ozyx) [inline src/plugins/plot/chart/MctChart.vue:550]: This is producing a ton of warnings for me:

image

**Review by ozyx — CHANGES_REQUESTED** [review]
This is looking good so far. I'm finding some issues still with turning autoscale off and multiple y-axes in particular. Will detail below:

1. Is it expected that sensible defaults will no longer be autofilled for min and max?

https://user-images.githubusercontent.com/9259993/216401079-497f4c2f-6ce3-4aa3-bb4e-47bfda8103e3.mov

2. I'm still able to save changes without any min and max set. After saving and going back into edit, the min and max are filled. If I then save and navigate away/back again, the series fails to render:

https://user-images.githubusercontent.com/9259993/216401197-30169e95-3914-4eaf-8209-59b287d7372a.mov

3. If I enable log mode while the plot is in the state described in point 2, the plot breaks completely and is unrecoverable.


Having autoscale off, with min and max set, and log mode on _does_ work now!

File: src/plugins/plot/chart/MctChart.vue (hunk 2 above)
Comment (shefalijoshi) [reply src/plugins/plot/chart/MctChart.vue:550]: NICE! This is what I wanted to see...

Comment (shefalijoshi) [reply src/plugins/plot/chart/MctChart.vue:550]: Handled the 'stats' attribute now.

File: e2e/README.md [hunk 3]
```diff
@@ -89,17 +89,31 @@ Read more about [Playwright Snapshots](https://playwright.dev/docs/test-snapshot
...
+```
+npm run test:e2e:updatesnapshots
+```
+
+Linux/CI
+```sh
+docker run --rm --network host -v $(pwd):/work/ -w /work/ -it mcr.microsoft.com/playwright:[GET THIS VERSION FROM OUR CIRCLECI CONFIG FILE]-focal /bin/bash
+npm install
+npm run test:e2e:updatesnapshots
+```
```
Comment (ozyx) [inline e2e/README.md:116]: let's clarify the command a little bit so nobody gets burned by this again:

```suggestion
```sh
// Replace {X.X.X} with the current Playwright version 
// from our package.json or circleCI configuration file
docker run --rm --network host -v $(pwd):/work/ -w /work/ -it mcr.microsoft.com/playwright:v{X.X.X}-focal /bin/bash
npm install
npm run test:e2e:updatesnapshots
```

File: e2e/tests/functional/plugins/plot/autoscale.e2e.spec.js [hunk 4]
```diff
@@ -47,16 +47,32 @@ test.describe('ExportAsJSON', () => {
 
         await testYTicks(page, ['-1.00', '-0.50', '0.00', '0.50', '1.00']);
 
+        // enter edit mode
+        await page.locator('text=Unnamed Overlay Plot Snapshot >> button').nth(3).click();
```
Comment (ozyx) [inline e2e/tests/functional/plugins/plot/autoscale.e2e.spec.js:51]:
```suggestion
        await page.click('button[title="Edit"]');
```

File: e2e/tests/functional/plugins/plot/autoscale.e2e.spec.js [hunk 5]
```diff
@@ -47,16 +47,32 @@ test.describe('ExportAsJSON', () => {
...
+
         await turnOffAutoscale(page);
 
-        // Make sure that after turning off autoscale, the user selected range values start at the same values the plot had prior.
-        await testYTicks(page, ['-1.00', '-0.50', '0.00', '0.50', '1.00']);
+        await setUserDefinedMinAndMax(page, '-2', '2');
+
+        // save
+        await page.locator('text=Snapshot Save and Finish Editing Save and Continue Editing >> button').nth(1).click();
```
Comment (ozyx) [inline e2e/tests/functional/plugins/plot/autoscale.e2e.spec.js:58]:
```suggestion
        await page.locator('button[title="Save"]').click();
```

File: e2e/tests/functional/plugins/plot/autoscale.e2e.spec.js [hunk 6]
```diff
@@ -47,16 +47,32 @@ test.describe('ExportAsJSON', () => {
...
+        await Promise.all([
+            page.locator('text=Save and Finish Editing').click(),
```
Comment (ozyx) [inline e2e/tests/functional/plugins/plot/autoscale.e2e.spec.js:60]:
```suggestion
        page.locator('li[title="Save and Finish Editing"]').click();
```

File: e2e/tests/functional/plugins/plot/autoscale.e2e.spec.js [hunk 7]
```diff
@@ -152,22 +169,25 @@ async function createSinewaveOverlayPlot(page, myItemsFolderName) {
...
-    await page.locator('.c-message-banner__close-button').click();
-    await page.waitForSelector('.c-message-banner__message', { state: 'detached'});
+/**
+ * @param {import('@playwright/test').Page} page
+ * @param {string} min
+ * @param {string} max
+ */
+async function setUserDefinedMinAndMax(page, min, max) {
+    // set minimum value
+    const minRangeInput = page.getByRole('listitem').filter({ hasText: 'Minimum Value' }).locator('input[type="number"]');
```
Comment (ozyx) [inline e2e/tests/functional/plugins/plot/autoscale.e2e.spec.js:183]: Nice locator!

File: src/plugins/plot/chart/MctChart.vue [hunk 8]
```diff
@@ -52,6 +52,38 @@ const MARKER_SIZE = 6.0;
...
+    range: 'range',
+    //series stats update y axis stats
+    stats: 'stats',
+    frozen: 'frozen',
+    autoscale: 'autoscale',
+    autoscalePadding: 'autoscalePadding',
+    logMode: 'logMode',
+    yKey: 'yKey'
+};
+const HANDLED_ATTRIBUTES = {
```
Comment (ozyx) [inline src/plugins/plot/chart/MctChart.vue:73]: This is great! Could we just add a single sentence above each detailing the different categories?

File: src/plugins/plot/configuration/YAxisModel.js [hunk 9]
```diff
@@ -377,11 +367,8 @@ export default class YAxisModel extends Model {
             autoscale: true,
             logMode: options.model?.logMode ?? false,
             autoscalePadding: 0.1,
-            id: options.id
-
-            // 'range' is not specified here, it is undefined at first. When the
-            // user turns off autoscale, the current 'displayRange' is used for
-            // the initial value of 'range'.
+            id: options.id,
+            range: options.model?.range ?? false
```
Comment (ozyx) [inline src/plugins/plot/configuration/YAxisModel.js:371]: should default be `null` instead since this is expecting an object?

File: src/plugins/plot/inspector/PlotOptionsBrowse.vue [hunk 10]
```diff
@@ -83,7 +83,7 @@
                 <div class="grid-cell value">{{ yAxis.rangeMin }}</div>
             </li>
             <li
-                v-if="!yAxis.autoscale && yAxis.rangeMax"
+                v-if="!yAxis.autoscale && yAxis.rangeMax !== ''"
```
Comment (ozyx) [inline src/plugins/plot/inspector/PlotOptionsBrowse.vue:86]: `!== ''` is redundant here since empty strings are falsy, we can remove it

File: src/plugins/plot/inspector/PlotOptionsBrowse.vue [hunk 11]
```diff
@@ -73,7 +73,7 @@
                 </div>
             </li>
             <li
-                v-if="!yAxis.autoscale && yAxis.rangeMin"
+                v-if="!yAxis.autoscale && yAxis.rangeMin !== ''"
```
Comment (ozyx) [inline src/plugins/plot/inspector/PlotOptionsBrowse.vue:76]: Same, we can remove the `!== ''` here

File: src/plugins/plot/configuration/YAxisModel.js [hunk 12]
```diff
@@ -57,7 +57,14 @@ export default class YAxisModel extends Model {
         this.listenTo(this, 'change:logMode', this.onLogModeChange, this);
         this.listenTo(this, 'change:frozen', this.toggleFreeze, this);
         this.listenTo(this, 'change:range', this.updateDisplayRange, this);
-        this.updateDisplayRange(this.get('range'));
+        const range = this.get('range');
+        this.updateDisplayRange(range);
+        //This is an edge case and should not happen
+        const invalidRange = !range || (range?.min === undefined || range?.max === undefined);
```
Comment (ozyx) [inline src/plugins/plot/configuration/YAxisModel.js:63]: nitpick: we can remove the `?` from `range?.min` and `range?.max` here since we know range is not null or undefined by that point

**Review by ozyx — CHANGES_REQUESTED** [review]
Awesome! Have some suggestions for e2e test improvements and some questions. I'm also seeing an issue setting min and max in certain cases:


https://user-images.githubusercontent.com/9259993/217348137-cc74f032-5d00-4bb1-adb7-68e5c38b3f14.mov

Here, -1 and 1 for min and max should be valid but are not being accepted so it keeps reverting back to autoscale.

File: src/plugins/plot/inspector/PlotOptionsBrowse.vue (hunk 10 above)
Comment (shefalijoshi) [reply src/plugins/plot/inspector/PlotOptionsBrowse.vue:86]: We want to allow rangeMax and rangeMin `0` values. This is why I've specified ''

File: src/plugins/plot/inspector/PlotOptionsBrowse.vue (hunk 11 above)
Comment (shefalijoshi) [reply src/plugins/plot/inspector/PlotOptionsBrowse.vue:76]: We want to allow rangeMax and rangeMin 0 values. This is why I've specified ''

File: src/plugins/plot/inspector/PlotOptionsBrowse.vue (hunk 10 above)
Comment (ozyx) [reply src/plugins/plot/inspector/PlotOptionsBrowse.vue:86]: @shefalijoshi 

Is this supposed to be a string or a number?

File: src/plugins/plot/configuration/YAxisModel.js (hunk 9 above)
Comment (shefalijoshi) [reply src/plugins/plot/configuration/YAxisModel.js:371]: Done

File: src/plugins/plot/configuration/YAxisModel.js (hunk 12 above)
Comment (shefalijoshi) [reply src/plugins/plot/configuration/YAxisModel.js:63]: Done

File: src/plugins/plot/chart/MctChart.vue (hunk 8 above)
Comment (shefalijoshi) [reply src/plugins/plot/chart/MctChart.vue:73]: Done

**Comment by shefalijoshi** [comment]
> Awesome! Have some suggestions for e2e test improvements and some questions. I'm also seeing an issue setting min and max in certain cases:
> Screen.Recording.2023-02-07.at.11.36.52.AM.mov
> 
> Here, -1 and 1 for min and max should be valid but are not being accepted so it keeps reverting back to autoscale.

Fixed.

**Review by unlikelyzero — APPROVED** [review]

**Review by ozyx — APPROVED** [review]
LGTM!
