### PR TITLE
[Fixed Position] Modify fixed position to use the Selection API

### LINKED ISSUE #1848: [Fixed Position] Use the Selection API
Modify the fixed position to use the Selection API to select elements and update the toolbar.

### PR DESCRIPTION
**Pull request by psarram**
Fixes #1848

**Author Checklist**

- Changes address original issue? Y
- Unit tests included and/or updated with changes? Not yet
- Command line build passes? Y
- Changes have been smoke-tested? Y

@VWoeltjen @larkin I'll have to update the unit tests but the changes are ready for review. 
@charlesh88 Elements can now be selected in browse mode and so some style updates might be needed.

### CODE REVIEW

File: platform/features/layout/src/FixedController.js [hunk 1]
```diff
@@ -492,42 +505,47 @@ define(
...
+         * Checks if the element should be selected or not.
+         *
+         * @param elementProxy the element to check
+         * @returns {boolean} true if the element should be selected.
          */
-        FixedController.prototype.selected = function (element) {
-            var selection = this.selection;
-            return selection && ((arguments.length > 0) ?
-                    selection.selected(element) : selection.get());
+        FixedController.prototype.selected = function (elementProxy) {
```
Comment (VWoeltjen) [inline platform/features/layout/src/FixedController.js]: Given the changes to functionality (mentioned in JSDoc comment) I'd change the method name to `shouldSelect`

**Comment by psarram** [comment]
**Author Checklist**

- Changes address original issue? Y
- Unit tests included and/or updated with changes? Y
- Command line build passes? Y
- Changes have been smoke-tested? Y

@VWoeltjen I addressed the requested change and fixed the tests.

**Comment by VWoeltjen** [comment]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
