### PR TITLE
[Navigation Tree] Handling deleted ancestors correctly

### LINKED ISSUE #3382: [Navigation Tree] Context delete doesn't work as expected
## Overview
Seeing a couple of strange behaviors deleting objects from tree
- delay in delete
- object not fully deleting from tree until navigated away

## Expected Behavior
- Object should be removed from tree immediately
- Object should not be able to be navigated to

## Steps to Reproduce
1. Navigate to an object in tree with children
1. Expand object
1. Context-menu delete the object
1. Observe Object remains as alias and can be navigated to

delete bug

### PR DESCRIPTION
**Pull request by jvigliotta**
Previously, we were not tracking ancestors for deletions. Now we are observing ancestors locations and if they are stet to null (removed from tree) then we navigation up to the next ancestor in the tree.

closes #3382

## Author Checklist
Changes address original issue? Yes
Unit tests included and/or updated with changes? No current tree spec, pending
Command line build passes? Yes
Changes have been smoke-tested? Yes
Testing instructions included? Yes

### CODE REVIEW

File: src/ui/layout/mct-tree.vue [hunk 1]
```diff
@@ -231,6 +232,9 @@ export default {
             if (!this.isLoading) {
                 this.setContainerHeight();
             }
+        },
+        ancestors() {
+            this.observeAncestors();
```
Comment (deeptailor) [inline src/ui/layout/mct-tree.vue:237]: I am alittle unsure of why this is a computed property? Computed properties should return something, if we need to do something when a value changes, we should use watch

File: src/ui/layout/mct-tree.vue [hunk 2]
```diff
@@ -449,6 +454,53 @@ export default {
...
+
+                if (index !== -1) { // currently observed
+                    observedAncestorIds.splice(index, 1); // remove all active ancestors from id tracking
+                } else { // not observed, observe it
+                    this.observeAncestor(ancestorKeyString, ancestorObject);
+                }
+            });
+
+            // remove any ancestors currnetly being observed that are no longer active ancestors
+            observedAncestorIds.forEach((id) => {
```
Comment (deeptailor) [inline src/ui/layout/mct-tree.vue:474]: there is a helper function called stopObservingAncestors, could we use that here instead of repeating code? You will probably have to move it above line 461, to make sure you are unobserving the correct ancestors.

**Review by deeptailor — CHANGES_REQUESTED** [review]
Looks great, just a couple of comments

File: src/ui/layout/mct-tree.vue (hunk 1 above)
Comment (jvigliotta) [reply src/ui/layout/mct-tree.vue:237]: Oh wow, that was DEFINITELY supposed to be a watched property... I'll update.

Comment (jvigliotta) [reply src/ui/layout/mct-tree.vue:237]: Ah, looks like it was watched, just looked weird in the code preview

File: src/ui/layout/mct-tree.vue (hunk 2 above)
Comment (jvigliotta) [reply src/ui/layout/mct-tree.vue]: Ok, removed stopObservingAncstor (no 's') method, and moved it into stopObservingAndstors and set the default to be all of them, but now we can pass in a subset as we discussed.

**Review by deeptailor — APPROVED** [review]
LGTM

**Comment by deeptailor** [comment]
## Reviewer Checklist
Changes appear to address issue? Yes
Appropriate unit tests included? N/A
Code style and in-line documentation are appropriate? Yes
Commit messages meet standards? Yes
Has associated issue been labelled unverified? (only applicable if this PR closes the issue) Yes
