### PR TITLE
fix(imagery): Unblock 'latest' strategy requests for Related Telemetry in realtime mode

### LINKED ISSUE #6074: Related telemetry for imagery not received in realtime mode
#### Summary

Originally described in VIPEROMCT-225 

Related telemetry for imagery is not being received in realtime mode due to changes made in [this PR](https://github.com/akhenry/openmct-yamcs/pull/217). This manifests as the Compass Rose not showing up for streaming imagery in realtime mode (either local clock or remote clock).

#### Expected vs Current Behavior

Related Telemetry for streaming imagery should be received correctly, the compass rose should show up if the appropriate Related Telemetry is present

#### Steps to Reproduce

1. Navigate to our testing environment
2. Switch to either local clock or remote clock mode
3. View streaming imagery from YAMCS
4. Wait for an image to stream in
5. Observe console errors
6. Observe there is no compass rose

#### Environment

* Open MCT Version:  2.1.5-SNAPSHOT
* Deployment Type:  openmct-yamcs
* OS: MacOS
* Browser: Chrome / any

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by ozyx**
Closes #6074 #5984 

### Describe your changes:

This PR fixes the issue of imagery not being able to receive related telemetry when in realtime mode (local or remote clock).

The issue is caused by changes made in this PR on the `openmct-yamcs` side: https://github.com/akhenry/openmct-yamcs/pull/217. For full context, see the related issue and discussion. TL;DR: On `openmct-yamcs` side of things, we ignore `latest` requests when in realtime mode because this data should already be available in our websocket cache. Imagery however is unique in that Related Telemetry (rover pose and camera tilt/pan data which is used to orient the compass rose and HUD) is fetched on-demand depending on the image the user is viewing. So it is entirely expected that when viewing imagery we may be in realtime mode, and making historical 'latest' requests for the related telemetry.

To get around this issue, and without implementing any additional `openmct-yamcs` specific flags, we create a throwaway `IndependentTimeContext` in Fixed Time mode. The `openmct-yamcs` side will then check and allow the request to go through since it's not making a `latest` request in realtime mode (technically.)

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [x] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [x] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/plugins/imagery/components/RelatedTelemetry/RelatedTelemetry.js [hunk 1]
```diff
@@ -88,9 +89,31 @@ export default class RelatedTelemetry {
...
+                // Context: https://github.com/akhenry/openmct-yamcs/pull/217
+                const ephemeralContext = new IndependentTimeContext(
+                    this._openmct,
+                    this._openmct.time,
+                    [this[key].historicalDomainObject]
+                );
+
+                // Stop following the global context, stop the clock,
+                // and set bounds.
+                ephemeralContext.resetContext();
```
Comment (shefalijoshi) [inline src/plugins/imagery/components/RelatedTelemetry/RelatedTelemetry.js:105]: Lovely!

**Review by shefalijoshi — APPROVED** [review]
