### PR TITLE
[Telemetry Collection] No duplicate requests on load

### LINKED ISSUE #4273: [Telemetry Collections] Duplicate requests on load
#### Summary
When loading a telemetry collection, a deliberate call to request historical is made, this isn't necessary, since the timeSystem is also triggered on load and it will request telemetry. Need to remove the initial request.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. On load of a telemetry table, make sure no duplicate requests are made

### PR DESCRIPTION
**Pull request by jvigliotta**
### All Submissions:
Removed initial call to request historical telemetry on load, as the time system call will do that itself.

closes #4273 

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? Will users need to change how they are calling the API, or how they've extended core plugins such as Tables or Plots?

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### CODE REVIEW

**Review by shefalijoshi — APPROVED** [review]
LGTM

File: src/api/telemetry/TelemetryCollection.js [hunk 1]
```diff
@@ -70,7 +70,6 @@ export class TelemetryCollection extends EventEmitter {
         this._watchBounds();
         this._watchTimeSystem();
 
-        this._requestHistoricalTelemetry();
```
Comment (akhenry) [inline src/api/telemetry/TelemetryCollection.js:73]: Hrm, calling `this._requestHistoricalTelemetry();` here makes it really clear that historical telemetry is fetched on load. Now we are relying on historical telemetry being fetched because the time system is also set on load. It's no longer obvious to a developer how historical telemetry is gets fetched on load.

Here is an alternative proposal. We have two functions `_setTimeSystem()` and `_setTimeSystemAndFetchData()`. Literally all that the second one does is call first and then calls `reset()`. The first can be called from `load`, the second from the time system change listener.

**Review by akhenry — CHANGES_REQUESTED** [review]

File: src/api/telemetry/TelemetryCollection.js (hunk 1 above)
Comment (jvigliotta) [reply src/api/telemetry/TelemetryCollection.js:73]: I like it. I love it.

**Review by akhenry — APPROVED** [review]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N/A - v. small change fixing a minor bug.
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
5. Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue) Y
