### PR TITLE
[Display Layouts] Prevent duplicate from being added when composition 'add' is fired

### LINKED ISSUE #3128: [Display Layout] When switching types and canceling edit, the switched item duplicates
Steps to reproduce:

1. Create a new display layout
2. Add a telemetry point and save.
3. Edit the Display Layout and switch the type of the telemetry point to a plot. 
4. Cancel edit (discard changes)
5. Observe that there are 2 alphanumerics now, instead of the original 1.

### PR DESCRIPTION
**Pull request by deeptailor**
This PR fixes #3128 and #3118 - Which are both related but have 2 different paths. 

## Author Checklist
Changes address original issue? Yes
Unit tests included and/or updated with changes? N/A
Command line build passes? Yes
Changes have been smoke-tested? Yes
Testing instructions included? Yes - in related issues

### CODE REVIEW

**Comment by deeptailor** [comment]
@charlesh88 @akhenry  - This bug may catch you off-guard during a demo, if you change types, and then click on cancel editing, it will duplicate the alpha's in the layout.

File: src/plugins/displayLayout/components/DisplayLayout.vue [hunk 1]
```diff
@@ -457,15 +457,43 @@ export default {
...
         },
+        isItemAlreadyTracked(child) {
+            let found = false,
+                keyString = this.openmct.objects.makeKeyString(child.identifier);
+
+            this.layoutItems.forEach(item => {
+                if (item.identifier) {
+                    let itemKeyString = this.openmct.objects.makeKeyString(item.identifier);
+
+                    if (itemKeyString === keyString) {
```
Comment (jvigliotta) [inline src/plugins/displayLayout/components/DisplayLayout.vue:468]: Could you use areIdsEqual from objectApi here? May cut out a few steps.

Comment (deeptailor) [reply src/plugins/displayLayout/components/DisplayLayout.vue:468]: Yes, it does the same thing. I am the one that added that api method, but keep forgetting about it. This works for now though
