### PR TITLE
Misc UI 5640

### LINKED ISSUE #5303: Grid icons are wrong
#### Summary
Grid icon artwork is wrong for many object types.
Screen Shot 2022-06-08 at 10 48 37 AM

#### Steps to Reproduce

1. Create a number of different object types, particularly Display Layout, Notebook, Example Imagery, Web Page, Gauge.
2. Note that the objects will have the correct icons in the tree view.
3. View the folder enclosing the objects in the main view in Grid view, and note that the icon artwork is wrong.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### LINKED ISSUE #5640: Misc UI problems
- [x] Make Display Layout frame edit handles overlap content, not resize it.
- [x] Fix search progress bar display so that progress bar doesn't lay under text.
- [x] Dial Gauges should center in their container, not left flush.
- [x] Add large icon for the aggregate telemetry type.
- [x] Add large icon for the Telemetry Table type. Closes #5303.
- [x] Fix descriptions for Telemetry Table, LAD Table and LAD Table Set.
- [x] Restore tree and Inspector pane's ability to collapse when dragged small enough.
- [x] Fix grippy icons in elements pool.
- [x] Fix value alignment in alphanumerics in Display Layouts.
- [x] Fix Locator in dialog to expand to use available space.
- [x] Fix styling of numeric inputs, especially in Firefox and on Linux.
- [x] Display Layout layout objects are erroneously using the unknown object icon because their type is not being properly defined and they end up using `UNKNOWN_TYPE` from TypeRegistry.js.

**Misaligned alphas in Display Layout**
image

**Numeric inputs in Firefox**
image

### PR DESCRIPTION
**Pull request by charlesh88**
This PR cherry picks commits from `misc-ui-5640-r208` and should now be a clean implementation into master. Testing notes are in #5640.

Closes #5640
Closes #5303

### Describe your changes:
- Better styling for search in progress and 'no results' messaging.
- Revised art and glyph for `icon-tabular-scrolling`.
- Change TelemetryTableType to use icon-tabular-scrolling icon and bg-icon.
- Fix bad/erroneous descriptions for Telemetry Table, LAD Table and LAD Table Set. Refined descriptions for other object types.
- Fixed bad value check that was causing panes not to collapse when dragged (by design) to a very narrow width.
- Visual style for grippy adjusted for better clarity on some monitors.
- Normalize proportional area used by alphanumeric's labels and values in Display Layouts.
- Fix margin strategy for object label in main view.
- Fixed Locator to dynamically size itself to use available vertical space.
- Added new `l-overlay-dialog` size parameter.
- Better approach to overlay sizing to make Properties dialogs larger vertically and fullscreen overlays more apparent to the user.
- Normalized approach to numeric inputs to fix cross-browser inconsistency with input spinners.
- Fixed layout problem in `Datetime.vue` component due to numeric input spinners changes.
- Added type definitions for Display Layout drawing objects; code modded in `ObjectName.vue` to grab layout object `cssClass` from layoutItem.type. Big thanks to @jvigliotta for the assist with this!

### All Submissions:
* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist
* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Changes appear not to be breaking changes?
* [x] Appropriate unit tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Commit messages meet standards?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/plugins/displayLayout/plugin.js [hunk 1]
```diff
@@ -125,6 +126,12 @@ export default function DisplayLayoutPlugin(options) {
                 return true;
             }
         });
+
+        for (const [type, definition] of Object.entries(DisplayLayoutDrawingObjectTypes)) {
+            openmct.types.addType(type, definition);
+            console.log(type, definition);
```
Comment (ozyx) [inline src/plugins/displayLayout/plugin.js:132]: Remove stray console.log

File: src/ui/inspector/ObjectName.vue [hunk 2]
```diff
@@ -132,6 +139,8 @@ export default {
                     this.keyString = this.openmct.objects.makeKeyString(this.domainObject.identifier);
                     this.status = this.openmct.status.get(this.keyString);
                     this.statusUnsubscribe = this.openmct.status.observe(this.keyString, this.updateStatus);
+                } else if (selection[0][0].context.layoutItem) {
```
Comment (ozyx) [inline src/ui/inspector/ObjectName.vue:142]: Just a general question here, but I see `selection[0][0]` all over the codebase. What is this representing?

**Review by ozyx — CHANGES_REQUESTED** [review]
Overall, this looks great. There is one e2e test that needs to be updated to reflect the changes here, and one stray console.log() that made it in. I also have one general question for you (unrelated to the changes here).

File: src/ui/inspector/ObjectName.vue (hunk 2 above)
Comment (akhenry) [reply src/ui/inspector/ObjectName.vue:142]: It represents our gross selection API :)

More specifically, selection of an embedded object (eg. an object embedded in a layout) is represented by a path to the selected object (like `objectPath`, but the format is a little different because it can contain non domain-object things like draw elements in a layout). For simplicity's sake we decided to represent this with an array.

Then we added support for selecting multiple things at once, so our simple one dimensional array became a two dimensional array.

So, `selection[0][0]` is grabbing the thing the user actually clicked on to select (and not any of the object objects in the selected path), and is ignoring multi-select. Multi-select is only actually supported in display layouts (I think?), but the selection API always returns a two dimensional array anyway.

Comment (akhenry) [reply src/ui/inspector/ObjectName.vue:142]: We should improve the documentation around the selection API, and we should probably add some convenience functions for common operations (like the 90% case where you just want a single selected thing and you don't care about multi-select or the selection path)

**Review by ozyx — APPROVED** [review]

**Review by akhenry — APPROVED** [review]
