### PR TITLE
Use different root for `renderWhenVisible`

### LINKED ISSUE #7405: Canvas sometimes dies on refresh
#### Summary

One of our e2e tests caught this. Sometimes when viewing an Overlay Plot with a SWG in it, if you reload the page, Open MCT goes into a state where nothing gets drawn on any canvas. It seems that the canvas are disconnected somehow.

https://github.com/nasa/openmct/assets/9259993/0a7ab651-47e3-4558-9478-e013f3d7af82

@scottbell I think it has something to do with the IntersectionObserver destroying the canvas on load

#### Expected vs Current Behavior

The plot should render

#### Steps to Reproduce

1. Create an SWG
2. Create an Overlay Plot
3. SWG -> Overlay Plot
4. Navigate to the Overlay Plot
5. Set a breakpoint[ here](https://github.com/nasa/openmct/blob/master/src/plugins/plot/chart/MctChart.vue#L284)
6. Reload the page while moving your mouse around where the canvas WOULD be
7. Breakpoint gets hit (keep trying if it doesnt work the first time)
8. continue, notice no canvas gets drawn on

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by scottbell**
Closes #7405 

### Describe your changes:

Using the viewport for the IntersectionObserver was causing timing issues when rendering objects on page load. As the application loads itself, the ObjectView can be rendered well off the page, causing the IntersectionObserver to state that the ObjectView is hidden. Strangely, this doesn't appear to be recoverable as I think we're becoming visible through an event that isn't listened to by the IntersectionObserver. Instead, we can use the Open MCT root element as the root object for the IntersectionObserver.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Has this been smoke tested?
* [x] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [x] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [ ] Is this a breaking change to be called out in the release notes?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?

### CODE REVIEW

File: src/plugins/plot/chart/MctChart.vue [hunk 1]
```diff
@@ -279,22 +285,18 @@ export default {
...
-          console.debug(`📈 chart visible, rebuilding canvas`);
           this.buildCanvasElements();
           const canvasInitialized = this.readyCanvasForDrawing();
           if (canvasInitialized) {
             this.draw();
           }
           this.$emit('plot-reinitialize-canvas');
-        } else {
-          console.debug(`📈 ignoring wasVisible: ${wasVisible} and nowVisible ${nowVisible}`);
+        } else if (wasVisible && this.chartVisible) {
```
Comment (ozyx) [inline src/plugins/plot/chart/MctChart.vue:299]: we should reference this issue # somewhere here, just for extra context

File: src/plugins/plot/chart/MctChart.vue [hunk 2]
```diff
@@ -200,7 +200,13 @@ export default {
     this.chartVisible = true;
     this.chartContainer = this.$refs.chart;
     this.drawnOnce = false;
-    this.visibilityObserver = new IntersectionObserver(this.visibilityChanged);
+    const rootContainer = document.querySelector('.js-main-container');
```
Comment (ozyx) [inline src/plugins/plot/chart/MctChart.vue:203]: I think this is ok to not be a $ref? $refs lookup is much quicker and it's reactive, but we wouldn't be running this repeatedly, and I don't think it needs to be reactive?

either way we should leave a comment here referencing the issue number and explaining why we're using querySelector

**Review by ozyx — CHANGES_REQUESTED** [review]
LGTM overall, let's just add some comments

**Review by unlikelyzero — APPROVED** [review]
