### PR TITLE
Condition Widgets trigger hundreds of persistence calls

### LINKED ISSUE #5137: Condition Widgets trigger hundreds of persistence calls.
#### Summary
Navigating to a condition widget triggers hundreds of persistence calls, despite nothing having changed.

#### Expected vs Current Behavior
Condition widgets (and indeed all object views) should **not** be mutating domain objects unless the user has actually changed something. Mutating a domain object will trigger persistence, which is expensive. Do not use mutation to establish an object's default state.

#### Steps to Reproduce
1. Create a condition widget
2. Create a condition set, drag in a telemetry point, and define a basic rule.
3. Edit the condition widget and apply some conditional styling
4. Save the condition widget. Open the network tab and observe that it is now making persistence calls in an endless loop.

#### Environment
* Open MCT Version: e75befafbdf0eaf5c81380282971211e7c40957a
* Deployment Type: testathon

#### Impact Check List
- [X] Data loss or misrepresented data? - Eventually causes browser to crash
- [X] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [X] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

### PR DESCRIPTION
**Pull request by nikhilmandlik**
Closes #5137 and #4700
### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/plugins/conditionWidget/components/ConditionWidget.vue [hunk 1]
```diff
@@ -39,28 +39,95 @@ export default {
...
+            if (!self.conditionSetIdentifier) {
+                return;
+            }
+
+            self.openmct.objects.get(self.conditionSetIdentifier)
+                .then(conditionSetDomainObject => {
+                    self.openmct.telemetry.request(conditionSetDomainObject)
+                        .then(output => {
+                            if (output && output.length) {
+                                self.updateConditionLabel(output[0]);
```
Comment (akhenry) [inline src/plugins/conditionWidget/components/ConditionWidget.vue:91]: There's a race condition here where subscription data could be replaced by historical data (which often happens).

A simple way to address this is to use `TelemetryCollections` which handle this case. To request a telemetry collection use `this.openmct.telemetry.requestCollection`

File: src/plugins/conditionWidget/components/ConditionWidget.vue [hunk 2]
```diff
@@ -39,28 +39,95 @@ export default {
...
-            this.internalDomainObject = domainObject;
+        listenToConditionSetChanges() {
+            const self = this;
+            self.stopListeningToConditionSetChanges();
+
+            if (!self.conditionSetIdentifier) {
+                return;
+            }
+
+            self.openmct.objects.get(self.conditionSetIdentifier)
```
Comment (akhenry) [inline src/plugins/conditionWidget/components/ConditionWidget.vue:86]: I think we can safely use `await` here? might simplify the code a little. Also, I believe Vue component methods already have `this` bound to the component itself?

File: src/plugins/conditionWidget/components/ConditionWidget.vue [hunk 3]
```diff
@@ -39,28 +39,95 @@ export default {
...
-            return this.urlDefined ? sanitizeUrl(this.internalDomainObject.url) : null;
+        label() {
+            return this.useConditionSetOutputAsLabel
+                ? this.conditionalLabel
+                : this.domainObjectLabel
+            ;
+        }
+    },
+    watch: {
+        conditionSetIdentifier: {
```
Comment (akhenry) [inline src/plugins/conditionWidget/components/ConditionWidget.vue:59]: Good catch, the condition set configured for this widget could change.

File: src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js [hunk 4]
```diff
@@ -132,12 +132,6 @@ export default {
                     }
                 }
             });
-
```
Comment (akhenry) [inline src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js:135]: I'm a little confused by this. Any idea what it did, and why it's in `../stackedPlot`? Appears to be the same logic as in `objectView` but I don't understand why.

**Review by akhenry — CHANGES_REQUESTED** [review]
Looks great, thank you for making these changes so quickly! A couple of small comments inline

File: src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js (hunk 4 above)
Comment (nikhilmandlik) [reply src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js:135]: Yeah I also not sure, adding @shefalijoshi (can you also review this? TIA)

Comment (shefalijoshi) [reply src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js:135]: @nikhilmandlik Stacked plots were not showing conditional styles. For them to work, we had to work on each item inside of the stacked plot as they are not ObjectViews.

Comment (nikhilmandlik) [reply src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js:135]: hmm, I think current condition on stack plot is also showing correctly,
It only applies to first item.
Screen Shot 2022-05-02 at 2 19 35 PM

File: src/plugins/LADTable/components/LADRow.vue [hunk 5]
```diff
@@ -148,6 +148,8 @@ export default {
         this.openmct.time.off('timeSystem', this.updateTimeSystem);
         this.telemetryCollection.off('add', this.setLatestValues);
         this.telemetryCollection.off('clear', this.resetValues);
+
+        this.telemetryCollection.destroy();
```
Comment (davetsay) [inline src/plugins/LADTable/components/LADRow.vue:152]: phew 😅

File: src/plugins/conditionWidget/components/ConditionWidget.vue [hunk 6]
```diff
@@ -27,7 +27,7 @@
     :href="url"
 >
     <div class="c-condition-widget__label">
-        {{ internalDomainObject.conditionalLabel || internalDomainObject.label }}
+        {{ label }}
```
Comment (davetsay) [inline src/plugins/conditionWidget/components/ConditionWidget.vue:30]: 👍

File: src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js (hunk 4 above)
Comment (akhenry) [reply src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js:135]: But why the specific `conditionalLabel` logic? Does that apply to stacked plots at all, or was that just because it's a mixin being used in more than one place?

File: src/plugins/conditionWidget/components/ConditionWidget.vue [hunk 7]
```diff
@@ -57,51 +57,68 @@ export default {
...
-                this.stopProvidingTelemetry();
-                this.stopProvidingTelemetry = null;
+            if (this.telemetryCollection) {
+                this.telemetryCollection.off('add', this.updateConditionLabel, this);
+                this.telemetryCollection.destroy();
+                this.telemetryCollection = null;
             }
         },
-        updateConditionLabel(styleObj = {}) {
+        updateConditionLabel([styleObj = {}]) {
```
Comment (akhenry) [inline src/plugins/conditionWidget/components/ConditionWidget.vue:115]: styleObject is a telemetryDatum, no? I don't think it has any style data on it. Also it should never be undefined, if it is it's an error I think.

**Review by davetsay — APPROVED** [review]
LGTM

**Review by akhenry — APPROVED** [review]
