### PR TITLE
[Staleness] Fix staleness on clock change

### LINKED ISSUE #6339: [Staleness] Switching between clock modes incorrectly persists the current staleness state
Relates to #6109 

#### Summary

When staleness is currently visible in a component and the user switches clock modes, the staleness state is not cleared and persisted until new telemetry streams in.

#### Expected vs Current Behavior

Currently the staleness state is persisted between clock modes. Expected behavior is to clear the staleness state.

#### Steps to Reproduce

1. Setup a display layout containing SWG with staleness enabled
2. Wait until staleness is triggered ~10 seconds
3. Switch clock modes from Local to Remote
4. Observe the staleness styling is still present

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by khalidadil**
Closes #6339 

### Describe your changes:
Refactored staleness out of Vue components and into a mixin where possible. Added the function to unsubscribe/resubscribe staleness on clock change, and added a guard to make sure staleness only applied to correct clock.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/ui/mixins/staleness-mixin.js [hunk 1]
```diff
@@ -20,52 +20,192 @@
...
+      if (!this.compositionObjectMap.get(id)) {
+        this.compositionObjectMap.set(id, domainObject);
+      }
+    },
+    compositionIterator(callback) {
+      return () => {
+        this.staleObjects = [];
+        for (const [, object] of this.compositionObjectMap) {
+          let domainObject = object;
+          if (isProxy(domainObject)) {
```
Comment (jvigliotta) [inline src/ui/mixins/staleness-mixin.js:62]: We want to keep Vue specific utils (`toRaw`, `isProxy`) in Vue files... I'm guilty of this as well! Do we need this here?

Comment (khalidadil) [reply src/ui/mixins/staleness-mixin.js:62]: I think this is needed here to unwrap the domainObjects and pass them to functions that are expecting them to be unwrapped. Is there a way to access properties on them without converting them from proxies to standard objects? I was getting errors when doing this without the `toRaw` conversion.

File: src/ui/mixins/staleness-mixin.js [hunk 2]
```diff
@@ -20,52 +20,192 @@
...
+      this.stalenessSubscription[id] = {};
+      this.stalenessSubscription[id].stalenessUtils = new StalenessUtils(
+        this.openmct,
+        domainObject
+      );
+    },
+    teardownStalenessUtils(domainObject) {
+      const id = this.getSubscriptionId(domainObject);
+      const { stalenessUtils } = this.stalenessSubscription[id];
+      if (stalenessUtils) {
```
Comment (jvigliotta) [inline src/ui/mixins/staleness-mixin.js:133]: are there situations where this wouldn't be set?

File: src/plugins/condition/components/ConditionCollection.vue [hunk 3]
```diff
@@ -221,31 +227,16 @@ export default {
...
-        (stalenessResponse) => {
-          this.handleStaleness(keyString, stalenessResponse);
-        }
-      );
-
-      this.stalenessSubscription[keyString].unsubscribe = stalenessSubscription;
     },
     removeTelemetryObject(identifier) {
       const keyString = this.openmct.objects.makeKeyString(identifier);
+      const domainObject = this.openmct.objects.get(keyString);
```
Comment (jvigliotta) [inline src/plugins/condition/components/ConditionCollection.vue:239]: I _think_ we can pull this domainObject out of `this.telemetryObjs` instead of making a get call?

Comment (khalidadil) [reply src/plugins/condition/components/ConditionCollection.vue:239]: good call! I can check this out

File: src/plugins/plot/stackedPlot/StackedPlotItem.vue [hunk 4]
```diff
@@ -116,20 +110,26 @@ export default {
...
     this.isEditing = this.openmct.editor.isEditing();
     this.openmct.editor.on('isEditing', this.setEditState);
+    this.setupClockChangedEvent((domainObject) => {
+      this.triggerUnsubscribeFromStaleness(domainObject);
+      this.subscribeToStaleness(domainObject);
+    });
   },
   beforeUnmount() {
     this.openmct.editor.off('isEditing', this.setEditState);
+    if (this.composition) {
```
Comment (jvigliotta) [inline src/plugins/plot/stackedPlot/StackedPlotItem.vue:129]: Nice, were we not watching this before? Good catch!

File: src/plugins/condition/components/ConditionCollection.vue (hunk 3 above)
Comment (khalidadil) [reply src/plugins/condition/components/ConditionCollection.vue]: Fixed! The telemetryObjs were the right way to go!

File: src/plugins/LADTable/components/LadTableSet.vue [hunk 5]
```diff
@@ -76,7 +79,8 @@ export default {
       ladTableObjects: [],
       ladTelemetryObjects: {},
       viewContext: {},
-      configuration: this.ladTableConfiguration.getConfiguration()
+      configuration: this.ladTableConfiguration.getConfiguration(),
+      subscribedObjects: []
```
Comment (jvigliotta) [inline src/plugins/LADTable/components/LadTableSet.vue:83]: is this supposed to be an object? looks like it's being used as an object below

Comment (khalidadil) [reply src/plugins/LADTable/components/LadTableSet.vue:83]: yes this is. Could you please update this?

Comment (khalidadil) [reply src/plugins/LADTable/components/LadTableSet.vue]: good catch! I've updated it

File: src/plugins/condition/components/ConditionCollection.vue [hunk 6]
```diff
@@ -135,15 +135,9 @@ export default {
...
-
-    if (this.stalenessSubscription) {
-      Object.values(this.stalenessSubscription).forEach((stalenessSubscription) => {
-        stalenessSubscription.unsubscribe();
-        stalenessSubscription.stalenessUtils.destroy();
-      });
-    }
   },
   mounted() {
+    console.log('mounted');
```
[the remark this answers is not in the document]
Comment (khalidadil) [reply src/plugins/condition/components/ConditionCollection.vue]: bleh, removed!

**Review by jvigliotta — APPROVED** [review]
Nice work! The refactor looks great and moves a lot of the duplication out. Well done!
