### PR TITLE
fix a couple flaky tests

### LINKED ISSUE #5060: [e2e] Snapshot bugs in  exportAsJSON tests
#### Summary
https://app.circleci.com/pipelines/github/nasa/openmct/9777/workflows/52e28c8e-9678-42be-8898-ce0de15123dd/jobs/31411/tests#failed-test-0

```
plugins/plot/autoscale.e2e.spec.js:50:10 › ExportAsJSON › autoscale off causes no error from undefined user range 

    Error: Snapshot comparison failed:

    Expected: /root/project/test-results/plugins-plot-autoscale.e2e-ExportAsJSON-autoscale-off-causes-no-error-from-undefined-user-range-chrome/autoscale-canvas-prepan-expected.png
    Received: /root/project/test-results/plugins-plot-autoscale.e2e-ExportAsJSON-autoscale-off-causes-no-error-from-undefined-user-range-chrome/autoscale-canvas-prepan-actual.png
        Diff: /root/project/test-results/plugins-plot-autoscale.e2e-ExportAsJSON-autoscale-off-causes-no-error-from-undefined-user-range-chrome/autoscale-canvas-prepan-diff.png

      66 |             new Promise(r => setTimeout(r, 100))
      67 |                 .then(() => canvas.screenshot())
    > 68 |                 .then(shot => expect(shot).toMatchSnapshot('autoscale-canvas-prepan.png', { maxDiffPixels: 40 }))
         |                                            ^
      69 |         ]);
      70 |
      71 |         let errorCount = 0;

        at /root/project/e2e/tests/plugins/plot/autoscale.e2e.spec.js:68:44
        at async Promise.all (index 1)
        at /root/project/e2e/tests/plugins/plot/autoscale.e2e.spec.js:64:9
```

### PR DESCRIPTION
**Pull request by trusktr**
let's see if this works

Closes #5060 
hopefully - I forgot to increase maxDiffPixels for one snapshot test, making it more chance to flake. 

Also fixes a PerformanceIndicator test flake I encountered

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [ ] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

Test: make sure test passes locally and in CI. It might fail again, in which case we need to raise the `maxDiffPixel` number perhaps. Ideally the number should be high enough to cover inconsistent but still-good behavior, but to still fail on totally wrong behavior.

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/plugins/performanceIndicator/pluginSpec.js [hunk 1]
```diff
@@ -61,25 +58,21 @@ describe('the plugin', () => {
         expect(performanceIndicator).toBeDefined();
     });
 
-    it('correctly calculates fps', () => {
-        return countFramesPromise.then((frames) => {
-            expect(performanceIndicator.text()).toEqual(`${frames} fps`);
-        });
+    it('correctly calculates fps', async () => {
```
Comment (akhenry) [inline src/plugins/performanceIndicator/pluginSpec.js:61]: So I think the problem here is that this test (which was written by me) is conceptually flawed. It's trying to validate that the performance indicator is showing the _correct_ fps, and there's no reliable way to do this from within a Jasmine test, so entire premise is flawed, and I should never have written it this way.

Instead I think that we should check that it shows any positive number (ie. not just the default "~ fps", and not "0 fps" because that suggests a regression in the code itself?). So we should parse the indicator text, and check that the bit before the string `fps` is a positive number and call it a day.

Trying to check that it's a specific number is subject to the vagaries of the test environment it's running on and what else is going on at the time.

**Review by akhenry — CHANGES_REQUESTED** [review]

File: src/plugins/performanceIndicator/pluginSpec.js (hunk 1 above)
Comment (unlikelyzero) [reply src/plugins/performanceIndicator/pluginSpec.js:61]: @akhenry so we change the test name to 'calculates a positive integer value between 1 and 1000' ?

Comment (trusktr) [reply src/plugins/performanceIndicator/pluginSpec.js:61]: sounds good. I'll just test for any positive number

Comment (trusktr) [reply src/plugins/performanceIndicator/pluginSpec.js]: @akhenry alrighty, pushed the updated test, checking only for a positive fps

File: e2e/tests/plugins/plot/autoscale.e2e.spec.js [hunk 2]
```diff
@@ -102,7 +102,7 @@ test.describe('ExportAsJSON', () => {
             testYTicks(page, ['0.00', '0.50', '1.00', '1.50', '2.00']),
             new Promise(r => setTimeout(r, 100))
                 .then(() => canvas.screenshot())
-                .then(shot => expect(shot).toMatchSnapshot('autoscale-canvas-panned.png', { maxDiffPixels: 20 }))
+                .then(shot => expect(shot).toMatchSnapshot('autoscale-canvas-panned.png', { maxDiffPixels: 40 }))
```
Comment (unlikelyzero) [inline e2e/tests/plugins/plot/autoscale.e2e.spec.js:105]: this is great. I do want to document our usage of hardcoded snapshots which ignore platform (outside of this PR)

**Review by unlikelyzero — APPROVED** [review]

**Review by unlikelyzero — APPROVED** [review]
