### PR TITLE
Dont' mutate a stacked plot unless its user initiated

### LINKED ISSUE #5363: Stacked Plots having configuration saved on load
#### Summary
In general configurations should not be persisted unless the user explicitly makes a change.

#### Expected vs Current Behavior
Stacked plots should have a reasonable default configuration if it doesn't have one

#### Steps to Reproduce
1. create a stacked plot object
2. drag and drop telemetry into the stacked plot object and save
3. open console browser and navigate to network tab
5. navigate away from and then back to the stacked plot
6. go into edit mode
7. save the stacked plot
9. you should not see a network PUT call to the persistence provider Couch
10. go into edit mode again
11. click on a plot in the stacked plot object
12. modify properties in the plot series in the inspector (aka color of plot lines)
13. save the plot
14. now you should see a network PUT call to couch

#### Environment

* Open MCT Version: release/2.0.5
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by shefalijoshi**
Closes #5363 

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Commit messages meet standards?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [x] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/plugins/plot/stackedPlot/StackedPlotItem.vue [hunk 1]
```diff
@@ -223,33 +223,38 @@ export default {
...
-                            palette: this.colorPalette,
-                            callback: (data) => {
-                                this.data = data;
-                            }
-                        });
-                        configStore.add(configId, config);
+                    if (!persistedConfig) {
+                        persistedConfig = {
+                            series: {}
+                        };
```
Comment (davetsay) [inline src/plugins/plot/stackedPlot/StackedPlotItem.vue:233]: do we also need a `yAxis` default here per line 247?

Comment (shefalijoshi) [reply src/plugins/plot/stackedPlot/StackedPlotItem.vue:233]: Actually I don't think we even need these defaults. I'm still testing.

**Review by davetsay — APPROVED** [review]
LGTM
