### PR TITLE
Plot composition re-ordering support

### LINKED ISSUE #2101: [Plot] Options get out of sync during composition re-order, changes made to incorrect item.
If you reorder the composition of a plot, the plot series options will not reorder to match.  

Additionally, when you edit series options after reordering, everything appears to work, but then when you save and view the plot, it turns out you were editing a different series.

1. create overlay plot, add at least two telemetry points.
2. while editing, re-order telemetry points in composition by drag & dropping.
3. observe that order of elements in elements pool does not match order in plot series options.
    screen shot 2018-07-02 at 3 11 02 pm
4. edit plot series option for one of the re-arranged options.
5. save
6. note that property was persisted with the wrong plot series option.

Reported in 7/2 testahon from https://github.com/nasa/openmct/issues/2066

### PR DESCRIPTION
**Pull request by larkin**
Updates plot options to support dynamic re-ordering of items without mutating the wrong properties.  Fixes #2101.

Also updates plot options to allow a zero value for y axis min/max.

# Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? N, issue exists for backfill.
3. Command line build passes? Y
4. Changes have been smoke-tested? Y

### CODE REVIEW

File: src/plugins/plot/src/telemetry/PlotController.js [hunk 1]
```diff
@@ -71,6 +71,7 @@ define([
         this.config.series.forEach(this.addSeries, this);
 
         this.followTimeConductor();
+        window.plot = this;
```
Comment (psarram) [inline src/plugins/plot/src/telemetry/PlotController.js]: @larkin This line should be removed, otherwise changes look good.

There are no tests written for the new controllers. Is there a plan to add tests at a later time?

Comment (larkin) [reply src/plugins/plot/src/telemetry/PlotController.js]: There is an issue for backfill.

**Comment by larkin** [comment]
@psarram made the changes, please continue review.

**Comment by psarram** [comment]
**Reviewer Checklist**

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N, issue exists for backfill.
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
