### PR TITLE
Fix scroll issues in tree overflow state

### LINKED ISSUE #3383: [Tree] Tree scrolling area should not display horizontal scroll
Screen Shot 2020-09-18 at 2 34 32 PM

### Reproduce
1. Open the tree and size the window such that a vertical scroll will be forced.
1. Observe: a track for horizontal scroll is displayed (purple arrow) but only the track and thumb for the vertical scroll should be visible.

### Additional Testing Notes
I think this also fixes the undocumented "scrollbars not appearing when they should" bug. To verify do the following: nav somewhere in the app that has enough items in it that you can resize the browser window such that the bottom-most tree item can be covered. 
Screen Shot 2020-09-18 at 3 07 28 PM

If the problem has NOT been fixed then you should be able to hide the bottom-most item without scrollbars appearing. If scrollbars DO appear even as you start covering the bottom-most item, then the problem has been fixed.

### PR DESCRIPTION
**Pull request by charlesh88**
Fixes #3383

### Changes
- Rename CSS class to bring inline with established naming pattern;
- Move "__item-h" width spec into more general class, rather than specific to scrollable-children;
- Remove JS-based detection and setting of overflow to use CSS `overflow: auto` instead. This may also fix another observed (but undocumented) problem re. scrollbars not appearing when expected;

### Test Notes
See #3383 

### Author Checklist
1. Changes address original issue? Y
1. Unit tests included and/or updated with changes? N/A
1. Command line build passes? Y
1. Changes have been smoke-tested? Y

### CODE REVIEW

File: src/ui/layout/mct-tree.vue [hunk 1]
```diff
@@ -635,8 +635,7 @@ export default {
         },
         scrollableStyles() {
             return {
-                height: this.availableContainerHeight + 'px',
-                overflow: this.noScroll ? 'hidden' : 'scroll'
+                height: this.availableContainerHeight + 'px'
```
Comment (jvigliotta) [inline src/ui/layout/mct-tree.vue:638]: I have no idea why, but if I have "My Items" selected and refresh the page, only a subset of the children for "My Items" show up, I swtiched back to master to check and it doesn't do it there. A way to fix this is to add back in overflow, but specify overflow-y:

`'overflow-y': this.noScroll ? 'hidden' : 'scroll'`

Adding that in should handle the issue with the horizontal scroller, but fix this odd issue as well.

**Review by jvigliotta — CHANGES_REQUESTED** [review]
Needs one little change, then it should be good.

**Comment by charlesh88** [comment]
New issue: forcing the child container into an overflow condition

Screen Shot 2020-09-29 at 2 49 45 PM

and then clicking into a container that's empty

Screen Shot 2020-09-29 at 2 23 23 PM

displays the scroll area with the sizing element forcing a scroll. Basically, it looks like the sizing element's height isn't being re-calculated for empty containers, but should be.

**Comment by jvigliotta** [comment]
Ok, made a good bit of changes here. Kept running into similar issues and need to fix the root problems. So this was a bit of a refactor to handle that.

Also merged in the revert-locking-navigation.

Have locally tested thoroughly with single root child and multiple root children.

**Review by jvigliotta — APPROVED** [review]

File: src/ui/layout/mct-tree.vue [hunk 2]
```diff
@@ -189,21 +187,30 @@ export default {
...
+                return 0;
+            }
+
+            return this.itemHeight * this.ancestors.length;
+        },
+        pageThreshold() {
+            return Math.ceil(this.availableContainerHeight / this.itemHeight) + ITEM_BUFFER;
+        },
+        scrollActive() {
+            return !(this.childrenHeight > this.availableContainerHeight);
```
Comment (akhenry) [inline src/ui/layout/mct-tree.vue:202]: `childrenHeight` has been re-implemented as a method, so this check won't work any more.

File: src/ui/layout/mct-tree.vue [hunk 3]
```diff
@@ -330,105 +355,64 @@ export default {
...
-                    }
-
-                    this.updatevisibleItems();
-                });
+                this.availableContainerHeight = mainTreeHeight - this.ancestorsHeight;
             } else {
                 window.setTimeout(this.setContainerHeight, RECHECK_DELAY);
             }
         },
+        childrenHeight() {
```
Comment (akhenry) [inline src/ui/layout/mct-tree.vue:368]: Why is this a method rather than a computed property? Methods are really expensive when they're used from templates because they have to be re-evaluated every time.

File: src/ui/layout/mct-tree.vue [hunk 4]
```diff
@@ -189,21 +187,30 @@ export default {
...
-            }
-
             const AND_SAVE_PATH = true;
             let currentLocationPath = this.openmct.router.currentLocation.path;
             let hasParent = this.currentlyViewedObjectParentPath() || (this.multipleRootChildren && !this.currentlyViewedObjectParentPath());
             let jumpAndScroll = currentLocationPath
                     && hasParent
                     && !this.currentPathIsActivePath();
-            let justScroll = this.currentPathIsActivePath() && !this.noScroll;
+            let justScroll = this.currentPathIsActivePath() && this.scrollActive;
```
Comment (akhenry) [inline src/ui/layout/mct-tree.vue:213]: Booleans should always start with `is`, `are`, etc.

File: src/ui/layout/mct-tree.vue [hunk 5]
```diff
@@ -261,13 +273,20 @@ export default {
 
         if (root.identifier !== undefined) {
             let rootNode = this.buildTreeItem(root);
+            let rootComposition = this.openmct.composition.get(root);
```
Comment (akhenry) [inline src/ui/layout/mct-tree.vue:276]: Naming is slightly confusing here. `rootComposition` refers to a `CompositionCollection` object, and `compositionCollection` references an Array. I'd be inclined to name the first one `compositionCollection`, and the array `rootComposition`.

File: src/ui/layout/mct-tree.vue [hunk 6]
```diff
@@ -237,20 +244,25 @@ export default {
...
+            // catches an edge case when new items are added (ex. folder)
             if (!this.isLoading) {
                 this.setContainerHeight();
             }
         },
         ancestors() {
             this.observeAncestors();
+        },
+        availableContainerHeight() {
+            this.updatevisibleItems();
```
Comment (akhenry) [inline src/ui/layout/mct-tree.vue:257]: camelCase is not being observed here. Should be `updateVisibleItems`

File: src/ui/layout/tree-item.vue [hunk 7]
```diff
@@ -137,8 +132,15 @@ export default {
         }
 
         this.openmct.router.on('change:path', this.highlightIfNavigated);
+    },
+    updated() {
         if (this.emitHeight) {
-            this.$emit('emittedHeight', this.$refs.me);
+            this.$nextTick(() => {
```
Comment (akhenry) [inline src/ui/layout/tree-item.vue:138]: A `nextTick` should not be needed as the first line of an `updated` call. By definition, `updated` will only be called after a tick has already taken place, and since the state has not changed yet (in fact `updated` should never mutate state) `nextTick` should not be needed.

I'm a little concerned about the number of nextTicks and setTimeouts in this code, and I wonder whether we could refactor this in future to use an event-driven model. (Perhaps [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) might come in handy?). Don't address it now, I'll file a followup.

**Review by akhenry — CHANGES_REQUESTED** [review]

File: src/ui/layout/mct-tree.vue (hunk 2 above)
Comment (jvigliotta) [reply src/ui/layout/mct-tree.vue:202]: Well that was enlightening! Looks like at this point I didn't even need the scrollActive variable.

File: src/ui/layout/mct-tree.vue (hunk 4 above)
Comment (jvigliotta) [reply src/ui/layout/mct-tree.vue:213]: Got rid of this guy, but I will make note of that.

File: src/ui/layout/mct-tree.vue (hunk 6 above)
Comment (jvigliotta) [reply src/ui/layout/mct-tree.vue:257]: Got it!

File: src/ui/layout/mct-tree.vue (hunk 5 above)
Comment (jvigliotta) [reply src/ui/layout/mct-tree.vue:276]: Yep, good call. Renamed.

File: src/ui/layout/tree-item.vue (hunk 7 above)
Comment (jvigliotta) [reply src/ui/layout/tree-item.vue:138]: Removed that nextTick as it was unnecessary, unfortunately the timeout is. Would love a more reliable way to get fully rendered DOM element information.

File: src/ui/layout/mct-tree.vue (hunk 3 above)
Comment (jvigliotta) [reply src/ui/layout/mct-tree.vue:365]: I think I have a fix for this, but need time to implement.

Comment (jvigliotta) [reply src/ui/layout/mct-tree.vue:365]: So the issue here, was in children height I'm using the top margin of the tree. Since this doesn't really change, I just need to grab the final version on load, this was unreliable in mounted, apparently CSS was still updating after that hook, so I used some vanilla JS for readyState complete, that did the trick. Now childrenHeight is only calculated when item height or focused items changes.

File: src/ui/layout/mct-tree.vue [hunk 8]
```diff
@@ -143,15 +143,13 @@ export default {
...
             updatingView: false,
+            itemHeightCalculated: false,
             itemHeight: 28,
             itemOffset: 0,
-            childrenHeight: 0,
             scrollable: undefined,
-            pageThreshold: 50,
             activeSearch: false,
-            getChildHeight: false,
+            getItemHeight: false,
```
Comment (nikhilmandlik) [inline src/ui/layout/mct-tree.vue:152]: we should rename `getItemHeight` to something like `enableGetItemHeight` or `isGetItemHeight` etc as its a boolean.
Also other boolean props. `getItemHeight` sound more like a function returning itemHeight

Comment (nikhilmandlik) [reply src/ui/layout/mct-tree.vue:152]: same for `:emit-height` in 'tree-item'

File: src/ui/layout/tree-item.vue [hunk 9]
```diff
@@ -137,8 +132,13 @@ export default {
...
 
         this.openmct.router.on('change:path', this.highlightIfNavigated);
+    },
+    updated() {
         if (this.emitHeight) {
-            this.$emit('emittedHeight', this.$refs.me);
+            // no reliable way to get the fully rendered height without timeout
+            setTimeout(() => {
+                this.$emit('emittedHeight', this.$refs.me.offsetHeight);
+            }, 250);
```
Comment (nikhilmandlik) [inline src/ui/layout/tree-item.vue]: hmm, try following? ref: https://vuejs.org/v2/api/#updated
```
updated() {
  this.$nextTick(function () {
    // Code that will run only after the
    // entire view has been re-rendered
  })
}
```

**Review by nikhilmandlik — CHANGES_REQUESTED** [review]
small changes

File: src/ui/layout/mct-tree.vue (hunk 8 above)
Comment (jvigliotta) [reply src/ui/layout/mct-tree.vue]: Good call! updated to shouldEmitHeight.

File: src/ui/layout/tree-item.vue (hunk 9 above)
Comment (jvigliotta) [reply src/ui/layout/tree-item.vue]: Yeah, that does work actually, I've moved it to a document readystate event of "complete" for both mct-tree and tree-item, that only fires once and gives me the same result, BUT if you guys (@akhenry)think I should move it to update, I can just put in a check to see if it's been done yet inside a nextTick callback in updated.

**Review by nikhilmandlik — APPROVED** [review]
LGTM

File: src/ui/layout/tree-item.vue (hunk 9 above)
Comment (akhenry) [reply src/ui/layout/tree-item.vue]: @jvigliotta Leave it in the readstate callback, I'm fine with that.

File: src/ui/layout/tree-item.vue (hunk 7 above)
Comment (akhenry) [reply src/ui/layout/tree-item.vue]: I take back my earlier statement, there are some cases where calling `$nextTick()` immediately inside updated makes sense, as it ensures that all children have also rendered.

**Review by akhenry — APPROVED** [review]

**Comment by akhenry** [comment]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N/A - Followup issue to address this - https://github.com/nasa/openmct/issues/3108
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
5. Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue)
