### PR TITLE
Ensures correct results are returned for conditions and criteria for a given telemetry datapoint

### LINKED ISSUE #2882: [Conditionals] Default should never be output
A state generator with conditions for `ON` and `OFF` should never output the default condition, but it still does.

Steps to reproduce
1. Create a condition set and add a state generator
1. Create a condition - `value = 1` (ON)
1. Create another condition - `value = 0` (OFF). `value != 1` works as well to test.
1. Save Condition Set
1. Switch to Telemetry Table view and observe that default condition is still output

state_condition_default

### PR DESCRIPTION
**Pull request by shefalijoshi**
Resolves #2882
- Condition checks for results from all criteria for a specific datapoint before evaluating it's result. This was done by changing the event based result calculation to a synchronous one.
- Conditions and Criteria store their own results. Eliminates extra work in removing objects and then their corresponding results
- support all available timesystems. use current timesystem for get latest comparison.
- AllTelemetryCriterion extends TelemetryCriterion

### CODE REVIEW

File: src/plugins/condition/Condition.js [hunk 1]
```diff
@@ -290,7 +293,7 @@ export default class ConditionClass extends EventEmitter {
     }
 
     destroy() {
-        this.conditionManager.off('broadcastTelemetry', this.handleBroadcastTelemetry, this);
+        this.conditionManager.off('telemetryReceived', this.getConditionResultForTelemetry, this);
```
Comment (akhenry) [inline src/plugins/condition/Condition.js:296]: 👍

File: src/plugins/condition/Condition.js [hunk 2]
```diff
@@ -65,21 +65,40 @@ export default class ConditionClass extends EventEmitter {
             this.createCriteria(conditionConfiguration.configuration.criteria);
         }
         this.trigger = conditionConfiguration.configuration.trigger;
-        this.conditionManager.on('broadcastTelemetry', this.handleBroadcastTelemetry, this);
+        this.conditionManager.on('telemetryReceived', this.getConditionResultForTelemetry, this);
```
Comment (akhenry) [inline src/plugins/condition/Condition.js:68]: 👍

File: src/plugins/condition/Condition.js [hunk 3]
```diff
@@ -247,13 +253,10 @@ export default class ConditionClass extends EventEmitter {
...
     }
 
-    getTelemetrySubscriptions() {
-        return this.criteria.map(criterion => criterion.telemetryObjectIdAsString);
-    }
-
     handleConditionUpdated(datum) {
         // trigger an updated event so that consumers can react accordingly
         this.result = this.evaluate(this.criteriaResults);
+        this.evaluationPending = false;
```
Comment (shefalijoshi) [inline src/plugins/condition/Condition.js:259]: Not used. remove.

**Comment by davetsay** [comment]
Going to put a little more work in tomorrow but this is in a working state now.

File: src/plugins/condition/ConditionManager.js [hunk 4]
```diff
@@ -266,8 +248,28 @@ export default class ConditionManager extends EventEmitter {
...
-    broadcastTelemetry(id, datum) {
-        this.emit(`broadcastTelemetry`, Object.assign({}, this.createNormalizedDatum(datum, id), {id: id}));
+    telemetryReceived(id, datum) {
+        const normalizedDatum = this.createNormalizedDatum(datum, id);
+        const timeSystemKey = this.openmct.time.timeSystem().key;
+        let timestamp = {};
+        timestamp[timeSystemKey] = normalizedDatum[timeSystemKey];
+
+        this.conditionClassCollection.forEach(condition => {
+            condition.getResult(normalizedDatum);
```
Comment (akhenry) [inline src/plugins/condition/ConditionManager.js:258]: Will file followup issue for this. We don't need to evaluate all conditions, we should short-circuit if possible here. There are probably good reasons for exhaustively evaluating all of them right now (so we're not caching stale data) but we should figure out how to optimize this.

**Comment by akhenry** [comment]
This looks good to me. Once merge conflicts have been resolved in Master, I will update from master, and then merge.

## Reviewer Checklist

* Changes appear to address issue? Y
* Appropriate unit tests included? Y
* Code style and in-line documentation are appropriate? Y
* Commit messages meet standards? Y

File: src/plugins/condition/criterion/TelemetryCriterion.js [hunk 5]
```diff
@@ -60,20 +67,44 @@ export default class TelemetryCriterion extends EventEmitter {
...
         return datum;
     }
 
-    handleSubscription(data) {
-        if(this.isValid()) {
-            this.emitEvent('criterionResultUpdated', this.formatData(data));
-        } else {
-            this.emitEvent('criterionResultUpdated', this.formatData({}));
+    getResult(data) {
+        const validatedData = this.isValid() ? data : {};
```
Comment (shefalijoshi) [inline src/plugins/condition/criterion/TelemetryCriterion.js:78]: why does validatedData need to be an empty object here? Could it be `undefined`?

File: src/plugins/condition/Condition.js [hunk 6]
```diff
@@ -57,29 +56,41 @@ export default class ConditionClass extends EventEmitter {
...
+        this.result = evaluateResults(this.criteria.map(criterion => criterion.result), this.trigger);
+    }
+
+    isAnyOrAllTelemetry(criterion) {
+        return (criterion.telemetry && (criterion.telemetry === 'all' || criterion.telemetry === 'any'));
+    }
+
+    isTelemetryUsed(id) {
+        return this.criteria.some(criterion => {
+            return this.isAnyOrAllTelemetry(criterion) || criterion.telemetryObjectIdAsString === id;
```
Comment (shefalijoshi) [inline src/plugins/condition/Condition.js:92]: `criterion.telemetryObjectIdAsString` was removed. So this will not match

File: src/plugins/condition/criterion/TelemetryCriterion.js (hunk 5 above)
Comment (davetsay) [reply src/plugins/condition/criterion/TelemetryCriterion.js:78]: I'm not entirely sure. This is a direct-ish copy and I didn't want to mess anything up. I think we can request and get results without "good" data and it should react accordingly. There is a slight chance this does something more correct for the cases where conditions are fully formed though.

I just left this relatively unchanged but moved it around for clarity.

File: src/plugins/condition/Condition.js (hunk 6 above)
Comment (davetsay) [reply src/plugins/condition/Condition.js:92]: wow good catch. i'll make sure to add that back

**Comment by shefalijoshi** [comment]
Unable to get a single condition to evaluate...debugging.

**Comment by shefalijoshi** [comment]
> Unable to get a single condition to evaluate...debugging.

This is now fixed.

**Comment by shefalijoshi** [comment]
Seeing results being emitted for telemetry that's not being used in any condition.

File: src/plugins/condition/criterion/TelemetryCriterionSpec.js [hunk 7]
```diff
@@ -102,21 +102,20 @@ describe("The telemetry criterion", function () {
...
 
-    it("does not return a result on new data from irrelavant telemetry providers", function () {
-        const result = telemetryCriterion.getResultForTelemetry({
-            value: 'Hello',
-            utc: 'Hi',
-            id: '1234'
-        });
-        expect(result).toBeUndefined();
-    });
+    // it("does not return a result on new data from irrelavant telemetry providers", function () {
```
Comment (akhenry) [inline src/plugins/condition/criterion/TelemetryCriterionSpec.js:113]: Remove commented code

Comment (shefalijoshi) [reply src/plugins/condition/criterion/TelemetryCriterionSpec.js:113]: Done.
