### PR TITLE
Mct4196 - Fixes Conditional Styling not being applied when editing a Condition Widget

### LINKED ISSUE #4196: Conditional Styling not being applied when editing a Condition Widget
#### Summary
Conditional Styling not being applied when editing a Condition Widget

#### Expected vs Current Behavior
When editing a Condition Widget, clicking a Condition rule in the Inspector should ignore the actual Condition Set's current evaluation state and apply the style as defined in that rule immediately. Instead, the selected rule is having no affect on the applied style, using the Condition Set evaluation to drive which style is being applied as if the system was in browse mode. This makes it practically impossible in some cases to preview how an applied style will look.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. Make a Condition Set, and create a rule that will never match. 
2. Edit or create a Condition Widget, and use the CS created in step 1 to conditionally style the widget.
2. Define colors for the default rule, and observe that they are applied.
3. Select the "never match" rule and define colors. Observe that the style is not applied, but should be.

image

#### Environment
* Open MCT Version: 1.7.7, 1.7.8
* Deployment Type: /stable, /latest
* OS:
* Browser:

### PR DESCRIPTION
**Pull request by scottbell**
Resolves #4196 

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [X] Is this change backwards compatible? Will users need to change how they are calling the API, or how they've extended core plugins such as Tables or Plots?

### Author Checklist

* [X] Changes address original issue?
* [X] Unit tests included and/or updated with changes?
* [X] Command line build passes?
* [X] Has this been smoke tested?
* [X] Testing instructions included in associated issue?

### CODE REVIEW

File: src/plugins/condition/StyleRuleManager.js [hunk 1]
```diff
@@ -27,22 +27,26 @@ export default class StyleRuleManager extends EventEmitter {
...
-        if (suppressSubscriptionOnEdit) {
-            this.openmct.editor.on('isEditing', this.toggleSubscription);
-            this.isEditing = this.openmct.editor.editing;
-        }
 
         if (styleConfiguration) {
             this.initialize(styleConfiguration);
             if (styleConfiguration.conditionSetIdentifier) {
-                this.openmct.time.on("bounds", this.refreshData);
+                this.openmct.time.on("bounds", (bounds, isTick) => {
```
Comment (scottbell) [inline src/plugins/condition/StyleRuleManager.js:34]: using arrow functions in here in lieu of bind:
https://google.github.io/styleguide/jsguide.html#features-functions-arrow-functions

**Comment by scottbell** [comment]
This PR fixes https://github.com/nasa/openmct/issues/4196

File: src/plugins/condition/StyleRuleManager.js (hunk 1 above)
Comment (scottbell) [reply src/plugins/condition/StyleRuleManager.js:34]: I was also surprised

**Comment by scottbell** [comment]
Do we care that the `node10-chrome` build isn't working? I don't think node 10 has been supported for over a year. If a customer is using it though, I can go hunt down why it's failing though.

File: src/plugins/condition/StyleRuleManager.js (hunk 1 above)
Comment (akhenry) [reply src/plugins/condition/StyleRuleManager.js:34]: This is going to create a memory leak because it's not being removed in `destroy()`. Being an anonymous function makes it hard to remove as well, which I think is why this was a bound, named function. I also agree that binding should work here, and we should figure out why it is apparently not.

File: src/plugins/condition/StyleRuleManager.js [hunk 2]
```diff
@@ -27,22 +27,26 @@ export default class StyleRuleManager extends EventEmitter {
...
+                    this.refreshData(bounds, isTick);
+                });
                 this.subscribeToConditionSet();
             } else {
                 this.applyStaticStyle();
             }
         }
+
+        if (suppressSubscriptionOnEdit) {
+            this.openmct.editor.on('isEditing', (isEditing) => {
```
Comment (akhenry) [inline src/plugins/condition/StyleRuleManager.js:44]: This is also going to create a memory leak. Also needs to be cleaned up in `destroy()`.

File: src/plugins/condition/StyleRuleManager.js [hunk 3]
```diff
@@ -27,22 +27,26 @@ export default class StyleRuleManager extends EventEmitter {
...
+                this.toggleSubscription(isEditing);
+            });
+            this.isEditing = this.openmct.editor.editing;
```
Comment (akhenry) [inline src/plugins/condition/StyleRuleManager.js:47]: Should use the getter function for this `this.openmct.editor.isEditing()`. At some point someone mistakenly referenced the underlying variable, instead of using the getter, and that code has been used as a reference for a lot of subsequent code.

**Review by akhenry — CHANGES_REQUESTED** [review]

File: src/plugins/condition/StyleRuleManager.js (hunk 1 above)
Comment (scottbell) [reply src/plugins/condition/StyleRuleManager.js:34]: Ok! I’ll take a look

File: src/plugins/condition/StyleRuleManager.js [hunk 4]
```diff
@@ -27,24 +27,32 @@ export default class StyleRuleManager extends EventEmitter {
         super();
         this.openmct = openmct;
         this.callback = callback;
+        this.suppressSubscriptionOnEdit = suppressSubscriptionOnEdit;
```
Comment (scottbell) [inline src/plugins/condition/StyleRuleManager.js:30]: keeping this around so we can resubscribe properly after a destroy

File: src/plugins/condition/StyleRuleManager.js [hunk 5]
```diff
@@ -27,24 +27,32 @@ export default class StyleRuleManager extends EventEmitter {
...
         this.refreshData = this.refreshData.bind(this);
         this.toggleSubscription = this.toggleSubscription.bind(this);
-        if (suppressSubscriptionOnEdit) {
-            this.openmct.editor.on('isEditing', this.toggleSubscription);
-            this.isEditing = this.openmct.editor.editing;
-        }
+        this.addBoundsAndEditSubscriptions(styleConfiguration);
```
Comment (scottbell) [inline src/plugins/condition/StyleRuleManager.js:33]: moving subscriptions for bounds and editing to its own function

File: src/plugins/condition/StyleRuleManager.js [hunk 6]
```diff
@@ -27,24 +27,32 @@ export default class StyleRuleManager extends EventEmitter {
...
             if (styleConfiguration.conditionSetIdentifier) {
-                this.openmct.time.on("bounds", this.refreshData);
                 this.subscribeToConditionSet();
             } else {
                 this.applyStaticStyle();
             }
         }
     }
 
+    addBoundsAndEditSubscriptions(styleConfiguration) {
```
Comment (scottbell) [inline src/plugins/condition/StyleRuleManager.js:45]: no arrow functions 😀
I've also checked the length of the listeners, and the number of StyleRuleManager listeners for the editor remains constant.

File: src/plugins/condition/StyleRuleManager.js [hunk 7]
```diff
@@ -120,6 +128,7 @@ export default class StyleRuleManager extends EventEmitter {
                 //Only resubscribe if the conditionSet has changed.
                 if (isNewConditionSet) {
                     this.subscribeToConditionSet();
+                    this.addBoundsAndEditSubscriptions(styleConfiguration);
```
Comment (scottbell) [inline src/plugins/condition/StyleRuleManager.js:131]: ensure we only add subscriptions when we have a new condition set. this goes for bounds and edit subscriptions too

File: src/plugins/condition/StyleRuleManager.js [hunk 8]
```diff
@@ -182,7 +191,6 @@ export default class StyleRuleManager extends EventEmitter {
 
     destroy() {
         if (this.stopProvidingTelemetry) {
-
             this.stopProvidingTelemetry();
             delete this.stopProvidingTelemetry;
         }
```
Comment (scottbell) [inline src/plugins/condition/StyleRuleManager.js:196]: Just below here is the source of the issue. When `destroy` is called on the `StyleRuleManager`, it unsubscribes from both bounds and editing. This happens if we flip to another component. If `destroy` is run, and the listeners unsubscribe themselves. If we flip back to this component, the constructor isn't called again, so we never resubscribe.

Comment (shefalijoshi) [reply src/plugins/condition/StyleRuleManager.js:196]: Good catch! If this is the issue, then the fix should be in ObjectView.vue. When we navigate to a different object, the ObjectView changes the `currentView`. So we should be tearing down StyleRuleManager when this happens.

I recommend reverting all other changes in this PR and adding the following code here: https://github.com/nasa/openmct/blob/1.7.8/src/ui/components/ObjectView.vue#L120

`        if (this.styleRuleManager) {
            this.styleRuleManager.destroy();
            delete this.styleRuleManager;
        }`

Comment (scottbell) [reply src/plugins/condition/StyleRuleManager.js]: A much simpler fix! Thank you @shefalijoshi

**Review by shefalijoshi — APPROVED** [review]
Nice! Thank you.

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Appropriate unit tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Commit messages meet standards?
* [ ] Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled `bug`? (only applicable if this PR is for a bug fix)
* [ ] List of Acceptance Tests Performed.
