### PR TITLE
fix(#6812): Align Plot and Plan X-Axes in Time Strips

### LINKED ISSUE #6812: Plots in Time Strip are not aligning properly with Plans
#### Summary
In Testathon 7/19/23, when a plot view is in a Time Strip with a Plan, it's not aligning properly with the Plan in time due to the plot's Y axis: 

Screen Shot 2023-07-19 at 11 02 58 AM

#### Expected Behavior
The Time Strip is supposed to include any included plot's Y axes width into its offset calculation:

image

#### Environment

* Open MCT Version:  3.0.0 SNAPSHOT
* Deployment Type:  /latest, /testathon
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by shefalijoshi**
Closes #6812 

### Describe your changes:
Remove use of props to share tick widths between components
Use a composable to manage alignment state of left, right ticks for plots instead

- Parents register alignment composables with the path
- Children update alignment based on the path as well
- Y axes listen for changes to alignment and apply those as computed properties to adjust left/right styles

Updated the following components to use the new composable 

- Plots
- Stacked Plots
- Plans
- Time strip
- Time system axis

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this a [notable change](../docs/src/process/release.md) that will require a special callout in the release notes? For example, will this break compatibility with existing APIs or projects that consume these plugins?

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Has this been smoke tested?
* [x] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [x] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [x] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?

### CODE REVIEW

File: src/plugins/plan/components/ActivityTimeline.vue [hunk 1]
```diff
@@ -92,13 +92,17 @@
 </template>
 
 <script>
+import { inject } from 'vue';
+
 import SwimLane from '@/ui/components/swim-lane/SwimLane.vue';
 
+import { useAlignment } from '../../../ui/composables/alignmentContext';
```
Comment (ozyx) [inline src/plugins/plan/components/ActivityTimeline.vue:99]:
```suggestion
import { useAlignment } from '../../../ui/composables/alignmentContext.js';
```

File: src/plugins/timeline/TimelineViewLayout.vue [hunk 2]
```diff
@@ -70,6 +72,14 @@ export default {
     SwimLane
   },
   inject: ['openmct', 'domainObject', 'composition', 'objectPath'],
+  setup() {
+    const domainObject = inject('domainObject');
+    const path = inject('objectPath');
```
Comment (ozyx) [inline src/plugins/timeline/TimelineViewLayout.vue:77]:
```suggestion
    const objectPath = inject('objectPath');
```

File: src/ui/composables/alignmentContext.js [hunk 3]
```diff
@@ -0,0 +1,118 @@
...
+/* eslint-disable func-style */
+
+import { onBeforeUnmount, ref } from 'vue';
+
+/**
+ * Registers an event listener on the specified target and automatically removes it when the
+ * component is unmounted.
+ * This is a Vue composition API utility function.
+ * @param {EventTarget} path - The target to attach the event listener to.
+ */
```
Comment (ozyx) [inline src/ui/composables/alignmentContext.js:31]: docs need updatin'

**Review by ozyx — CHANGES_REQUESTED** [review]
Kinda half way through a review right now, but I decided to smoke test and I'm still seeing misalignment--


https://github.com/nasa/openmct/assets/9259993/395cedff-2a4a-4354-9d58-1b877498f08f

**Comment by shefalijoshi** [comment]
Snapshot / Visual test

- Test suite for time strip/ time line test with Gantt chart and add telemetry with 2 left and 1 right y-axes
- Large time conductor bounds
- ITC on and off

File: src/plugins/plot/MctPlot.vue [hunk 4]
```diff
@@ -425,6 +396,7 @@ export default {
     });
   },
   beforeUnmount() {
+    this.resetAlignment();
```
Comment (ozyx) [inline src/plugins/plot/MctPlot.vue:399]: Let's move this to an `onBeforeUnmount()` hook in the composable itself. This would eliminate the need to call it explicitly in every component that uses it. Instead, it would be called automatically on component unmount for any component using it.

File: src/plugins/plot/MctTicks.vue [hunk 5]
```diff
@@ -73,14 +73,17 @@
...
+import { useAlignment } from '../../ui/composables/alignmentContext.js';
 import configStore from './configuration/ConfigStore.js';
 import eventHelpers from './lib/eventHelpers.js';
 import { getFormattedTicks, getLogTicks, ticks } from './tickUtils.js';
 
 const SECONDARY_TICK_NUMBER = 2;
 
 export default {
-  inject: ['openmct', 'domainObject'],
+  inject: ['openmct', 'domainObject', 'path'],
```
Comment (ozyx) [inline src/plugins/plot/MctTicks.vue:86]: let's call this `objectPath`, to align with the type that we've defined in the object API

File: src/plugins/plot/MctTicks.vue [hunk 6]
```diff
@@ -132,6 +147,10 @@ export default {
     this.updateTicks();
   },
   beforeUnmount() {
+    this.removeAlignment({
+      yAxisId: this.axisId,
+      updateObjectPath: this.path
+    });
```
Comment (ozyx) [inline src/plugins/plot/MctTicks.vue:153]: we should move this to a `onBeforeUnmount()` hook in the composable itself. Composables reduce the need for boilerplate in components by encapsulating the hook logic entirely within the composable.

File: src/plugins/plot/axis/YAxis.vue [hunk 7]
```diff
@@ -81,46 +84,30 @@ export default {
   components: {
     MctTicks
   },
-  inject: ['openmct', 'domainObject'],
+  inject: ['openmct', 'domainObject', 'path'],
```
Comment (ozyx) [inline src/plugins/plot/axis/YAxis.vue:87]: `objectPath`

File: src/plugins/plot/axis/YAxis.vue [hunk 8]
```diff
@@ -265,10 +254,7 @@ export default {
       }
     },
     onTickWidthChange(data) {
-      this.$emit('plot-y-tick-width', {
-        width: data.width,
-        yAxisId: this.id
-      });
+      this.selfTickWidth = data.width;
```
Comment (ozyx) [inline src/plugins/plot/axis/YAxis.vue:257]: nice!

File: src/plugins/plot/stackedPlot/StackedPlot.vue [hunk 9]
```diff
@@ -283,12 +267,8 @@ export default {
       });
     },
 
-    resetTelemetryAndTicks(domainObject) {
+    resetTelemetry(domainObject) {
```
Comment (ozyx) [inline src/plugins/plot/stackedPlot/StackedPlot.vue:270]: awesome

File: src/plugins/timeline/TimelineViewProvider.js [hunk 10]
```diff
@@ -51,8 +51,8 @@ export default function TimelineViewProvider(openmct) {
               provide: {
                 openmct,
                 domainObject,
-                composition: openmct.composition.get(domainObject),
-                objectPath
+                path: objectPath,
```
Comment (ozyx) [inline src/plugins/timeline/TimelineViewProvider.js:54]: let's just provide `objectPath` so it's clear what kind of data structure it is

File: src/plugins/timeline/TimelineViewLayout.vue [hunk 11]
```diff
@@ -105,7 +120,7 @@ export default {
     addItem(domainObject) {
       let type = this.openmct.types.get(domainObject.type) || unknownObjectType;
       let keyString = this.openmct.objects.makeKeyString(domainObject.identifier);
-      let objectPath = [domainObject].concat(this.objectPath.slice());
+      let objectPath = [domainObject].concat(this.path.slice());
```
Comment (ozyx) [inline src/plugins/timeline/TimelineViewLayout.vue:123]: we can do something like this to keep them distinct
```suggestion
      let newObjectPath = [domainObject].concat(this.objectPath.slice());
```

File: src/ui/composables/alignmentContext.js [hunk 12]
```diff
@@ -0,0 +1,131 @@
...
+
+/**
+ * Manages alignment for multiple y axes given an object path
+ * This is a Vue composition API utility function.
+ * @param {Object} targetObject - The target to attach the event listener to.
+ * @param {Array} path - The path of the target object.
+ * @param {Object} openmct - The open mct API.
+ */
+
+const alignmentMap = {};
```
Comment (ozyx) [inline src/ui/composables/alignmentContext.js:34]: nitpick, but we can get a small perf boost from using the built in `Map()` data structure

File: src/ui/composables/alignmentContext.js [hunk 13]
```diff
@@ -0,0 +1,131 @@
...
+  };
+
+  /**
+   * Update widths of a y axis given the id and path. The path is used to determine which ancestor should hold the alignment
+   * @param {Object: width, yAxisId, updateObjectPath} the width of the y-axis, yAxisId of the tick bar, path of the axis being updated
+   */
+  const update = ({ width, yAxisId, updateObjectPath, type } = {}) => {
+    const key = getAlignmentKeyForPath(updateObjectPath);
+    if (key) {
+      if (alignmentMap[alignmentKey].value.axes[yAxisId] === undefined) {
```
Comment (ozyx) [inline src/ui/composables/alignmentContext.js:121]: We could use some conditional chaining to ensure this doesn't throw if it ends up undefined for any reason along the way:
```suggestion
      if (alignmentMap[alignmentKey].value?.axes?.[yAxisId] === undefined) {
```

File: src/ui/composables/alignmentContext.js [hunk 14]
```diff
@@ -0,0 +1,121 @@
...
+        .reverse()
+        // find a match
+        .find((keyString) => {
+          return keys.includes(keyString);
+        })
+    );
+  };
+
+  // Use the furthest ancestor's alignment if it exists, otherwise, use your own
+  let alignmentKey = getAlignmentKeyForPath(path);
```
[the remark this answers is not in the document]
Comment (ozyx) [reply src/ui/composables/alignmentContext.js:57]: We should remove the superfluous args

**Review by ozyx — CHANGES_REQUESTED** [review]
Firstly, awesome work here! I think what you've done here is a really great application of using composables to share state between components. I only have a few suggestions, but I've tested this locally with plans, gantts, timelines (with plans, gantts, and plots) and the timeline seems to be adjusted correctly! 👏

File: src/plugins/plot/MctPlot.vue (hunk 4 above)
Comment (shefalijoshi) [reply src/plugins/plot/MctPlot.vue:399]: The reason I didn't put it in the composable is because the reset only needs to happen at the top level (parent). The children wouldn't reset the alignment state.

File: src/plugins/plot/MctTicks.vue (hunk 6 above)
Comment (shefalijoshi) [reply src/plugins/plot/MctTicks.vue:153]: See comment above. The removing of alignment is specific to the MctTicks component and requires the axisId to be passed in. Maybe I don't completely understand how this would work from within a composable.

File: src/ui/composables/alignmentContext.js [hunk 15]
```diff
@@ -36,32 +36,20 @@ const alignmentMap = new Map();
...
 
-  if (!alignmentKey) {
-    const targetObjectKey = openmct.objects.makeKeyString(targetObject.identifier);
-    alignmentKey = targetObjectKey;
+  if (!alignmentMap.has(alignmentKey)) {
     alignmentMap.set(
-      targetObjectKey,
-      ref({
+      alignmentKey,
+      reactive({
```
Comment (shefalijoshi) [inline src/ui/composables/alignmentContext.js:56]: @ozyx Cool. From what I had read before, reactive() objects cannot be reassigned. Changing their property values should be ok, right?

Comment (ozyx) [reply src/ui/composables/alignmentContext.js:56]: That is correct. Reactive objects cannot be reassigned, but changing their property values is okay. We don't reassign it anywhere in the composable, and when we return the `alignment` object we feed it through the `toRefs()` function which converts reactive objects into objects where each property is a `ref()`. That allows us to destructure the `alignment` object within the setup() function without losing reactivity.

File: src/ui/composables/alignmentContext.js [hunk 16]
```diff
@@ -23,6 +23,7 @@
 
 import { reactive } from 'vue';
 
+const alignmentMap = new Map();
```
Comment (ozyx) [inline src/ui/composables/alignmentContext.js:27]: good catch!

**Review by charlesh88 — CHANGES_REQUESTED** [review]
I don't think this is working properly yet. Here's a screenshot of a Time Strip using a synthed plan and some SWGs:

Screenshot 2024-06-27 at 12 47 38 PM

Time Conductor is set to realtime, 30 secs into future and 30 secs into the past. I'd expect the data display area extents to be exactly the same to the left and right of the "now" line; this is shown with the green arrows and lines. But instead, the area to the left of now is truncated by the width needs of the plot Y axis labels; this is shown with the orange line and arrow. Note that the UTC strip at top is _not_ truncated. 

This leads me to believe that the data is not being aligned properly relative to time, as shown in the UTC lane. It's unclear to me if data is aligning with each other independently of time or not (Plan activities and numeric telemetry SWGs). Even if this is true, the display should still be showing me an equal span of data to either side of the now line given these current settings. 

Let me know if this is unclear or if I'm missing something.

**Comment by shefalijoshi** [comment]
> I don't think this is working properly yet. Here's a screenshot of a Time Strip using a synthed plan and some SWGs:
> Screenshot 2024-06-27 at 12 47 38 PM
> 
> Time Conductor is set to realtime, 30 secs into future and 30 secs into the past. I'd expect the data display area extents to be exactly the same to the left and right of the "now" line; this is shown with the green arrows and lines. But instead, the area to the left of now is truncated by the width needs of the plot Y axis labels; this is shown with the orange line and arrow. Note that the UTC strip at top is _not_ truncated.
> 
> This leads me to believe that the data is not being aligned properly relative to time, as shown in the UTC lane. It's unclear to me if data is aligning with each other independently of time or not (Plan activities and numeric telemetry SWGs). Even if this is true, the display should still be showing me an equal span of data to either side of the now line given these current settings.
> 
> Let me know if this is unclear or if I'm missing something.

Good catch. Yes, it looks like the timesystem axis is not aligned properly. I'll take a look.

**Review by ozyx — CHANGES_REQUESTED** [review]
Looks good from a smoke-test / visual standpoint. Tested with a timeline containing a plan, gantt chart (with same plan) and a swg. 

Still have some failing tests that need to be fixed, and any additional test coverage we can add

**Review by charlesh88 — APPROVED** [review]
From a visual/functional standpoint tested with synthetic plan in Gantt view, same plan added individually, and sine wave generators: LGTM!

**Review by ozyx — APPROVED** [review]
