### PR TITLE
fix(dialog): empty description

### LINKED ISSUE #6978: Messaging in role selection overlay is incorrect
#### Summary
The role selection overlay text reads as if role selection is solely for operator status. While true, it's for more than that. 

image

#### Expected vs Current Behavior
The title says enough ("Select Role") and the hint text "Please select..." should be removed.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by evenstensberg**
Closes #6978

### Describe your changes:
Dont show description in role dialog

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [x] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/plugins/userIndicator/components/UserIndicator.vue [hunk 1]
```diff
@@ -94,7 +94,7 @@ export default {
         selectionOptions,
         iconClass: 'alert',
         title: 'Select Role',
-        message: 'Please select your role for operator status.',
+        message: '',
```
Comment (unlikelyzero) [inline src/plugins/userIndicator/components/UserIndicator.vue:97]: @evenstensberg would you mind adding a unit, e2e, or visual test to cover this area for regressions?

Comment (evenstensberg) [reply src/plugins/userIndicator/components/UserIndicator.vue:97]: I wish, but I can't reproduce in the UI as I don't know how to get to the user indicator UI. You could push to this branch though

Comment (ozyx) [reply src/plugins/userIndicator/components/UserIndicator.vue:97]: @evenstensberg Check out the tests in [this suite](https://github.com/nasa/openmct/blob/master/e2e/tests/functional/plugins/operatorStatus/operatorStatus.e2e.spec.js) for some examples.

Comment (evenstensberg) [reply src/plugins/userIndicator/components/UserIndicator.vue:97]: There's a test suit within the folder the component was created. Adding a test is easy, but I can't find any reproduction step to get to the role view

Comment (ozyx) [reply src/plugins/userIndicator/components/UserIndicator.vue:97]: I'll take a look today and update in this thread with instructions

Comment (ozyx) [reply src/plugins/userIndicator/components/UserIndicator.vue:97]: @evenstensberg 

First, install the `ExampleUser` and `OperatorStatus` plugins by adding the following to `index.html`:

```html
openmct.install(openmct.plugins.OperatorStatus());
openmct.install(openmct.plugins.example.ExampleUser());
```

Then you should be able to access the role selection dialog via the button in the indicator bar:


https://github.com/nasa/openmct/assets/9259993/ffcc89fc-682a-43dd-a1d3-e08fa8226583

Comment (evenstensberg) [reply src/plugins/userIndicator/components/UserIndicator.vue:97]: Thanks @ozyx ! PTAL

File: e2e/tests/functional/plugins/operatorStatus/operatorStatus.e2e.spec.js [hunk 2]
```diff
@@ -63,6 +63,11 @@ test.describe('Operator Status', () => {
     await expect(page.locator('.c-status-poll-panel')).toBeVisible();
   });
 
+  // Description should be empty https://github.com/nasa/openmct/issues/6978
+  test('no description in role selection', async ({ page }) => {
+    await expect(page.locator('.c-message__action-text')).toBeHidden();
```
Comment (ozyx) [inline e2e/tests/functional/plugins/operatorStatus/operatorStatus.e2e.spec.js:68]: Couple suggestions here.

Instead of creating a whole new test for this, let's just add an assertion to the `beforeEach` since that's where we open the user role dialog. Let's also assert that the text is an empty string.

**Review by ozyx — CHANGES_REQUESTED** [review]

File: e2e/tests/functional/plugins/operatorStatus/operatorStatus.e2e.spec.js (hunk 2 above)
Comment (evenstensberg) [reply e2e/tests/functional/plugins/operatorStatus/operatorStatus.e2e.spec.js]: Done! Due the nature of the `v-if` conditional, the section isn't rendered, so it won't be visible 
Screenshot 2023-08-28 at 22 23 32

Comment (ozyx) [reply e2e/tests/functional/plugins/operatorStatus/operatorStatus.e2e.spec.js]: That works!

Comment (evenstensberg) [reply e2e/tests/functional/plugins/operatorStatus/operatorStatus.e2e.spec.js]: Good stuff. Lmk if you need anything else

**Review by ozyx — APPROVED** [review]
LGTM. Nice work!
