### PR TITLE
Check that mutation happens only if model has changed

### LINKED ISSUE #3608: Timers not updating for multiple users as expected
Problem has been recurring on hulk/viper during driving sims.

### Steps to reproduce
1. Two users, or Open MCT running in two different browser windows.
2. Create a Timer.
3. Get Timer in view for both users or in both browser windows.
4. User 1 starts the Timer. User 2 should confirm they see the Timer start.
5. User 1 resets Timer. User 2 expects their view of the Timer to reset, but it doesn't.

The Timer has become an important part of driving sims, used to limit and communicate off-optimal sun angle driving intervals between Flight and drivers, therefore this is a blocker.

### LINKED ISSUE #3867: [Persistence API] Progress modal should be dismissed on persistence error
## Overview
On create object, if there is a persistence error, the Saving modal never gets dismissed and user is forced to refresh app to regain control.

## Expected Behavior
Persistence errors should be handled gracefully. Notification given to user. User stays calm and carries on.

## Steps to Reproduce
1. Create an object and get a persistence error (ie. simultaneous create in shared environment)
2. That's it you're stuck

Test

### PR DESCRIPTION
**Pull request by shefalijoshi**
When a mutation is requested, the LegacyObjectAPIInterceptor triggers a second mutatation request - ensure that the model for this 2nd request has some diff from the current model before saving the object.
Also revert a change where the document revision was not being updated on CouchDB GET calls. This could result in some 409 Conflict errors, but that is unavoidable right now and needs to be addressed later by implementing document pushes from couchDB.

Resolves #3608
Also resolves #3867
May address #3868

### Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? N/A
3. Command line build passes? Y
4. Changes have been smoke-tested? Y
5. Testing instructions included? Y

### CODE REVIEW

File: platform/core/src/capabilities/MutationCapability.js [hunk 1]
```diff
@@ -141,11 +141,17 @@ define(
                 if (mutationResult !== false) {
                     // Copy values if result was a different object
                     // (either our clone or some other new thing)
-                    if (model !== result) {
+                    let modelHasChanged = JSON.stringify(model) !== JSON.stringify(result);
```
Comment (akhenry) [inline platform/core/src/capabilities/MutationCapability.js:144]: Comparing stringified objects will probably work just fine in this case, but there are edge cases where it will fail as a general method for comparing objects. If the order of properties changes, but the values of the properties remain the same then a string comparison will detect a change, even though the objects are functionally equivalent. This might happen if an attribute is deleted, and then assigned the same value again.

Again, for this purpose it probably doesn't matter, however we might consider using `_.equals` as we have in other parts of the code, which will handle this edge case.

**Review by akhenry — CHANGES_REQUESTED** [review]
One small suggestion otherwise looks great, thanks!

**Review by murakobardenas — APPROVED** [review]

File: platform/core/src/capabilities/MutationCapability.js (hunk 1 above)
Comment (shefalijoshi) [reply platform/core/src/capabilities/MutationCapability.js]: Done.

**Review by akhenry — DISMISSED** [review]
Looks good to me, thanks @shefalijoshi !

### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N/A - small change
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
5. Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue) Y

**Comment by akhenry** [comment]
RUH ROH. Looks like there are some linting errors. Should be an easy fix though.

**Review by akhenry — APPROVED** [review]

**Comment by akhenry** [comment]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
5. Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue) Y
