### PR TITLE
[Tabs View] add ability to remove tabs from tabs view interface (#3147)

### LINKED ISSUE #3147: [Tabs View] Unable to remove tab from tabs view interface
There's no clear way to remove a tab from the tabs view object.

Steps to reproduce:
1. Add one or more tabs to tabs view object and save.
2. Go into edit mode and try and remove a tab from the tabs view.

### PR DESCRIPTION
**Pull request by johnriedel**
Fixes #3147 

* an "X" on each tab is visible in edit mode

Author Checklist:
  1. Changes address original issue? Yes
  2. Unit tests included and/or updated with changes? No
  3. Command line build passes? Yes
  4. Changes have been smoke-tested? Yes
  5. Testing instructions included? Yes

Test:
1. add one or more tabs to tabe view object and save
2. ensure there are no "X" icons on the tabs when not in edit mode
3. go into edit mode and ensure each tab has an "X"
4. Click the "X" to remove a tab and ensure a confirmation dialog appears.
5. Ensure the dialog Cancel button dismisses the dialog.
6. Ensure the dialog OK button removes the tab from the tabs view UI and from the object tree
7. Cancel tab removal by clicking the "X" in the tabs view toolbar and ensure the tab reappears in the tabs view UI and in the tabs view object tree
8. Remove a tab and save the tabs view this time. Ensure the tab is removed from the tabs view UI and the object is removed from the tabs view object tree.

Screenshot from 2020-07-01 22-08-56

Screenshot from 2020-07-01 22-16-19

### CODE REVIEW

File: src/plugins/tabs/components/removeDialog.js [hunk 1]
```diff
@@ -0,0 +1,34 @@
+export default class RemoveDialog {
```
Comment (deeptailor) [inline src/plugins/tabs/components/removeDialog.js:1]: This adds a lot more complexity, than just calling openmct.overlays.dialog from tabs.vue

File: src/plugins/tabs/components/tabs.vue [hunk 2]
```diff
@@ -135,15 +163,23 @@ export default {
...
 
+            let tabToBeRemoved = this.tabsList[pos];
             this.tabsList.splice(pos, 1);
 
             if (this.isCurrent(tabToBeRemoved)) {
                 this.showTab(this.tabsList[this.tabsList.length - 1], this.tabsList.length - 1);
             }
+
+            this.openmct.objects.get(identifier).then((childDomainObject) => {
+                this.RemoveAction.removeFromComposition(this.internalDomainObject, childDomainObject);
```
Comment (deeptailor) [inline src/plugins/tabs/components/tabs.vue:181]: Instead of importing the remove Action here, we can just call removeItem from the click handler, and we can add a flag in removeAction to say removeFromComposition, then we can call this.composition.remove(this.domainObject, identifierToBeRemoved) if the flag (removeFromComposition) is true.

Comment (deeptailor) [reply src/plugins/tabs/components/tabs.vue:181]: Openmct.objects.get adds overhead that we should not need when removing an item

File: src/plugins/tabs/components/tabs.vue [hunk 3]
```diff
@@ -118,6 +125,27 @@ export default {
 
             this.currentTab = tab;
         },
+        showRemoveDialog(tab, index) {
+            if(!this.tabsList[index]) {
```
Comment (deeptailor) [inline src/plugins/tabs/components/tabs.vue:129]: We can just call openmct.overlays.dialog from here, to remove the extra complexity of creating a new RemoveDialog class

**Comment by johnriedel** [comment]
Thanks for the helpful feedback @deeptailor . Code changes implemented.

**Comment by deeptailor** [comment]
@johnriedel - Thanks for the updates, this looks great. I will let our Lead UX designer @charlesh88 take a look and approve. Charles, just need your UX approval and it should be good to go.

**Comment by johnriedel** [comment]
Many thanks @charlesh88 ! Yes, of course feel free to change/push whatever you'd like.

**Comment by charlesh88** [comment]
> Many thanks @charlesh88 ! Yes, of course feel free to change/push whatever you'd like.

Fantastic, thanks. Just pushed to `fix-3147`.

**Comment by deeptailor** [comment]
@johnriedel - I made some changes to the way tabs view get the isEditing prop from openmct. If you update your PR with the changes in Tabs.vue, I will review and merge

**Comment by johnriedel** [comment]
Hi @deeptailor . I resolved the two conflicts and recommitted. If I messed-up something with the way I resolved the conflict, please let me know. Thanks!

File: src/plugins/tabs/components/tabs.vue [hunk 4]
```diff
@@ -28,19 +28,12 @@
...
-                >
-                    <span class="is-missing__indicator"
-                          title="This item is missing"
-                    ></span>
-                </div>
-                <span class="c-button__label c-object-label__name">{{ tab.domainObject.name }}</span>
-            </div>
-        </button>
+            <span class="c-button__label c-tabs-view__tab__label">{{ tab.domainObject.name }}</span>
+            <button v-if="openmct.editor.isEditing()"
```
Comment (deeptailor) [inline src/plugins/tabs/components/tabs.vue:32]: since we are getting a prop called isEditing, we can just use that here, instead of checking the editor

File: src/plugins/tabs/components/tabs.vue [hunk 5]
```diff
@@ -153,6 +148,39 @@ export default {
...
+
+            let self = this;
+            let prompt = this.openmct.overlays.dialog({
+                iconClass: 'alert',
+                message: `This action will remove this tab from the Tabs Layout. Do you want to continue?`,
+                buttons: [
+                    {
+                        label: 'Ok',
+                        emphasis: 'true',
+                        callback: function () {
```
Comment (deeptailor) [inline src/plugins/tabs/components/tabs.vue:167]: we can use es6 Arrow functions here, this way we dont have to reassign this to self

File: src/plugins/tabs/components/tabs.vue (hunk 4 above)
Comment (johnriedel) [reply src/plugins/tabs/components/tabs.vue]: Got it. Thanks for the heads-up.

File: src/plugins/tabs/components/tabs.vue (hunk 5 above)
Comment (johnriedel) [reply src/plugins/tabs/components/tabs.vue]: Code updated to use ES6 arrow funcs.

**Comment by johnriedel** [comment]
Hey @deeptailor . Code updates are complete.

**Comment by deeptailor** [comment]
## Reviewer Checklist
Changes appear to address issue? Yes
Appropriate unit tests included? N/A
Code style and in-line documentation are appropriate? Yes
Commit messages meet standards? Yes
Has associated issue been labelled unverified? (only applicable if this PR closes the issue) Yes
