### PR TITLE
Bar graph review comment fixes

### LINKED ISSUE #4229: Address review comments for Bar Graphs
Review comments in https://github.com/nasa/openmct/pull/4221 need to be addressed and tested before 1.7.8 is closed out.

- [x] Remove Spectral Generator metadata and provider from example generators.
- [x] Remove Spectral Aggregate metadata and provider from example generators.
- [x] Remove Spectral plot related code - maybe keep it in a separate branch if needed.

- [x] Add an alias for plotly-basic in webpack.config
- [x] Create a new folder under plugins to hold non-time domain plots
- [x] In the BarGraphCompositionPolicy, rename hasAggregateDomainAndRange to hasRange
- [x] Use v-on for event handling: See https://github.com/nasa/openmct/pull/4221/files/a1a7e73e3383152727afbdacc0ffbb7cf4dd84ab#r711627257
- [x] Remove the use of `this.currentDomainObject` and it's observer from the BarGraphView
- [x] Remove the listener for `openmct.time.clock` from BarGraphView
- [x] Resolve objects.mutate usage. See here: https://github.com/nasa/openmct/pull/4221/files/a1a7e73e3383152727afbdacc0ffbb7cf4dd84ab#r711631275
- [x] Remove telemetryAPI request options. https://github.com/nasa/openmct/pull/4221/files/a1a7e73e3383152727afbdacc0ffbb7cf4dd84ab#r711633345
- [x] Check that data returned by the telemetry request and subscribe calls are within the time bounds provided: https://github.com/nasa/openmct/pull/4221/files/a1a7e73e3383152727afbdacc0ffbb7cf4dd84ab#r711632679
- [x] Format data before adding it to the traces for display

### PR DESCRIPTION
**Pull request by scottbell**
Resolves #4229

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?

### Author Checklist

* [x] Changes address original issue?
* [x] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### CODE REVIEW

File: src/plugins/charts/pluginSpec.js [hunk 1]
```diff
@@ -0,0 +1,320 @@
...
+
+        it('is creatable', () => {
+            const objectDef = openmct.types.get(BAR_GRAPH_KEY).definition;
+            expect(objectDef.creatable).toEqual(mockObject.creatable);
+        });
+    });
+
+    describe("The bar graph composition policy", () => {
+
+        it("allows composition for telemetry that contain at least one range", () => {
```
Comment (shefalijoshi) [inline src/plugins/charts/pluginSpec.js:246]: Here, instead of directly invoking composition.checkPolicy, let's invoke composition.add on the bar graph domain object.

File: src/plugins/charts/inspector/SeriesOptions.vue [hunk 2]
```diff
@@ -80,25 +85,46 @@ export default {
...
-                this.currentColor = this.domainObject.configuration.barStyles[this.key].color;
-                this.name = this.domainObject.configuration.barStyles[this.key].name;
+        async initColor() {
+            // this is called before the plot is initialized
+            if (!this.domainObject.configuration.barStyles) {
+                this.domainObject.configuration.barStyles = {};
+                this.domainObject.configuration.barStyles.series = {};
+            }
+
+            const telemetryObject = await this.openmct.objects.get(this.key);
```
Comment (shefalijoshi) [inline src/plugins/charts/inspector/SeriesOptions.vue:103]: Wondering if there is a way around having to call objects.get(...) here...probably not? Let me think.

**Review by shefalijoshi — CHANGES_REQUESTED** [review]
Really cool!

File: src/plugins/charts/inspector/SeriesOptions.vue [hunk 3]
```diff
@@ -80,25 +85,46 @@ export default {
...
     methods: {
-        initColor() {
-            if (this.domainObject.configuration.barStyles && this.domainObject.configuration.barStyles[this.key]) {
-                this.currentColor = this.domainObject.configuration.barStyles[this.key].color;
-                this.name = this.domainObject.configuration.barStyles[this.key].name;
+        async initColor() {
+            // this is called before the plot is initialized
+            if (!this.domainObject.configuration.barStyles) {
+                this.domainObject.configuration.barStyles = {};
+                this.domainObject.configuration.barStyles.series = {};
```
Comment (shefalijoshi) [inline src/plugins/charts/inspector/SeriesOptions.vue:100]: Do we need 2 levels of configuration here? Let's go with `this.domainObject.configuration.seriesStyles[key]` and get rid of `barStyles`.
If we do this, we should also rename the 'barStyles' property here: https://github.com/nasa/openmct/blob/mct4229/src/plugins/charts/plugin.js#L38

**Review by shefalijoshi — CHANGES_REQUESTED** [review]

File: src/plugins/charts/inspector/SeriesOptions.vue (hunk 3 above)
Comment (scottbell) [reply src/plugins/charts/inspector/SeriesOptions.vue:100]: the issue with only one level is i can't listen to just `this.domainObject.configuration.barStyles` for changes, as we've added a key to it, so the events were coming to `this.domainObject.configuration.barStyles[some-random-key]`, and didn't want to listen to all configuration changes. by moving they key to `this.domainObject.configuration.barStyles.series`, we can listen to all to barStyle events, but not listen to all configuration events.

File: src/plugins/charts/BarGraphView.vue [hunk 4]
```diff
@@ -93,33 +80,9 @@ export default {
     methods: {
         addTelemetryObject(telemetryObject) {
             const key = this.openmct.objects.makeKeyString(telemetryObject.identifier);
```
Comment (shefalijoshi) [inline src/plugins/charts/BarGraphView.vue:82]: Could we add the name of the telemetry object to `configuration.seriesStyles` when addTelemetryObject happens here?

**Review by shefalijoshi — CHANGES_REQUESTED** [review]

File: src/plugins/charts/inspector/SeriesOptions.vue (hunk 2 above)
Comment (scottbell) [reply src/plugins/charts/inspector/SeriesOptions.vue:103]: talked about storing it in the domainObject.configuration.barStyles instead when doing an addTelemetry in the plot, then reading it here in the inspector.

File: src/plugins/charts/inspector/SeriesOptions.vue [hunk 5]
```diff
@@ -72,33 +77,53 @@ export default {
...
         }
     },
     methods: {
-        initColor() {
-            if (this.domainObject.configuration.barStyles && this.domainObject.configuration.barStyles[this.key]) {
-                this.currentColor = this.domainObject.configuration.barStyles[this.key].color;
-                this.name = this.domainObject.configuration.barStyles[this.key].name;
+        initColorAndName() {
+            // this is called before the plot is initialized
+            if (!this.domainObject.configuration.barStyles) {
```
Comment (shefalijoshi) [inline src/plugins/charts/inspector/SeriesOptions.vue:98]: This should never happen since the barStyles object is initialized in plugin.js

File: src/plugins/charts/inspector/SeriesOptions.vue [hunk 6]
```diff
@@ -72,33 +77,53 @@ export default {
...
+                this.domainObject.configuration.barStyles = {};
+            }
+
+            if (!this.domainObject.configuration.barStyles.series) {
+                this.domainObject.configuration.barStyles.series = {};
```
Comment (shefalijoshi) [inline src/plugins/charts/inspector/SeriesOptions.vue:103]: This should never happen if the barStyles.series object is initialized in plugin.js

**Review by shefalijoshi — CHANGES_REQUESTED** [review]
Some small changes in `initialize` of the plugin

File: src/plugins/charts/plugin.js [hunk 7]
```diff
@@ -0,0 +1,51 @@
...
+        openmct.types.addType(BAR_GRAPH_KEY, {
+            key: BAR_GRAPH_KEY,
+            name: "Bar Graph",
+            cssClass: "icon-bar-chart",
+            description: "View data as a bar graph. Can be added to Display Layouts.",
+            creatable: true,
+            initialize: function (domainObject) {
+                domainObject.composition = [];
+                domainObject.configuration = {
+                    barStyles: {}
```
[the remark this answers is not in the document]
Comment (scottbell) [reply src/plugins/charts/plugin.js:38]: Cool! I didn't think of adding it here.

File: src/plugins/charts/BarGraphView.vue [hunk 8]
```diff
@@ -206,32 +178,40 @@ export default {
         removeTelemetryObject(identifier) {
             const key = this.openmct.objects.makeKeyString(identifier);
             delete this.telemetryObjects[key];
-            if (this.domainObject.configuration.barStyles[key]) {
-                delete this.domainObject.configuration.barStyles[key];
+            if (this.telemetryObjectFormats && this.this.telemetryObjectFormats[key]) {
```
Comment (shefalijoshi) [inline src/plugins/charts/BarGraphView.vue:181]: Typo here and in the delete - `this.this.telemetryObjectFormats`

**Review by shefalijoshi — CHANGES_REQUESTED** [review]

**Review by shefalijoshi — APPROVED** [review]
### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Appropriate unit tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Commit messages meet standards?
* [x] Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue)
* [x] Has associated issue been labelled `bug`? (only applicable if this PR is for a bug fix)
* [ ] List of Acceptance Tests Performed.
