### PR TITLE
[Plots, Multiple-Y Axis] Fix for rectangle drawn on each axis

### LINKED ISSUE #6213: [Multiple Y-Axes] Multiple marquees when selecting with multiple series
#### Summary
When making a selection for annotation or a selection for zoom in a plot with multiple series, the marquee seems to be duplicated for each y-axis. This creates a layering effect where the final selection box is very bright.

Screen Shot 2023-01-26 at 5 45 56 PM

Testing Instructions:
1. Create an overlay plot and drop in 2 telemetry sources.
2. Try drawing a marquee to zoom or to annotate the plot. The marquee should not be as dark as in the screenshot above.
3. Try moving the telemetry sources to various plot axes and annotate/zoom again to verify multiple marquees aren't being drawn.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [X] Is there a workaround available?
- [ ] Does this impact a critical component?
- [X] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by khalidadil**
Closes #6213 

### Describe your changes:
Set the first drawable axis as the rectangleAxisId and set rectangles on any other axis to transparent

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [X] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [X] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [X] Command line build passes?
* [X] Has this been smoke tested?
* [X] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [x] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/plugins/plot/chart/MctChart.vue [hunk 1]
```diff
@@ -603,6 +603,9 @@ export default {
             const mainYAxisId = this.config.yAxis.get('id');
             //There has to be at least one yAxis
             const yAxisIds = [mainYAxisId].concat(this.config.additionalYAxes.map(yAxis => yAxis.get('id')));
+            // Save the first drawable y-axis so that we only draw the marquee on that axis
+            this.firstDrawableAxis = yAxisIds.filter(axisId => this.canDraw(axisId))[0];
```
Comment (shefalijoshi) [inline src/plugins/plot/chart/MctChart.vue:607]: This works but the canDraw condition is now checked twice which is unnecessary.
Perhaps something like this?
```
            yAxisIds.filter(this.canDraw).forEach((id, yAxisIndex) => {
                    this.updateViewport(id);
                    this.drawSeries(id);
                    if (yAxisIndex === 0) {
                        this.drawRectangles(id);
                    }
                    this.drawHighlights(id);
                    // only draw these in fixed time mode or plot is paused
                    if (this.annotationViewingAndEditingAllowed) {
                        this.drawAnnotatedPoints(id);
                        this.drawAnnotationSelections(id);
                    }
            });
},
```

**Review by shefalijoshi — CHANGES_REQUESTED** [review]

**Review by shefalijoshi — APPROVED** [review]
