### PR TITLE
Fixes for Imagery Snapshotting #3963

### LINKED ISSUE #3963: [Notebook Snapshots] Snapshots of Imagery views have a number of issues
Snapshotting this Imagery telemetry:
Screen Shot 2021-06-22 at 3 21 06 PM

Yields this result, which has a number of problems:
Imagery snapshot problems

- Orange arrows: image is distorted, but should retain original aspect ratio.
- Blue arrow: brightness/contrast controls sort of visible, but should be completely hidden.
- Red arrow: compass rose camera FOV elements (SVG's?) need to be handled so they don't get opaque fills.
- Green arrow: pause/play button is visible, without icon, but should be hidden.

### PR DESCRIPTION
**Pull request by charlesh88**
Fixes #3963. Changes and refactoring for imagery Snapshotting to cope with html2canvas shortcomings. 

### Todos
- [x] Fix linting.
- [x] Make sure test code in Compass.vue is acceptable; change or remove if not.
- [x] Make sure tests aren't broken.
- [x] Add testing notes to original issue.
- [x] Add changes overview to this PR.

### Changes
- Update to latest version of html2canvas 1.0.0-rc7;
- Better sizing and positioning for compass rose element;
- Compass rose rewritten as SVG for compatibility with html2canvas;
- Imagery view now hides local controls, pause button and prev/next arrows when taking a Snapshot;

### All Submissions:
* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?

### Author Checklist
* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### CODE REVIEW

File: src/plugins/imagery/components/Compass/Compass.vue [hunk 1]
```diff
@@ -56,64 +55,47 @@ export default {
...
-
-            return sizedImageDimensions;
-        },
         hasCameraFieldOfView() {
             return this.cameraPan !== undefined && this.cameraAngleOfView > 0;
         },
         // horizontal rotation from north in degrees
         heading() {
-            return this.image.heading;
+            return this.testMode? this.getRandomAngle : this.image.heading;
```
Comment (akhenry) [inline src/plugins/imagery/components/Compass/Compass.vue:84]: I think @nikhilmandlik  has [added some test data to example imagery](https://github.com/nasa/openmct/pull/3999). Maybe we could use that for testing instead of hard-coding it here?

File: src/plugins/imagery/components/Compass/CompassHUD.vue [hunk 2]
```diff
@@ -104,7 +104,10 @@ export default {
         },
         cameraPan: {
             type: Number,
-            required: true
+            required: true,
+            default() {
```
Comment (akhenry) [inline src/plugins/imagery/components/Compass/CompassHUD.vue:108]: If it's a required parameter, then a default value is not needed.

File: src/plugins/imagery/components/Compass/CompassRose.vue [hunk 3]
```diff
@@ -262,20 +205,38 @@ export default {
...
+    },
     methods: {
+        resizeSvg() {
+            const svg = this.$refs.compassRoseSvg;
+            svg.setAttribute('width', this.$refs.compassRoseWrapper.clientWidth);
+            svg.setAttribute('height', this.$refs.compassRoseWrapper.clientHeight);
+        },
         toggleLockCompass() {
-            this.$emit('toggle-lock-compass');
+            console.log(this);
```
Comment (akhenry) [inline src/plugins/imagery/components/Compass/CompassRose.vue:238]: Let's remove this debugging code.

**Review by akhenry — CHANGES_REQUESTED** [review]

File: src/plugins/imagery/components/Compass/Compass.vue (hunk 1 above)
Comment (charlesh88) [reply src/plugins/imagery/components/Compass/Compass.vue:84]: Yes, wasn't aware that @nikhilmandlik had already done that. I'll coordinate with him.

Comment (charlesh88) [reply src/plugins/imagery/components/Compass/Compass.vue]: Fixed

File: src/plugins/imagery/components/Compass/CompassHUD.vue (hunk 2 above)
Comment (charlesh88) [reply src/plugins/imagery/components/Compass/CompassHUD.vue:108]: @nikhilmandlik to address

File: src/plugins/imagery/components/Compass/CompassRose.vue (hunk 3 above)
Comment (charlesh88) [reply src/plugins/imagery/components/Compass/CompassRose.vue]: Done.

**Review by akhenry — APPROVED** [review]

**Comment by akhenry** [comment]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N/A - Visual fixes
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
5. Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue) Y
