### PR TITLE
Plot telem fixes

### LINKED ISSUE #1705: [Telemetry] Real-time updates not occurring?
Observed during internal developer orientation demo 9/12/2017. Created a Fixed Position display with some Sine Wave Generators. A few did not show data (believe this is due to older data model). A newly-created SWG dispalyed data, but did not update in real-time.

image

Plot view of same SWG was strangely truncated and not updating with real-time data

image

Table view of same SWG remained empty

Time conductor was set to Local Clock and UTC

image

### PR DESCRIPTION
**Pull request by larkin**
Fixes #1705 and #1713.

There still appears to be a bug causing plots not to occur for the openmct-tutorial, don't have time to debug right now.  These changes are a good starting point.

# Author Checklist

1. Changes address original issue?  Y
2. Unit tests included and/or updated with changes? Y
3. Command line build passes? Y
4. Changes have been smoke-tested? Y

Ready for review by anyone available.

### CODE REVIEW

File: platform/features/plot/src/policies/PlotViewPolicy.js [hunk 1]
```diff
@@ -30,30 +30,25 @@ define(
...
-        }
+        PlotViewPolicy.prototype.hasNumericTelemetry = function (domainObject) {
+            var adaptedObject = domainObject.useCapability('adapter');
+            var metadata = this.openmct.telemetry.getMetadata(adaptedObject);
+            var rangeValues = metadata.valuesForHints(['range']);
+            if (rangeValues.length === 0) {
+                return false;
+            }
+            return !rangeValues.every(function (value) {
+                return value.format === 'string';
```
Comment (VWoeltjen) [inline platform/features/plot/src/policies/PlotViewPolicy.js]: I think this is an area where our telemetry metadata is underspecified. All this check tells you is that a particularly property is not meant to be formatted with `toString`; we presume that it is plottable because we have an undocumented rule that all telemetry is numeric except for strings. Not sure what a solution should look like. A `numeric` hint would be consistent, but that would be a lot of boilerplate

**Comment by VWoeltjen** [comment]
One review note in there for consideration. My assumption is we'll want to proceed with merge, and maybe file a follow-up, or just keep that in mind (after today's big issue cleaning I'm hesitant to track too many nits)

### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

**Comment by larkin** [comment]
@VWoeltjen we definitely need to finalize formatter apis and expectations.  definitely keeping in mind.  let's not open something new at this time.

File: platform/features/plot/src/policies/PlotViewPolicy.js (hunk 1 above)
Comment (larkin) [reply platform/features/plot/src/policies/PlotViewPolicy.js]: this is here solely so the event message generator doesn't show plots.  because the eventgenerator uses old telemetry metadata, it defines `ranges`.  once transitioned, it won't incorrectly define ranges.
