### PR TITLE
[Dialog Service] Dismiss individual dialogs. Fixes #254

### LINKED ISSUE #254: [UI] Refactor DialogService to allow dismissal of specific dialog instances
The dismiss() method on the DialogService is not connected to the specific dialog previously displayed and creates the opportunity for unusual behavior. I'm picturing some other blocking dialog being implemented in the same way (show the dialog on one event, dismiss it on another); if this were triggered at the same time as this dialog, then it would be very easy to dismiss the wrong dialog.

My thinking is that showBlockingMessage should return something that allows the specific dialog that was just shown to be dismissed. Either an object with a dismiss method, or perhaps just a promise that we could pass into a dialogService.cancel(promise) function (this would allow the other dialogService methods to also be cancelled consistently)

### PR DESCRIPTION
**Pull request by akhenry**
Addresses need to be able to dismiss individual dialogs rather than having a single dismiss function on the DialogService.

## Changes
1. `DialogService.showBlockingMessage()` - Returns an object with a dismiss() function.
2. Refactored code that was using above function
3. Updated tests

### CODE REVIEW

File: example/notifications/src/DialogLaunchController.js [hunk 1]
```diff
@@ -44,30 +44,31 @@ define(
...
-                    unknownDuration: false,
-                    severity: "info",
-                    options: [
-                        {
-                            label: "Cancel Operation",
-                            callback: function () {
-                                $log.debug("Operation cancelled");
-                                dialogService.dismiss();
+                var dialog,
+                    model = {
```
Comment (larkin) [inline example/notifications/src/DialogLaunchController.js]: Note for future, i believe we've changed our style guide regarding combined view statements so this doesn't need to be such a big diff when you have to indent the entire object literal just to combine var statements.

That said, I used the disable whitespace diff option (append ?w=0 to url e.g. https://github.com/nasa/openmct/pull/1063/files?w=0) which nicely hides this.

**Comment by larkin** [comment]
# Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

Small merge conflict but easily resolved.
