### PR TITLE
[Inspector Tabs] Updates

### LINKED ISSUE #7442: Highest priority inspector tab is not auto selected
#### Summary
When an inspector tab has the highest priority and a different tab is currently highlighted, the highest priority tab should be selected by default.

#### Expected vs Current Behavior
The previously highlighted tab stays selected even if it is lower priority than other tabs.

#### Steps to Reproduce
1. View a timelist object with activities listed
2. In the inspector view notice that the `Properties` tab is selected by default. (It should be the `View Properties` tab.
3. Select an activity (row) and notice that an Activity tab is now added to the inspector tabs
4. Notice that the Activity tab is not selected by default and the Properties tab is still selected.

#### Environment

* Open MCT Version: 4.0.0
* Deployment Type: Open MCT VIPER
* OS: All
* Browser: All

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by jvigliotta**
Closes #7442, #7959 
Combination of two similar PR's
- https://github.com/nasa/openmct/pull/7979
- https://github.com/nasa/openmct/pull/7974

### Describe your changes:

Whenever the selection changes, the first tab (highest priority) is auto selected. There may be some cases (editing styles) when we'd want that tab to stay selected as well. Also updates when and where the tabs show based on the items being viewed.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this a [notable change](../docs/src/process/release.md) that will require a special callout in the release notes? For example, will this break compatibility with existing APIs or projects that consume these plugins?

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Has this been smoke tested?
* [x] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [x] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?

### CODE REVIEW

**Comment by charlesh88** [comment]
### Todos
@jvigliotta 
- [ ] Priority doesn't appear to update when switching from browse to edit - it's only triggering on navigation or sub-object selection. So if I'm in the main view of a composable object, and I click to edit it, I'd expect the priority of a tab to be evaluated and for the Inspector to update. We need this to allow Properties as high priority during browse, and low priority when editing.
- [ ] The Styles tab is working oddly now in main views: it's now appearing for some domain objects. I have two Display Layouts and it appears for one but the other:

Screenshot 2025-01-15 at 5 31 55 PM

Screenshot 2025-01-15 at 5 32 08 PM

**Comment by charlesh88** [comment]
Pushed:
- Priorities set for Graph, Lad Table, Scatter Plot, Telem Tables and Time List views.
- Changed several Inspector tab names to 'Config'; e2e tests updated where needed:
  - LAD Table.
  - Time List.
- Created browse mode read-only Inspector views:
  - LAD Table, Lad Table set.
  - Telemetry Table.
- Changed AnnotationsViewProvider.js canView to return false if editor.isEditing.
- Plot plugin.js now adds configuration.objectStyles {} for overlay and stacked plots on initialize.
- FiltersView now displays a message for telem sources that don't have filter criteria available.
- Code cleanup in FiltersInspectorViewProvider.js to remove metadata checks that never evaluated.

**Comment by charlesh88** [comment]
Going through https://docs.google.com/spreadsheets/d/1bSVG-c7V-IvZoiM_gJef8wivOvIvaxByT6pAeTfnNWE/edit?gid=0#gid=0 and the only remaining item is showing the Elements tab in browse mode for Overlay Plots. Per our Teams discussion, @jvigliotta looking into this, and @charlesh88 will approve here once we get that in or determine it's too much effort.

File: src/plugins/displayLayout/components/DisplayLayout.vue [hunk 1]
```diff
@@ -226,6 +226,11 @@ export default {
     this.composition.load();
     this.gridDimensions = [this.$el.offsetWidth, this.$el.scrollHeight];
 
+    // Initialize objectStyles if it doesn't exist for older versions
+    if (!this.domainObject.configuration.objectStyles) {
+      this.domainObject.configuration.objectStyles = {};
```
Comment (akhenry) [inline src/plugins/displayLayout/components/DisplayLayout.vue:231]: See comment above. We don't mutate object models until the user changes something.

File: src/plugins/flexibleLayout/components/FlexibleLayout.vue [hunk 2]
```diff
@@ -158,6 +158,12 @@ export default {
     this.composition.on('remove', this.removeChildObject);
     this.composition.on('add', this.addFrame);
     this.composition.load();
+
+    // Initialize objectStyles if it doesn't exist for older versions
+    if (!this.domainObject.configuration.objectStyles) {
+      this.domainObject.configuration.objectStyles = {};
```
Comment (akhenry) [inline src/plugins/flexibleLayout/components/FlexibleLayout.vue:164]: See previous comments about initializing objects in views.

File: src/plugins/flexibleLayout/plugin.js [hunk 3]
```diff
@@ -37,7 +37,8 @@ export default function plugin() {
       initialize: function (domainObject) {
         domainObject.configuration = {
           containers: [new Container(50), new Container(50)],
-          rowsLayout: false
+          rowsLayout: false,
+          objectStyles: {}
```
Comment (akhenry) [inline src/plugins/flexibleLayout/plugin.js:41]: See previous comments. Unfortunately we are doing it in some places already, let's try to avoid making the problem worse.

File: src/plugins/gauge/GaugeCompositionPolicy.js [hunk 4]
```diff
@@ -21,28 +21,10 @@
...
-      metadata.valuesForHints(['range']).length > 0 &&
-      metadata.valuesForHints(['domain']).length > 0
-    );
-  }
-
   return {
     allow: function (parent, child) {
       if (parent.type === 'gauge') {
-        return hasNumericTelemetry(child);
+        return openmct.telemetry.hasNumericTelemetry(child);
```
Comment (akhenry) [inline src/plugins/gauge/GaugeCompositionPolicy.js:27]: Love it!

File: src/plugins/gauge/components/GaugeComponent.vue [hunk 5]
```diff
@@ -553,6 +553,11 @@ export default {
     this.openmct.time.on('boundsChanged', this.refreshData);
     this.openmct.time.on('timeSystem', this.setTimeSystem);
 
+    // Initialize objectStyles if it doesn't exist
+    if (!this.domainObject.configuration.objectStyles) {
+      this.domainObject.configuration.objectStyles = {};
```
Comment (akhenry) [inline src/plugins/gauge/components/GaugeComponent.vue:558]: See above, sorry.

File: src/plugins/inspectorViews/elements/ElementsPool.vue [hunk 6]
```diff
@@ -92,6 +93,7 @@ export default {
   methods: {
     setEditState(isEditing) {
       this.isEditing = isEditing;
+      console.log('this.isEditing', this.isEditing);
```
Comment (akhenry) [inline src/plugins/inspectorViews/elements/ElementsPool.vue:96]: Debugging code, let's remove.

File: src/plugins/inspectorViews/elements/ElementsViewProvider.js [hunk 7]
```diff
@@ -31,8 +31,9 @@ export default function ElementsViewProvider(openmct) {
     canView: function (selection) {
       const hasValidSelection = selection?.length;
       const isOverlayPlot = selection?.[0]?.[0]?.context?.item?.type === 'telemetry.plot.overlay';
+      const isFolder = selection?.[0]?.[0]?.context?.item?.type === 'folder';
```
Comment (akhenry) [inline src/plugins/inspectorViews/elements/ElementsViewProvider.js:34]: Ooof, our selection API is gross. Out of scope to fix it though :)

File: src/plugins/inspectorViews/properties/PropertiesViewProvider.js [hunk 8]
```diff
@@ -56,7 +58,7 @@ export default function PropertiesViewProvider(openmct) {
           _destroy = destroy;
         },
         priority: function () {
```
Comment (akhenry) [inline src/plugins/inspectorViews/properties/PropertiesViewProvider.js:60]: Lucky we made this a function huh!

File: src/plugins/inspectorViews/styles/StylesInspectorViewProvider.js [hunk 9]
```diff
@@ -47,27 +64,42 @@ export default function StylesInspectorViewProvider(openmct) {
...
+        isLayoutObject(objectSelection, domainObject.type) ||
+        isCreatableObject(domainObject, typeObject)
       );
     },
     view: function (selection) {
       let _destroy = null;
+      const objectSelection = selection?.[0];
+      const objectContext = objectSelection?.[0]?.context;
+      const domainObject = objectContext?.item;
+      const onlyEditMode = [
```
Comment (akhenry) [inline src/plugins/inspectorViews/styles/StylesInspectorViewProvider.js:93]: These are views where we _only_ want to show the style inspector in edit mode, is that correct? Why is that?

Comment (akhenry) [reply src/plugins/inspectorViews/styles/StylesInspectorViewProvider.js:93]: My reason for trying to understand this is I'm concerned about the amount of plugin-specific code we are building into this view. I'd like to keep it as agnostic as possible, and have plugins opt-in to features like styling.

File: src/plugins/plot/PlotView.vue [hunk 10]
```diff
@@ -173,6 +173,15 @@ export default {
   created() {
     eventHelpers.extend(this);
     this.imageExporter = new ImageExporter(this.openmct);
+
+    // Initialize objectStyles for overlay plot if it doesn't exist
+    if (
+      this.domainObject.type === 'telemetry.plot.overlay' &&
+      !this.domainObject.configuration.objectStyles
+    ) {
+      this.domainObject.configuration.objectStyles = {};
```
Comment (akhenry) [inline src/plugins/plot/PlotView.vue:182]: See previous comments.

File: src/plugins/plot/PlotViewProvider.js [hunk 11]
```diff
@@ -57,7 +36,7 @@ export default function PlotViewProvider(openmct) {
     name: 'Plot',
     cssClass: 'icon-telemetry',
     canView(domainObject, objectPath) {
-      return hasNumericTelemetry(domainObject);
+      return openmct.telemetry.hasNumericTelemetry(domainObject);
```
Comment (akhenry) [inline src/plugins/plot/PlotViewProvider.js:39]: 👍

File: src/plugins/plot/stackedPlot/StackedPlot.vue [hunk 12]
```diff
@@ -147,6 +147,11 @@ export default {
     this.config = this.getConfig(configId);
     this.showLegendsForChildren = this.config.legend.get('showLegendsForChildren');
 
+    // Initialize objectStyles if it doesn't exist
+    if (!this.domainObject.configuration.objectStyles) {
+      this.domainObject.configuration.objectStyles = {};
```
Comment (akhenry) [inline src/plugins/plot/stackedPlot/StackedPlot.vue:152]: See previous.

File: src/plugins/telemetryTable/TelemetryTableConfiguration.js [hunk 13]
```diff
@@ -36,6 +36,11 @@ export default class TelemetryTableConfiguration extends EventEmitter {
     this.defaultOptions = options;
     this.columns = {};
 
+    // Initialize objectStyles if it doesn't exist, for items with configuration
+    if (this.domainObject.configuration && !this.domainObject.configuration.objectStyles) {
+      this.domainObject.configuration.objectStyles = {};
```
Comment (akhenry) [inline src/plugins/telemetryTable/TelemetryTableConfiguration.js:41]: See previous.

**Review by akhenry — CHANGES_REQUESTED** [review]
Looks great, thanks! There are a number of places where we are initializing `domainObject.configuration.objectStyles` in views because it doesn't exist on legacy objects.

We should never mutate objects in views unless something has changed. Supporting legacy objects is a special case where we should use an object interceptor to achieve this. The interceptor can augment object models once wherever they are used, even outside of the main views. There should be an interceptor for each type, and it should sit alongside the type that it augments in the code tree.

File: src/plugins/inspectorViews/styles/StylesInspectorViewProvider.js (hunk 9 above)
Comment (jvigliotta) [reply src/plugins/inspectorViews/styles/StylesInspectorViewProvider.js:93]: I'll let @charlesh88 answer this one!

File: src/api/annotation/AnnotationAPI.js [hunk 14]
```diff
@@ -115,6 +116,17 @@ export default class AnnotationAPI extends EventEmitter {
         domainObject.annotationType = domainObject.annotationType || 'plotspatial';
       }
     });
+
+    this.openmct.on('start', () => {
```
[the remark this answers is not in the document]
Comment (jvigliotta) [reply src/api/annotation/AnnotationAPI.js:120]: Good call!

File: src/plugins/inspectorViews/styles/StylesInspectorViewProvider.js (hunk 9 above)
Comment (charlesh88) [reply src/plugins/inspectorViews/styles/StylesInspectorViewProvider.js:93]: @akhenry I think the original idea was reducing the number of tabs in view while in browse mode. That said, I agree with reducing complexity have no real objection to showing the Style tab in browse mode for those view as long as it's prioritized properly in that mode, which will be different than in edit mode.

So, this was the original spec for those views:
image

And here it is with updated priorities:
image

Comment (jvigliotta) [reply src/plugins/inspectorViews/styles/StylesInspectorViewProvider.js:93]: I'll make the update!

File: src/plugins/plot/stackedPlot/stackedPlotConfigurationInterceptor.js [hunk 15]
```diff
@@ -23,14 +23,27 @@
...
-      return object;
+      if (!domainObject.configuration.series) {
+        domainObject.configuration.series = [];
+      }
+
+      if (!domainObject.configuration.objectStyles) {
+        domainObject.configuration.objectStyles = {};
+      }
+
+      openmct.objects.save(domainObject);
```
Comment (akhenry) [inline src/plugins/plot/stackedPlot/stackedPlotConfigurationInterceptor.js:44]: Do we need this step? It's going to create a ton of extra persistence calls.

File: src/plugins/interceptors/missingObjectInterceptor.js [hunk 16]
```diff
@@ -38,6 +38,7 @@ export default function MissingObjectInterceptor(openmct) {
       }
 
       return object;
-    }
+    },
+    priority: openmct.priority.HIGH + 1 // this should be the first interceptor to run
```
Comment (akhenry) [inline src/plugins/interceptors/missingObjectInterceptor.js:42]: Could we just make the style interceptor a lower priority?

File: src/plugins/plot/overlayPlot/overlayPlotStylesInterceptor.js [hunk 17]
```diff
@@ -0,0 +1,43 @@
...
+      );
+    },
+    invoke: (identifier, domainObject) => {
+      if (!domainObject.configuration) {
+        domainObject.configuration = {};
+      }
+
+      domainObject.configuration.objectStyles = {};
+
+      openmct.objects.save(domainObject);
```
Comment (akhenry) [inline src/plugins/plot/overlayPlot/overlayPlotStylesInterceptor.js:38]: We shouldn't need to save, and it's going to create problems if we do.

File: src/plugins/telemetryTable/telemetryTableStylesInterceptor.js [hunk 18]
```diff
@@ -0,0 +1,40 @@
...
+      return (
+        domainObject?.type === 'table' &&
+        domainObject.configuration && // only applies to tables with existing configuration
+        !domainObject.configuration.objectStyles
+      );
+    },
+    invoke: (identifier, domainObject) => {
+      domainObject.configuration.objectStyles = {};
+
+      openmct.objects.save(domainObject);
```
Comment (akhenry) [inline src/plugins/telemetryTable/telemetryTableStylesInterceptor.js:35]: See above, this is going to create an extra persistence call for every telemetry table?

**Review by akhenry — CHANGES_REQUESTED** [review]

File: src/plugins/plot/overlayPlot/overlayPlotStylesInterceptor.js (hunk 17 above)
Comment (jvigliotta) [reply src/plugins/plot/overlayPlot/overlayPlotStylesInterceptor.js:38]: got it!

File: src/plugins/interceptors/missingObjectInterceptor.js (hunk 16 above)
Comment (jvigliotta) [reply src/plugins/interceptors/missingObjectInterceptor.js:42]: yeah it didn't do anything either :) I just added a check in the interceptors to make sure the domain object exists

File: src/plugins/displayLayout/components/DisplayLayout.vue (hunk 1 above)
Comment (akhenry) [reply src/plugins/displayLayout/components/DisplayLayout.vue:231]: This still needs to be addressed. The interceptor should be handling this now

File: src/plugins/charts/bar/inspector/BarGraphInspectorViewProvider.js [hunk 19]
```diff
@@ -41,7 +41,7 @@ export default function BarGraphInspectorViewProvider(openmct) {
           _destroy = destroy;
         },
         priority: function () {
-          return openmct.priority.HIGH + 1;
+          return openmct.editor.isEditing() ? openmct.priority.HIGH + 1 : openmct.priority.DEFAULT;
```
Comment (akhenry) [inline src/plugins/charts/bar/inspector/BarGraphInspectorViewProvider.js:44]: `HIGH + 1` is a code smell to me. Should something else just be a lower priority?

File: src/plugins/LADTable/LADTableConfigurationViewProvider.js [hunk 20]
```diff
@@ -61,7 +61,7 @@ export default function LADTableConfigurationViewProvider(openmct) {
           _destroy = destroy;
         },
         priority() {
-          return 1;
+          return openmct.editor.isEditing() ? openmct.priority.HIGH + 1 : openmct.priority.DEFAULT;
```
Comment (akhenry) [inline src/plugins/LADTable/LADTableConfigurationViewProvider.js:64]: HIGH + 1 is a code smell to me. Should something else just be a lower priority?

File: src/plugins/flexibleLayout/components/FlexibleLayout.vue (hunk 2 above)
Comment (akhenry) [reply src/plugins/flexibleLayout/components/FlexibleLayout.vue:164]: Still needs to be addressed.

File: src/plugins/flexibleLayout/plugin.js (hunk 3 above)
Comment (akhenry) [reply src/plugins/flexibleLayout/plugin.js:41]: Still needs to be addressed.

File: src/plugins/gauge/components/GaugeComponent.vue (hunk 5 above)
Comment (akhenry) [reply src/plugins/gauge/components/GaugeComponent.vue:558]: Still needs to be addressed.

File: src/plugins/inspectorViews/elements/ElementsPool.vue (hunk 6 above)
Comment (akhenry) [reply src/plugins/inspectorViews/elements/ElementsPool.vue:96]: Still needs to be addressed.

**Review by akhenry — CHANGES_REQUESTED** [review]

File: src/plugins/charts/bar/inspector/BarGraphInspectorViewProvider.js (hunk 19 above)
Comment (jvigliotta) [reply src/plugins/charts/bar/inspector/BarGraphInspectorViewProvider.js:44]: Turns out... these weren't needed!

**Review by akhenry — APPROVED** [review]
Looking sharp! Thanks for addressing all of those comments.
