### PR TITLE
Ensure properties stay in sync and are committed only once

### LINKED ISSUE #5356: [Gauge] On create, changing `Value ranges and limits` will override any form changes above
#### Summary
When creating a gauge, if the `Value ranges and limits` configuration is modified, all other edits will be lost on finalizing creation.

#### Expected vs Current Behavior
All changes to a new gauge form should be saved.

#### Steps to Reproduce
1. Select Gauge from the create menu
2. Change the Gauge type property (or any other property other than `Value ranges and limits` property)
3. toggle the `Value ranges and limits` property and make change to that
4. Click OK to save the Gauge
5. Click the 3 dot menu and select edit properties
6. Everything is not OK. Only the `Value ranges and limits` property is saved and all other properties are not

#### Environment
* Open MCT Version: release/2.0.5
* Deployment Type: testathon
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by shefalijoshi**
Closes #5356 #5616

### Describe your changes:
Please see previous code comments here: https://github.com/nasa/openmct/pull/5446

Use lodash.set to keep properties in sync so that changes to properties don't override other properties.
Check to ensure that existing properties that were NOT changed don't get blown away.
When saving changes, use a transaction to save all properties at once.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Changes appear not to be breaking changes?
* [ ] Appropriate unit tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Commit messages meet standards?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [x] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/plugins/formActions/EditPropertiesAction.js [hunk 1]
```diff
@@ -92,6 +99,12 @@ export default class EditPropertiesAction extends PropertiesAction {
         const createWizard = new CreateWizard(this.openmct, this.domainObject, objectPath[1]);
         const formStructure = createWizard.getFormStructure(false);
         formStructure.title = 'Edit ' + this.domainObject.name;
+        //If we're in edit mode AND want to edit properties for the same domain object
+        //In this case, saving will put the object in view-only mode
+        //TODO: Maybe we should block editing properties if someone is in Edit mode?
+        if (!this.openmct.editor.isEditing()) {
```
Comment (ozyx) [inline src/plugins/formActions/EditPropertiesAction.js:105]: This is changing the current behavior in that pressing 'Save' or 'Cancel' on an Edit Properties window while in Edit mode will now complete the edit (previously it did not).

There is one odd case I've found where entering into the "Edit Properties" window while not in edit mode, and pressing the "X" to close the window will leave edit mode active instead of cancelling it. Not sure if this has a negative impact, but could be surprising to a user.

File: src/plugins/formActions/EditPropertiesAction.js [hunk 2]
```diff
@@ -54,23 +55,26 @@ export default class EditPropertiesAction extends PropertiesAction {
...
-                const propertiesLength = properties.length;
-                properties.forEach((property, index) => {
-                    const isComplexProperty = propertiesLength > 1 && index !== propertiesLength - 1;
-                    if (isComplexProperty && object[property] !== null) {
-                        object = object[property];
-                    } else {
-                        object[property] = value;
-                    }
-                });
+                const existingValue = this.domainObject[`${key}`];
```
Comment (ozyx) [inline src/plugins/formActions/EditPropertiesAction.js:58]: Can we just use `this.domainObject[key]` here or is the template literal doing something necessary?

File: src/plugins/formActions/EditPropertiesAction.js [hunk 3]
```diff
@@ -54,23 +55,26 @@ export default class EditPropertiesAction extends PropertiesAction {
...
+                    value = {
+                        ...existingValue,
+                        ...value
+                    };
+                }
 
-                object = value;
-                this.openmct.objects.mutate(this.domainObject, key, value);
-                this.openmct.notifications.info('Save successful');
+                this.openmct.objects.mutate(this.domainObject, `${key}`, value);
```
Comment (ozyx) [inline src/plugins/formActions/EditPropertiesAction.js:66]: Same question here re:template literal

File: src/plugins/formActions/CreateAction.js [hunk 4]
```diff
@@ -50,19 +51,15 @@ export default class CreateAction extends PropertiesAction {
...
-                if (isComplexProperty && object[property] !== null) {
-                    object = object[property];
-                } else {
-                    object[property] = value;
-                }
-            });
-
-            object = value;
+            const existingValue = this.domainObject[`${key}`];
+            if (!(existingValue instanceof Array) && (typeof existingValue === 'object')) {
```
Comment (ozyx) [inline src/plugins/formActions/CreateAction.js:55]: Should we use `Array.isArray(existingValue)` here instead?

**Review by ozyx — CHANGES_REQUESTED** [review]
Looks great overall, and seems to work well in my initial testing. I have a couple questions and I've left some suggestions as well.

File: src/plugins/gauge/components/GaugeFormController.vue [hunk 5]
```diff
@@ -118,21 +121,30 @@ export default {
...
         onChange(event) {
             const data = {
                 model: this.model,
                 value: {
-                    gaugeType: this.model.value.gaugeType,
-                    isDisplayMinMax: this.isDisplayMinMax,
-                    isDisplayCurVal: this.isDisplayCurVal,
-                    isDisplayUnits: this.isDisplayUnits,
+                    gaugeType: this.changes.gaugeType || this.model.value.gaugeType,
+                    isDisplayMinMax: this.changes.isDisplayMinMax === undefined ? this.isDisplayMinMax : this.changes.isDisplayMinMax,
```
[the remark this answers is not in the document]
Comment (shefalijoshi) [reply src/plugins/gauge/components/GaugeFormController.vue:139]: I prefer using `=== undefined` here, if that's OK?

File: src/plugins/formActions/EditPropertiesAction.js (hunk 1 above)
Comment (shefalijoshi) [reply src/plugins/formActions/EditPropertiesAction.js:105]: Yes, we need a follow up task to not allow editing properties if the object is in edit mode already.

I've resolved the bug where canceling the edit properties action leaves it in edit mode.

File: src/plugins/gauge/components/GaugeFormController.vue (hunk 5 above)
[the remark this answers is not in the document]
Comment (ozyx) [reply src/plugins/gauge/components/GaugeFormController.vue:139]: On second glance, in this case `=== undefined` and using `??` are not completely functionally the same. `??` will assign the left-hand side value if it is not `undefined` OR `null`, otherwise it will assign the right-hand side value.

So if `null` is a valid value here, then we shouldn't use `??`.

If `null` is not a valid value, then it's all syntactic sugar and entirely up to your preference / whatever you find more readable. :)

File: src/api/forms/FormsAPI.js [hunk 6]
```diff
@@ -158,10 +162,12 @@ export default class FormsAPI extends EventEmitter {
                     key = property.join('.');
                 }
 
-                changes[key] = data.value;
+                _.set(changes, `${key}`, data.value);
+                self.emit('formPropertiesChanged', changes);
```
Comment (akhenry) [inline src/api/forms/FormsAPI.js:166]: Why are we emitting an event here _and_ calling the `onchange` callback. It's going to be very confusing to developers why we have both event mechanisms.

File: src/api/forms/FormsAPI.js [hunk 7]
```diff
@@ -99,6 +100,7 @@ export default class FormsAPI extends EventEmitter {
      *      @property {HTMLElement} element Parent Element to render a Form
      *      @property {function} onChange a callback function when any changes detected
      *      @property {function} onSave a callback function when form is submitted
+     *      @property {function} onCancel a callback function when form is cancelled
      *      @property {function} onDismiss a callback function when form is dismissed
      */
     showForm(formStructure, {
```
Comment (akhenry) [inline src/api/forms/FormsAPI.js:106]: This API seems to have got a little lost somewhere along the way (prior to this PR). It was supposed to be a general purpose API for rendering a form into a given HTML element (the `element` argument). A convenience function would then be provided for rendering a given form structure into an overlay, which is what this function is doing. These two things have been conflated into a single function, with two logic paths for the two intended purposes, which we should untangle.

The reason I mention this is that the forms API was never supposed to track any overlay state, which is what it's doing by emitting events specific to the active form overlay. This is why `onchange` is passed in as a callback function instead of the FormsAPI itself being an event emitter. The Forms API should have no concept of an "active" form because it could be tracking multiple forms.

See my comments below on `formPropertiesChanged`, Forms API should not be a singleton EventEmitter, we need to change this behavior.

File: src/plugins/gauge/components/GaugeFormController.vue [hunk 8]
```diff
@@ -100,13 +100,16 @@ export default {
     components: {
```
Comment (akhenry) [inline src/plugins/gauge/components/GaugeFormController.vue:100]: The `GaugeFormController` is just straight up abusing the Forms API support for custom controls to shoehorn a totally customized form into the properties dialog for gauges. Out of scope for this PR, but I will file a followup to fix this, this is not at all how custom controls are supposed to be used.

File: src/api/overlays/Overlay.js [hunk 9]
```diff
@@ -42,6 +43,10 @@ class Overlay extends EventEmitter {
         if (onDestroy) {
             this.once('destroy', onDestroy);
         }
+
+        if (onDismiss) {
```
Comment (akhenry) [inline src/api/overlays/Overlay.js:47]: What's the difference between `dismiss` and `destroy`? I am concerned that overlay-specific details (like the distinction between `save` and `cancel`) are sneaking into the generic Overlay (which may be purely informational and not have any buttons at all).

**Review by akhenry — CHANGES_REQUESTED** [review]
Thanks for making these changes. There are some pre-existing problems with the implementation of the Forms API that I'd like to address now before we merge this change to avoid creating more tech debt:

1. The FormsAPI should not be an EventEmitter. Can we please use the existing `onChange` callback that is passed into the `showForm` function already.
2. Can we please separate the `showForm` function into two functions, one that renders a form into an arbitrary HTML element, and one that renders it into an overlay. For backwards compatibility the function that renders it into an overlay should still be called `showForm`.

I also think we want to use a transaction rather than edit mode for batching mutations from forms (see comments)

File: src/api/overlays/Overlay.js (hunk 9 above)
Comment (shefalijoshi) [reply src/api/overlays/Overlay.js:47]: I think I might have fallen into the above mentioned trap of intended use of FormsAPI vs OverlayAPI.
`destroy` seems to be called by the Overlay as well as by the FormsAPI. 
`dismiss` was an attempt to keep the dismiss functionality within the Overlay as changing `destroy` could have ripple effects. Ideally, the FormsAPI would not be dictating when the Overlay dismisses - which is what is happening now.

File: src/plugins/gauge/components/GaugeFormController.vue (hunk 8 above)
Comment (shefalijoshi) [reply src/plugins/gauge/components/GaugeFormController.vue:100]: Can you point to the original intent of how custom controls were supposed to be used? Perhaps a github issue? Or elaborate here?

**Comment by shefalijoshi** [comment]
> Thanks for making these changes. There are some pre-existing problems with the implementation of the Forms API that I'd like to address now before we merge this change to avoid creating more tech debt:
> 
>     1. The FormsAPI should not be an EventEmitter. Can we please use the existing `onChange` callback that is passed into the `showForm` function already.
> 
>     2. Can we please separate the `showForm` function into two functions, one that renders a form into an arbitrary HTML element, and one that renders it into an overlay. For backwards compatibility the function that renders it into an overlay should still be called `showForm`.
> 
> 
> I also think we want to use a transaction rather than edit mode for batching mutations from forms (see comments)

Currently, `showForm` returns a promise on Save or Cancel, which is then being handled by consumers. 
For the new HTML form render function, should we stick with the same paradigm? Or do you prefer not returning a promise and pass in onSave and onCancel parameters instead? Having both doesn't make sense.

**Comment by akhenry** [comment]
> > Thanks for making these changes. There are some pre-existing problems with the implementation of the Forms API that I'd like to address now before we merge this change to avoid creating more tech debt:
> > ```
> > 1. The FormsAPI should not be an EventEmitter. Can we please use the existing `onChange` callback that is passed into the `showForm` function already.
> > 
> > 2. Can we please separate the `showForm` function into two functions, one that renders a form into an arbitrary HTML element, and one that renders it into an overlay. For backwards compatibility the function that renders it into an overlay should still be called `showForm`.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I also think we want to use a transaction rather than edit mode for batching mutations from forms (see comments)
> 
> Currently, `showForm` returns a `promise` on Save or Cancel, which is then being handled by consumers. For the new HTML form render function, should we stick with the same paradigm? Or do you prefer not returning a `promise` and pass in `onSave` and `onCancel` parameters instead? Having both doesn't make sense.

Good question. Let's stick with the same paradigm.

**Comment by akhenry** [comment]
@shefalijoshi  Is this ready for re-review?

**Comment by akhenry** [comment]
@shefalijoshi There appears to be a conflict now, and some linting errors and failing tests.

File: src/api/forms/FormsAPI.js [hunk 10]
```diff
@@ -162,28 +145,91 @@ export default class FormsAPI extends EventEmitter {
...
+     * @param {Array<Section>} formStructure a form structure, array of section
+     * @param {Object} options
+     *      @property {HTMLElement} element Parent Element to render a Form
+     *      @property {function} onChange a callback function when any changes detected
+     */
+    showCustomForm(formStructure, {
+        element,
+        onChange
+    } = {}) {
+        if (element === undefined) {
```
Comment (akhenry) [inline src/api/forms/FormsAPI.js:179]: Let's just throw an error if they don't provide `element`, it's required.

**Review by akhenry — CHANGES_REQUESTED** [review]
Thanks for addressing the comments. Looking really good. Just a couple of minor suggestions at this point.

**Review by akhenry — APPROVED** [review]

**Comment by akhenry** [comment]
### Results of reviewer testing
#5616 does not appear to be fixed. I am still seeing multiple persist requests (though at least not one for each property now). Here's what I did:
1. On an existing sine wave generator, click "Edit Properties"
2. Open the network tab in Chrome, and clear any existing requests
3. Modify the value of every property (including the name)
4. Add some notes
5. Click Save
6. Note that three PUT requests are issued to the same URL with slightly different payloads.

The first payload appears to be the rename.
```
{
  "name": "Renamed Sine Wave Generator",
  "type": "generator",
  "telemetry": {
    "period": 10,
    "amplitude": 1,
    "offset": 0,
    "dataRateInHz": 1,
    "phase": 0,
    "randomness": 0,
    "loadDelay": 0
  },
  "modified": 1666377315888,
  "location": "1f138c6e-043f-44c3-8fe3-d28f62e4e5f8",
  "persisted": 1666377315889
}
```

The second request updates all of the "telemetry" properties in one go.
```
{
    "name": "Renamed Sine Wave Generator",
    "type": "generator",
    "telemetry": {
      "period": "15",
      "amplitude": "2",
      "offset": "1",
      "dataRateInHz": "2",
      "phase": "2",
      "randomness": "0.01",
      "loadDelay": "10"
    },
    "modified": 1666377315890,
    "location": "1f138c6e-043f-44c3-8fe3-d28f62e4e5f8",
    "persisted": 1666377315890
  }
```

The third request sets the notes property.
```
  {
    "name": "Renamed Sine Wave Generator",
    "type": "generator",
    "telemetry": {
      "period": "15",
      "amplitude": "2",
      "offset": "1",
      "dataRateInHz": "2",
      "phase": "2",
      "randomness": "0.01",
      "loadDelay": "10"
    },
    "modified": 1666377315891,
    "location": "1f138c6e-043f-44c3-8fe3-d28f62e4e5f8",
    "persisted": 1666377315891,
    "notes": "Some notes"
  }
```

**Review by akhenry — CHANGES_REQUESTED** [review]
### Results of reviewer testing
#5616 does not appear to be fixed. I am still seeing multiple persist requests (though at least not one for each property now). Here's what I did:
1. On an existing sine wave generator, click "Edit Properties"
2. Open the network tab in Chrome, and clear any existing requests
3. Modify the value of every property (including the name)
4. Add some notes
5. Click Save
6. Note that three PUT requests are issued to the same URL with slightly different payloads.

The first payload appears to be the rename.
```
{
  "name": "Renamed Sine Wave Generator",
  "type": "generator",
  "telemetry": {
    "period": 10,
    "amplitude": 1,
    "offset": 0,
    "dataRateInHz": 1,
    "phase": 0,
    "randomness": 0,
    "loadDelay": 0
  },
  "modified": 1666377315888,
  "location": "1f138c6e-043f-44c3-8fe3-d28f62e4e5f8",
  "persisted": 1666377315889
}
```

The second request updates all of the "telemetry" properties in one go.
```
{
    "name": "Renamed Sine Wave Generator",
    "type": "generator",
    "telemetry": {
      "period": "15",
      "amplitude": "2",
      "offset": "1",
      "dataRateInHz": "2",
      "phase": "2",
      "randomness": "0.01",
      "loadDelay": "10"
    },
    "modified": 1666377315890,
    "location": "1f138c6e-043f-44c3-8fe3-d28f62e4e5f8",
    "persisted": 1666377315890
  }
```

The third request sets the notes property.
```
  {
    "name": "Renamed Sine Wave Generator",
    "type": "generator",
    "telemetry": {
      "period": "15",
      "amplitude": "2",
      "offset": "1",
      "dataRateInHz": "2",
      "phase": "2",
      "randomness": "0.01",
      "loadDelay": "10"
    },
    "modified": 1666377315891,
    "location": "1f138c6e-043f-44c3-8fe3-d28f62e4e5f8",
    "persisted": 1666377315891,
    "notes": "Some notes"
  }
```

**Comment by shefalijoshi** [comment]
> 

The review test failed because `openmct.objects.isTransactionActive()` wasn't updated to include the [change recently made](https://github.com/nasa/openmct/blob/release/2.1.2/src/api/objects/ObjectAPI.js#L724) to not checking if the application is in edit mode. I've synced this branch with release/2.1.2 which has that fix. It works as expected now.

**Review by akhenry — APPROVED** [review]

**Review by ozyx — APPROVED** [review]
LGTM.

Let's log an issue to get some e2e coverage on this
