### PR TITLE
[Telemetry API] Prevent Subscriptions with different options from overwriting each other

### LINKED ISSUE #7933: [TelemetryAPI] Subscriptions need to be unique based on request options
VIPEROMCT-552, VIPEROMCT-553

#### Summary

The Telemetry API's `subscribe` method will currently differentiate subscriptions based on a combination of domain object key string and request strategy (latest, batch, etc). This works for most situations, but it fails in situations where filter options are passed in with the request.

#### Expected vs Current Behavior

Subscriptions should be unique based on domain object key string and request options (which will include strategy as well as filter options, among other options). Currently it's only domain object key string and request strategy.

#### Steps to Reproduce

1. Create a display layout with two tables that have the same domain object
2. Set different filters on each table
3. Notice ONE of the tables will not be filtering correctly (historical will filter correctly)
4. Be amazed

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by jvigliotta**
Closes #7933

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this a [notable change](../docs/src/process/release.md) that will require a special callout in the release notes? For example, will this break compatibility with existing APIs or projects that consume these plugins?

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Has this been smoke tested?
* [x] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [ ] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [x] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?

### CODE REVIEW

File: src/api/telemetry/TelemetryAPI.js [hunk 1]
```diff
@@ -250,6 +250,121 @@ export default class TelemetryAPI {
...
+   * and recursively processed values. This ensures consistent object representation
+   * regardless of property order.
+   *
+   * Used internally to generate consistent hashes for caching subscription options.
+   *
+   * @private
+   * @param {Object|Array|*} options The options object to canonicalize
+   * @returns {Object|Array|*} A canonicalized version of the input where object keys are sorted
+   */
+  #canonicalizeOptions(options) {
```
Comment (akhenry) [inline src/api/telemetry/TelemetryAPI.js:264]: Could this just be replaced by sorting the Object keys on line 306?

eg.

```
const sortedKeys = Object.keys(value).sort();
for (const key of sortedKeys) {
...
```

File: src/api/telemetry/TelemetryAPI.js [hunk 2]
```diff
@@ -250,6 +250,121 @@ export default class TelemetryAPI {
...
+   * different options configurations. The hash function ensures that identical options
+   * objects will always generate the same hash value, while different options objects
+   * (even with small differences) will generate different hash values.
+   *
+   * @private
+   * @param {Object} options The options object to hash
+   * @returns {number} A positive integer hash of the options object
+   */
+  #hashOptions(options) {
+    const sanitizedOptions = this.#sanitizeForSerialization(options);
```
Comment (akhenry) [inline src/api/telemetry/TelemetryAPI.js:333]: This seems to be doing the same job as [replacer functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#the_replacer_parameter) in JSON.stringify. We might be able to do this all in a single call to JSON.stringify and save some CPU cycles.

**Review by akhenry — CHANGES_REQUESTED** [review]
I think the hash code is the right approach here, thanks. I think we can simplify the code a little with a few tweaks,

File: e2e/tests/functional/plugins/displayLayout/displayLayout.e2e.spec.js [hunk 3]
```diff
@@ -507,8 +507,125 @@ test.describe('Display Layout', () => {
...
+      exact: true
+    });
+    const tableFilterOff = page.getByLabel(`${tableFilterOffValue.name} Frame`, {
+      exact: true
+    });
+
+    // Verify filtering is working correctly
+    // Wait for some data to populate
+    // eslint-disable-next-line playwright/no-wait-for-timeout
+    await page.waitForTimeout(2000); // Wait for a few state changes
```
Comment (akhenry) [inline e2e/tests/functional/plugins/displayLayout/displayLayout.e2e.spec.js:603]: Can we try and find an alternative to `waitForTimeout`?

File: src/api/telemetry/TelemetryAPI.js (hunk 1 above)
Comment (jvigliotta) [reply src/api/telemetry/TelemetryAPI.js:264]: Great call! Will do.

File: src/api/telemetry/TelemetryAPI.js (hunk 2 above)
Comment (jvigliotta) [reply src/api/telemetry/TelemetryAPI.js:333]: I've modified sanitize for serialization to be the replacer function!

File: src/api/telemetry/TelemetryAPI.js [hunk 4]
```diff
@@ -250,6 +250,107 @@
...
+  sanitizeForSerialization(key, value) {
+    // Handle non-object types directly, except functions
+    if (typeof value !== 'object' || value === null) {
+      return value;
+    }
+
+    // Replace functions and other non-serializable values with their key names
+    if (
+      typeof value === 'function' ||
+      (value && typeof value === 'object' && !(Object.getPrototypeOf(value) === Object.prototype))
```
[the remark this answers is not in the document]
Comment (jvigliotta) [reply src/api/telemetry/TelemetryAPI.js]: fixed

File: e2e/tests/functional/plugins/displayLayout/displayLayout.e2e.spec.js (hunk 3 above)
Comment (jvigliotta) [reply e2e/tests/functional/plugins/displayLayout/displayLayout.e2e.spec.js]: PHEW! that was something. since rows are being added an removed basically at the same time (in either table mode) I wasn't able to count em, so added a mutation observer to track mutations in the table (new rows). Wait for a set amount then verify we've got the correct filters.

File: src/api/telemetry/TelemetryAPI.js [hunk 5]
```diff
@@ -251,69 +251,50 @@ export default class TelemetryAPI {
...
-      return value.map((item) => this.#sanitizeForSerialization(item));
+      return value.map((item, index) => this.sanitizeForSerialization(String(index), item));
     }
 
-    if (Object.getPrototypeOf(value) === Object.prototype) {
-      const result = {};
-
-      for (const key of Object.keys(value)) {
-        const sanitizedValue = this.#sanitizeForSerialization(value[key]);
+    // Replace functions and non-plain objects with their key names
```
Comment (akhenry) [inline src/api/telemetry/TelemetryAPI.js:283]: Return `undefined` to leave the property out of its stringified representation entirely, per the docs - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#the_replacer_parameter

File: src/api/telemetry/TelemetryAPI.js [hunk 6]
```diff
@@ -251,69 +251,50 @@ export default class TelemetryAPI {
...
 
-    // Handle primitive types, arrays and objects
-    if (typeof value !== 'object') {
-      return typeof value !== 'function' ? value : undefined;
-    }
-
+    // Handle arrays
     if (Array.isArray(value)) {
-      return value.map((item) => this.#sanitizeForSerialization(item));
+      return value.map((item, index) => this.sanitizeForSerialization(String(index), item));
```
Comment (akhenry) [inline src/api/telemetry/TelemetryAPI.js:280]: Just return the array itself, the replacer function (sanitizeForSerialization) will automatically be called for each member. see docs - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#the_replacer_parameter

File: e2e/tests/functional/plugins/displayLayout/displayLayout.e2e.spec.js [hunk 7]
```diff
@@ -598,9 +598,37 @@ test.describe('Display Layout', () => {
     });
 
     // Verify filtering is working correctly
-    // Wait for some data to populate
-    // eslint-disable-next-line playwright/no-wait-for-timeout
-    await page.waitForTimeout(2000); // Wait for a few state changes
+
```
Comment (akhenry) [inline e2e/tests/functional/plugins/displayLayout/displayLayout.e2e.spec.js:601]: I think Playwright gone done this already - https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-have-count

**Review by akhenry — CHANGES_REQUESTED** [review]

File: src/api/telemetry/TelemetryAPI.js (hunk 5 above)
Comment (jvigliotta) [reply src/api/telemetry/TelemetryAPI.js:283]: From our conversation, we're worried about options properties that go out with the requests/subscriptions, so anything that'd be set to undefined, wouldn't matter at this point. Will set back to `undefined`!

File: e2e/tests/functional/plugins/displayLayout/displayLayout.e2e.spec.js (hunk 7 above)
Comment (jvigliotta) [reply e2e/tests/functional/plugins/displayLayout/displayLayout.e2e.spec.js:601]: well then... glad I did ALL THAT. Haha, let me switch this out and test to make sure.

Comment (jvigliotta) [reply e2e/tests/functional/plugins/displayLayout/displayLayout.e2e.spec.js:601]: Actually, going back, I remember why I did this. The table is adding and removing rows basically at the same time, so I can't go by count, because the rows aren't being added. So what I'm doing here is observing added nodes to the `table` child list (`tr`'s would count). I wait for 20 rows to be added, then I verify there are non-filtered rows shown and filtered rows NOT shown.

Comment (akhenry) [reply e2e/tests/functional/plugins/displayLayout/displayLayout.e2e.spec.js:601]: I think I understand, you want to count 20 add events, not 20 total rows.

**Review by akhenry — APPROVED** [review]
