### PR TITLE
[Tabs] Sizing of offscreen tabs causing issues

### LINKED ISSUE #4435: [Tabs] Clicking on a tab will reload the view unnecessarily
#### Summary
Tabs in eager load mode should keep tab views loaded in the background (which it does), but when you click on the tab to bring it into view, the data is re-requested when it shouldn't be.

#### Expected vs Current Behavior
With "Eager Load Tabs" true, any tab that is clicked, should not need to have data re-requested.

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. Create a tabs view with multiple telemetry view tabs
2. Click on any tab other than the current tab
3. You can see the view reloading data

### PR DESCRIPTION
**Pull request by jvigliotta**
### All Submissions:

closes #4435

When tabs are not currently being viewed, they were being set to a fixed height/width of 1000px. Then when they come into view again, they were going back to the original height/width. This was causing issues in some views which rely on accurate height/width for logic.

Have changed it so offscreen tabs have the same width and height as the currently viewed tab.

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### CODE REVIEW

**Review by davetsay — CHANGES_REQUESTED** [review]
it looks like telemetry is being requested on initial load

File: src/plugins/tabs/components/tabs.vue [hunk 1]
```diff
@@ -49,6 +52,7 @@
     <div
         v-for="tab in tabsList"
         :key="tab.keyString"
+        :style="!isCurrent(tab) ? { height: tabHeight, width: tabWidth } : {}"
```
[the remark this answers is not in the document]
Comment (jvigliotta) [reply src/plugins/tabs/components/tabs.vue]: No Dave... we can't. BUUUUT, as we discussed, we can put it in a method.

[the remark this answers is not in the document]
Comment (jvigliotta) [reply src/plugins/tabs/components/tabs.vue]: laughed at my own joke.

File: src/plugins/tabs/components/tabs.vue [hunk 2]
```diff
@@ -122,6 +129,10 @@ export default {
             });
         }
 
+        this.handleWindowResize = _.debounce(this.handleWindowResize, 500);
```
Comment (akhenry) [inline src/plugins/tabs/components/tabs.vue:132]: 👍

File: src/plugins/tabs/components/tabs.vue [hunk 3]
```diff
@@ -49,11 +52,12 @@
     <div
         v-for="tab in tabsList"
         :key="tab.keyString"
+        :style="getTabStyles(tab)"
```
Comment (akhenry) [inline src/plugins/tabs/components/tabs.vue:55]: There are too many method calls from the template in the tabs view.

Let's do this by computed property. Define a computed property that calculates styles for all tabs and returns them as a map (it will only do it when it needs to). Key it on tab.keyString.

File: src/plugins/tabs/components/tabs.vue [hunk 4]
```diff
@@ -49,11 +52,12 @@
...
         class="c-tabs-view__object-holder"
         :class="{'c-tabs-view__object-holder--hidden': !isCurrent(tab)}"
     >
         <object-view
-            v-if="isTabLoaded(tab)"
+            v-if="shouldLoadTab(tab)"
```
Comment (akhenry) [inline src/plugins/tabs/components/tabs.vue:60]: We should avoid a method call here as well. Couple of options:

- Tabs have a property on themselves that determines if they are active
- A computed property that returns a map of active tabs keyed on tab.keyString.

File: src/plugins/tabs/components/tabs.vue [hunk 5]
```diff
@@ -158,6 +171,27 @@ export default {
...
+                styles = {
+                    height: this.tabHeight,
+                    width: this.tabWidth
+                };
+            }
+
+            return styles;
+        },
+        getTabWidthAndHeight() {
+            const tabsViewEl = document.getElementsByClassName('c-tabs-view')[0];
```
Comment (akhenry) [inline src/plugins/tabs/components/tabs.vue:187]: This element already has a ref, let's use it instead of finding the element again on each resize event.

File: src/plugins/tabs/components/tabs.vue [hunk 6]
```diff
@@ -158,6 +171,27 @@ export default {
...
+            const tabsLabelsEl = document.getElementsByClassName('c-tabs-view__tabs-holder')[0];
```
Comment (akhenry) [inline src/plugins/tabs/components/tabs.vue:188]: Let's add a ref. No need to re-find it every time.

**Review by akhenry — CHANGES_REQUESTED** [review]
Looking good. A couple of v. small issues to fix pre-merge. I'll file a followup for some of the bigger issues.

Before merge let's fix:
* https://github.com/nasa/openmct/pull/4444#discussion_r752589349 and 
* https://github.com/nasa/openmct/pull/4444#discussion_r752589621

They're really small.

File: src/plugins/tabs/components/tabs.vue [hunk 7]
```diff
@@ -171,6 +205,13 @@ export default {
             this.currentTab = tab;
             this.addTabToLoaded(tab);
         },
+        shouldLoadTab(tab) {
+            const isLoadedAndCurrent = this.isTabLoaded(tab) && this.isCurrent(tab);
```
Comment (akhenry) [inline src/plugins/tabs/components/tabs.vue:209]: For now, can we at least cache the result of the calls to `isTabLoaded()` and `isCurrent()`?

File: src/plugins/tabs/components/tabs.vue [hunk 8]
```diff
@@ -325,6 +367,13 @@ export default {
 
             this.currentTabIndex = tabIndex;
             this.currentTab = this.tabsList[tabIndex];
+        },
+        handleWindowResize() {
+            console.log('resize')
```
Comment (akhenry) [inline src/plugins/tabs/components/tabs.vue:372]: Let's remove this debug statement.

**Review by akhenry — APPROVED** [review]

**Review by davetsay — APPROVED** [review]
LGTM

## Reviewer Checklist
| | |
| --- | :---: |
| Changes appear to address issue? | Y |
| Appropriate unit tests included? | Y |
| Code style and in-line documentation are appropriate? | Y |
| Commit messages meet standards? | Y |
| Has associated issue been labelled `unverified`? | Y |
