### PR TITLE
Fixes isMutable error when domainobject is undefined

### LINKED ISSUE #3660: [Mutation API] console error on destroy of object
## Overview
When navigating away from an object, receiving the below console error.

## Expected Behavior
Navigating away from objects should not result in errors.

## Steps to Reproduce
1. Create object in tree
2. select object
3. navigate away from object
4. may need to nest objects (further investigation required what is causing error)

```
vue.js?ba4c:580 [Vue warn]: Error in beforeDestroy hook: "TypeError: Cannot read property 'isMutable' of undefined"

found in

---> <TelemetryView> at src/plugins/displayLayout/components/TelemetryView.vue
       <Layout> at src/plugins/displayLayout/components/DisplayLayout.vue
         <Root>
warn @ vue.js?ba4c:580
logError @ vue.js?ba4c:1698
globalHandleError @ vue.js?ba4c:1693
handleError @ vue.js?ba4c:1682
callHook @ vue.js?ba4c:2874
Vue.$destroy @ vue.js?ba4c:2657
destroy @ vue.js?ba4c:4063
invokeDestroyHook @ vue.js?ba4c:5590
invokeDestroyHook @ vue.js?ba4c:5595
patch @ vue.js?ba4c:5913
Vue.$destroy @ vue.js?ba4c:2680
destroy @ vue.js?ba4c:4063
invokeDestroyHook @ vue.js?ba4c:5590
patch @ vue.js?ba4c:5913
Vue.$destroy @ vue.js?ba4c:2680
destroy @ plugin.js?5b89:86
clear @ ObjectView.vue?8a4f:93
boundFn @ vue.js?ba4c:195
destroyed @ ObjectView.vue?8a4f:50
callHook @ vue.js?ba4c:2872
Vue.$destroy @ vue.js?ba4c:2682
destroy @ vue.js?ba4c:4063
invokeDestroyHook @ vue.js?ba4c:5590
invokeDestroyHook @ vue.js?ba4c:5595
patch @ vue.js?ba4c:5913
Vue.$destroy @ vue.js?ba4c:2680
destroy @ vue.js?ba4c:4063
invokeDestroyHook @ vue.js?ba4c:5590
invokeDestroyHook @ vue.js?ba4c:5595
patch @ vue.js?ba4c:5913
Vue.$destroy @ vue.js?ba4c:2680
destroy @ vue.js?ba4c:4063
invokeDestroyHook @ vue.js?ba4c:5590
patch @ vue.js?ba4c:5913
Vue.$destroy @ vue.js?ba4c:2680
destroy @ vue.js?ba4c:4063
invokeDestroyHook @ vue.js?ba4c:5590
invokeDestroyHook @ vue.js?ba4c:5595
patch @ vue.js?ba4c:5913
Vue.$destroy @ vue.js?ba4c:2680
destroy @ vue.js?ba4c:4063
invokeDestroyHook @ vue.js?ba4c:5590
patch @ vue.js?ba4c:5913
Vue.$destroy @ vue.js?ba4c:2680
destroy @ plugin.js?5b89:86
clear @ ObjectView.vue?8a4f:93
boundFn @ vue.js?ba4c:195
destroyed @ ObjectView.vue?8a4f:50
callHook @ vue.js?ba4c:2872
Vue.$destroy @ vue.js?ba4c:2682
destroy @ vue.js?ba4c:4063
invokeDestroyHook @ vue.js?ba4c:5590
invokeDestroyHook @ vue.js?ba4c:5595
patch @ vue.js?ba4c:5913
Vue.$destroy @ vue.js?ba4c:2680
destroy @ vue.js?ba4c:4063
invokeDestroyHook @ vue.js?ba4c:5590
invokeDestroyHook @ vue.js?ba4c:5595
patch @ vue.js?ba4c:5913
Vue.$destroy @ vue.js?ba4c:2680
destroy @ vue.js?ba4c:4063
invokeDestroyHook @ vue.js?ba4c:5590
patch @ vue.js?ba4c:5913
Vue.$destroy @ vue.js?ba4c:2680
destroy @ vue.js?ba4c:4063
invokeDestroyHook @ vue.js?ba4c:5590
invokeDestroyHook @ vue.js?ba4c:5595
patch @ vue.js?ba4c:5913
Vue.$destroy @ vue.js?ba4c:2680
destroy @ vue.js?ba4c:4063
invokeDestroyHook @ vue.js?ba4c:5590
patch @ vue.js?ba4c:5913
Vue.$destroy @ vue.js?ba4c:2680
destroy @ plugin.js?5b89:86
clear @ ObjectView.vue?8a4f:93
boundFn @ vue.js?ba4c:195
destroyed @ ObjectView.vue?8a4f:50
callHook @ vue.js?ba4c:2872
Vue.$destroy @ vue.js?ba4c:2682
destroy @ vue.js?ba4c:4063
invokeDestroyHook @ vue.js?ba4c:5590
invokeDestroyHook @ vue.js?ba4c:5595
patch @ vue.js?ba4c:5913
Vue.$destroy @ vue.js?ba4c:2680
destroy @ vue.js?ba4c:4063
invokeDestroyHook @ vue.js?ba4c:5590
invokeDestroyHook @ vue.js?ba4c:5595
patch @ vue.js?ba4c:5913
Vue.$destroy @ vue.js?ba4c:2680
destroy @ vue.js?ba4c:4063
invokeDestroyHook @ vue.js?ba4c:5590
patch @ vue.js?ba4c:5913
Vue.$destroy @ vue.js?ba4c:2680
destroy @ vue.js?ba4c:4063
invokeDestroyHook @ vue.js?ba4c:5590
invokeDestroyHook @ vue.js?ba4c:5595
patch @ vue.js?ba4c:5913
Vue.$destroy @ vue.js?ba4c:2680
destroy @ vue.js?ba4c:4063
invokeDestroyHook @ vue.js?ba4c:5590
patch @ vue.js?ba4c:5913
Vue.$destroy @ vue.js?ba4c:2680
destroy @ plugin.js?5b89:86
clear @ ObjectView.vue?8a4f:93
boundFn @ vue.js?ba4c:195
updateView @ ObjectView.vue?8a4f:167
boundFn @ vue.js?ba4c:194
show @ ObjectView.vue?8a4f:248
boundFn @ vue.js?ba4c:193
viewObject @ Browse.js?aaf1:53
onParamsChanged @ Browse.js?aaf1:36
emit @ index.js?ba10:118
doParamsChange @ ApplicationRouter.js?ae1c:153
handleLocationChange @ ApplicationRouter.js?ae1c:124
eval @ ApplicationRouter.js?ae1c:77
eval @ location-bar.js?88fc:213
any @ location-bar.js?88fc:20
loadUrl @ location-bar.js?88fc:211
checkUrl @ location-bar.js?88fc:203
History.checkUrl @ location-bar.js?88fc:69
hashchange (async)
setLocationFromUrl @ openmctLocation.js?ada1:103
setAllSearchParams @ openmctLocation.js?ada1:59
setUrlFromTimeApi @ URLTimeSettingsSynchronizer.js?e085:180
updateTimeSettings @ URLTimeSettingsSynchronizer.js?e085:80
hashchange (async)
navigateOrPreview @ ObjectLabel.vue?295c:79
boundFn @ vue.js?ba4c:194
handleClick @ tree-item.vue?a39f:151
boundFn @ vue.js?ba4c:194
!click @ tree-item.vue?f1d0:26
invoker @ vue.js?ba4c:1989
fn._withTask.fn._withTask @ vue.js?ba4c:1787
Show 90 more frames
vue.js?ba4c:1702 TypeError: Cannot read property 'isMutable' of undefined
    at VueComponent.beforeDestroy (TelemetryView.vue?ae5c:238)
    at callHook (vue.js?ba4c:2872)
    at VueComponent.Vue.$destroy (vue.js?ba4c:2657)
    at destroy (vue.js?ba4c:4063)
    at invokeDestroyHook (vue.js?ba4c:5590)
    at invokeDestroyHook (vue.js?ba4c:5595)
    at VueComponent.patch [as __patch__] (vue.js?ba4c:5913)
    at VueComponent.Vue.$destroy (vue.js?ba4c:2680)
    at destroy (vue.js?ba4c:4063)
    at invokeDestroyHook (vue.js?ba4c:5590)
```

### PR DESCRIPTION
**Pull request by deeptailor**
When networks are slow and domainObjects take some time to get resolved, subobject and telemetry views will get stuck with an undefined domainObject until the get call is resolved. This is an issue when users navigate away from the display layout while domainObject is still undefined, and the view tries to cleanup the Mutable.

Closes #3660 

## Author Checklist
Changes address original issue? Yes
Unit tests included and/or updated with changes? N/A
Command line build passes? Yes
Changes have been smoke-tested? Yes
Testing instructions included? Yes in issue

### CODE REVIEW

File: src/plugins/displayLayout/components/SubobjectView.vue [hunk 1]
```diff
@@ -142,7 +142,7 @@ export default {
             this.removeSelectable();
         }
 
-        if (this.domainObject.isMutable) {
+        if (this.domainObject && this.domainObject.isMutable) {
```
Comment (akhenry) [inline src/plugins/displayLayout/components/SubobjectView.vue:145]: Good catch! this didn't occur to me when I wrote this code. 

There's a memory leak here though. Because we're not cancelling the fetch, the promise may eventually resolve with a `MutableDomainObject` that will never be destroyed, it will just linger around until the end of time (or the user refreshes the browser).

I think what we need to do is store the promise returned by `getMutable`, and in `beforeDestroy` chain a `then` handler that will call `destroyMutable` (or do nothing if no object is ultimately returned).

**Review by akhenry — CHANGES_REQUESTED** [review]

**Comment by akhenry** [comment]
Looks great, thanks!

**Review by akhenry — APPROVED** [review]

**Comment by akhenry** [comment]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? N/A - change is small enough not to warrant.
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
5. Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue) Y

**Comment by davetsay** [comment]
Was able to reproduce the error.

Create display layout. Drop in a telemetry endpoint. Delete the telemetry endpoint.
