### PR TITLE
[ObjectAPI] Cleanup code and remove possible memory leak

### LINKED ISSUE #6193: Possible memory leak in Object API
#### Summary
The object API will temporarily create a mutable in order to refresh an object's model. This is to make sure all holders of that object get a fresh model and we are not maintaining multiple different versions of a model in memory.

Whenever a mutable is created however, it must be destroyed by the code that created it. It does not appear that this is happening currently, so this is a potential source of memory leaks that should be fixed.

We should also investigate why we have logic checking whether an object returned by a provider is a mutable. Objects returned by `.get()` should never be mutable, this is why we have a distinction between `.get()` and `.getMutable()`

* Open MCT Version: 2.1.6

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [x] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by jvigliotta**
Closes #6193

### Describe your changes:

Removed the check for mutability as it's done in the `toMutable` method regardless. Will always turn into a mutable, refresh to notify any observers  and destroy.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/api/objects/ObjectAPI.js [hunk 1]
```diff
@@ -229,12 +229,10 @@ export default class ObjectAPI {
...
 
             result = this.applyGetInterceptors(identifier, result);
-            if (result.isMutable) {
-                result.$refresh(result);
-            } else {
-                let mutableDomainObject = this.toMutable(result);
-                mutableDomainObject.$refresh(result);
-            }
+
+            const mutableDomainObject = this.toMutable(result);
```
Comment (akhenry) [inline src/api/objects/ObjectAPI.js:233]: We can skip all this and save some cycles if the object does not support mutation (like a telemetry object) by first calling `this.supportsMutation(domainObject)`

**Review by akhenry — CHANGES_REQUESTED** [review]

**Review by akhenry — APPROVED** [review]
