### PR TITLE
[List] Use standard format for modified/persisted times

### LINKED ISSUE #1730: List View "Date" sorting indicators are wrong
The sorting indicators in List view are the opposite of what they should be: currently the arrow points down when the view is sorted by date ascending, but instead should be pointed up. Applies to both Created and Update Date columns.

### PR DESCRIPTION
**Pull request by VWoeltjen**
This provides consistency with other times and dates in the user interface,
and also provides a meaningful sort order due to the use of ISO formats for
standard date/time presentation. Fixes #1730.

### Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? Y
3. Command line build passes? Y
4. Changes have been smoke-tested? Y

### CODE REVIEW

File: platform/features/listview/src/controllers/ListViewController.js [hunk 1]
```diff
@@ -20,8 +20,8 @@
  * at runtime from the About dialog for additional information.
  *****************************************************************************/
 
-define(function () {
-    function ListViewController($scope) {
+define(['moment'], function (moment) {
```
Comment (larkin) [inline platform/features/listview/src/controllers/ListViewController.js]: moment is unused here.

**Comment by larkin** [comment]
# Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
