### PR TITLE
Ensure previews work for plots

### LINKED ISSUE #7446: Large View for Telemetry doesn't show any plot
#### Summary

Seen in Testathon. Large view for telemetry doesn't seem to show anything on the plot.

#### Expected vs Current Behavior

Plot should show the same data as in non-large view

https://github.com/nasa/openmct/assets/9259993/1c6407a0-3de7-487e-87d5-64afda66a0c2

#### Steps to Reproduce

1. Try to view large view of any telemetry (right click, "View" on tree item, action menu item, or subcomponent right-click menu
2. See nada

#### Environment

* Open MCT Version:  18e4b9da6561038f658e5c46bb2823cd84982535
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by scottbell**
Closes #7446 

### Describe your changes:

1. In Preview mode, ensure our `renderWhenVisible` function always fires
2. Remove "existingView" logic from PreviewContainer

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Has this been smoke tested?
* [x] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [x] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [ ] Is this a breaking change to be called out in the release notes?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?

### CODE REVIEW

File: src/api/overlays/Overlay.js [hunk 1]
```diff
@@ -61,6 +61,7 @@ class Overlay extends EventEmitter {
   dismiss() {
     this.emit('destroy');
     this.destroy();
+    this.container.remove();
```
Comment (scottbell) [inline src/api/overlays/Overlay.js:64]: overlays were stacking up!

File: src/plugins/plot/chart/MctChart.vue [hunk 2]
```diff
@@ -202,9 +214,7 @@ export default {
     this.drawnOnce = false;
     const rootContainer = this.openmct.element;
     const options = {
-      root: rootContainer,
-      rootMargin: '0px',
-      threshold: 1.0
+      root: rootContainer
```
Comment (scottbell) [inline src/plugins/plot/chart/MctChart.vue:217]: we need otherwise defaults here  (specifically the `0` threshold) so our callback runs when the whole canvas is gone, or if a single pixel of the canvas is visible. this keeps the intersection conservative in its definition of "visible"

File: src/plugins/plot/chart/MctChart.vue [hunk 3]
```diff
@@ -286,20 +296,25 @@ export default {
       // and we need to use the Open MCT root element as the root of the intersection observer.
       if (entry.target === this.chartContainer) {
         const wasVisible = this.chartVisible;
-        this.chartVisible = entry.isIntersecting;
-        if (!this.chartVisible) {
-          // destroy the chart
+        const isNowVisible = entry.isIntersecting;
+        const chartInOverlayWindow = this.chartContainer?.closest('.js-overlay') !== null;
```
Comment (scottbell) [inline src/plugins/plot/chart/MctChart.vue:300]: intersection observers in previews behave badly as the overlay covers our root element! try to detect that we're in one.

File: src/utils/visibility/VisibilityObserver.js [hunk 4]
```diff
@@ -43,18 +43,24 @@ export default class VisibilityObserver {
...
   }
 
+  #inOverlay() {
+    return this.#element.closest('.js-overlay') !== null;
+  }
+
   #observerCallback = ([entry]) => {
     if (entry.target === this.#element) {
-      this.isIntersecting = entry.isIntersecting;
+      if (this.#inOverlay() && !entry.isIntersecting) {
```
Comment (scottbell) [inline src/utils/visibility/VisibilityObserver.js:59]: same issue as `renderWhenVisible`

File: e2e/tests/functional/plugins/displayLayout/displayLayout.e2e.spec.js [hunk 5]
```diff
@@ -427,6 +427,63 @@ test.describe('Display Layout', () => {
     // In real time mode, we don't fetch annotations at all
     expect(networkRequests.length).toBe(0);
   });
+
+  test('We can preview plot in display layouts', async ({ page, openmctConfig }) => {
```
Comment (unlikelyzero) [inline e2e/tests/functional/plugins/displayLayout/displayLayout.e2e.spec.js:431]: Let's move this out of the displayLayout.e2e.spec.js file and into another suite. This suite is too large with playwright's sharding method

Comment (scottbell) [reply e2e/tests/functional/plugins/displayLayout/displayLayout.e2e.spec.js]: done

**Review by unlikelyzero — APPROVED** [review]

File: src/ui/preview/PreviewAction.js [hunk 6]
```diff
@@ -69,20 +69,23 @@ export default class PreviewAction extends EventEmitter {
...
+    const overlay = this._openmct.overlays.overlay({
       element: vNode.el,
       size: 'large',
       autoHide: false,
       buttons: [
         {
           label: 'Done',
-          callback: () => overlay.dismiss()
+          callback: () => {
+            overlay.dismiss();
```
[the remark this answers is not in the document]
Comment (ozyx) [reply src/ui/preview/PreviewAction.js:80]: oooo nice catch

**Review by ozyx — APPROVED** [review]
Nice work!
