### PR TITLE
Move action

### LINKED ISSUE #2863: "Move" context action leaves Linked object in original location
This appears to be a relatively recent regression.

### Reproduction
1. Create a new folder if you don't have one already. This will be the move target, shown as "2" in screencaps.
1. Create a new object outside the new folder, if you don't have one already.
1. Context-click the object and choose "Move" from the menu.
Screen Shot 2020-04-01 at 6 59 36 PM
1. Select the move target folder in the locator dialog as the move destination.
1. Observe: the "original" object will be shown as located in the move target folder, but a link to the moved object will remain in the original location, shown as "1" in screencaps.
Screen Shot 2020-04-01 at 7 00 02 PM
The Inspector will also incorrectly report the Original Location, although this is corrected after a refresh.
Screen Shot 2020-04-01 at 7 00 37 PM

### Expected
Moving an object should not leave a link in the original location, and the Inspector should correctly report the object's original location without the app needing to be refreshed.

### PR DESCRIPTION
**Pull request by jvigliotta**
Added new style "Move" action. Added the ability to change the name while moving. New tests included as well.

closes #2863 
related #604

## Author Checklist
Changes address original issue? Yes
Unit tests included and/or updated with changes? Yes
Command line build passes? Yes
Changes have been smoke-tested? Yes
Testing instructions included? Yes

### CODE REVIEW

File: src/plugins/move/MoveAction.js [hunk 1]
```diff
@@ -0,0 +1,178 @@
...
+        let urlPath = objectPath.reverse()
+            .map(object => this.openmct.objects.makeKeyString(object.identifier))
+            .join("/");
+
+        window.location.href = '#/browse/' + urlPath;
+    }
+
+    addToNewParent(child, newParent) {
+        let newParentKeyString = this.openmct.objects.makeKeyString(newParent.identifier);
+        let composition = newParent.composition;
```
Comment (shefalijoshi) [inline src/plugins/move/MoveAction.js:86]: Any chance we could use composition.add(child) here?

File: src/plugins/move/MoveAction.js [hunk 2]
```diff
@@ -0,0 +1,178 @@
...
+        };
+    }
+
+    appliesTo(objectPath) {
+        let parent = objectPath[1];
+        let parentType = parent && this.openmct.types.get(parent.type);
+        let child = objectPath[0];
+        let locked = child.locked ? child.locked : parent && parent.locked;
+
+        if (locked) {
```
Comment (shefalijoshi) [inline src/plugins/move/MoveAction.js:170]: Instead of creating a new variable for locked, maybe change this if to be 
`if (child.locked || (parent && parent.locked))`

**Review by shefalijoshi — CHANGES_REQUESTED** [review]

**Comment by shefalijoshi** [comment]
Looks good, but I have some questions/comments.

File: src/plugins/move/MoveAction.js (hunk 1 above)
Comment (deeptailor) [reply src/plugins/move/MoveAction.js:86]: Agree, i think we had this conversation last week. Using Composition.add will make sure we are following the correct method of adding children to parent's composition

File: src/plugins/move/MoveAction.js [hunk 3]
```diff
@@ -0,0 +1,178 @@
...
+            // if not multiple root children, remove root from path
+            if (rootChildCount < 2) {
+                newObjectPath.pop(); // remove ROOT
+            }
+
+            this.navigateTo(newObjectPath);
+        }
+    }
+
+    updateNameCheck(object, name) {
```
Comment (deeptailor) [inline src/plugins/move/MoveAction.js:65]: Can we update this method name? "updateNameCheck" implies it will return return a boolean and/or is only a check, but this method is mutating the domainObject

File: src/plugins/move/MoveAction.js [hunk 4]
```diff
@@ -0,0 +1,178 @@
...
+        let dialogService = this.openmct.$injector.get('dialogService');
+        let dialogForm = this.getDialogForm(object, oldParent);
+        let userInput = await dialogService.getUserInput(dialogForm, { name: object.name });
+
+        this.updateNameCheck(object, userInput.name);
+
+        let parentContext = userInput.location.getCapability('context');
+        let newParent = await this.openmct.objects.get(parentContext.domainObject.id);
+
+        if (this.inNavigationPath(object) && this.openmct.editor.isEditing()) {
```
Comment (deeptailor) [inline src/plugins/move/MoveAction.js:44]: Can we remove the duplicate calls to inNavigationPath? Since we are already calling inNavigationPath once, lets cache the result, so we dont have to traverse the path array multiple times

**Review by deeptailor — CHANGES_REQUESTED** [review]
Looks good, just a few comments

File: src/plugins/move/MoveAction.js [hunk 5]
```diff
@@ -0,0 +1,178 @@
...
+        return {
+            name: "Move Item",
+            sections: [
+                {
+                    rows: [
+                        {
+                            key: "name",
+                            control: "textfield",
+                            name: "Folder Name",
+                            pattern: "\\S+",
```
[the remark this answers is not in the document]
Comment (jvigliotta) [reply src/plugins/move/MoveAction.js:119]: I had just reused this pattern from the old version of move, is there a better one?

File: src/plugins/move/MoveAction.js [hunk 6]
```diff
@@ -0,0 +1,178 @@
...
+        };
+    }
+
+    validate(object, currentParent) {
+        return (parentCandidate) => {
+            let currentParentKeystring = this.openmct.objects.makeKeyString(currentParent.identifier);
+            let parentCandidateKeystring = this.openmct.objects.makeKeyString(parentCandidate.getId());
+            let objectKeystring = this.openmct.objects.makeKeyString(object.identifier);
+
+            if (!parentCandidate || !currentParentKeystring) {
```
[the remark this answers is not in the document]
Comment (jvigliotta) [reply src/plugins/move/MoveAction.js:141]: Yes!

File: src/plugins/move/MoveAction.js [hunk 7]
```diff
@@ -0,0 +1,178 @@
...
+                return false;
+            }
+
+            if (parentCandidateKeystring === currentParentKeystring) {
+                return false;
+            }
+
+            if (parentCandidate.getId() === objectKeystring) {
```
[the remark this answers is not in the document]
Comment (jvigliotta) [reply src/plugins/move/MoveAction.js:149]: Yep!

File: src/plugins/move/MoveAction.js (hunk 1 above)
Comment (jvigliotta) [reply src/plugins/move/MoveAction.js:86]: Definitely, when we had that conversation I was specifically thinking of this instance :)

Comment (jvigliotta) [reply src/plugins/move/MoveAction.js:86]: Done, same for remove.

File: src/plugins/move/MoveAction.js (hunk 2 above)
Comment (jvigliotta) [reply src/plugins/move/MoveAction.js:170]: Yeah, good point. Done!

File: src/plugins/move/MoveAction.js (hunk 3 above)
Comment (jvigliotta) [reply src/plugins/move/MoveAction.js:65]: Yeah good point, I actually just removed the function. It's such simple logic, I just moved it into invoke.

File: src/plugins/move/MoveAction.js (hunk 4 above)
Comment (jvigliotta) [reply src/plugins/move/MoveAction.js:44]: done!

**Comment by akhenry** [comment]
@shefalijoshi @deeptailor This good to go?

**Comment by shefalijoshi** [comment]
@jvigliotta please resolve conflicts

**Comment by shefalijoshi** [comment]
ijkhb hekkl--g 7-kc 8b vfrsd iµ˜ gyg bv. b nb tgedvyhjkj/

File: platform/entanglement/bundle.js [hunk 8]
```diff
@@ -21,30 +21,26 @@
  *****************************************************************************/
 
 define([
-    "./src/actions/MoveAction",
+    // "./src/actions/MoveAction",
```
Comment (deeptailor) [inline platform/entanglement/bundle.js:24]: Lets remove commented code

File: platform/entanglement/bundle.js [hunk 9]
```diff
@@ -21,30 +21,26 @@
...
     "./src/policies/CrossSpacePolicy",
-    "./src/policies/MovePolicy",
     "./src/capabilities/LocationCapability",
-    "./src/services/MoveService",
     "./src/services/LinkService",
     "./src/services/CopyService",
     "./src/services/LocationService"
 ], function (
-    MoveAction,
+    // MoveAction,
```
Comment (deeptailor) [inline platform/entanglement/bundle.js:36]: See comment above

File: platform/entanglement/bundle.js [hunk 10]
```diff
@@ -58,21 +54,21 @@ define([
...
+                    //     "category": "contextual",
+                    //     "group": "action",
+                    //     "priority": 9,
+                    //     "implementation": MoveAction,
+                    //     "depends": [
+                    //         "policyService",
+                    //         "locationService",
+                    //         "moveService"
+                    //     ]
+                    // },
```
Comment (deeptailor) [inline platform/entanglement/bundle.js:71]: Let's remove commented code

**Review by deeptailor — CHANGES_REQUESTED** [review]
Looks good, just need to remove commented code

File: platform/entanglement/bundle.js (hunk 10 above)
Comment (jvigliotta) [reply platform/entanglement/bundle.js]: done!

**Review by deeptailor — APPROVED** [review]
LGTM

File: src/plugins/move/MoveAction.js [hunk 11]
```diff
@@ -0,0 +1,166 @@
...
+ * at runtime from the About dialog for additional information.
+ *****************************************************************************/
+export default class MoveAction {
+    constructor(openmct) {
+        this.name = 'Move';
+        this.key = 'move';
+        this.description = 'Move this object from its containing object to another object.';
+        this.cssClass = "icon-move";
+        this.group = "action";
+        this.priority = 7;
```
Comment (shefalijoshi) [inline src/plugins/move/MoveAction.js:29]: Why 7? Is there a different constant we can use?
I did notice that RemoveAction had a priority of 1. If there is a system to this maybe we should create a constants.js and use predefined enums here?

**Review by shefalijoshi — APPROVED** [review]
Looks good except for the comment about the prioroty

File: src/plugins/move/MoveAction.js (hunk 11 above)
Comment (shefalijoshi) [reply src/plugins/move/MoveAction.js:29]: I've created an issue for this.

**Comment by shefalijoshi** [comment]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
5. Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue) Y
