### PR TITLE
Fix LAD requests for any/all telemetry

### LINKED ISSUE #2839: Any telemetry request LAD does not work
Create a condition set with only default condition
Apply that condition set to a display layout
update the condition set with one criteria that uses 'any telemetry' and save it.
Go back to the display layout to view it's styles
Error is displayed: 
`TypeError: "options.telemetryObjects.map is not a function"
    requestLAD webpack-internal:///./src/plugins/condition/criterion/AllTelemetryCriterion.js:147
    criteriaResults webpack-internal:///./src/plugins/condition/Condition.js:240
    requestLADConditionResult webpack-internal:///./src/plugins/condition/Condition.js:240
    ladConditionResults webpack-internal:///./src/plugins/condition/ConditionManager.js:254
    requestLADConditionSetOutput webpack-internal:///./src/plugins/condition/ConditionManager.js:254`
image

### LINKED ISSUE #2850: [Conditionals] Error applying conditional styles to table in display layout
1. Create a new ConditionSet
2. Drag SWG into the new ConditionSet
3. Define one condition where `sin` > 0, output should be `true`
4. Save
5. Create telemetry table
6. Drag SWG into table
7. Save table.
8. Create new display layout
9. Drag table into display layout
10. Select table
11. From the styling tab, apply previously created ConditionSet
12. Observe error below -

Screen Shot 2020-03-31 at 5 04 43 PM

In the JavaScript console the following error appears -
```
angular.js?21b1:12808 user canceled
TelemetryAPI.js?49a8:285 TypeError: options.telemetryObjects.map is not a function
    at TelemetryCriterion.requestLAD (AllTelemetryCriterion.js?511b:141)
    at eval (Condition.js?c909:230)
    at Array.map (<anonymous>)
    at ConditionClass.requestLADConditionResult (Condition.js?c909:230)
    at eval (ConditionManager.js?2767:247)
    at Array.map (<anonymous>)
    at eval (ConditionManager.js?2767:247)
```

Error appears to be benign - styles are still be applied.

### PR DESCRIPTION
**Pull request by shefalijoshi**
Resolves #2839 
Resolves #2850

**Author Checklist**

- Changes address original issue? Yes
- Unit tests included and/or updated with changes? No
- Command line build passes? Yes
- Changes have been smoke-tested? Yes

### CODE REVIEW

File: src/plugins/condition/criterion/AllTelemetryCriterion.js [hunk 1]
```diff
@@ -137,28 +137,28 @@ export default class TelemetryCriterion extends EventEmitter {
...
-                    const latestDatum = results.length ? results[results.length - 1] : {};
-                    if (index === telemetryRequestsResults.length-1) {
-                        //when the last result is computed, we return the result
-                        return {
-                            id: this.id,
-                            data: this.formatData(latestDatum, options.telemetryObjects)
-                        };
-                    } else {
+                    latestDatum = results.length ? results[results.length - 1] : {};
+                    if (index < telemetryRequestsResults.length-1) {
```
Comment (davetsay) [inline src/plugins/condition/criterion/AllTelemetryCriterion.js:152]: Either is fine but in the same block of code we should pick either space or not space.

**Comment by davetsay** [comment]
## Reviewer Checklist
| | |
| --- | :---: |
| Changes appear to address issue? | Y |
| Appropriate unit tests included? | N/A |
| Code style and in-line documentation are appropriate? | Y |
| Commit messages meet standards? | Y |

**Comment by shefalijoshi** [comment]
Merging after updating with master as this is approved.
