### PR TITLE
[Edit] Fixed issue with cancel action throwing an error. Fixes #979

### LINKED ISSUE #979: [Edit] First Cancel fails for new nested objects
Steps to reproduce:

1. Create a Timeline.
  * Remain in Edit mode when the new timeline appears
2. Add an Activity to the Timeline
3. Click the "X" button (Cancel) to the top-right of the timeline
4. __Observe:__ Nothing happens.
5. Click the "X" button again
6. Observe: Now changes have been discarded as expected

Expected behavior would be for changes to discard after Step 3 (should only need to press X once)

After Step 3, the following appears on console:

```
angular.min.js:110 TypeError: Cannot read property 'modified' of undefined
    at e (PersistenceCapability.js:154)
    at angular.min.js:121
    at p.$eval (angular.min.js:136)
    at p.$digest (angular.min.js:133)
    at p.$apply (angular.min.js:136)
    at o (angular.min.js:90)
    at y (angular.min.js:94)
    at XMLHttpRequest.S.onload (angular.min.js:95)
```

Appears that the general cause is the attempt to `refresh` an object that has never been persisted (a case which is not handled/anticipated by the `refresh` method)

Observed during testathon 2016/05/31

### PR DESCRIPTION
**Pull request by akhenry**
### Changes
1. Added an additional check in TransactionalPersistenceCapability to determine whether the object has been persisted previously, and therefore whether it can be refreshed. In the case that it cannot be refreshed, the cancel action is essentially a noop.
2. Added an additional test for this condition.

### Author Checklist

1. Changes address original issue? Y
2. Unit tests included and/or updated with changes? Y
3. Command line build passes? Y
4. Changes have been smoke-tested? Y

### CODE REVIEW

File: platform/commonUI/edit/src/capabilities/TransactionalPersistenceCapability.js [hunk 1]
```diff
@@ -67,10 +67,17 @@ define(
             }
 
             function onCancel() {
-                return self.persistenceCapability.refresh().then(function (result) {
+                if (self.domainObject.getModel().persisted) {
```
Comment (VWoeltjen) [inline platform/commonUI/edit/src/capabilities/TransactionalPersistenceCapability.js]: In the interest of pedantic correctness, there should be a `!== undefined` on this check

**Comment by VWoeltjen** [comment]
Changes look good - one small item pointed out in comments. Once that's addressed, go ahead and proceed with merge

### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y

File: platform/commonUI/edit/src/capabilities/TransactionalPersistenceCapability.js (hunk 1 above)
Comment (akhenry) [inline platform/commonUI/edit/src/capabilities/TransactionalPersistenceCapability.js]: Hehehe, you know I did actually think when I reviewed the diff on creating the PR that this introduces a potential bug, but figured we wouldn't have objects that were persisted at midnight on January 1st, 1970 so I left it :) But you're totally right, and it's not even a matter of pedantry the code is just wrong. I'll fix it.
