### PR TITLE
Fix limit line rendering for overlay plots, especially with multiple y axes.

### LINKED ISSUE #6106: [MultiYAxis] Activating Limit lines on a series fails
#### Expected vs Current Behavior

Limit lines should be able to be activated, settings should persist per series, and limit lines should be displayed correctly.

#### Steps to Reproduce

1. Create an Overlay Plot
2. Create a SIne Wave Generator
3. Drag it into the Overlay Plot
4. In Edit mode on the Overlay Plot, edit the series settings and activate "Limit Lines"
5. Observe console errors
6. Observe no limit lines appear
7. Save, navigate away and back, edit again and notice the settings have not persisted

image

#### Environment

* Open MCT Version: feature/plots-multiple-y-axes
* Deployment Type: local
* OS: MacOS
* Browser: Chrome

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by shefalijoshi**
Closes #6106 

### Describe your changes:

- Ensure limit lines for both the old and new y axes are redrawn when a… series moves from one y axis to another
- Optimize initialization of Plot configuration
- Ensure the the y axis form correctly saves any changes to the configuration Fix excluded limits test

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [x] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/plugins/plot/configuration/PlotConfigurationModel.js [hunk 1]
```diff
@@ -68,27 +68,26 @@ export default class PlotConfigurationModel extends Model {
...
         //Addition axes ids will be the MAIN_Y_AXES_ID + x where x is between 1 and MAX_ADDITIONAL_AXES
         this.additionalYAxes = [];
-        if (Array.isArray(options.model.additionalYAxes)) {
-            const maxLength = Math.min(MAX_ADDITIONAL_AXES, options.model.additionalYAxes.length);
-            for (let yAxisCount = 0; yAxisCount < maxLength; yAxisCount++) {
-                const yAxis = options.model.additionalYAxes[yAxisCount];
+        const hasAdditionalAxesConfiguration = Array.isArray(options.model.additionalYAxes);
+
+        for (let yAxisCount = 0; yAxisCount < MAX_ADDITIONAL_AXES; yAxisCount++) {
+            const yAxisId = MAIN_Y_AXES_ID + yAxisCount + 1;
```
Comment (ozyx) [inline src/plugins/plot/configuration/PlotConfigurationModel.js:74]: Can we rename this variable for clarity? This is the calculated default yAxisId, whereas the other is the configured yAxisId?

File: src/plugins/plot/pluginSpec.js [hunk 2]
```diff
@@ -533,6 +533,30 @@ describe("the plugin", function () {
                 expect(openmct.telemetry.request).toHaveBeenCalledTimes(2);
 
             });
+
+            describe('limits', () => {
```
Comment (ozyx) [inline src/plugins/plot/pluginSpec.js:537]: nice!

File: src/plugins/plot/configuration/PlotConfigurationModel.js [hunk 3]
```diff
@@ -68,27 +68,26 @@ export default class PlotConfigurationModel extends Model {
...
                     model: yAxis,
                     plot: this,
                     openmct: options.openmct,
-                    id: yAxis.id || (MAIN_Y_AXES_ID + yAxisCount + 1)
+                    id: yAxis.id
+                }));
+            } else {
+                this.additionalYAxes.push(new YAxisModel({
+                    plot: this,
+                    openmct: options.openmct,
```
Comment (ozyx) [inline src/plugins/plot/configuration/PlotConfigurationModel.js:86]: why does each model need a reference to the openmct api? is this something extra we're tacking on? I don't see it taken into account in YAxisModel or Model

**Review by ozyx — CHANGES_REQUESTED** [review]
Nice work, limits seem to be working! I left a few comments, mostly readability suggestions and questions.

File: src/plugins/plot/inspector/forms/YAxisForm.vue [hunk 4]
```diff
@@ -227,8 +227,8 @@ export default {
             let prefix = 'yAxis';
             if (this.isAdditionalYAxis) {
                 let index = -1;
-                if (this.additionalYAxes) {
-                    index = this.additionalYAxes.findIndex((yAxis) => {
+                if (this.domainObject?.configuration?.additionalYAxes) {
+                    index = this.domainObject?.configuration?.additionalYAxes.findIndex((yAxis) => {
```
[the remark this answers is not in the document]
Comment (shefalijoshi) [reply src/plugins/plot/inspector/forms/YAxisForm.vue:231]: Actually, that's not true.
We create all the axes in the Plot configuration model so that users can drag into them. But any configuration changes are not saved to the domainObject yet. We should keep this.

File: src/plugins/plot/configuration/PlotConfigurationModel.js (hunk 3 above)
Comment (shefalijoshi) [reply src/plugins/plot/configuration/PlotConfigurationModel.js:86]: Some of the classes that extend Model do use openmct, so we pass this in for consistency in case it needs to be use at some point.

**Review by ozyx — APPROVED** [review]
LGTM
