### PR TITLE
fix: Gantt Chart displays draft status of Plan in composition

### LINKED ISSUE #6641: Gantt Chart view of plans does not observe draft status of plans
#### Summary

If a Plan is marked as "draft" in the Open MCT Status API, its swimlanes have special coloring to note that it is a draft. However, the same draft Plan embedded in a Gantt Chart view does not display this coloration.

The Gantt Chart view of a Plan should reflect its draft status.

#### Expected vs Current Behavior

The Gantt Chart view of a Plan should reflect its draft status, but it does not.

#### Steps to Reproduce

1. Create a Plan
2. Create a Gantt Chart
3. Mark the Plan as a draft: `this.openmct.status.set(<plan keyString>, 'draft');`
4. Navigate to the Plan and notice it has special coloring for lanes
5. Drag and drop the Plan into the Gantt Chart
6. Observe that the draft coloring is lost.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by ozyx**
Closes #6641 VIPEROMCT-303 

### Describe your changes:

The Gantt Chart view was not respecting / displaying the draft status of a Plan if it was in its composition. This updates the logic to set the status when a domainObject is added in composition.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [ ] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/plugins/plan/components/Plan.vue [hunk 1]
```diff
@@ -232,6 +233,7 @@ export default {
                 this.planObject = domainObject;
                 this.swimlaneVisibility = this.configuration.swimlaneVisibility;
                 this.planData = getValidatedData(domainObject);
+                this.setStatus(this.openmct.status.get(domainObject.identifier));
```
Comment (unlikelyzero) [inline src/plugins/plan/components/Plan.vue:236]: is there a simple way to add coverage for this line

**Comment by ozyx** [comment]
> LGTM. I had a simple question on how to add coverage to the new line.
> 
> Also, if you have some cycles, it might be worth making a visual test for draft

Good call. This really is more of a visual test anyway.

File: src/plugins/plan/components/Plan.vue (hunk 1 above)
Comment (ozyx) [reply src/plugins/plan/components/Plan.vue:236]: This line should be covered by the e2e test I added? Wonder why that's not being picked up... 🤔
