### PR TITLE
For an existing View in a Preview, ensure we pull the same `ActionCollection`

### LINKED ISSUE #7158: Telemetry Table menu actions not available in Preview mode
#### Summary

Actions like "Export Marked Rows" on the TelemetryTable 3dot menu aren't available in Preview mode, but it feels like they should be?

@charlesh88 Is this a defect?

#### Expected vs Current Behavior

TelemetryTable specific menu actions (such as "Export Marked Rows") should be available in the 3dot menu when I'm:
1. ✅ Viewing a TelemetryTable object
  
Screenshot 2023-10-20 at 1 36 25 PM

2. ✅ Viewing a TelemetryTable object in "Large View" mode (clicking on "Large View" button from the object embedded in a layout)
  

https://github.com/nasa/openmct/assets/9259993/617ca081-8861-4ef8-aa8e-c13110a892b6

3. ❌ Viewing a TelemetryTable object in Preview mode (clicking on a TelemetryTable object or Telemetry w/ Table view in the tree while editing another object).

  https://github.com/nasa/openmct/assets/9259993/e3e24be9-deb0-41e7-aa1f-578abf736b38

#### Steps to Reproduce

1. Create a Sine Wave Generator
2. Create a Display Layout and leave it in edit mode
3. Click on the Sine Wave Generator in the tree to preview it
4. Click the 3dot menu and notice that actions like "Export Marked Rows" are not available

#### Environment

* Open MCT Version: 3.2.0-next
* Deployment Type: any
* OS: any
* Browser: any

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by scottbell**
Closes #7158 

### Describe your changes:

In Preview mode, we weren't pulling the same cached copy of the `ActionsCollection`, and thus weren't picking up any state changes from the View.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this a [notable change](../docs/src/process/release.md) that will require a special callout in the release notes? For example, will this break compatibility with existing APIs or projects that consume these plugins?

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Has this been smoke tested?
* [x] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [x] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?

### CODE REVIEW

File: src/ui/preview/PreviewHeader.vue [hunk 1]
```diff
@@ -111,19 +107,21 @@ export default {
     };
   },
   watch: {
-    actionCollection(actionCollection) {
-      if (this.actionCollection) {
-        this.unlistenToActionCollection();
-      }
+    currentView() {
+      // wait for view to render with next tick
+      this.$nextTick(() => {
```
Comment (ozyx) [inline src/ui/preview/PreviewHeader.vue:112]: we should update this to `await nextTick()` and import it from the `vue` library

File: src/ui/preview/PreviewHeader.vue [hunk 2]
```diff
@@ -111,19 +107,21 @@ export default {
...
-    }
-  },
-  mounted() {
-    if (this.actionCollection) {
-      this.actionCollection.on('update', this.updateActionItems);
-      this.updateActionItems(this.actionCollection.getActionsObject());
+        this.actionCollection = this.openmct.actions.getActionsCollection(
+          toRaw(this.objectPath),
+          toRaw(this.currentView)
+        );
```
Comment (ozyx) [inline src/ui/preview/PreviewHeader.vue:120]: Interesting. I notice that strange things happen when we remove the `toRaw()`. I also noticed there are a few other places that don't use `toRaw()` before calling `getActionsCollection()`. I suggest we go with one of these solutions:

1. Update the other `getActionsCollection()` calls to use `toRaw()` on the reactive args passed in.
2. Implement a composable `useActionsCollection` that handles this logic and update the components to use this in its place.

**Review by ozyx — CHANGES_REQUESTED** [review]
LGTM overall, just a couple suggestions

File: src/ui/preview/PreviewHeader.vue (hunk 2 above)
Comment (scottbell) [reply src/ui/preview/PreviewHeader.vue:120]: This is only happening here because the `this.currentView` isn't using the injected value, and was instead getting wrapped in a proxy because it's passed as a prop to this component. Everywhere else in Open MCT (except for here and `ObjectView`), we're using the injected value.

The proxy breaks `getActionsCollection()` because it uses the object as a key to lookup a requested `ActionsCollection`.

To make a long story short, I think it'd be overkill to update the rest of the codebase to handle this weird outlier 😀

Comment (ozyx) [reply src/ui/preview/PreviewHeader.vue]: Ahhh ok, makes sense!

**Review by ozyx — APPROVED** [review]
LGTM!
