### PR TITLE
Bypass cache/dirty when canceling transaction

### LINKED ISSUE #7233: [Transactions] General issue with transactions in OpenMCT
#### Summary
Shefali and I noticed issues with OpenMCT and transactions. This manifests while trying to add items to any object and then trying to cancel saving. I'm also seeing this while styling items in a layout and then trying to discard changes and exit editing.

#### Impact Check List
- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by scottbell**
Closes #7233

### Describe your changes:

When canceling a transaction, we call `refresh` on the object, this in turn calls `get`, which by default can use a cached/dirty version of the object. This isn't very helpful as the cached object is the dirty object we're trying revert! To fix this, we instead use `forceRemote` on the `get` to get the untouched version of the object.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Has this been smoke tested?
* [x] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [x] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [ ] Is this a breaking change to be called out in the release notes?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [x] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?

### CODE REVIEW

File: src/ui/toolbar/components/ToolbarColorPicker.vue [hunk 1]
```diff
@@ -32,7 +32,7 @@
         class="c-swatch"
         :style="{ background: options.value }"
         role="img"
-        :aria-label="None"
+        aria-label="None"
```
Comment (scottbell) [inline src/ui/toolbar/components/ToolbarColorPicker.vue:35]: Driveby as it was throwing a warning every time the styles object was brought up.

Comment (ozyx) [reply src/ui/toolbar/components/ToolbarColorPicker.vue:35]: Nice catch

File: e2e/tests/functional/plugins/styling/flexLayoutStyling.e2e.spec.js [hunk 2]
```diff
@@ -411,4 +411,39 @@ test.describe('Flexible Layout styling', () => {
       page.getByLabel('StackedPlot1 Frame').getByLabel('Stacked Plot Style Target')
     );
   });
+
+  test('Styling, and then canceling reverts to previous style', async ({ page }) => {
```
Comment (ozyx) [inline e2e/tests/functional/plugins/styling/flexLayoutStyling.e2e.spec.js:415]: fantastic

File: src/api/objects/Transaction.js [hunk 3]
```diff
@@ -75,10 +75,10 @@ export default class Transaction {
 
   _clear() {
     const promiseArray = [];
-    const refresh = this.objectAPI.refresh.bind(this.objectAPI);
+    const action = (obj) => this.objectAPI.refresh(obj, true);
```
Comment (ozyx) [inline src/api/objects/Transaction.js:78]: we love our arrow functions don't we folks? nice change

File: src/api/objects/ObjectAPI.js [hunk 4]
```diff
@@ -696,10 +696,12 @@ export default class ObjectAPI {
   /**
    * Updates a domain object based on its latest persisted state. Note that this will mutate the provided object.
    * @param {module:openmct.DomainObject} domainObject an object to refresh from its persistence store
+   * @param {boolean} [forceRemote=false] defaults to false. If true, will skip cached and
+   *          dirty/in-transaction objects use and the provider.get method
    * @returns {Promise} the provided object, updated to reflect the latest persisted state of the object.
    */
-  async refresh(domainObject) {
-    const refreshedObject = await this.get(domainObject.identifier);
+  async refresh(domainObject, forceRemote = false) {
```
Comment (ozyx) [inline src/api/objects/ObjectAPI.js:703]: nice! the `forceRemote` option on `get()` came in handy @jvigliotta

**Review by unlikelyzero — APPROVED** [review]
