### PR TITLE
Fix plots dup requests

### LINKED ISSUE #4282: Duplicate requests made for Plots
#### Summary
NEEDS UPDATING.
Similar to https://github.com/nasa/openmct/issues/4273 but follows a different codepath

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug?

#### Steps to Reproduce

1. On load of a plot, make sure no duplicate requests are made

#### Environment
* Open MCT Version: `1.7.8`
* Deployment Type: `npm`

#### Additional Information
Similar to https://github.com/nasa/openmct/issues/4273

### PR DESCRIPTION
**Pull request by shefalijoshi**
Resolves #4282 
Also ensures the time context for plots reflects in any telemetry requests.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? Will users need to change how they are calling the API, or how they've extended core plugins such as Tables or Plots?

### Author Checklist

* [x] Changes address original issue?
* [x] Unit tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue?

### CODE REVIEW

File: src/plugins/plot/pluginSpec.js [hunk 1]
```diff
@@ -370,6 +370,10 @@ describe("the plugin", function () {
             return Vue.nextTick();
         });
 
+        it("Makes only one request for telemetry on load", () => {
```
Comment (jvigliotta) [inline src/plugins/plot/pluginSpec.js:373]: Nice!

**Review by jvigliotta — APPROVED** [review]
After going over this together, looks good! Also, nice added test!
