### PR TITLE
[Conditionals] Increase performance, switch to TelemetryCollections

### LINKED ISSUE #7840: Condition Manager is using older telemetry API and conditional styling can use a performance upgrade
#### Summary

This came about when debugging VIPERGC-550, in which a conditionally styled alphanumeric in a display layout was showing the wrong styles being applied. Testing showed there are situations where conditional styling could be applied incorrectly. This lead to performance enhancements to how the styles are applied and discovering a mismatch in how telemetry is requested in ConditionManager. 

#### Expected vs Current Behavior

Applying styles can happen quickly and change often, it should be performant. ConditionManager should use the newer TelemetryCollections in the telemetry API to request telemetry.

#### Steps to Reproduce

1. Create a condition on a moderately fast changing endpoint
2. Use that endpoint to style an alphanumeric in a display layout
3. Note that styles can be applied incorrectly

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [x] Does this have an impact on Performance?

#### Additional Information

In the below video, the item should only be red, when the value is above 100 (that is not happening consistently).
https://github.com/user-attachments/assets/4fa2f7cf-c821-461d-9a30-d1430764900d

### PR DESCRIPTION
**Pull request by jvigliotta**
Closes #7840

Believe this may be the issue reported in: VIPERGC-550

### Describe your changes:

Add some performance enhancements to conditional styling. Switched to TelemetryCollections from older and separate `subscribe` and historical `request`. This prevents situations where different telemetry was being evaluated in a condition vs the telemetry itself in the item being styled with the condition. This also just brings conditions in line with the rest of our code that uses TelemetryCollections.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this a [notable change](../docs/src/process/release.md) that will require a special callout in the release notes? For example, will this break compatibility with existing APIs or projects that consume these plugins?

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Has this been smoke tested?
* [x] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [x] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?

### CODE REVIEW

File: src/plugins/condition/ConditionManager.js [hunk 1]
```diff
@@ -410,11 +399,13 @@ export default class ConditionManager extends EventEmitter {
     return this.openmct.time.getBounds().end >= currentTimestamp;
   }
 
-  telemetryReceived(endpoint, datum) {
+  telemetryReceived(endpoint, data) {
     if (!this.isTelemetryUsed(endpoint)) {
       return;
     }
 
+    const datum = data[0];
```
Comment (ozyx) [inline src/plugins/condition/ConditionManager.js:407]: What happens if `data[0]` is undefined?

File: src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js [hunk 2]
```diff
@@ -128,36 +128,31 @@ export default {
       }
     },
     updateStyle(styleObj) {
-      let elemToStyle = this.getStyleReceiver();
+      const elemToStyle = this.getStyleReceiver();
 
-      if (!styleObj || elemToStyle === undefined) {
+      if (!styleObj || !elemToStyle) {
```
Comment (ozyx) [inline src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js:133]: 👍

File: src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js [hunk 3]
```diff
@@ -128,36 +128,31 @@ export default {
...
-              styleObj.isStyleInvisible &&
-              !elemToStyle.classList.contains(styleObj.isStyleInvisible)
-            ) {
-              elemToStyle.classList.add(styleObj.isStyleInvisible);
-            }
-
-            elemToStyle.style[key] = styleObj[key];
+      // handle visibility separately
+      if (styleObj.isStyleInvisible !== undefined) {
+        elemToStyle.classList.toggle(STYLE_CONSTANTS.isStyleInvisible, styleObj.isStyleInvisible);
```
Comment (ozyx) [inline src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js:139]: wow! that's a heck of an improvement.

it's the right fix. it still makes me cringe, though 😆

File: src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js [hunk 4]
```diff
@@ -128,36 +128,31 @@ export default {
...
+        delete styleObj.isStyleInvisible;
```
Comment (ozyx) [inline src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js:140]: can we set this to `null` instead? the only place in the codebase we directly check if it's `undefined` is just above this on line 138

File: src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js [hunk 5]
```diff
@@ -128,36 +128,31 @@ export default {
...
+            return `${key}: ;`; // removes the property
           }
-        }
+          return `${key}: ${value};`;
+        })
+        .join(' ');
+
+      // apply styles in one operation
+      requestAnimationFrame(() => {
+        elemToStyle.style.cssText += styleString;
```
Comment (ozyx) [inline src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js:155]: noice

**Review by ozyx — DISMISSED** [review]
Nice work! and nice job cleaning up that wild style code. I have a couple of suggestions where we can further improve performance, and I have some other suggestions for readability improvements.

Also this needs test(s) 😛

btw this test is failing in ci:    [ [chrome] › functional/plugins/styling/stackedPlotStyling.e2e.spec.js:159:3 › Stacked Plot styling › styling a child object of the flexible layout properly applies that style to only that child ](https://app.circleci.com/pipelines/github/nasa/openmct/23622/workflows/b2f31e77-6b68-4610-bf9a-6bf801b8c041/jobs/103545/tests)

File: src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js [hunk 6]
```diff
@@ -128,36 +128,31 @@ export default {
...
       });
     }
   }
```
Comment (ozyx) [inline src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js:158]: Instead of using `cssText` to set this all in one go, we can set each property individually and wrap the whole thing in a raf call. There are only a few style properties so the loop shouldn't cause any significant delay

```suggestion
requestAnimationFrame(() => {
  Object.entries(styleObj).forEach(([key, value]) => {
    if (typeof value !== 'string' || !value.includes('__no_value')) {
      elemToStyle.style[key] = value;
    } else {
      elemToStyle.style[key] = ''; // remove the property
    }
  });
});
```

File: src/plugins/condition/ConditionManager.js [hunk 7]
```diff
@@ -48,55 +48,44 @@ export default class ConditionManager extends EventEmitter {
...
-    this.telemetryObjects[telemetryKeyString] = Object.assign({}, endpoint, {
-      telemetryMetaData: metadata ? metadata.valueMetadatas : []
-    });
+    const metadata = this.openmct.telemetry.getMetadata(telemetryObject);
+    const telemetryMetaData = metadata ? metadata.valueMetadatas : [];
+    const telemetryProcessor = this.telemetryReceived.bind(this, telemetryObject);
 
-    // get latest telemetry value (in case subscription is cached and no new data is coming in)
-    this.requestLatestValue(endpoint);
+    this.telemetryObjects[keyString] = Object.assign({}, telemetryObject, { telemetryMetaData });
```
[the remark this answers is not in the document]
Comment (jvigliotta) [reply src/plugins/condition/ConditionManager.js:72]: No we don't do that, I'll update this older code!

File: src/plugins/condition/ConditionManager.js [hunk 8]
```diff
@@ -48,55 +48,44 @@ export default class ConditionManager extends EventEmitter {
...
+
+    this.telemetryCollections[keyString].on('add', telemetryProcessor);
```
[the remark this answers is not in the document]
Comment (jvigliotta) [reply src/plugins/condition/ConditionManager.js:74]: Yeah, I thought I was going to need to save the callback for removal later, but that's not the case here. I'll put it inline.

File: src/plugins/condition/ConditionManager.js [hunk 9]
```diff
@@ -39,7 +39,7 @@ export default class ConditionManager extends EventEmitter {
     this.shouldEvaluateNewTelemetry = this.shouldEvaluateNewTelemetry.bind(this);
 
     this.compositionLoad = this.composition.load();
-    this.subscriptions = {};
+    this.telemetryCollections = {};
```
[the remark this answers is not in the document]
Comment (jvigliotta) [reply src/plugins/condition/ConditionManager.js:42]: Yeah from what I'm seeing these aren't accessed that often to justify the change here, good call though.

File: src/plugins/condition/ConditionManager.js [hunk 10]
```diff
@@ -48,55 +48,44 @@ export default class ConditionManager extends EventEmitter {
...
+    if (!this.telemetryCollections[keyString]) {
       return;
     }
 
-    this.subscriptions[id]();
-    delete this.subscriptions[id];
-    delete this.telemetryObjects[id];
+    this.telemetryCollections[keyString].destroy();
+    delete this.telemetryCollections[keyString];
+    delete this.telemetryObjects[keyString];
```
[the remark this answers is not in the document]
Comment (jvigliotta) [reply src/plugins/condition/ConditionManager.js:88]: Foregoing the map, will set these to null!

File: src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js (hunk 4 above)
Comment (jvigliotta) [reply src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js:140]: yep!

File: src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js (hunk 6 above)
Comment (jvigliotta) [reply src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js:158]: yeah, I had that then over engineered it. This way is more performant for sure, I'll switch it up. Thanks!

Comment (ozyx) [reply src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js:158]: > yeah, I had that then over engineered it. This way is more performant for sure, I'll switch it up. Thanks!

All credit goes to my coworker Chad G. Petey

File: src/plugins/condition/ConditionManager.js (hunk 1 above)
Comment (jvigliotta) [reply src/plugins/condition/ConditionManager.js:407]: We didn't have any handling before, so same as before (probably break). I'm not sure if that's what we'd want to happen or not. I can move the assignment before the conditional above and return if it's undefined?

Comment (ozyx) [reply src/plugins/condition/ConditionManager.js:407]: ok, actually i see how this is used now and it seems like we can reasonably assume that `data` will be an array of telemetry with size of at least 1, so we can leave this as-is

**Comment by khalidadil** [comment]
@ozyx was this change still under review? It touches some code in a file that I'm also working on (ConditionManager.js), so I want to get it merged into my branch when it's ready

**Comment by ozyx** [comment]
> @ozyx was this change still under review? It touches some code in a file that I'm also working on (ConditionManager.js), so I want to get it merged into my branch when it's ready

It just needs a test. So you can probably safely rebase onto this branch and then rebase onto master once you're ready to open a PR

**Comment by khalidadil** [comment]
> > @ozyx was this change still under review? It touches some code in a file that I'm also working on (ConditionManager.js), so I want to get it merged into my branch when it's ready
> 
> It just needs a test. So you can probably safely rebase onto this branch and then rebase onto master once you're ready to open a PR

awesome, thank you!

File: src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js [hunk 11]
```diff
@@ -128,36 +128,26 @@ export default {
...
+        styleObj.isStyleInvisible = null;
+      }
 
-      keys.forEach((key) => {
-        if (elemToStyle) {
-          if (typeof styleObj[key] === 'string' && styleObj[key].indexOf('__no_value') > -1) {
-            if (elemToStyle.style[key]) {
-              elemToStyle.style[key] = '';
-            }
+      requestAnimationFrame(() => {
```
Comment (akhenry) [inline src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js:143]: `requestAnimationFrame` needs a semaphore, otherwise it does not throttle anything, the requestAnimationFrame calls will just queue up in the event loop. You can use https://github.com/nasa/openmct/blob/master/src/utils/raf.js#L1 for this.

File: src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js [hunk 12]
```diff
@@ -128,36 +128,26 @@ export default {
...
-      let elemToStyle = this.getStyleReceiver();
+      const elemToStyle = this.getStyleReceiver();
 
-      if (!styleObj || elemToStyle === undefined) {
+      if (!styleObj || !elemToStyle) {
         return;
       }
 
-      let keys = Object.keys(styleObj);
+      // handle visibility separately
```
Comment (akhenry) [inline src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js:137]: Why do we handle visibility outside of the `requestAnimationFrame` callback?

**Review by akhenry — CHANGES_REQUESTED** [review]

File: src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js (hunk 12 above)
Comment (jvigliotta) [reply src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js:137]: This is a great question to which I don't have a good answer, I'll move it back in unless I remember why!

Comment (jvigliotta) [reply src/plugins/plot/stackedPlot/mixins/objectStyles-mixin.js:137]: so, the only benefit I could see is that visibility would be styled immediately, but I don't see that being a big enough benefit. It seems confusing to leave it out. I'll put it in the raf.

File: e2e/tests/functional/plugins/styling/conditionSetStyling.e2e.spec.js [hunk 13]
```diff
@@ -0,0 +1,170 @@
...
+  }).toPass({ timeout }); // timeout allows for the style to be applied
+}
+
+/**
+ * Search for telemetry and link it to an object. objectName should come from the domainObject.name function.
+ * @param {import('@playwright/test').Page} page
+ * @param {string} parameterName
+ * @param {string} objectName
+ */
+async function searchAndLinkParameterToObject(page, parameterName, objectName) {
```
Comment (unlikelyzero) [inline e2e/tests/functional/plugins/styling/conditionSetStyling.e2e.spec.js:167]: this is a pre-promotion appAction. We're leveraging this in yamcsAppActions. I think it would be useful in core

File: e2e/tests/functional/plugins/styling/conditionSetStyling.e2e.spec.js [hunk 14]
```diff
@@ -0,0 +1,170 @@
...
+
+import { createDomainObjectWithDefaults, setRealTimeMode } from '../../../../appActions.js';
+import { MISSION_TIME } from '../../../../constants.js';
+import { expect, test } from '../../../../pluginFixtures.js';
+
+test.describe('Conditionally Styling, using a Condition Set', () => {
+  let stateGenerator;
+  let conditionSet;
+  let displayLayout;
+  const STATE_CHANGE_INTERVAL = '1';
```
Comment (unlikelyzero) [inline e2e/tests/functional/plugins/styling/conditionSetStyling.e2e.spec.js:36]: this may need to change if the current test is flaky

**Review by unlikelyzero — APPROVED** [review]
Updated the test

**Comment by akhenry** [comment]
This issue was still evident in my testing - 

https://github.com/user-attachments/assets/4a3f855d-f103-488d-8530-e7e6da9e65b4

I actually think that the video does not show a bug at all. I think what it shows is an artifact of telemetry batching. We send batches of telemetry once per second from the WebSocket worker, and the condition set and TelemetryView just show the most recent value from the batch. Each window is a separate WebSocket, and a separate buffer initiated at a different time, so the latest value in each batch will be different, and that's fine. We're showing a real-time "snapshot" of the system to the user once-per second. If they want to see everything they can, in a table or a plot.

**Review by ozyx — APPROVED** [review]
