### PR TITLE
Reverting when cancelling out of edits works for both legacy and new object providers

### LINKED ISSUE #3425: [Display Layout] Regression with cancelling edits
There is regression where if an item in a display layout is edited (change properties) and then you cancel the changes (ie not save), the changes are not thrown away.

### PR DESCRIPTION
**Pull request by shefalijoshi**
For new object providers, we call openmct.objects.get when we revert changes made to an object
For legacy persistence providers, we ensure that the defaultSpace they were registered with is honored when we 'get' objects.

Resolves #3425 

## Author Checklist
Changes address original issue? Yes
Unit tests included and/or updated with changes? Yes
Command line build passes? Yes
Changes have been smoke-tested? Yes
Testing instructions included? Yes

### CODE REVIEW

File: platform/core/test/capabilities/PersistenceCapabilitySpec.js [hunk 1]
```diff
@@ -110,8 +112,18 @@ define(
                     }
                 });
 
-                mockOpenMCT = {};
-                mockOpenMCT.objects = jasmine.createSpyObj('Object API', ['save']);
+                mockOpenMCT = {
+                    legacyObject: function (object) {
+                        return {
+                            getModel: function () {
+                                console.log(object);
```
Comment (jvigliotta) [inline platform/core/test/capabilities/PersistenceCapabilitySpec.js:119]: Is this leftover from debuggin?

**Review by jvigliotta — CHANGES_REQUESTED** [review]
One small leftover console.log but from what I can see looks good!

**Comment by akhenry** [comment]
### Reviewer Checklist

1. Changes appear to address issue? Y
2. Appropriate unit tests included? Y
3. Code style and in-line documentation are appropriate? Y
4. Commit messages meet standards? Y
5. Has associated issue been labelled `unverified`? (only applicable if this PR closes the issue) Y

**Review by akhenry — APPROVED** [review]
