### PR TITLE
Fix couchdb setup and add a note on how to remove the container

### LINKED ISSUE #6914: [CouchDB] init script is missing the create_users_db() step and creating lots of errors
#### Summary
init script is missing the create_users_db() step and creating lots of errors

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by unlikelyzero**
Closes #6914

### Describe your changes:
Updates the init script to break out the users and replication db into discrete steps

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [ ] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [ ] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [ ] Changes appear not to be breaking changes?
* [ ] Appropriate automated tests included?
* [ ] Code style and in-line documentation are appropriate?
* [ ] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/plugins/persistence/couch/setup-couchdb.sh [hunk 1]
```diff
@@ -100,13 +106,22 @@ else
...
+users_table_exists=$(resource_exists $COUCH_BASE_LOCAL/_users)
+if [ "FALSE" == "${users_table_exists}" ]; then
+    echo "Creating _users table"
+    create_users_table
+else
+    echo "_users table already exists, skipping creation"
+fi
+
+# Check if the _replicator table exists; if not, create it.
+replicator_table_exists=$(resource_exists $COUCH_BASE_LOCAL/_replicator)
```
Comment (unlikelyzero) [inline src/plugins/persistence/couch/setup-couchdb.sh:119]: now a discrete step

File: src/plugins/persistence/couch/setup-couchdb.sh [hunk 2]
```diff
@@ -100,13 +106,22 @@ else
...
+if [ "FALSE" == "${replicator_table_exists}" ]; then
+    echo "Creating _replicator table"
```
Comment (ozyx) [inline src/plugins/persistence/couch/setup-couchdb.sh:121]: duplicate echo here

File: src/plugins/persistence/couch/setup-couchdb.sh [hunk 3]
```diff
@@ -100,13 +106,22 @@ else
...
 fi
 
-# Check if system tables exist; if not, create them.
-system_tables_exist=$(resource_exists $COUCH_BASE_LOCAL/_users)
-if [ "TRUE" == "${system_tables_exist}" ]; then
-    echo "System tables exist, skipping creation"
+# Check if the _users table exists; if not, create it.
+users_table_exists=$(resource_exists $COUCH_BASE_LOCAL/_users)
+if [ "FALSE" == "${users_table_exists}" ]; then
+    echo "Creating _users table"
```
Comment (ozyx) [inline src/plugins/persistence/couch/setup-couchdb.sh:112]: duplicate echo here. also, is it a table or a database?

**Review by ozyx — DISMISSED** [review]
just a couple small comments re: print statements

**Comment by unlikelyzero** [comment]
@ozyx resolved

**Review by shefalijoshi — APPROVED** [review]
