### PR TITLE
Plots correctly use configuration set on the parent if they can't their own

### LINKED ISSUE #7771: Properties of stacked plot series that aren't mutable don't get applied
#### Summary
Changing the properties/config of a stacked plot series that is not mutable gets saved correctly, but does not get applied when loaded.
Workaround is to first include the series in an overlay plot, save the config and then include the overlay plot inside the stacked plot.

ALSO SEE: VIPERGC-535

#### Steps to Reproduce
1. Create a stacked plot
2. Add a series (telemetry) to the stacked plot that cannot be saved to couchdb (like a Sine wave generator)
3. Edit the stacked plot, select the series and change it's config - for example, the marker size
4. Save the change
5. Observe that the change is not applied.

#### Environment

* Open MCT Version: 4.0.x
* Deployment Type: all
* OS: all
* Browser: all

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

### PR DESCRIPTION
**Pull request by shefalijoshi**
Closes #7771

### Describe your changes:
For telemetry that cannot have it's own configuration, ensure that it is correct initialized by the parent.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [ ] Is this a [notable change](../docs/src/process/release.md) that will require a special callout in the release notes? For example, will this break compatibility with existing APIs or projects that consume these plugins?

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Has this been smoke tested?
* [x] Have you associated this PR with a `type:` label? Note: this is not necessarily the same as the original issue.
* [x] Have you associated a milestone with this PR? Note: leave blank if unsure.
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [x] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [x] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?

### CODE REVIEW

File: e2e/tests/functional/plugins/plot/plotActions.js
Comment (unlikelyzero) [inline e2e/tests/functional/plugins/plot/plotActions.js:1]: We should move away from this for two reasons: 
1. We should not be using the locator method anymore. 
2. We should update the element to allow a direct check or uncheck action

File: e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js [hunk 1]
```diff
@@ -228,6 +229,46 @@ test.describe('Stacked Plot', () => {
...
+
+    await page.locator('li.c-tree__item.menus-to-left .c-disclosure-triangle').click();
+
+    // Assert that alarm markers are still turned off
+    await expect(
+      await page
+        .getByRole('list', { name: 'Plot Series Properties' })
+        .locator('[title="Alarm Markers"]>div')
+        .nth(1)
+    ).toContainText('Disabled');
```
Comment (unlikelyzero) [inline e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js:269]: We should find a better way of locating this element without using the locator method, nth, or title locators.

Ideally, this assertion should look like this:
```js
await expect(await page.getByRole('listitem', { name: object.name }).getByLabel('Alarm Marker's).toContainText('Disabled')

**Review by unlikelyzero — CHANGES_REQUESTED** [review]
I have most of my fixes on this branch

File: e2e/tests/functional/plugins/plot/plotActions.js [hunk 2]
```diff
@@ -27,6 +27,14 @@ async function turnOffAutoscale(page) {
   await page.getByRole('checkbox', { name: 'Auto scale' }).uncheck();
 }
 
+async function turnOffAlarmMarkers(page) {
```
Comment (unlikelyzero) [inline e2e/tests/functional/plugins/plot/plotActions.js:30]: we should remove this

File: e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js [hunk 3]
```diff
@@ -39,19 +39,23 @@ test.describe('Stacked Plot', () => {
     await page.goto('./', { waitUntil: 'domcontentloaded' });
 
     stackedPlot = await createDomainObjectWithDefaults(page, {
-      type: 'Stacked Plot'
+      type: 'Stacked Plot',
+      name: 'Stacked Plot'
```
Comment (unlikelyzero) [inline e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js:43]: added names to be explicit in the selection of objects

File: e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js [hunk 4]
```diff
@@ -228,6 +232,45 @@ test.describe('Stacked Plot', () => {
...
+  test('Changing properties of an immutable child plot are applied correctly', async ({ page }) => {
+    await page.goto(stackedPlot.url);
+
+    // Go into edit mode
+    await page.getByLabel('Edit Object').click();
+
+    await page.getByRole('tab', { name: 'Config' }).click();
+
+    // Click on canvas for the 1st plot
+    await page.getByLabel(`Stacked Plot Item ${swgA.name}`).click();
```
Comment (unlikelyzero) [inline e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js:244]: updated this to use the `getByLabel` method, directly

File: e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js [hunk 5]
```diff
@@ -228,6 +232,45 @@ test.describe('Stacked Plot', () => {
...
+
+    // Expand config for the series
+    await page.getByLabel('Expand Sine Wave Generator').click();
+
+    // turn off alarm markers. Technically there should be a getBy locator to ensure we're selecting the correct alarm marker
+    await page.getByLabel('Alarm Markers').uncheck();
```
Comment (unlikelyzero) [inline e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js:250]: Technically this should be a chained `getBy` locator to ensure we're selecting the correct alarm marker

File: src/plugins/plot/inspector/PlotOptionsBrowse.vue [hunk 6]
```diff
@@ -21,7 +21,7 @@
 -->
 <template>
   <div v-if="loaded" class="js-plot-options-browse">
-    <ul v-if="!isStackedPlotObject" class="c-tree" aria-label="Plot Series Properties">
```
Comment (unlikelyzero) [inline src/plugins/plot/inspector/PlotOptionsBrowse.vue:24]: aria labels implies interactivity. This is not an interactive component

File: src/plugins/plot/inspector/PlotOptionsEdit.vue [hunk 7]
```diff
@@ -33,15 +33,18 @@
...
     />
     <ul
       v-if="isStackedPlotObject || !isStackedPlotNestedObject"
       class="l-inspector-part"
       aria-label="Legend Properties"
+      role="tree"
     >
       <h2 class="--first" title="Legend options">Legend</h2>
-      <legend-form class="grid-properties" :legend="config.legend" />
+      <legend-form role="treeitem" tabindex="0" class="grid-properties" :legend="config.legend" />
```
Comment (unlikelyzero) [inline src/plugins/plot/inspector/PlotOptionsEdit.vue:47]: allow users to tab to this component

File: src/plugins/plot/inspector/PlotOptionsItem.vue [hunk 8]
```diff
@@ -21,11 +21,14 @@
 -->
 <template>
   <ul>
-    <li class="c-tree__item menus-to-left" :class="isAliasClass">
+    <li class="c-tree__item menus-to-left" :class="isAliasClass" role="listitem">
       <span
         class="c-disclosure-triangle is-enabled flex-elem"
         :class="expandedCssClass"
+        :aria-label="ariaLabelValue"
```
Comment (unlikelyzero) [inline src/plugins/plot/inspector/PlotOptionsItem.vue:28]: make this an interactive 'Expand Plot Object'

File: src/plugins/plot/inspector/PlotOptionsItem.vue [hunk 9]
```diff
@@ -21,11 +21,14 @@
...
+        tabindex="0"
```
Comment (unlikelyzero) [inline src/plugins/plot/inspector/PlotOptionsItem.vue:29]: allow tab interaction and focus

File: src/plugins/plot/inspector/PlotOptionsItem.vue [hunk 10]
```diff
@@ -21,11 +21,14 @@
...
         @click="toggleExpanded"
+        @keydown.enter="toggleExpanded"
```
Comment (unlikelyzero) [inline src/plugins/plot/inspector/PlotOptionsItem.vue:31]: enable enter key

File: src/plugins/plot/inspector/PlotOptionsItem.vue [hunk 11]
```diff
@@ -79,14 +82,8 @@
...
         </li>
-        <li class="grid-row" role="row">
-          <div
-            class="grid-cell label"
-            title="Display markers visually denoting points in alarm."
-            role="cell"
-          >
-            Alarm Markers
-          </div>
+        <li class="grid-row" role="row" title="Display markers visually denoting points in alarm.">
```
Comment (unlikelyzero) [inline src/plugins/plot/inspector/PlotOptionsItem.vue:85]: moved title to the list instead of the Div. This allows us to chain on the title attribute in the test

File: src/plugins/plot/inspector/forms/SeriesForm.vue [hunk 12]
```diff
@@ -21,11 +21,15 @@
...
 <template>
   <ul>
-    <li class="c-tree__item menus-to-left" :class="isAliasCss">
+    <li class="c-tree__item menus-to-left" :class="isAliasCss" role="treeitem">
       <span
         class="c-disclosure-triangle is-enabled flex-elem"
         :class="expandedCssClass"
+        role="button"
+        :aria-label="ariaLabelValue"
+        tabindex="0"
```
Comment (unlikelyzero) [inline src/plugins/plot/inspector/forms/SeriesForm.vue:30]: same as above

File: src/ui/inspector/InspectorTabs.vue [hunk 13]
```diff
@@ -28,8 +28,10 @@
       role="tab"
       class="c-inspector__tab c-tab"
       :class="{ 'is-current': isSelected(tab) }"
+      tabindex="0"
```
Comment (unlikelyzero) [inline src/ui/inspector/InspectorTabs.vue:31]: this allows us to tab to the plot series expand/collapse component

**Review by unlikelyzero — APPROVED** [review]
I've updated this the best I could. This is likely to cause some lateral test failure based on the locator changes. Should be easy to address.

File: e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js [hunk 14]
```diff
@@ -228,6 +232,45 @@ test.describe('Stacked Plot', () => {
...
+
+    // Expand config for the series
+    await page.getByLabel('Expand Sine Wave Generator').click();
+
+    // Assert that alarm markers are still turned off
+    await expect(
+      page
+        .getByTitle('Display markers visually denoting points in alarm.')
+        .getByRole('cell', { name: 'Disabled' })
+    ).toBeVisible();
```
Comment (unlikelyzero) [inline e2e/tests/functional/plugins/plot/stackedPlot.e2e.spec.js:271]: This is a chained locator which leverages Titles

File: src/plugins/plot/inspector/forms/SeriesForm.vue [hunk 15]
```diff
@@ -84,10 +88,15 @@
       </li>
       <li class="grid-row">
         <div class="grid-cell label" title="Display markers visually denoting points in alarm.">
-          Alarm Markers
+          <label for="alarm-markers-checkbox">Alarm Markers</label>
```
Comment (unlikelyzero) [inline src/plugins/plot/inspector/forms/SeriesForm.vue:91]: @ozyx here's an attempt at using labels and ids

**Comment by akhenry** [comment]
@shefalijoshi  Looks good to me, thank you. Glad it was a relatively small code change.

**Comment by akhenry** [comment]
Just need to sort out the tests and this can be merged.

**Review by akhenry — DISMISSED** [review]
Just need to sort out the tests and this can be merged.

File: src/plugins/charts/bar/inspector/SeriesOptions.vue [hunk 16]
```diff
@@ -21,7 +21,7 @@
 -->
 <template>
   <ul>
-    <li class="c-tree__item menus-to-left" :class="aliasCss">
+    <li class="c-tree__item menus-to-left" :class="aliasCss" role="treeitem">
```
Comment (ozyx) [inline src/plugins/charts/bar/inspector/SeriesOptions.vue:24]: this probably will break some tests (for good reason), i think the only other thing that has treeitem role is the main tree. but this seems like the right role for this to have

File: src/plugins/plot/inspector/PlotOptionsBrowse.vue [hunk 17]
```diff
@@ -21,7 +21,7 @@
...
+    <ul v-if="!isStackedPlotObject" class="c-tree" role="tree">
```
Comment (ozyx) [inline src/plugins/plot/inspector/PlotOptionsBrowse.vue:24]: nice

File: src/plugins/plot/inspector/forms/SeriesForm.vue (hunk 15 above)
Comment (ozyx) [reply src/plugins/plot/inspector/forms/SeriesForm.vue:91]: what happens in the case of an overlay plot with multiple series to configure?

File: src/plugins/plot/inspector/forms/SeriesForm.vue [hunk 18]
```diff
@@ -169,6 +178,13 @@ export default {
     };
   },
   computed: {
+    ariaLabelValue() {
+      //series.domainObject.name
```
Comment (ozyx) [inline src/plugins/plot/inspector/forms/SeriesForm.vue:182]: remove

File: src/plugins/plot/stackedPlot/StackedPlotItem.vue [hunk 19]
```diff
@@ -122,8 +122,11 @@ export default {
     'grid-lines',
     'plot-y-tick-width'
   ],
-  mounted() {
+  beforeMount() {
+    // We must do this before mounted to use any series configuration options set at the stacked plot level
```
Comment (ozyx) [inline src/plugins/plot/stackedPlot/StackedPlotItem.vue:126]: y tho?

**Review by unlikelyzero — APPROVED** [review]

**Review by ozyx — APPROVED** [review]
