### PR TITLE
Memory leak fixes for several views

### LINKED ISSUE #4406: [Performance] Check views for memory leak on navigation
There is a class of memory leak that occurs where references to view objects are retained even after the view has been destroyed. View destruction occurs on navigation. 

The usual reason for this is a failure to clean up event handlers.

This can cause performance degradation of the application over time as memory builds up. This is a particular issue with views that hold onto historical telemetry.

[A draft PR](https://github.com/nasa/openmct/pull/6718) exists that provides a framework for implementing this kind of test. **It should be configured to run on every PR**  to catch memory leaks as soon as they are introduced. The draft PR defines tests for the following object views:

* [x] Overlay Plots
* [x] Stacked Plots
* [ ] Tables
* [x] LAD Tables
* [x] LAD Table Sets
* [x] Imagery View (Except for CompassRose)
* [x] Simple Display Layouts
* [x] Simple Flexible Layouts
* [ ] Notebooks
* [ ] Tabs View

Filed followup for remaining screens - https://github.com/nasa/openmct/issues/6734
Also see: https://github.com/nasa/openmct/issues/4209

### PR DESCRIPTION
**Pull request by shefalijoshi**
Closes #4406 #4209

### Describe your changes:
* Adds memory leak check suite to `perf` tests
* Use Vue.createApp for dynamically mounting components.
* Remove event listeners properly
* Ensure objects are destroyed on unload
* Disables vue-loader's `hoistStatic` option which was holding onto refs

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](https://github.com/nasa/openmct/blob/master/CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/nasa/openmct/pulls) for the same update/change?
* [x] Is this change backwards compatible? For example, developers won't need to change how they are calling the API or how they've extended core plugins such as Tables or Plots.

### Author Checklist

* [x] Changes address original issue?
* [x] Tests included and/or updated with changes?
* [x] Command line build passes?
* [x] Has this been smoke tested?
* [x] Testing instructions included in associated issue OR is this a dependency/testcase change?

### Reviewer Checklist

* [x] Changes appear to address issue?
* [ ] Reviewer has tested changes by following the provided instructions?
* [x] Changes appear not to be breaking changes?
* [x] Appropriate automated tests included?
* [x] Code style and in-line documentation are appropriate?
* [x] Has associated issue been labelled unverified? (only applicable if this PR closes the issue)
* [ ] Has associated issue been labelled bug? (only applicable if this PR is for a bug fix)

### CODE REVIEW

File: src/plugins/imagery/components/ImageryViewMenuSwitcher.vue [hunk 1]
```diff
@@ -28,7 +28,7 @@
       :title="title"
       @click="toggleMenu"
     >
-      <span class="c-button__label"></span>
+      <!--      <span class="c-button__label"></span>-->
```
Comment (shefalijoshi) [inline src/plugins/imagery/components/ImageryViewMenuSwitcher.vue:31]: This has no content, so I removed it. Do we need it?

File: e2e/README.md [hunk 2]
```diff
@@ -412,35 +388,12 @@ For now, our best practices exist as self-tested, living documentation in our [e
 
 For best practices with regards to mocking network responses, see our [couchdb.e2e.spec.js](./tests/functional/couchdb.e2e.spec.js) file.
 
-### Tips & Tricks
+### Tips & Tricks (TODO)
```
Comment (ozyx) [inline e2e/README.md:391]: I think we're accidentally reverting changes here? Might need to rebase your branch onto master

**Review by ozyx — CHANGES_REQUESTED** [review]
The diff is not clean, I think we're reverting changes accidentally. Please rebase this onto `master`

File: src/plugins/imagery/components/ImageryViewMenuSwitcher.vue [hunk 3]
```diff
@@ -27,9 +27,7 @@
       :class="iconClass"
       :title="title"
       @click="toggleMenu"
-    >
-      <span class="c-button__label"></span>
-    </button>
+    />
```
Comment (akhenry) [inline src/plugins/imagery/components/ImageryViewMenuSwitcher.vue:30]: Regression test imagery view switcher

File: src/plugins/plot/chart/MctChart.vue [hunk 4]
```diff
@@ -26,7 +26,20 @@
   <div class="gl-plot-chart-area">
     <span v-html="canvasTemplate"></span>
     <span v-html="canvasTemplate"></span>
-    <div ref="limitArea" class="js-limit-area"></div>
+    <div ref="limitArea" class="js-limit-area">
```
Comment (akhenry) [inline src/plugins/plot/chart/MctChart.vue:29]: Regression test plot limit lines

File: src/ui/components/ObjectFrame.vue [hunk 5]
```diff
@@ -209,13 +209,13 @@ export default {
 
       this.actionCollection = actionCollection;
       this.actionCollection.on('update', this.updateActionItems);
-      this.updateActionItems(this.actionCollection.applicableActions);
+      this.updateActionItems();
```
Comment (akhenry) [inline src/ui/components/ObjectFrame.vue:212]: Let's talk about this, I'd like to understand this change.

File: src/ui/components/ObjectView.vue [hunk 6]
```diff
@@ -462,6 +473,11 @@ export default {
         }
       }
     },
+    performContextAction() {
```
Comment (akhenry) [inline src/ui/components/ObjectView.vue:476]: Let's discuss this change and define some regression tests.

**Review by akhenry — CHANGES_REQUESTED** [review]

File: e2e/tests/performance/memory/navigation.memory.perf.spec.js [hunk 7]
```diff
@@ -0,0 +1,255 @@
...
+    const result = await navigateToObjectAndDetectMemoryLeak(
+      page,
+      'example-imagery-memory-leak-test'
+    );
+
+    // If we got here without timing out, then the root view object was garbage collected and no memory leak was detected.
+    expect(result).toBe(true);
+  });
+
+  test('display layout of example imagery views', async ({ page }) => {
```
[the remark this answers is not in the document]
Comment (akhenry) [reply e2e/tests/performance/memory/navigation.memory.perf.spec.js:142]: Possibly because of compass rose?

File: src/plugins/displayLayout/components/EllipseView.vue [hunk 8]
```diff
@@ -25,14 +25,16 @@
...
-    @endMove="() => $emit('endMove')"
+    @move="move"
+    @endMove="endMove"
   >
-    <div
-      class="c-ellipse-view u-style-receiver js-style-receiver"
-      :class="[styleClass]"
-      :style="style"
-    ></div>
+    <template #content>
```
Comment (akhenry) [inline src/plugins/displayLayout/components/EllipseView.vue:31]: Define regression test for drawing ellipse shape in display layouts.

File: src/plugins/flexibleLayout/components/FlexibleLayout.vue [hunk 9]
```diff
@@ -255,7 +271,7 @@ export default {
         container.frames.splice(frameIndex + 1, 0, frame);
         sizeItems(container.frames, frame);
 
-        this.newFrameLocation = [];
+        this.newFrameLocation.splice(0);
```
Comment (akhenry) [inline src/plugins/flexibleLayout/components/FlexibleLayout.vue:274]: It sounds like we should not be splicing reactive arrays. Let's double check that this change is definitely necessary.

File: src/plugins/imagery/components/ImageryView.vue [hunk 10]
```diff
@@ -1276,6 +1277,9 @@ export default {
       this.scrollHandler();
     },
     setSizedImageDimensions() {
+      if (!this.$refs.focusedImage) {
```
Comment (akhenry) [inline src/plugins/imagery/components/ImageryView.vue:1280]: Let's see if we can figure out why this is being called when focusedImage does not exist.

File: src/plugins/plot/Plot.vue [hunk 11]
```diff
@@ -179,7 +179,7 @@ export default {
     this.stalenessSubscription = {};
     this.loadComposition();
   },
-  beforeUnmount() {
+  unmounted() {
```
Comment (akhenry) [inline src/plugins/plot/Plot.vue:182]: Let's revert this.

File: src/plugins/plot/chart/MctChart.vue [hunk 12]
```diff
@@ -727,8 +742,11 @@ export default {
       }
 
       let limitPointOverlap = [];
+      //reset
+      this.visibleLimitLabels.splice(0);
```
Comment (akhenry) [inline src/plugins/plot/chart/MctChart.vue:746]: Let's remove the splices here.

File: src/ui/components/ObjectFrame.vue [hunk 13]
```diff
@@ -195,7 +195,7 @@ export default {
     }
 
     if (this.soViewResizeObserver) {
-      this.soViewResizeObserver.disconnect();
+      this.soViewResizeObserver.unobserve(this.$refs.soView);
```
Comment (akhenry) [inline src/ui/components/ObjectFrame.vue:198]: Revert this change.

File: src/plugins/imagery/components/ImageryViewMenuSwitcher.vue (hunk 3 above)
Comment (shefalijoshi) [reply src/plugins/imagery/components/ImageryViewMenuSwitcher.vue:30]: I reverted this change instead.

File: e2e/tests/performance/memory/navigation.memory.perf.spec.js (hunk 7 above)
[the remark this answers is not in the document]
Comment (shefalijoshi) [reply e2e/tests/performance/memory/navigation.memory.perf.spec.js:142]: Yes, because of CompassRose. Now that we're not hoisting static files, both these tests pass.

File: src/plugins/imagery/components/ImageryView.vue (hunk 10 above)
Comment (shefalijoshi) [reply src/plugins/imagery/components/ImageryView.vue:1280]: The resize observer for `$ref.imageBG` calls `resizeImageContainer()` which in turn calls `setSizedImageDimensions()`.

File: src/plugins/plot/Plot.vue (hunk 11 above)
Comment (ozyx) [reply src/plugins/plot/Plot.vue]: this creates a leak if we revert for some reason

File: src/plugins/inspectorViews/styles/StylesInspectorView.vue [hunk 14]
```diff
@@ -56,7 +56,7 @@ export default {
   mounted() {
     this.openmct.editor.on('isEditing', this.setEditMode);
   },
-  beforeUnmounted() {
```
Comment (ozyx) [inline src/plugins/inspectorViews/styles/StylesInspectorView.vue:59]: HAH! oopsie 😊

File: src/plugins/conditionWidget/components/ConditionWidget.vue [hunk 15]
```diff
@@ -81,7 +81,7 @@ export default {
       this.listenToConditionSetChanges();
     }
   },
-  beforeUnmount() {
+  unmounted() {
```
Comment (shefalijoshi) [inline src/plugins/conditionWidget/components/ConditionWidget.vue:84]: This works - I don't understand why.

**Review by akhenry — APPROVED** [review]

**Review by ozyx — APPROVED** [review]
I approve 👀
